Particular/NServiceBus

- src/NServiceBus.AcceptanceTesting/Support/EndpointBehaviorBuilder.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
**NB; we are migrating NSB v4 to v5, along w/our customised version of the v4 Acceptance Testing f/w.**
In our own custom version of the v4 Acceptance Testing framework we would specify an AppConfig on the `EndpointConfiguration` and set via `EndpointConfigurationBuilder`, but using this required calling `.Get()` on a *created* instance of the endpoint configuration given it wasn't 'to hand', this seems sub-optimal. We could have alternatively tried passing this setting into the `ScenarioRunner` for conditional usage (behaviour.AppConfig ?? endpointConfiguration.AppConfig), or better still default each new behaviour to use `AppConfig` from `EndpointConfiguration`. The changes required seemed quite substantial though.
Our aim is to switch to the vanilla v5 AcceptanceTesting NuGet with the …
> AcceptanceTesting: AppConfig on Behaviour DSL + AppDomain ConfigFile

- src/NServiceBus.AcceptanceTests/Basic/When_injecting_handler_props.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core/ConfigureHandlerSettings.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Unicast/Config/RegisterHandlersInOrder.cs
As currently pointed out in #2600, v5 of NServiceBus no longer has a hook to assign config settings to `IHandleMessages<T>` types.
This PR addresses this issue by introducing a more explicit API.
Only property injection is supported, no ctor injection :disappointed: 
```c#
config.InitializeHandlerProperty<MyHandler>("MyProp", myvalue);
config.InitializeHandlerProperty<MyHandler2>("MyProp2", myvalue2);
```
> Add support for settings injection

- src/NServiceBus.Core.Tests/Utils/ExceptionHeaderHelperTests.cs
- src/NServiceBus.Core/Utils/ExceptionHeaderHelper.cs
When values are are added to an exception's "Data" property, they will be written to the exception headers of a failed message.
Fixes #2630
> Add Data to exception headers

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Persistence/PersistenceStorageMergerTests.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Persistence/PersistenceConfig.cs
- src/NServiceBus.Core/Persistence/PersistenceExtentions.cs
- src/NServiceBus.Core/Persistence/PersistenceStartup.cs
- src/NServiceBus.Core/Persistence/PersistenceStorageMerger.cs
- src/NServiceBus.Core/Settings/SettingsHolder.cs
Fix for issue https://github.com/Particular/NServiceBus/issues/2622  as a result of bug in https://github.com/Particular/NServiceBus/pull/2587 PR 
`PersistenceExtentions<PersistenceDefinition, StorageType>` did not provide a way for `PersistenceExtentions<PersistenceDefinition>` to know what `StorageType` `PersistenceExtentions` should set as selected storage when using extension method `configuration.UsePersistence<T, S>()`
Items left:
> Bug where individual storage persistence overrides all storage options

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/Issue_2080.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_message_has_a_saga_id.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_sagas_cant_be_found.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
- src/NServiceBus.Core/Sagas/Sagas.cs
- src/NServiceBus.Core/Unicast/Behaviors/InvokeSagaNotFoundBehavior.cs
- src/NServiceBus.Core/Unicast/Behaviors/LoadHandlersBehavior.cs
This PR fixes both:
- IHandleSagaNotFound should only fire if no saga was invoked for the message
- IHandleSagaNotFound fires multiple times for a message that targets multiple sagas
> IHandleSagaNotFound fires multiple times for a message that targets multiple sagas

- src/NServiceBus.Core/Configure.cs
- src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
When a ReflectionTypeLoadException occurs, the Types property may contain null values.  These null values are being inserted directly into the result set in GetAllowedTypes.
Explanation for why nulls exist: http://msdn.microsoft.com/en-us/library/system.reflection.reflectiontypeloadexception.types(v=vs.110).aspx
I also noticed the Types property was bypassing the AssemblyScanner.IsAllowedType check, so I placed the null check in that method and then ran the Types property through it to follow the same semantics used when no exception thrown.
> null values are being inserted into the GetAllowedTypes result set

- src/NServiceBus.Core.Tests/Sagas/TypeBasedSagaMetaModelTests.cs
- src/NServiceBus.Core/Sagas/TypeBasedSagaMetaModel.cs
Whilst upgrading one of our repositories to v5 we noticed that our (admittedly unusual but historically necessary) use of an inheritance chain through to `Saga<>` was broken due to the v5 code-base assuming that only one generic-parameter would exist - *and* - that it would be the `SagaDataEntity`. 
Included in this PR is a slight amendment to `TypeBasedSagaMetaModel.cs` that follows the inheritance chain as to be certain the assumed call to `GetGenericArguments.Single()` will be correct, and thus avoiding the exception below. An accompanying test is included.
```text
System.InvalidOperationExceptionSequence contains more than one element
at System.Linq.Enumerable.Single(IEnumerable`1 source)
at NServiceBus.Sagas.TypeBasedSagaMetaModel.Create(Type sagaType, IEnumerable`1 availableTypes, Co …
```
> Support inheritance-based sagas of +1 generic args

- src/NServiceBus.Core.Tests/Features/FeatureStartupTests.cs
- src/NServiceBus.Core/AutomaticSubscriptions/AutoSubscribe.cs
- src/NServiceBus.Core/Configure.cs
- src/NServiceBus.Core/Features/FeatureActivator.cs
- src/NServiceBus.Core/Features/FeatureRunner.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Unicast/UnicastBus.cs
We should not drive them from `IWantToRunWhenTheBusStartsAndStops`
We should also support the startup tasks to implement `IDisposable`
Closes #2672
Decided to not execute the feature startup on separate task. Because features are now started and stopped all the time it is the feature's responsibility to check whether it makes sense to run. Especially if it is enabled by default. That's why this Pull also changes the `AutoSubscribe` feature
@Particular/engineers please review
> FeatureStartupTasks are not invoked for send only endpoint

- src/NServiceBus.Core.Tests/API/approvals/NServiceBus.Core.approved.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Unicast/Behaviors/CallbackInvocationBehavior.cs
- src/NServiceBus.Core/Unicast/BusAsyncResult.cs
- src/NServiceBus.Core/Unicast/BusAsyncResultEventArgs.cs
- src/NServiceBus.Core/Unicast/Callback.cs
- src/NServiceBus.Core/Unicast/CallbackMessageLookup.cs
- src/NServiceBus.Core/Unicast/CallbackResultEventArgs.cs
- src/NServiceBus.Core/Unicast/ContextualBus.cs
Instead of implementing our own IAsyncResult this delegates to a task, and allows all the task based overrides to work with the task directly instead of wrapping the IAsyncResult.
> Changed callback code to use tasks

- src/NServiceBus.Core.Tests/Serializers/XML/SerializerTests.cs
- src/NServiceBus.Core/Serializers/XML/Serializer.cs
- src/NServiceBus.Core/Serializers/XML/XmlMessageSerializer.cs
So the current XML Serialize does 3 steps
1. write the entire xml to a string
2. UTF8 encode the entire string to a byte array
3. write the whole byte array to the target stream
So we loose the entire memory for the serialization **twice**. this makes @johnsimons angry
This PR changes it over to a streamwriter so we just stream each small text chunk to the target stream.
> use streamwriter for XML

- src/NServiceBus.AcceptanceTests/MessageId/When_message_has_empty_id_header.cs
- src/NServiceBus.AcceptanceTests/MessageId/When_message_has_no_id_header.cs
- src/NServiceBus.AcceptanceTests/Mutators/When_defining_outgoing_message_mutators.cs
- src/NServiceBus.AcceptanceTests/Mutators/When_outgoing_mutator_replaces_instance.cs
- src/NServiceBus.AcceptanceTests/Retries/When_performing_slr.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Impersonation/Windows/WindowsIdentityEnricher.cs
- src/NServiceBus.Core/MessageMutator/IMutateOutgoingMessages.cs
- src/NServiceBus.Core/MessageMutator/IMutateOutgoingPhysicalMessages.cs
- src/NServiceBus.Core/MessageMutator/MutateOutgoingMessageBehavior.cs
- src/NServiceBus.Core/MessageMutator/MutateOutgoingMessagesContext.cs
- src/NServiceBus.Core/MessageMutator/MutateOutgoingPhysicalMessageBehavior.cs
- src/NServiceBus.Core/MessageMutator/MutateOutgoingPhysicalMessageContext.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/v6-obsoletes.cs
* adds obsoletes for the old Bus.Get|SetMessageHeader methods
* introduces a context for the outgoingmessagemutator
* renames the transport message mutator to physical message mutator
@SimonCropp please give this a once over before I fix the doco and upgrade guide
> Allow headers to be set from outgoing mutators

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Persistence/InMemory/Outbox/InMemoryOutboxPersistence.cs
- src/NServiceBus.Core/Persistence/InMemory/Outbox/InMemoryOutboxSettingsExtensions.cs
- src/NServiceBus.Core/Reliability/Outbox/Outbox.cs
- src/NServiceBus.Core/Reliability/Outbox/OutboxSettings.cs
For code only APIs we need to make `OutboxSettings` extensible so that for example RavenDB persistence and NH persistence can write extension methods on top of `OutboxSettings`. This also cleans up the `TimeToKeepDeduplicationData` which was exposed on the `OutboxSettings` but in reality only belongs to the InMemoryOutbox.
@andreasohlund That's what I wanted to talk about today. Without this there is no proper way to expose code only settings for outbox
> Make OutboxSettings extensible for code only APIs

- src/NServiceBus.AcceptanceTests/Basic/When_aborting_the_behavior_chain.cs
- src/NServiceBus.AcceptanceTests/Basic/When_handling_current_message_later.cs
- src/NServiceBus.AcceptanceTests/Basic/When_incoming_headers_should_be_shared.cs
- src/NServiceBus.AcceptanceTests/Sagas/Issue_1819.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_receiving_that_completes_the_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_receiving_that_should_start_a_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_sagas_cant_be_found.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/HandlerOrdering/First.cs
- src/NServiceBus.Core/HandlerOrdering/ISpecifyMessageHandlerOrdering.cs
- src/NServiceBus.Core/HandlerOrdering/Order.cs
- src/NServiceBus.Core/Unicast/Config/LoadMessageHandlersExtentions.cs
- src/NServiceBus.Core/Unicast/Config/RegisterHandlersInOrder.cs
At the moment we have a very IMO unintuitive API to specify message ordering.
1. The user needs to implement `ISpecifyMessageHandlerOrdering`, eg 
```c#
class EnsureOrdering : ISpecifyMessageHandlerOrdering
{
public void SpecifyOrder(Order order)
{
order.Specify(First<H1>.Then<H2>());
}
}
```
2. The user can also specify order via the `config.LoadMessageHandlers` overloads, eg:
```c#
config.LoadMessageHandlers(First<H1>.Then<H2>().AndThen<H3>().AndThen<H4>())
```
```c#
config.ExecuteTheseHandlersFirst(params Type[] handlerTypes)
```
> Simplify the handle ordering API

- src/NServiceBus.AcceptanceTests/Exceptions/StackTraceAssert.cs
@Particular/nservicebus @SimonCropp can you review?
> Added a case that removes "at lambda_method" from clean stack trace when asserting

- src/NServiceBus.Core.Tests/Unicast/Config/ConfigurationSettings.cs
Some while ago generic message handlers were re-enabled in version 4 
and the tests were modified accordingly. However, the test method names
were never changed. This commit corrects that omission.
> Correct unit test names for generic handlers

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Persistence/InMemory/InMemoryPersisterBuilder.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_completing_a_saga_with_the_InMemory_persister.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_completing_a_saga_with_unique_property_with_InMemory_persister.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_multiple_workers_retrieve_same_saga.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_the_same_unique_property_as_a_completed_saga.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_the_same_unique_property_as_another_saga.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_the_same_unique_property_as_the_original_value_of_another_saga_before_updating.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_different_sagas_with_unique_properties.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_property_is_null.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_saga_not_found_return_default.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_saving_a_null_unique_property.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_updating_a_saga_with_the_same_unique_property_as_another_saga.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_updating_a_saga_with_the_same_unique_property_value.cs
- src/NServiceBus.Core.Tests/Sagas/SagaModelTests.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs
- src/NServiceBus.Core/Saga/ISagaPersister.cs
- src/NServiceBus.Core/Sagas/LoadSagaByIdWrapper.cs
- src/NServiceBus.Core/Sagas/PropertySagaFinder.cs
- src/NServiceBus.Core/Sagas/SagaMetaModel.cs
- src/NServiceBus.Core/Sagas/SagaMetadata.cs
- src/NServiceBus.Core/Sagas/SagaMetadataCollection.cs
- src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
- src/NServiceBus.Core/Sagas/Sagas.cs
As @danielmarbach and I started to apply SataMetadata to the NH and RavenDB persisters, some usability concerns came up. So I added a test to validate all my assumptions about what a SagaMetadata should look like based on the Saga under test, and made a few modifications.
First, where `[Unique]` had always been distinct before because of how reflection works, CorrelationProperties were not. Two message mappings pointing to the same saga property would create duplicate correlation properties, which is a mess for a persister to have to deal with. The persister should be able to make the assumption they are already distinct. So I changed that.
Side note: We have a problem with how RavenDB handles this because Raven always assumed one and only one `[Unique]`, and having multiple would …
> Make SagaMetadata CorrelationProps distinct, validate other assumptions

- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_clearing_saga_timeouts.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Persistence/InMemory/InMemoryOutboxPersisterTests.cs
- src/NServiceBus.Core.Tests/Reliability/Outbox/FakeOutboxStorage.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Persistence/InMemory/Outbox/InMemoryOutboxStorage.cs
- src/NServiceBus.Core/Reliability/Outbox/IOutboxStorage.cs
- src/NServiceBus.Core/Reliability/Outbox/OutboxDeduplicationBehavior.cs
- src/NServiceBus.Core/Reliability/Outbox/OutboxStorageOptions.cs
Introduces `OutboxStorageOptions` to float pipeline context stuff into the outbox persister
@Particular/nservicebus thoughts?
> Introduced OutboxStorageOptions

- src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists_and_context_information_added.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Extensibility/ContextBag.cs
- src/NServiceBus.Core/Extensibility/ReadonlyContextBag.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Reliability/Outbox/OutboxStorageOptions.cs
- src/NServiceBus.Core/Saga/SagaPersistenceOptions.cs
Introduces a readonly view onto the `ContextBag`. While working on the saga persister, outbox persister and such I realized that when we pass the `ContextBag` into the persister they should probably not be allowed to modify this bag. 
@Particular/nservicebus thoughts?
> Interface for readonly context bag

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Msmq/MsmqMessageSenderTests.cs
- src/NServiceBus.Core.Tests/Msmq/MsmqUtilitiesTests.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Core/DefaultTimeoutManager.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Hosting/Windows/TimeoutDispatcherProcessorBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Hosting/Windows/TimeoutMessageProcessorBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Hosting/Windows/TimeoutPersisterReceiver.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenUnsubscribeTerminator.cs
- src/NServiceBus.Core/Transports/DispatchOptions.cs
- src/NServiceBus.Core/Unicast/ContextualBus.cs
It aligns the `DispatchOptions` with the newly introduced options
@Particular/nservicebus please review.
> Making context bag mandatory and exposed as readonly

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Timeout/InMemoryTimeoutPersisterTests.cs
- src/NServiceBus.Core.Tests/Timeout/InMemoryTimeoutPersisterThreadTests.cs
- src/NServiceBus.Core.Tests/Timeout/When_fetching_timeouts_from_storage.cs
- src/NServiceBus.Core.Tests/Timeout/When_pooling_timeouts.cs
- src/NServiceBus.Core.Tests/Timeout/When_receiving_timeouts.cs
- src/NServiceBus.Core.Tests/Timeout/When_removing_timeouts_from_the_storage.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Core/DefaultTimeoutManager.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Core/IPersistTimeouts.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Core/IQueryTimeouts.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Core/TimeoutPersistenceOptions.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Hosting/Windows/TimeoutDispatcherProcessorBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Hosting/Windows/TimeoutMessageProcessorBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Hosting/Windows/TimeoutPersisterReceiver.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Persistence/InMemory/TimeoutPersister/InMemoryTimeoutPersister.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/ISubscriptionStorage.cs
We want to be able to float context information into the timeout persister. This makes this possible. This splits also the `IPersistTimeouts` interface into two concerns. One is the timeout querying `IQueryTimeouts` and the other one is the timeout storage operations `IPersistTimeouts`.
@andreasohlund I also removed a few of the timeout persister base tests (which were only ever used with the `InMemoryTimeoutPersister`. I quickly checked and I didn't see that we deploy them with any kind of nuget package or so.
~~Please see there are still two TODO left~~
~~https://github.com/Particular/NServiceBus/pull/2802/files#diff-f71f998dbe767ca05a306b7567d9bccaR27~~
~~I will update this as …
> Timeout persistence options

- src/NServiceBus.AcceptanceTests/Routing/When_publishing_from_sendonly.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Persistence/InMemory/SubscriptionStorage/InMemorySubscriptionStorage.cs
- src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorage.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/IInitializableSubscriptionStorage.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/IQuerySubscriptions.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/ISubscriptionStorage.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/StorageInitializer.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/SubscriptionReceiverBehavior.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/SubscriptionStorageOptions.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/Routing/StorageDrivenPublishing/StorageDrivenDispatcher.cs
- src/NServiceBus.PerformanceTests/PubSub/PubSubTestCase.cs
* It introduces `SubscriptionStorageOptions`
* Split the `ISubscriptionStorage` into `IQuerySubscriptions`, `ISubscriptionStorage` and `IInitializableSubscriptionStorage`
We can debate whether we still need the `Init()` and therefore the `IInitializableSubscriptionStorage` I quickly checked and at least `MsmqSubscriptionStorage` and `NHibernate` needs it. We could also say that initializing the storage itself is a concern of the persister and no longer of the core. I'm fine with that as well. Thoughts?
@Particular/nservicebus please review.
> Introduced SubscriptionStorageOptions

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Serializers/XML/Issue_2796.cs
- src/NServiceBus.Core/Serializers/XML/Serializer.cs
Users with V5.X endpoints configured to use XML message serialization, when using fields of type `System.Object` that are assigned primitive or simple (e.g. Guid, DateTime) types.
Serialization will not generate namespaces for simple types, and deserialization will fail, since the message element does not have all the appropriate namespaces.
Trying to serialize, then deserialize the following type fill fail, when the `Value` property is assigned a simple type, e.g. Guid:
public class SerializedPair
{
public string Key { get; set; }
public object Value { get; set; }
}
none
I'm currently upgrading from NServiceBus 4.7.5 to NServiceBus 5.2.4, and when using the XmlSerializer, I noticed that it generates an invalid XML message when I try to serialize a message - 
the namespaces for the simple …
> XmlSerializer now serializes properties of `object` type properly

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/SelfVerification/When_running_acceptance_tests.cs
Just a little bit of reflection to make sure that when acceptance tests are run in the core, all saga entities must have virtual properties, so that we don't wait until we hit NHibernate to figure that out, and waste time in the process.
> Make sure a Saga entity in acceptance tests always has virtual members

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_containing_a_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_base_class_message_hits_a_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_existing_saga_instance_exists.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists_and_context_information_added.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists_and_found_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_saga_message_goes_through_the_slr.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_an_endpoint_replies_to_a_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_doing_request_response_between_sagas.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_message_has_a_saga_id.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_receiving_that_completes_the_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_receiving_that_should_start_a_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_replies_to_message_published_by_a_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_reply_from_a_finder.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_has_a_non_empty_constructor.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_id_changed.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_is_mapped_to_complex_expression.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_sagas_cant_be_found.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_handle.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_timeout.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_started_by_base_event_from_other_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_started_by_event_from_another_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_timeout_hit_not_found_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_using_a_received_message_for_timeout.cs
- src/NServiceBus.AcceptanceTests/Sagas/when_receiving_multiple_timeouts.cs
- src/NServiceBus.AcceptanceTests/Sagas/when_reply_from_saga_not_found_handler.cs
- src/NServiceBus.AcceptanceTests/SelfVerification/When_running_saga_tests.cs
We're awful at naming things. There are more names available than TestSaga, MySaga, Saga1, Saga2, etc. NHibernate mapping conventions (although not necessarily a unique problem for NHibernate) maps saga names based on the class names (not full names, so namespace doesn't matter!) of the Saga and SagaEntity. If not unique, then the same SQL table is shared between the tests, even if their structure is radically different, introducing subtle testing bugs based on which tests run first and get the opportunity to create the table.
Ideally, all sagas would be well named so that they described, in some way, what was under test. But that takes more time and energy than I have available today.
This PR introduces a reflection test to ensure that all Sagas and SagaEntities have unique names, at the …
> Acceptance test sagas/entities need unique names

- src/NServiceBus.AcceptanceTests/Exceptions/Handler_and_UowEnd_throws.cs
- src/NServiceBus.AcceptanceTests/Exceptions/Handler_throws.cs
- src/NServiceBus.AcceptanceTests/Exceptions/Handler_throws_AggregateEx.cs
- src/NServiceBus.AcceptanceTests/Exceptions/StackTraceAssert.cs
- src/NServiceBus.AcceptanceTests/Exceptions/Uow_Begin_and_diff_End_throws.cs
- src/NServiceBus.AcceptanceTests/Exceptions/Uow_Begin_throws.cs
- src/NServiceBus.AcceptanceTests/Exceptions/Uow_End_throws.cs
- src/NServiceBus.Core.Tests/Encryption/ConfigureRijndaelEncryptionServiceTests.cs
- src/NServiceBus.Core.Tests/Utils/ExceptionHeaderHelperTests.cs
- src/NServiceBus.Core.Tests/Utils/Reflection/ReflectTests.cs
@SimonCropp you may want to have a look at the changes in `StackTraceAssert` helper.
I used the `StackTrace` class to get the localized stack traces without the file infos so we don't need to do that manually. As for the culture I decided to go with the minimal invasive way, which is setting the UICulture and accessing the Exception on a separate thread to avoid potential issues. This seems to work fine for the localization of the stack trace (although it won't work for certain exception messages like ArgumentNullException, but that doesn't matter here).
let me know what you think
> Fix culture dependent tests

- src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
- src/NServiceBus.AcceptanceTests/Exceptions/TransportMessage/Cant_convert_NoTransactions.cs
- src/NServiceBus.AcceptanceTests/Exceptions/TransportMessage/Cant_convert_SuppressedDTC.cs
Acceptance Tests using the ScenarioContext.Logs collection to define *Done* conditions on acceptance tests may run into InvalidOperationExceptions due to concurrent access to the underlying List.
> make ScenarioContext.Logs threadsafe

- src/NServiceBus.AcceptanceTesting/ContextAppender.cs
- src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
- src/NServiceBus.AcceptanceTesting/Support/ActiveRunner.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
put the Exceptions into a list instead concatenating all exception's string representations. This should allow better assertions, filtering and logging.
> log the original exception in ScenarioContext

- src/NServiceBus.AcceptanceTesting/ContextAppender.cs
- src/NServiceBus.Core/Faults/MoveFaultsToErrorQueueBehavior.cs
- src/NServiceBus.Core/Features/DisplayDiagnosticsForFeatures.cs
- src/NServiceBus.Core/Persistence/PersistenceStartup.cs
- src/NServiceBus.Core/Pipeline/PipelineCollection.cs
- src/NServiceBus.Core/Pipeline/PipelineModelBuilder.cs
- src/NServiceBus.Core/Unicast/Config/UnicastBus.cs
@SimonCropp first pass on dialing back the logging. Please review.
After this the acpt tests output:
```
smqTransport - Started @ 2015-08-26 16:18:30
Trial for Particular Service Platform is still active, trial expires on 2016-06-25.
Queue ANDREAS2015\private$\StartupIsComplete.StartedEndpoint does not exist.
Did not attempt to add user 'Andreas2015\andreas.ohlund' to group 'Performance Monitor Users' since process is not running with elevate privileges. Processing will continue. To manually perform this action run the following command from an admin console:
net localgroup "Performance Monitor Users" "Andreas2015\andreas.ohlund" /add
Queue [private$\StartupIsComplete.StartedEndpoint] is running with [Everyone] and [NT AUTHORITY\ANONYMOUS LOGON] permissions. Consider setting appropriate …
```
> Less info logging

- src/NServiceBus.AcceptanceTesting/Support/EndpointBehavior.cs
- src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
As part of the Async/Await work we found out the the `Whens` are executed at the wrong place. Previously they were executed during the initialization phase of the endpoint. But they should be executed after the `Givens` during the startup phase of the endpoint.
Removed the unnecessary contextChanged semphare (no longer needed because of no more appdomains) and also the `[ Serializable]` attribute usage.
> ATT Framework Improvements

- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_Subscribing_to_errors.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_sagas_cant_be_found.cs
As part of the async/await work I figured the ATT infrastructure is still a bit too complex and heavyweight regarding unnecessary parallelism. This PR introduces two changes. One change is the reduction of the parallel execution of the `should` verify and the `SpinWait` on the `done` delegate. This effectively reduces the number of background operations by the number of runners and endpoints. Therefore reducing the load on the thread pool and leading to less allocations and ramping up in the ThreadPool. 
Furthermore I changed `When_sagas_cant_be_found` to be a bit smarter regarding its execution. Before these ATTs just lasted each for over 10 seconds. Now they finish as soon as possible. To be honest I still think these tests are a bit weird but at least this improves the execution time. …
> More att framework improvements

- src/NServiceBus.AcceptanceTesting/Support/EndpointConfiguration.cs
- src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
- src/NServiceBus.AcceptanceTesting/Support/IEndpointSetupTemplate.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.AcceptanceTests/ConfigureMsmqTransport.cs
- src/NServiceBus.AcceptanceTests/Encryption/EndpointTemplates/ConfigureExtensions.cs
- src/NServiceBus.AcceptanceTests/Encryption/EndpointTemplates/DefaultPublisher.cs
- src/NServiceBus.AcceptanceTests/Encryption/EndpointTemplates/DefaultServer.cs
`Configure` and `Cleanup` phase for persistence and transport are now async as well.
> Cleanup and Configuration phase of ATTs is async as well

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Gateway/IDeduplicateMessages.cs
- src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs
The question is:
Should this still be in core?
> Gateway message deduplication is async

- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_clearing_saga_timeouts.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Persistence/InMemory/InMemoryOutboxPersisterTests.cs
- src/NServiceBus.Core.Tests/Reliability/Outbox/FakeOutboxStorage.cs
- src/NServiceBus.Core/Persistence/InMemory/Outbox/InMemoryOutboxStorage.cs
- src/NServiceBus.Core/Reliability/Outbox/IOutboxStorage.cs
- src/NServiceBus.Core/Reliability/Outbox/OutboxDeduplicationBehavior.cs
@timbussmann and I decided to streamline the API of the timeout persister and the outbox storage. Out parameters are not supported with async/await. For simplicity we went with returning null if nothing found. Here in this PR I also enforce that complete `OutboxMessage` needs to be passed into `Store`.
@Particular/tf-asyncawait Please review
> OutboxStorage is async

- src/NServiceBus.AcceptanceTests/Sagas/When_a_existing_saga_instance_exists.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_saga_message_goes_through_the_slr.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_receiving_that_completes_the_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_has_a_non_empty_constructor.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_using_a_received_message_for_timeout.cs
- src/NServiceBus.AcceptanceTests/SelfVerification/When_running_saga_tests.cs
Similar to #2814 - more ensuring names are unique. But this time, the target is declaring classes when saga entities are nested types, because NHibernate (for historical reasons, I think) will use the declaring type (one direct parent relationship, not all the way to the top) to determine the table name.
One acceptance test guarantees uniqueness via reflection, and the rest of the changes fix it for the acceptance tests in core.
> Guarantee uniqueness for saga entity declaring classes as well, for NH

- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs
- src/NServiceBus.Core/TaskEx.cs
- src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
Fixed the `MessagePump` to be able to process messages in parallel and proper shutdown. `AttachToParent` doesn't work with async.
@Particular/tf-asyncawait Please review
@andreasohlund We should have seen that before. But this is now the correct version. Try it out in your workbench sample.
> MessagePump receive in parallel and await pending receives

- src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
- src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
- src/NServiceBus.AcceptanceTesting/Support/IScenarioWithEndpointBehavior.cs
- src/NServiceBus.AcceptanceTesting/Support/SimulatedException.cs
- src/NServiceBus.AcceptanceTests/NonTx/When_sending_inside_ambient_tx.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_Subscribing_to_errors.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_doing_flr_with_default_settings.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_doing_flr_with_dtc_on.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_doing_flr_with_native_transactions.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_fails_flr.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_fails_with_retries_set_to_0.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_fails_retries.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_regular_exception.cs
- src/NServiceBus.AcceptanceTests/Recoverability/When_error_is_overridden_in_code.cs
- src/NServiceBus.AcceptanceTests/Recoverability/When_message_with_TimeToBeReceived_fails.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_a_message_is_audited.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_a_message_is_forwarded.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_blowing_up_just_after_dispatch.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_saga_message_goes_through_the_slr.cs
- src/NServiceBus.AcceptanceTests/Tx/When_receiving_with_native_multi_queue_transaction.cs
- src/NServiceBus.AcceptanceTests/Tx/When_receiving_with_transactions_disabled.cs
* adds a `SimulatedException` for acceptance tests to use instead of `Exception`
* allows a more fine grained `AllowExceptions()` configuration which should avoid allowing all Exceptions and possibly miss a non-expected exception
* adds a `AllowSimulatedExceptions()` configuration option for Scenario.Define which is a shortcut to `AllowExceptions(e => e is SimulatedException)`
* replaced all test specific fake/simulated exception classes
> add SimulatedException for acceptance tests

- src/NServiceBus.AcceptanceTesting/Support/IBusAdapter.cs
- src/NServiceBus.AcceptanceTests/Audit/When_auditing_message_with_TimeToBeReceived.cs
- src/NServiceBus.AcceptanceTests/Basic/When_handling_current_message_later.cs
- src/NServiceBus.AcceptanceTests/Recoverability/When_message_with_TimeToBeReceived_fails.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Fakes/FakeBus.cs
- src/NServiceBus.Core/IBus.cs
- src/NServiceBus.Core/Unicast/ContextualBus.cs
- src/NServiceBus.Core/Unicast/UnicastBusInternal_IBusImpl.cs
- src/NServiceBus.Core/obsoletes.cs
`IBus.HandleCurrentMessageLater` is now async
> IBus.HandleCurrentMessageLater is async

- src/NServiceBus.AcceptanceTests/FakeTransport/FakeDispatcher.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Msmq/MsmqMessageSenderTests.cs
- src/NServiceBus.Core.Tests/Timeout/FakeMessageDispatcher.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Reliability/Outbox/OutboxDeduplicationBehavior.cs
- src/NServiceBus.Core/Reliability/Outbox/OutboxDispatchStrategy.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenUnsubscribeTerminator.cs
- src/NServiceBus.Core/Routing/StorageDrivenPublishing/StorageDrivenDispatcher.cs
- src/NServiceBus.Core/TransportDispatch/DefaultDispatchStrategy.cs
- src/NServiceBus.Core/Transports/IDispatchMessages.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqMessageSender.cs
- src/NServiceBus.Core/Transports/TransportOperation.cs
- src/NServiceBus.Core/Unicast/ContextualBus.cs
Changed the API of `IDispatchMessages` to be able to pass a collection of `TransportOperation`s to be dispatched to the transport. Rationale:
* It allows for batching sends which can improve performance of certain transports
* It allows to get rid of `StorageDrivenDispatcher`
* It makes the concept of the transport operation explicit
> Batched dispatching

- src/NServiceBus.AcceptanceTests/Sagas/When_doing_request_response_between_sagas.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_timeout.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_started_by_event_from_another_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_timeout_hit_not_found_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_using_ReplyToOriginator.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_using_a_received_message_for_timeout.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_using_contain_saga_data.cs
- src/NServiceBus.AcceptanceTests/Sagas/when_receiving_multiple_timeouts.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Sagas/Saga.cs
Makes the reminders of the Saga infrastructure async. 
Discussed with @andreasohlund and @johnsimons that `MarkAsComplete` doesn't need to be virtual. I removed it here.
@udidahan do you see any reasons why `MarkAsComplete` should be virtual?
> Saga async

- src/NServiceBus.Core/Scheduling/DefaultScheduler.cs
- src/NServiceBus.Core/Unicast/StartAndStoppablesRunner.cs
@ramonsmits I checked the current continuations in the core. They should be fine regarding `ContinueWith`
> DefaultScheduler uses `Task.Run` + minor cleanups

- src/NServiceBus.AcceptanceTests/Sagas/When_receiving_that_completes_the_saga.cs
When_receiving_that_completes_the_saga makes assumptions about message ordering
> When_receiving_that_completes_the_saga makes assumptions

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/NonDTC/When_dispatching_deferred_message_fails_without_dtc.cs
- src/NServiceBus.AcceptanceTests/Timeouts/OutdatedTimeoutPersister.cs
- src/NServiceBus.AcceptanceTests/Timeouts/TransportWithFakeQueues.cs
- src/NServiceBus.AcceptanceTests/Timeouts/UpdatedTimeoutPersister.cs
- src/NServiceBus.AcceptanceTests/Timeouts/When_dispatched_timeout_already_removed_from_timeout_storage.cs
- src/NServiceBus.AcceptanceTests/Timeouts/When_endpoint_uses_outdated_timeout_persistence_with_disabled_dtc.cs
- src/NServiceBus.AcceptanceTests/Timeouts/When_endpoint_uses_outdated_timeout_persistence_with_dtc.cs
- src/NServiceBus.AcceptanceTests/Timeouts/When_endpoint_uses_outdated_timeout_persistence_without_dtc.cs
- src/NServiceBus.AcceptanceTests/Timeouts/When_endpoint_uses_updated_timeout_persistence.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Persistence/InMemory/TimeoutPersister/InMemoryTimeoutPersister.cs
- src/NServiceBus.Core/Timeout/Core/IPersistTimeoutsV2.cs
- src/NServiceBus.Core/Timeout/Core/TimeoutPersistenceVersionCheck.cs
- src/NServiceBus.Core/Timeout/Core/TimeoutPersistenceVersionCheckExtension.cs
- src/NServiceBus.Core/Timeout/Hosting/Windows/TimeoutDispatcherProcessor.cs
- src/NServiceBus.Core/Timeout/Hosting/Windows/TimeoutMessageProcessor.cs
You might be affected if you are using one of the following transport configurations:
* RabbitMQ transport
* Azure transport 
* MSMQ or SQL transport with distributed transactions (DTC) **disabled**.
**and** you are using timeouts or deferred messages (e.g. `Bus.Defer(...)`)
When experiencing connectivity issues with the transport there's a chance that a due timeout/deferred message is lost. Therefore the message will never arrive.
We highly recommend to update to the latest patch versions of your NServiceBus and optional persistence and transport packages. For more details see issue #2885
Connects to #2885
> Hotfix 5.2.8: prevent timeout message loss when not using DTC

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_distributing_a_command.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_updating_correlation_property.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_updating_a_saga_with_the_same_unique_property_as_another_saga.cs
- src/NServiceBus.Core/Sagas/ActiveSagaInstance.cs
- src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
Changing the value of correlated properties once the saga is loaded is not longer allowed
> Prevent saga correlation properties to be modified

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/When_forgetting_to_set_a_corr_property.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_message_has_a_saga_id.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_id_changed.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_handle.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_timeout.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_timeout_hit_not_found_saga.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_using_a_received_message_for_timeout.cs
- src/NServiceBus.Core/Sagas/ActiveSagaInstance.cs
We now makes sure that correlated saga properties are assigned a value to catch the common misstake to forget to assign the property to the value of the incoming message property.
> Correlated saga properties must have a value

- src/impl/unicast/transport/NServiceBus.Unicast.Transport.Transactional.Config/AdvancedTransactionalConfig.cs
- src/impl/unicast/transport/NServiceBus.Unicast.Transport.Transactional.Config/Bootstrapper.cs
You might be affected if you disabled DTC **and** you are using timeouts.
When experiencing connectivity issues with the transport there's a chance that a due timeout/deferred message is lost. Therefore the message will never arrive.
We highly recommend to upgrade to NServiceBus 4.4.8 or higher. For more details see issue #2885
Connects to #2885
> prevent timeout message loss when not using DTC

- src/NServiceBus.Core/Licensing/ConfigureLicenseExtensions.cs
- src/NServiceBus.Core/Licensing/LicenseManager.cs
- src/NServiceBus.Core/Licensing/LicenseReminder.cs
- src/NServiceBus.Core/Unicast/UnicastBusInternal.cs
fixes #3015 
removing static variables on LicenseManager. LicenseManager is registered in the container instead.
> Remove statics from LicenseManager

- src/impl/encryption/NServiceBus.Encryption.Rijndael.Config/ConfigureRijndaelEncryptionService.cs
- src/impl/encryption/NServiceBus.Encryption.Rijndael.Config/NServiceBus.Encryption.Rijndael.Config.csproj
- src/impl/encryption/NServiceBus.Encryption.Rijndael.Config/RijndaelEncryptionServiceConfig.cs
- src/impl/encryption/NServiceBus.Encryption.Rijndael.Config/RijndaelEncryptionServiceConfigValidations.cs
- src/impl/encryption/NServiceBus.Encryption.Rijndael.Config/RijndaelExpiredKey.cs
- src/impl/encryption/NServiceBus.Encryption.Rijndael.Tests/ConfigureRijndaelEncryptionServiceTests.cs
- src/impl/encryption/NServiceBus.Encryption.Rijndael.Tests/EncryptionServiceTests.cs
- src/impl/encryption/NServiceBus.Encryption.Rijndael.Tests/NServiceBus.Encryption.Rijndael.Tests.csproj
- src/impl/encryption/NServiceBus.Encryption.Rijndael.Tests/RijndaelEncryptionServiceConfigValidationsTests.cs
- src/impl/encryption/NServiceBus.Encryption.Rijndael/EncryptionService.cs
- src/impl/encryption/NServiceBus.Encryption.Rijndael/Headers.cs
- src/impl/encryption/NServiceBus.Encryption.Rijndael/NServiceBus.Encryption.Rijndael.csproj
Connects to Particular/PlatformDevelopment#423
Fixes: #3017 #3018
> Rijndael encryption service: Possible data corruption when using rotating encryption keys v3.3.x

- src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
- src/NServiceBus.AcceptanceTests/Encryption/When_using_Rijndael_with_config.cs
- src/NServiceBus.AcceptanceTests/Encryption/When_using_Rijndael_with_custom.cs
- src/NServiceBus.AcceptanceTests/Encryption/When_using_Rijndael_without_incoming_key_identifier.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj
- src/NServiceBus.Core.Tests/Encryption/ConfigureRijndaelEncryptionServiceTests.cs
- src/NServiceBus.Core.Tests/Encryption/RijndaelEncryptionServiceTest.cs
- src/NServiceBus.Core.Tests/Encryption/ValidationFixture.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core/Encryption/ConfigureRijndaelEncryptionService.cs
- src/NServiceBus.Core/Encryption/EncryptionMutator.cs
- src/NServiceBus.Core/Encryption/KeyFormat.cs
- src/NServiceBus.Core/Encryption/RijndaelEncryptionService.cs
- src/NServiceBus.Core/Encryption/RijndaelEncryptionServiceConfig.cs
- src/NServiceBus.Core/Encryption/RijndaelEncryptionServiceConfigValidations.cs
- src/NServiceBus.Core/Encryption/RijndaelExpiredKey.cs
- src/NServiceBus.Core/Headers.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.PerformanceTests/Program.cs
- src/NServiceBus.PowerShell.Development/NServiceBus.PowerShell.Development.csproj
- src/NServiceBus.sln
Connects to Particular/PlatformDevelopment#423
Fixes: #2994 #3017 #3018 #3019
> Rijndael encryption service: Possible data corruption when using rotating encryption keys v5.2.x

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Persistence/InMemory/AnotherSagaWithTwoUniquePropertiesData.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/SagaWithTwoUniquePropertiesData.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/SagaWithUniquePropertyData.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/SimpleSagaEntity.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/TestSagaData.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_property_is_null.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_saving_a_null_unique_property.cs
- src/NServiceBus.Core.Tests/Pipeline/Incoming/InvokeHandlerTerminatorTest.cs
- src/NServiceBus.Core.Tests/Sagas/SagaMetadataCreationTests.cs
- src/NServiceBus.Core.Tests/Sagas/SagaModelTests.cs
- src/NServiceBus.Core.Tests/Sagas/When_saga_has_no_start_message.cs
- src/NServiceBus.Core/Sagas/SagaMetadata.cs
Validating that users have marked at least one of the handled messages as allowed to start the given saga.
> Require sagas to have at least one start message

- src/NServiceBus.AcceptanceTests/ScenarioDescriptors/AllTransports.cs
- src/NServiceBus.AcceptanceTests/Tx/When_receiving_with_native_multi_queue_transaction.cs
I've made sure that AllNativeMultiQueueTransactionTransports is constructed properly (now this test is skipped for MSMQ). Secondly I've enabled flr to make sure retry happens.
> Fix for broken mulitqueue transaction test

- src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/DispatchTimeoutBehaviorTest.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs
- src/NServiceBus.Core/Persistence/InMemory/TimeoutPersister/InMemoryTimeoutPersister.cs
In case a timeout was concurrently removed from the storage, throw an exception to abort processing the message. This is required for DTC scenarios in order to avoid duplicate message dispatches.
> cause a rollback when timeout already removed

- src/NServiceBus.AcceptanceTests/FakeTransport/FakeQueueCreator.cs
- src/NServiceBus.AcceptanceTests/Performance/ProcessingOptimizations/When_using_concurrency_limit.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Transports/ICreateQueues.cs
- src/NServiceBus.Core/Transports/Msmq/QueueCreator.cs
- src/NServiceBus.Core/Unicast/Queuing/QueuesCreator.cs
Connects to #3076 
Creation of queues is async and done in parallel. I decided to go for parallel because this can speed up the installation process drastically. The downside of this would be that for example for SqlServer transport, since the connection is not thread safe, each `CreateQueueIfNecessary` would require its own connection. Thoughts?
> Queue creation is async and executed in parallel.

- src/NServiceBus.Core/Routing/Legacy/ReadyMessageSender.cs
Connect to #3076 
@janovesk @SzymonPobiega can you try to avoid `GetAwaiter().GetResult()` from now on?
> ReadyMessageSender no longer uses GetAwaiter().GetResult()

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/DataBus/When_applying_the_databus_message_mutator_to_incoming_messages.cs
- src/NServiceBus.Core.Tests/Pipeline/BehaviorRegistrationsCoordinatorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/Incoming/InvokeHandlerTerminatorTest.cs
- src/NServiceBus.Core.Tests/Unicast/LoadHandlersBehaviorTests.cs
- src/NServiceBus.Core/Pipeline/Incoming/IncomingContext.cs
- src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerContext.cs
- src/NServiceBus.Core/Pipeline/Incoming/LogicalMessageProcessingContext.cs
- src/NServiceBus.Core/Pipeline/Incoming/PhysicalMessageProcessingContext.cs
- src/NServiceBus.Core/Serializers/XML/Config/XmlSerialization.cs
- src/NServiceBus.Core/Unicast/Messages/MessageMetadata.cs
force all properties on a context to be provided via constructor to avoid magic setups in the ContextBag hierarchy within the same Pipeline.
Connects to Particular/PlatformDevelopment#187
> removed Get<IncomingMessage>() usages from IncomingContext

- src/NServiceBus.AcceptanceTests/CriticalError/When_registering_a_custom_criticalErrorHandler.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Faults/ForwardFaultsToErrorQueueTests.cs
- src/NServiceBus.Core/CriticalError/ConfigureCriticalErrorAction.cs
- src/NServiceBus.Core/CriticalError/CriticalError.cs
- src/NServiceBus.Core/CriticalError/CriticalErrorHandling.cs
- src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs
CriticalError now requires a `Func<string, Exception, Task>` instead of `Action<string, Exception>`. This allows callers of CriticalError to await asynchronous critical error callbacks.
> CriticalError supports async callbacks

- src/NServiceBus.Core/Encryption/EncryptionMutator.cs
- src/NServiceBus.Core/Encryption/Encryptor.cs
Found by @hmemcpy and the perf test suite. Since with V6 behaviors became pipeline static the `EncryptionMutator` was reused and multiple threads tried to access the `visitedMembers` HashSet.
> Removed unnecessary state in EncryptionMutator to fix multi threading issues

- src/NServiceBus.Core/UnitOfWork/UnitOfWorkBehavior.cs
Similar to #3102, the behavior was accessed from different threads, causing an out of bounds exception. This PR removes the state.
> Removed state from unit of work behavior

- src/NServiceBus.Core/Transports/Msmq/MsmqTransportConfigurator.cs
- src/NServiceBus.Core/Unicast/Transport/Config/UseTransportExtensions.cs
Msmq configurator should only run when msmq is the actual transport
> Configure msmq only when needed

- src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Endpoint.cs
Aligned the endpoint creation with the previous V5 model. The problem of the latest develop approach is that we guide users with obsoletes to use `Endpoint.Create` instead of `Bus.Create` but `Endpoint.Create` return an initializable endpoint. Therefore we bloat the code unnecessarily. With this change `Endpoint.Create` returns a startable endpoint similar to V5 `Bus.Create`
@SzymonPobiega needs this for the doco updates.
> Changed endpoint creation to better represent the V5 model

- src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
since c# doesn't do tail recursion we can avoid some unnecessary, long lived frames on the stack. Also removes an await.
> replace recursion with while loop

- src/NServiceBus.AcceptanceTests/FakeTransport/FakeTransport.cs
- src/NServiceBus.AcceptanceTests/Performance/ProcessingOptimizations/When_using_concurrency_limit.cs
- src/NServiceBus.AcceptanceTests/Routing/When_distributing_an_event.cs
- src/NServiceBus.AcceptanceTests/ScaleOut/When_no_discriminator_is_available.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Transports/Msmq/Msmq.cs
- src/NServiceBus.Core/Transports/TransportDefinition.cs
- src/NServiceBus.Core/Unicast/Config/UnicastBus.cs
@SzymonPobiega is that what you had in mind for passing settings?
I changed the test for distributing events, because the it made assumptions about format of address for scale-out that weren't true for SqlTransport, and don't have to be true for other transports either.
GetDiscriminatorForThisEndpointInstance() => would it be more descriptive if it was called "TransportDiscriminator" or "TransportSpecificDiscriminator"? Right now the difference between this and user discriminator isn't obvious.
> Routing - transport address changes required by SQLTransport

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_broadcasting_a_command.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Routing/DistributionPolicy.cs
- src/NServiceBus.Core/Routing/RoutingSettings.cs
* Renamed `SetDistributionStrategy` to `Set` as per @SeanFeldman 's suggestion
* Added an acceptance test to verify that overriding distribution strategies works (and that `AllInstancesDistributionStrategy` does what it is supposed to do)
> AT for broadcast + slight API rename

- src/NServiceBus.Core.Tests/Routing/EndpointInstancesTests.cs
- src/NServiceBus.Core/EnumerableEx.cs
- src/NServiceBus.Core/Routing/EndpointInstances.cs
Previously following routing setup would throw because no instances are configured:
```
c.Routing().UnicastRoutingTable.AddStatic(typeof(Request), new EndpointName("Sales"));
```
In order to make it work, we required to register a default single instance:
```
c.Routing().EndpointInstances.AddStatic(new EndpointName("Sales"), new EndpointInstanceName(new EndpointName("Sales"), null, null));
```
Now it will work perfectly fine without that line.
> Changed the instance resolution policy to default to single instance

- src/NServiceBus.Core.Tests/AssemblyScanner/When_scanning_directory_with_nested_directories.cs
- src/NServiceBus.Core.Tests/Config/When_using_initialization.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core/BusConfiguration.cs
If you specify a non-default ctor on a type that implements `INeedInitialization`, it would throw a nasty `System.MissingMethodException : No parameterless constructor defined for this object.` from within `Activator.CreateInstance`.
This PR checks for a presence of a default ctor prior to trying to create an instance, and would throw a meaningful exception otherwise.
> Throwing a meaningful exception when implementing INeedInitialization

- src/impl/encryption/NServiceBus.Encryption.Rijndael/EncryptionService.cs
The Rijndael encryption service modified the global headers resulting in all message to contain the key identifier header. This is not a critical bus and only fixed in version 5.2.11
- Setting of message header can not result in unhandled exception. (v3.3.18, v4.7.10, v5.0.9, v5.1.7, v5.2.11)
You are affected by the race condition when you:
- Use the latest version …
> Hotfix 3.3.18

- src/NServiceBus.Core/Encryption/Rijndael/EncryptionService.cs
The Rijndael encryption service modified the global headers resulting in all message to contain the key identifier header. This is not a critical bug and only fixed in version 5.2.11
- Setting of message header can not result in unhandled exception. (v3.3.18, v4.7.10, v5.0.9, v5.1.7, v5.2.11)
You are affected by the race condition when you:
- Use the latest version …
> Hotfix 4.7.10

- src/NServiceBus.Core.Tests/Encryption/RijndaelEncryptionServiceTest.cs
- src/NServiceBus.Core/Encryption/RijndaelEncryptionService.cs
The Rijndael encryption service modified the global headers resulting in all message to contain the key identifier header. This is not a critical bus and only fixed in version 5.2.11
- Setting of message header can not result in unhandled exception. (v3.3.18, v4.7.10, v5.0.9, v5.1.7, v5.2.11)
You are affected by the race condition when you:
- Use the latest version …
> Hotfix 5.0.9

- src/NServiceBus.Core.Tests/Encryption/RijndaelEncryptionServiceTest.cs
- src/NServiceBus.Core/Encryption/RijndaelEncryptionService.cs
The Rijndael encryption service modified the global headers resulting in all message to contain the key identifier header. This is not a critical bus and only fixed in version 5.2.11
- Setting of message header can not result in unhandled exception. (v3.3.18, v4.7.10, v5.0.9, v5.1.7, v5.2.11)
You are affected by the race condition when you:
- Use the latest version …
> Hotfix 5.1.7

- src/NServiceBus.AcceptanceTests/Encryption/When_using_Rijndael_with_multikey.cs
- src/NServiceBus.Core.Tests/Encryption/ConfigureRijndaelEncryptionServiceTests.cs
- src/NServiceBus.Core.Tests/Encryption/ConventionBasedEncryptedStringSpecs.cs
- src/NServiceBus.Core.Tests/Encryption/Issue_701.cs
- src/NServiceBus.Core.Tests/Encryption/Issue_949.cs
- src/NServiceBus.Core.Tests/Encryption/Mailing_list_complex_dto.cs
- src/NServiceBus.Core.Tests/Encryption/RijndaelEncryptionServiceTest.cs
- src/NServiceBus.Core.Tests/Encryption/When_message_contains_props_and_fields_that_cannot_be_set.cs
- src/NServiceBus.Core.Tests/Encryption/WireEncryptedStringSpecs.cs
- src/NServiceBus.Core/Encryption/ConfigureRijndaelEncryptionService.cs
- src/NServiceBus.Core/Encryption/DecryptBehavior.cs
- src/NServiceBus.Core/Encryption/EncryptBehavior.cs
- src/NServiceBus.Core/Encryption/EncryptionMutator.cs
- src/NServiceBus.Core/Encryption/IEncryptionServiceWithContext.cs
- src/NServiceBus.Core/Encryption/RijndaelEncryptionService.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
The Rijndael encryption service modified the global headers resulting in all message to contain the key identifier header.
- #3119 [RijndaelEncryptionService sets the outgoing headers globally, applying it to messages without encrypted properties as well](https://github.com/Particular/NServiceBus/issues/3119).
- Setting of message header can not result in unhandled …
> Hotfix 5.2.11

- src/NServiceBus.AcceptanceTests/Routing/SubscriptionBehavior.cs
For transports that have native pub/sub, `ProcessSubscriptionRequests` step (`SubscriptionReceiverBehavior`) doesn't exist, causing `SubscriptionBehavior` step to fail. By registering with `InsertBeforeIfExists` transports with native pub/sub can run ATTs.
> SubscriptionBehavior to register with InsertBeforeIfExists

- src/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/BusConfiguration.cs
- src/NServiceBus.Core/Settings/TransactionSettings.cs
- src/NServiceBus.Core/Unicast/Transport/TransactionSettings.cs
- src/NServiceBus.Core/obsoletes.cs
Since it's been replaced with `context.Settings.GetRequiredTransactionSupportForReceives() != TransactionSupport.Distributed`
> Removed the Transactions.SuppressDistributedTransactions settings key

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/BusConfiguration.cs
- src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionPersistence.cs
- src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetries.cs
- src/NServiceBus.Core/Reliability/Outbox/Outbox.cs
- src/NServiceBus.Core/Settings/TransactionSettings.cs
- src/NServiceBus.Core/Transports/Msmq/TimeToBeReceivedOverrideCheck.cs
- src/NServiceBus.Core/Unicast/Transport/TransactionSettings.cs
- src/NServiceBus.Core/obsoletes.cs
It's been replaced by
context.Settings.GetRequiredTransactionSupportForReceives() !=
TransactionSupport.None
> Removed the `Transactions.Enabled` setting

- src/NServiceBus.AcceptanceTests/UnitOfWork/When_a_subscription_message_arrives.cs
A few issues with this test
1. It is assuming a message based subscription, therefore failing for native pub/sub transports like ASB
2. Name of this test doesn't explain how it's working. From `When_a_subscription_message_arrives.Should_invoke_uow` it's not clear that "for a transport with message based subscription unit of work will be invoked".
3. This behaviour should be tested on _all_ transports
Fix to first issue is the PR. As for the rest issues, should another test be introduced instead?
> Test specific to message based subscription transports

- src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
The cleanup allows, for example, Raven databases (named based on guids) to be removed after the test, but if the test fails with an exception, currently it will not be cleaned up *ever*. Moving the cleanup to a finally block should take care of this in most cases.
Still can't do much if you press Stop, I think.
> Cleanup ATs even if they fail to avoid creating orphan DBs, etc.

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Unicast/RunningEndpointInstanceTest.cs
- src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs
Just a proposal
* Current `Stop` implementation contains a race condition which allows multiple threads to stop the related components multiple times (e.g. CriticalError triggered from multiple CircuitBreakers).
* Would deadlock on reentrancy but I can't see that happening.
* Do we need a timeout for the Wait?
* No longer throw an exception when endpoint already stopped (e.g. When CriticalError stops before the user). I don't think we should throw an exception to the user when calling `Stop`.
> serialize RunningEndpointInstance.Stop calls

- src/NServiceBus.AcceptanceTests/FakeTransport/FakeReceiver.cs
- src/NServiceBus.AcceptanceTests/FakeTransport/FakeTransport.cs
- src/NServiceBus.AcceptanceTests/Performance/ProcessingOptimizations/When_using_concurrency_limit.cs
- src/NServiceBus.AcceptanceTests/ScaleOut/When_no_discriminator_is_available.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Transports/IPushMessages.cs
- src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
- src/NServiceBus.Core/Transports/Msmq/Msmq.cs
- src/NServiceBus.Core/Transports/Receiving.cs
- src/NServiceBus.Core/Transports/TransportReceiver.cs
- src/NServiceBus.Core/Transports/TransportReceivingConfigurationResult.cs
so that all callbacks can be initialized in the same place when implementing a transport
> Passing critical error into init

- src/NServiceBus.AcceptanceTests/ConfigureInMemoryPersistence.cs
- src/NServiceBus.AcceptanceTests/ConfigureMsmqTransport.cs
- src/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/ScenarioDescriptors/Persistence.cs
By convention, if `ConfigureTRANSPORTNAME` is present in ATTs project, it will be used to perform cleanup at the end of each test execution. This is working for MSMQ because it's a default transport. If a custom `ConfigureX`class for a transport is registered, execution blows up because transport and its connection string are not registered. Exception:
```
System.AggregateException : Test run failed due to one or more exception
----> NServiceBus.AcceptanceTesting.Support.ScenarioException : Endpoint SubscribingToAPolymorphicEvent.Publisher failed to initialize
----> System.InvalidCastException : Unable to cast object of type 'NServiceBus.MsmqTransport' to type 'NServiceBus.AzureServiceBusTransport'.
```
This change allows other transport register `ConfigureX` and execute properly.
> Allow transports other than MSMQ to cleanup after ATTs

- src/NServiceBus.AcceptanceTests/Msmq/When_a_corrupted_message_is_received.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
- src/NServiceBus.Core/Transports/Msmq/ReceiveWithNoTransaction.cs
Tests and fixes to make sure corrupted msmq messages are moved to the error queue properly
> Use the correct error queue

- src/NServiceBus.AcceptanceTests/Basic/When_sending_from_a_send_only.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Config/When_no_custom_configuration_source_is_specified.cs
- src/NServiceBus.Core.Tests/Config/When_users_override_the_configuration_source.cs
- src/NServiceBus.Core.Tests/Features/FeatureStartupTests.cs
- src/NServiceBus.Core.Tests/Serializers/Json/When_not_overriding_stream_encoding.cs
- src/NServiceBus.Core.Tests/Serializers/Json/When_overriding_stream_encoding.cs
- src/NServiceBus.Core/DataBus/DataBus.cs
- src/NServiceBus.Core/Features/FeatureStartupTask.cs
- src/NServiceBus.Core/Reliability/Outbox/Outbox.cs
- src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTableFeature.cs
- src/NServiceBus.Core/Routing/Legacy/ReadyMessageSender.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/StorageInitializer.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/Serializers/XML/Config/XmlSerialization.cs
- src/NServiceBus.Core/Transports/Receiving.cs
- src/NServiceBus.Core/Transports/Sending.cs
implementing the virtual methods marked as obsolete doesn't yield an error. Therefore keeping these methods there is quite dangerous since the user may never notice (in case he's not calling the base method) while the code never executes.
For `OnStart` this shouldn't be an issue anyway, since the new OnStart is abstract, therefore users have to implement the correct OnStart method, but OnStop is easily missed.
Should OnStop also be abstract?
> remove obosolete OnStart and OnStop methods from FeatureStartupTask

- src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
- src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
- src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
- src/NServiceBus.AcceptanceTesting/Support/IConfigureTestExecution.cs
- src/NServiceBus.AcceptanceTests/ConfigureInMemoryPersistence.cs
- src/NServiceBus.AcceptanceTests/ConfigureMsmqTransport.cs
- src/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
Related to #3203 
Replaced the invocation of Configure{Transport/Persistence} classes as dynamic methods and reflection with a full interface `IConfigureTestEnvironment`. Saw a lot of duplication between transport and persistence and eliminated that.
Stopped short of replacing the settings as string dictionary with a class having defined properties, since this concept touches builders and serializers in addition to transports and persistences. Also didn't apply the requirement for an interface-implementing configurer class on builders/serializers.
If settings was replaced, the list of properties would (I think) be:
* UniqueTestRunId - Guid I would add that would uniquely identify each test run. Azure tests need this kind of concept to enable ignoring messages in queue from any other test …
> Change Transport/Configurer classes to require interface.

- src/NServiceBus.Core.Tests/Pipeline/BehaviorRegistrationsCoordinatorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/BehaviorTypeCheckerTests.cs
- src/NServiceBus.Core.Tests/Pipeline/PipelineModelBuilderTests.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Pipeline/BehaviorTypeChecker.cs
- src/NServiceBus.Core/Pipeline/PipelineModelBuilder.cs
- src/NServiceBus.Core/Pipeline/PipelineModifications.cs
- src/NServiceBus.Core/Pipeline/PipelineSettings.cs
- src/NServiceBus.Core/Pipeline/RegisterStepExtensions.cs
- src/NServiceBus.Core/Pipeline/ReplaceStep.cs
- src/NServiceBus.Core/Pipeline/StepRegistrationsCoordinator.cs
With making the behavior context classes public again it is now possible to declare a behavior like this:
```
class MyBehavior : Behavior<IncomingLogicalContext> { }
```
unforuntaly this behavior will never get picked up by the model builder internally. In this PR I'll add a runtime check to verify that behaviors use a interface inherited from `IBehaviorContext`.
> Enforce Behavior with interface for contexts

- src/NServiceBus.AcceptanceTesting/Support/EndpointBehaviorBuilder.cs
related to #3202 
casts the ScenarioContext to `TContext` to align with the rest of the API.
> change context parameter in CustomConfig strongly to TContext

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/EndpointInstancesTests.cs
- src/NServiceBus.Core.Tests/Routing/FileRoutingTableTests.cs
- src/NServiceBus.Core.Tests/Routing/SubscriptionRouterTests.cs
- src/NServiceBus.Core.Tests/Routing/UnicastRouterTests.cs
- src/NServiceBus.Core/EnumerableEx.cs
- src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs
- src/NServiceBus.Core/Routing/EndpointInstances.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTable.cs
- src/NServiceBus.Core/Routing/IUnicastRoute.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenUnsubscribeTerminator.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/PublisherAddress.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/SubscriptionRouter.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/Routing/UnicastRoute.cs
- src/NServiceBus.Core/Routing/UnicastRouter.cs
The second stage of routing is about determining the list of instances given the endpoint name. The first stage has already been `async`-ed. Because there is possibility of users implementing that second stage based on some kind of remote resource (e.g. DB or web service lookup), it makes sense to make it `async` so that they can take advantage of async APIs of their storage technology.
> Instance resolution made async.

- src/NServiceBus.AcceptanceTesting/Support/ScenarioConfigSource.cs
Refactoring to add meaningful exception when one in AcceptanceTest will use .AuditTo<Endpoint> without calling WithEndpoint<Endpoint>. Previously it caused key not found exception in dictionary
> Refactoring AcceptanceTesting ScenarioConfigSource more meaningful expcetion

- packaging/nuget/nservicebus.core.nuspec
To match the casing used at http://particular.net/service-platform
> Fix .NET casing in core nuspec

- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
Makes sure cleanup is called in the test scenario bombs
Note: In talking with @danielmarbach, we opted to go with the refactoring of the PerformScenarios method
`static async Task PerformScenarios(...` could possibly be refactored to achieve this as well
> Always Stop even when scenario throws

- src/NServiceBus.AcceptanceTests/Volatile/When_sending_to_non_durable_endpoint.cs
The error queue needs to be different otherwise the queue could already exist from previous tests and the durability flag is true.
This was found as part of testing in Rabbit transport because we don't delete queues (it was not reliable), instead we just purge them.
> Need to specify different error queue

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_InMemory_and_an_escalated_DTC_transaction.cs
- src/NServiceBus.Core/Persistence/InMemory/InMemoryTransaction.cs
- src/NServiceBus.Core/Persistence/InMemory/InMemoryTransactionalSynchronizedStorageAdapter.cs
InMemoryTransaction storage with concurrent access could result in valid
Exceptions being thrown, but the exception was thrown on the wrong
thread since the transaction wasn't being rolled back via DTC correctly
Connects to #3244
> InMemory escalated transactions throw exception via Rollback

- src/NServiceBus.AcceptanceTests/Performance/TimeToBeReceived/When_TimeToBeReceived_has_expired.cs
- src/NServiceBus.AcceptanceTests/Performance/TimeToBeReceived/When_TimeToBeReceived_has_expired_convention.cs
To support transports that do not support sub millisecond TTLs
In RabbitMQ transport  the TTL needs to be greater or equal then a millisecond.
> Increasing TTL for acceptance tests

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_using_legacy_routing_configuration_combined_with_message_driven_pub_sub.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/UnicastRouterTests.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/Routing/UnicastRouter.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs
- src/NServiceBus.Core/Transports/TransportDefinition.cs
Attempts to solve https://github.com/Particular/NServiceBus/issues/3274
The problem is that the transport addresses come in two flavours: `queue` or `queue@machine`. The former may be used in the `MessageEndpointMappings`. The latter is the correct/canonical form used e.g. when subscribing. 
The solution is to add a virtual method to `TransportDefinition` which transports can override to convert a non-canonical form of address to the canonical one (overridden for MSMQ).
> Deduplicate transport level destination

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Transports/IOutgoingTransportOperation.cs
- src/NServiceBus.Core/Transports/MulticastTransportOperation.cs
- src/NServiceBus.Core/Transports/UnicastTransportOperation.cs
adds a common interface `IOutgoingTransportOperation` to both `UnicastTransportOperation` and `MulticastTransportOperation` in order to allow having them in the same collection. Requested by @yvesgoeleven for Azure transport (see #3214 )
> add common interface to Unicast- and MulticastTransportOperation

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/StartableEndpoint.cs
- src/NServiceBus.Core/Transports/TransportConfig.cs
related to #2859 
* Marks the property as obsolete to avoid code based configuration
* Adds a check when starting the bus to throw an `NotSupportedException` when a non-default value has been configured by a configuration file.
> obsolete TransportConfig.MaximumMessageThroughputPerSecond

- src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/DefaultRetryPolicyTests.cs
- src/NServiceBus.Core/Recoverability/SecondLevelRetries/DefaultSecondLevelRetryPolicy.cs
`DefaultRetryPolicyTests.ShouldCapTheRetryMaxTimeTo24Hours` is a time dependent test which occasionally fail. The build that shows the failure: 
https://builds.particular.net/viewLog.html?buildId=140909&tab=buildResultsDiv&buildTypeId=NServiceBusCore_Build#testNameId6202276057678592675
> DefaultRetryPolicyTests.ShouldCapTheRetryMaxTimeTo24Hours occasionally fails

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Features/FeatureDiagnosticData.cs
- src/NServiceBus.Core/Features/FeaturesReport.cs
- src/NServiceBus.Core/Features/PrerequisiteStatus.cs
- src/NServiceBus.Core/InitializableEndpoint.cs
@andreasohlund @tmasternak @SzymonPobiega and I were discussing the usefulness of `FeaturesReport`. We came to the conclusion that since we expose the feature stats on the logger we don't actually need to expose the `FeaturesReport` as a public class and register it on the container.
https://github.com/Particular/docs.particular.net/pull/1053
> Removed Container binding of FeaturesReport and made it internal

- src/NServiceBus.AcceptanceTests/Routing/When_publishing_from_sendonly.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Msmq/MsmqSubscriptionStorageQueueTests.cs
- src/NServiceBus.Core/Persistence/InMemory/SubscriptionStorage/InMemorySubscriptionStorage.cs
- src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorage.cs
- src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/ISubscriptionStorage.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/SubscriptionReceiverBehavior.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
`ISubscriptionStorage` had some legacy baggage to do with when we used to manage subscriptions for message hierarchies. this is no longer true. the current api expects lists but it is only ever a single item in those lists
this PR changes that api to only pass in a single instance of messagetype when subscribing or unsubscribing
> move to single message type subscription

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Serializers/XML/SerializingArrayTests.cs
- src/NServiceBus.Core.Tests/Serializers/XML/SerializingNullableTypesTests.cs
- src/NServiceBus.Core/Serializers/XML/XmlSerialization.cs
Serializing of null values should serialize the tags to
<Tag xsi:nil="true"></Tag> instead of <Tag>null</Tag>.
This change implements that change. All previous versions of the
deserializers are able to deserialize both formats still so no changes
are required to the deserialization code.
Connects to https://github.com/Particular/NServiceBus/issues/3122
> Change XMLSerialization behavior to conform to XML standard

- src/NServiceBus.AcceptanceTests/Routing/When_publishing_with_only_local_messagehandlers.cs
This test assumes that pubsub models with a centralized storage, never require a message endpoint mapping. This is not true, it really depends on the underlying infrastructure and the configuration in which it's used.
> centralized pubsub may need MEM

- src/NServiceBus.Core.Tests/Features/FeatureDependencyTests.cs
- src/NServiceBus.Core/Features/FeatureActivator.cs
Added DFS to check that the dependecy graph is a directed acyclic graph and
does not have any cycles.
Used a simple DFS, which will execute in linear time. If this manifests as a performance concern we can implement something a little smarter like Tarjan's algorithm.
Connects to https://github.com/Particular/NServiceBus/issues/3329
> Added check to ensure that dependency graph is acyclic

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs
- src/NServiceBus.Core/Routing/Legacy/ReadyMessageSender.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenUnsubscribeTerminator.cs
- src/NServiceBus.Core/Transports/MulticastTransportOperation.cs
- src/NServiceBus.Core/Transports/TransportOperation.cs
- src/NServiceBus.Core/Transports/TransportOperations.cs
- src/NServiceBus.Core/Transports/UnicastTransportOperation.cs
I was updating the CustomChecks for V6. They are using raw sending. By going over the ugprade guide I realized we have a problem between `TransportOperation` and `MulticastTransportOperation` and `UnicastTransportOperation`. Basically it boils down to have two constructors and one of them being internal. This PR makes the constructor which accepts params of `TransportOperation` public and removes the ctor accepting `MulticastTransportOperation` and `UnicastTransportOperation`. This streamlines the creation of transport operations and makes it less noisy.
@Particular/tf-async-transport please review and merge if good
> Aligned UnicastTransportOperations and MulticastTransportOperations with TransportOperation

- src/NServiceBus.AcceptanceTests/Msmq/When_starting_up_the_endpoint.cs
Acceptance test fails on non-English OS due to hardcoded security principal names. The fix is to read them from the OS.
> Read group names from the OS rather than hard-code en-US versions (in tests)

- src/NServiceBus.AcceptanceTests/CriticalError/When_raising_critical_error.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Timeout/CyclingOutageTimeoutPersister.cs
- src/NServiceBus.AcceptanceTests/Timeout/When_timeout_storage_is_unavailable_temporarily.cs
- src/NServiceBus.Core/CriticalError/CriticalError.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs
- src/NServiceBus.Core/StartableEndpoint.cs
https://github.com/Particular/NServiceBus/pull/3014
https://github.com/Particular/NServiceBus/issues/2994
Porting the timeout tests and fix to v6
cc / @indualagarsamy @timbussmann 
I needed to refactor `CriticalError.cs` because features will raise critical errors before the endpoint property is actually populated. This meant that endpoint.Stop() was never called even though something deemed critical occurred. The expected error also never bubbled up.
**Scenario**: When the circuit breaker for the timeout storage breaks, it will raise a critical error indicating that the storage can not be reached. The critical error method threw an InvalidOperationException if the endpoint property was null, which never allowed the circuit breaker to stop the endpoint.
> Timeout circuit breaker bug fix v6

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Routing/Routers/MulticastPublishRouterBehaviorTests.cs
- src/NServiceBus.Core.Tests/Routing/Routers/UnicastPublishRouterConnectorTests.cs
- src/NServiceBus.Core.Tests/Routing/Routers/UnicastReplyRouterConnectorTests.cs
- src/NServiceBus.Core.Tests/Routing/Routers/UnicastSendRouterConnectorTests.cs
- src/NServiceBus.Core/Routing/Routers/UnicastPublishRouterConnector.cs
This PR fixes #3344 by correctly setting the `MessageIntent` to `Publish` inside the `UnicastPublishRouterConnector`. 
Also added tests to verify that all other Router connectors set the message intent correctly.
> `MessageIntent.Publish` for `UnicastPublishRouterConnector`, fixes #3344

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Persistence/ISynchronizedStorageAdapter.cs
- src/NServiceBus.Core/Persistence/InMemory/InMemoryTransactionalSynchronizedStorageAdapter.cs
- src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs
- src/NServiceBus.Core/Pipeline/Incoming/ReceiveFeature.cs
Includes small changes to the synchronized storage session API to make it more usable (adding a context bag to each call) and makes the `Adapt` methods async to allow usage of async session/transaction APIs if supported by infrastructure.
Also changes the order in which the adapters are called, giving precedence to the Outbox. This means that if the outbox is enabled, the storage session will hook up to it. Otherwise it will try to hook up to the transport.
* ~~Raven pull~~ Raven persister does not use the adapter API
> Minor tweaks to storage adapter API

- src/NServiceBus.Core/DelayedDelivery/DoNotDeliverBefore.cs
When users delay a message by providing a DateTime and they use local time, e.g. by using `DateTime.Now.AddMinutes(30);` we compare a local to an utc time. 
For users in GMT + x timezones it's therefore possible to send messages with a delivery date in the past while for GMT - x timezones, it's not valid to defere a message earlier than (LocalTime + x).
I think we shouldn't throw an exception at all, because there can always be a delay between a check (or the assignment to the sendOptions) and a send which can cause an exception. The v5 implementation actually just sends the message immediately if the send time is not in the future.
> fix DoNotDeliverBefore

- src/NServiceBus.AcceptanceTests/Sagas/when_receiving_multiple_timeouts.cs
@DavidBoike 
@Particular/nservicebus-maintainers 
Please review.
https://github.com/Particular/NServiceBus.RavenDB/commit/db43863cf536850ea573ecb5080eb459d6b0c277
> Enable retries for concurrency exceptions

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/IBusContext.cs
- src/NServiceBus.Core/IBusContextExtensions.cs
Connects to #3398 
It is potentially dangerous depending on your transactional level of the endpoint to call subscribe or unsubscribe when handling a message. Let's consider the following example
* Handle a message with a non-dtc transport
* context.Subscribe
* Message handling fails
Result: Endpoint is subscribed although the message rolled back
Will be done in one GO by @SimonCropp
> Removed Subscribe and Unsubscribe from bus context

- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Serializers/Json/JsonMessageSerializer.cs
- src/NServiceBus.Core/Serializers/Json/MessageContractResolver.cs
- src/NServiceBus.Core/packages.config
I'm using the latest version of JSon.NET in the custom checks and send messages against NServiceBus unstable using 5.x version of Json.NET and it works fine. I think any breaking changes should be captured by wire-compat tests or am I wrong?
> Upgrade to latest Json.NET

- src/NServiceBus.AcceptanceTests/Forwarding/When_ForwardReceivedMessagesTo_is_set.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_dispatching_forwarded_messages.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/DetectObsoleteConfigurationSettings.cs
- src/NServiceBus.Core/Forwarding/ConfigureForwarding.cs
- src/NServiceBus.Core/Forwarding/ForwardReceivedMessages.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Unicast/UnicastBusConfig.cs
move `ForwardReceivedMessagesTo` code first API in alignment with https://github.com/Particular/NServiceBus/issues/3424 and https://github.com/Particular/NServiceBus/issues/1465
since we already have quite a few obsolete checks spread around the code and there will be more, I added a feature dedicated to detecting obsolete configs. Does that make sense or should we handle that individually for each setting?
Found no docs page or snippets regarding the `ForwardReceivedMessagesTo` to update. Didn't check samples yet.
> obsolete UnicastBusConfig.ForwardReceivedMessagesTo

- src/NServiceBus.Core/Persistence/PersistenceDefinition.cs
this is `TreatAsErrorFromVersion = "6.0",` from v6 then it cannot be
possibly used, since people need to recompile to target. So we may as
well throw notimplemented from inside
> throw from notimplemented  from HasSupportFor

- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/packages.config
As part of #3340 this PR is the following:
- Adds a reference to nuget `Particular.CodeRules` which adds project properties to run the project through our specific set of requirements, and produce errors if they are not met.
> CodeRule for detecting missing ConfigureAwaits

- src/NServiceBus.Core/Audit/Audit.cs
- src/NServiceBus.Core/Features/FeatureConfigurationContext.cs
- src/NServiceBus.Core/Forwarding/ForwardReceivedMessages.cs
- src/NServiceBus.Core/Pipeline/Incoming/ReceiveFeature.cs
- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPipelineFeature.cs
- src/NServiceBus.Core/Pipeline/PipelineSettings.cs
- src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs
Discussed this with @SzymonPobiega 
We had `RegisterConnector` which was using `typeof(T).Name`. I think this is dangerous. Because when we rename a behavior the ID should rename stable for users to override it.
Also if we have `RegisterConnector` we should also have `RegisterStageForkConnector` and `RegisterForkConnector`. The better solution is to remove it.
Not affected. The implementation is internal
> Removed `RegisterConnector` from `PipelineSettings`

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj
- src/NServiceBus.ContainerTests/When_building_components.cs
- src/NServiceBus.ContainerTests/When_disposing_the_builder.cs
- src/NServiceBus.ContainerTests/When_releasing_components.cs
- src/NServiceBus.ContainerTests/When_using_nested_containers.cs
- src/NServiceBus.Core.Tests.x86/NServiceBus.Core.x86.Tests.csproj
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core/ObjectBuilder/Autofac/AutofacObjectBuilder.cs
I have a hunch a few of the container test in the core were not quite right. This is an attempt to fix it.
Implemented with
* AutoFac
Smoke tested my changes with
* CastleWindsor
* Unit of Work components resolved on the main conatiner should be singletons on the maint container
* Lambda Unit of Work components resolved on the main conatiner should be singletons on the maint container
* TransientClass for when_releasing_components should at least implement `IDisposable`. For example for Windsor a transient class is only tracked if it implements a decomision concern like `IDisposable`. Without that we would essentially only test the runtime and the garbage collector because `Release` is a noop.
* Removed the threads from `Instance_per_uow_components_should_not_be_shared_across_child_contain …
> Redesigned container tests for new core assumptions

- src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/FailureInfoStorageTests.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/FailureInfoStorage.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ProcessingFailureInfo.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutRecoverabilityBehavior.cs
After a discussion with @tmasternak we have identified a way to slightly simplify processing in `TimeoutRecoverabilityBehaviour` by removing some null-handling statements and ensuring that no nulls are passed around.
> Simplify processing by improving handling of null values

- src/NServiceBus.AcceptanceTests/Basic/When_registering_additional_deserializers.cs
- src/NServiceBus.AcceptanceTests/Basic/When_registering_custom_serializer.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Serialization/SerializationDefinition.cs
- src/NServiceBus.Core/Serializers/Json/JsonSerializer.cs
- src/NServiceBus.Core/Serializers/XML/XmlSerializer.cs
After a call with @SimonCropp @indualagarsamy and @timbussmann we decided to make this trade off. It adds no new public types since the mapper and `IMessageSerializer` is already public. 
This will:
* allow our serializer sample to work
* provides a way to give users a chance to migrate away from using our serializers (upgrade guide)
* allows users on the ASQ transport that has selected XML in the past to be wire compatible without copy pasting the custom XmlSerializer
NOTE:
The ASQ transport/heartbeats/etc should still go ahead as planned and not reuse any core serializers since we want to get rid of that dependency. This is only for user consumption in v6. We'll discuss the removal of this api in v7.
> [WIP] Making the factory method for serializer public

- src/NServiceBus.ContainerTests/When_using_nested_containers.cs
With WindsorContainer when you nest the scopes like in this test then the most outer scope always applies which causes this test to fail.
@Particular/container-maintainers @WilliamBZA please review & merge
> No longer nesting using in Instance_per_uow_components_should_yield_different_instances_between

- src/NServiceBus.ContainerTests/When_building_components.cs
- src/NServiceBus.ContainerTests/When_registering_components.cs
For example with Windsor it is only possible to do property injection on an externally owned instance with [evil hacks](http://stackoverflow.com/questions/851940/windsor-castle-injecting-properties-of-constructed-object). To be honest I think we should not do property injection on an instance not owned by the by us. 
@Particular/container-maintainers @Particular/nservicebus-maintainers @WilliamBZA thoughts?
> When registering a singleton the properties don't need to be autowired.

- src/NServiceBus.Core.Tests/DataBus/When_applying_the_databus_message_mutator_to_incoming_messages.cs
- src/NServiceBus.Core.Tests/DataBus/When_applying_the_databus_message_mutator_to_null_properties.cs
- src/NServiceBus.Core.Tests/DataBus/When_applying_the_databus_message_mutator_to_outgoing_messages.cs
- src/NServiceBus.Core/DataBus/DataBus.cs
- src/NServiceBus.Core/DataBus/DataBusReceiveBehavior.cs
- src/NServiceBus.Core/DataBus/DataBusSendBehavior.cs
- src/NServiceBus.Core/EndpointConfiguration.cs
- src/NServiceBus.Core/Hosting/HostInformationFeature.cs
- src/NServiceBus.Core/Routing/MessagingBestPractices/BestPracticeEnforcement.cs
While checking for `RegisterSingleton` usages I stumbled over the conventions. It was both registered in the settings dictionary and on the container. The core only needed it on the container for the best practices behaviors and the data bus behaviors. This PR removes `Conventions` from the container
> No longer register Conventions on container

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/obsoletes.cs
This complements PR #3025, where this type was removed completely. This PR adds `ConfigureTransport` back and obsoletes it.
> Obsoleting ConfigureTransport

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Correlation/CorrelationContextExtensionsTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Routing/DetermineRouteForReplyBehaviorTests.cs
- src/NServiceBus.Core.Tests/Routing/RoutingOptionExtensionsTests.cs
- src/NServiceBus.Core/Correlation/CorrelationContextExtensions.cs
- src/NServiceBus.Core/Routing/RoutingOptionExtensions.cs
- src/NServiceBus.Core/Sagas/Saga.cs
Adding setters to `SendOptions.SetCorrelationId` and `ReplyOptions.SetDestination` (renamed from `OverrideReplyToAddressOfIncomingMessage`)
We need access to the configured settings to SendOption in the testing framework. This is the approach which doesn't require us to make any internal implementation details public.
We want to try the idea with these two options to see how well it works on the testing library. If that proves to work, this would require a getter extension method for every extension to `SendOption` and `ReplyOption`.
We're very happy to hear alternative approaches to solve our unit testing problems.
> add getters for SendOption extensions

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/RoutingOptionExtensionsTests.cs
- src/NServiceBus.Core/Routing/RoutingOptionExtensions.cs
Relates to https://github.com/Particular/NServiceBus/pull/3473
@timbussmann is working on adding in more options getters but whilst he's away I'm just adding in the ones required to get the testing framework migrated to v6
> Adding GetDestination extension method for sendoptions

- src/NServiceBus.AcceptanceTests/ApiExtension/When_extending_sendoptions.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Encryption/EncryptBehavior.cs
- src/NServiceBus.Core/Pipeline/Incoming/IIncomingPhysicalMessageContext.cs
- src/NServiceBus.Core/Pipeline/Incoming/IncomingPhysicalMessageContext.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateIncomingMessageContext.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateOutgoingMessageContext.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageContext.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageContext.cs
- src/NServiceBus.Core/Pipeline/Outgoing/IOutgoingLogicalMessageContext.cs
- src/NServiceBus.Core/Pipeline/Outgoing/IOutgoingPhysicalMessageContext.cs
- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingLogicalMessageContext.cs
- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPhysicalMessageContext.cs
- src/NServiceBus.Core/Transports/OutgoingMessage.cs
While doing the API walkthrough I detected that we are inconsistently applying updates to message bodies and instances in the core. This PR attempts to streamline it by introducing `UpdateMessage` methods on the context. Currently the setter on the incoming message body is still public, thus allowing to set the body without using `UpdateMessage` on the context. This is unfortunate but I wanted to keep the amount of changes small. 
The next PR will address the inconsistent usage of IncomingMessage, OutgoingMessages vs. exposing it on the context. I will open up a separate issue for that.
I compiled the snippets and the mutator sample against this release and no changes had to be made to those projects. Did I miss anything?
> Mutator alignment

- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_and_counting.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_regular_exception.cs
- src/NServiceBus.AcceptanceTests/Sagas/when_receiving_multiple_timeouts.cs
- src/NServiceBus.AcceptanceTests/Scheduling/When_scheduling_a_recurring_task.cs
ASB tests are periodically failing due to the fact that time to run on these tests is too short.
> Test execution time too short and makes test flaky

- src/NServiceBus.Core/Encryption/RijndaelEncryptionService.cs
Connects to https://github.com/Particular/NServiceBus/issues/3313
Checks what the maximum keylength is from the SymmetricAlgorithm class and logs a warning if the key length used is less than the maximum.
This is intended to allow the user to see that they could improve their security.
> Add warning when not using max bits for encryption

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/DelayedDelivery/DelayedDeliveryOptionExtensionsTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Pipeline/HeaderOptionExtensionsTests.cs
- src/NServiceBus.Core.Tests/Pipeline/Outgoing/ImmediateDispatchOptionExtensionsTests.cs
- src/NServiceBus.Core.Tests/Pipeline/Outgoing/MessageIdExtensionsTests.cs
- src/NServiceBus.Core.Tests/Routing/BestPracticesOptionExtensionsTests.cs
- src/NServiceBus.Core.Tests/Routing/RoutingOptionExtensionsTests.cs
- src/NServiceBus.Core/DelayedDelivery/DelayedDeliveryOptionExtensions.cs
- src/NServiceBus.Core/Pipeline/Outgoing/HeaderOptionExtensions.cs
- src/NServiceBus.Core/Pipeline/Outgoing/ImmediateDispatchOptionExtensions.cs
- src/NServiceBus.Core/Pipeline/Outgoing/MessageIdExtensions.cs
- src/NServiceBus.Core/Routing/MessagingBestPractices/BestPracticesOptionExtensions.cs
- src/NServiceBus.Core/Routing/RoutingOptionExtensions.cs
Adds a "Getter" extension method to every `SendOptions` (and `ExtenableOptions`) extension to retrieve the configured value.
This is mainly required for testing purposes to let the testing framework and users verify the expected SendOptions configuration
> Getters for SendOption extensions

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/ScenarioDescriptors/EnvironmentHelper.cs
- src/NServiceBus.AcceptanceTests/ScenarioDescriptors/Persistence.cs
- src/NServiceBus.AcceptanceTests/ScenarioDescriptors/Transports.cs
Currently, it's always the process scope.
The change is to first try the user scope, if nothing is found, then fall back to the process scope.
Reason: when running ATTs locally ASB/ASB/Core, need constantly restart VS for environment variables refresh to be picked up. This change solve the problem.
> Reading ATT related environment variables from 2 scopes

- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutRecoverabilityBehavior.cs
* don't log FLRs as info to avoid confusion for users when retries happen which is perfectly normal.
* changed log output to indicate that it comes from a satellite queue.
@Particular/nservicebus-maintainers @tmasternak please review
> Reduce error output from satellite retry behavior

- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Properties/Resharper.Annotations.g.cs
This updates our existing annotations definitions to newly generated ones from ReSharper 10, but without conditional attributes (also removed in the csproj).
This allows retaining the definitions, to make them useful when NServiceBus is used as a library.
> Updating ReSharper annotations

- src/NServiceBus.AcceptanceTests/Routing/When_publishing_an_interface.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/ContextHelpers.cs
- src/NServiceBus.Core.Tests/Routing/ApplyReplyToAddressBehaviorTests.cs
- src/NServiceBus.Core.Tests/Routing/DetermineRouteForPublishBehaviorTests.cs
- src/NServiceBus.Core.Tests/Routing/DetermineRouteForReplyBehaviorTests.cs
- src/NServiceBus.Core.Tests/Routing/Routers/UnicastSendRouterConnectorTests.cs
- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingLogicalMessage.cs
- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingLogicalMessageContext.cs
- src/NServiceBus.Core/Unicast/MessageOperations.cs
When I was playing with the development transport I noticed that when publishing interfaces we where passing the "impl" type instead of the pure message type. Eg.
`bus.Publish<MyEvent>()` would result in `MyEvent__impl` would be passed to the dispatcher. The subscription manager would on the other hand get the "pure" types.
Are we good with making sure to not pass the impl type? 
This is the key change: https://github.com/Particular/NServiceBus/pull/3521/files#diff-59e8e774c2bd8041f702a3a0f23d4de2R13
> Passing correct event type as message type when publishing interface messages

- src/NServiceBus.AcceptanceTests/ScenarioDescriptors/Transports.cs
- src/NServiceBus.AcceptanceTests/Timeout/When_timeout_storage_is_unavailable_temporarily.cs
Since msmq acpt tests are now moved to a separate project. 
Also fixed a bug where transports where discarded if no connection string was available even if the transport didn't need one.
> Removed the Msmq `RunDescriptor`

- src/NServiceBus.Core/Properties/Resharper.Annotations.g.cs
This removes an obsolete annotation attribute, stopping Fody from generating a warning about it.
> Remove an obsolete R# annotation attribute

- src/NServiceBus.Core.Tests/MessageMapper/MessageMapperTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/MessageMapper.cs
When Concurrently Initializing the MessageMapper or using `CreateInstance` concurrently for the same type without initializing the mapper will cause an exception because the `ConcreteProxyCreator` implementation is not threadsafe (`System.ArgumentException : Duplicate type name within an assembly.`).
While this scenario usually can't occur in production since we use a single message mapper and initialize it once at startup, this can easily happen when testing. In testing users usually don't initialize the mapper but rely on it's "auto-initialize" logic which will initialize a type "on-demand" which can easily happen concurrently when sending messages in parallel from a handler or somewhere else. In those cases a race condition will try to create the proxy type twice which will cause the …
> Make MessageMapper threadsafe

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_multi_subscribing_to_a_polymorphic_event_on_multicast_transports.cs
- src/NServiceBus.AcceptanceTests/Routing/When_multi_subscribing_to_a_polymorphic_event_on_unicast_transports.cs
The unicast one now enables the FLR because the subscription stores can throw concurrency exceptions and expect retries to kick in.
This was discovered during attempts to fix the NHibernate ATs.
> Split When_multi_subscribing_to_a_polymorphic_event test into two focused tests

- src/NServiceBus.Core/Pipeline/Incoming/PendingTransportOperations.cs
- src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageProcessingConnector.cs
Closes #3539
Switches from using List<TransportOperation> to ConcurrentStack<TransportOperation>, making Add / AddRange threadsafe.
Operations converts ToList which makes a copy at that point of time making reads threadsafe.
> `PendingTransportOperations` should be thread-safe

- src/NServiceBus.ContainerTests/When_using_nested_containers.cs
This means that container impls don't have to write funky code to prevent
it should they support it.
This failed for structuremap which does support this. If the core wants to prevent this it needs to check and throw instead of forcing the containers to do it.
That said since the core [returns an `IBuilder`](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/ObjectBuilder/Common/CommonObjectBuilder.cs#L22) they only way to be able to reconfigure it is knowing how to cast it.
I'm convinced that we'll catch this in a code review so calling YAGNI on this test that is just limiting the individual containers. 
@WilliamBZA can you link to the code you had to write in Ninject?
> Removed assumption that reconfiguring child containers should throw

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Pipeline/Incoming/InvokeHandlerTerminatorTest.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Sagas/CustomFinderAdapterTests.cs
- src/NServiceBus.Core.Tests/Sagas/InvokeSagaNotFoundBehaviorTests.cs
- src/NServiceBus.Core.Tests/Unicast/StartAndStoppablesRunnerTests.cs
- src/NServiceBus.Core.Tests/UnitOfWork/UnitOfWorkBehaviorTests.cs
- src/NServiceBus.Core/IHandleMessages.cs
- src/NServiceBus.Core/IWantToRunWhenBusStartsAndStops.cs
- src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerTerminator.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/IMutateIncomingMessages.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/IMutateOutgoingMessages.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/IMutateIncomingTransportMessages.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/IMutateOutgoingTransportMessages.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageBehavior.cs
- src/NServiceBus.Core/Sagas/CustomFinderAdapter.cs
- src/NServiceBus.Core/Sagas/IFindSagas.cs
- src/NServiceBus.Core/Sagas/IHandleSagaNotFound.cs
- src/NServiceBus.Core/Sagas/IHandleTimeouts.cs
- src/NServiceBus.Core/Sagas/InvokeSagaNotFoundBehavior.cs
- src/NServiceBus.Core/TaskEx.cs
- src/NServiceBus.Core/Unicast/StartAndStoppablesRunner.cs
- src/NServiceBus.Core/UnitOfWork/IManageUnitsOfWork.cs
- src/NServiceBus.Core/UnitOfWork/UnitOfWorkBehavior.cs
Closes #3533
Null checks for:
- IHandleMessages.Handle
- Sagas:
- IHandleTimeouts.Timeout [Not explicitly tested]
- IFindSagas.FindBy
- IHandleSagaNotFound.Handle
- IWantToRunWhenBusStartsAndStops.Start
- IWantToRunWhenBusStartsAndStops.Stop [Not tested - exception is logged but swallowed]
@danielmarbach Can you review what I have done so far? Anything I missed for the first group?
> Null check for common user Task methods

- src/NServiceBus.AcceptanceTests/Correlation/When_repling_to_received_message_without_correlationid.cs
- src/NServiceBus.AcceptanceTests/Correlation/When_replying_to_received_message_without_correlationid.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core.Tests/Routing/MessageDrivenSubscribeTerminatorTests.cs
- src/NServiceBus.Core/Correlation/AttachCorrelationIdBehavior.cs
- src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenUnsubscribeTerminator.cs
- src/NServiceBus.Core/Unicast/Transport/ControlMessageFactory.cs
- src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj
- src/NServiceBus.Msmq.AcceptanceTests/When_receiving_control_message_with_body.cs
Theses issues were uncovered by #3573:
1. [x] Stop deserializing control messages  
Control messages are still being received from early versions of NServiceBus, eg v3.3
1. [x] Add missing Version and TimeSent headers to subscribe and unsubscribe messages
1. [x] Attempt to assign incoming message id as correlation id
fixes #3583
> Fix wire compatibility for v6

- src/NServiceBus.Core/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehavior.cs
For consistency reasons we should either pass in the headers always to the routing strategies or refactor those to not depend on headers. The simplest low hanging fruit seemed for me to pass in the headers also in the `RouteDeferredMessageToTimeoutManagerBehavior`
Or would it be better to get rid of the headers on the strategies (which would be a breaking change)?
// cc @SzymonPobiega @janovesk
> Passing headers to apply of routing strategy in RouteDeferredMessageToTimeoutManagerBehavior

- src/NServiceBus.Core/UnicastRoutingTarget.cs
The null guard checks the `transportAddress` twice, and throws an error if `transportAddress` is `null`, but the error says that `endpoint` parameter is `null` instead of the `transportAddress` parameter making it confusing to debug.
Ping @Particular/nservicebus-maintainers
> Guard against the correct parameter

- src/NServiceBus.AcceptanceTests/ApiExtension/When_extending_sendoptions.cs
- src/NServiceBus.AcceptanceTests/MessageId/When_message_has_empty_id_header.cs
- src/NServiceBus.AcceptanceTests/MessageId/When_message_has_no_id_header.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Pipeline/When_replacing_behavior.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_a_message_is_audited.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Pipeline/RegisterStepTests.cs
- src/NServiceBus.Core/Pipeline/PipelineModelBuilder.cs
- src/NServiceBus.Core/Pipeline/PipelineSettings.cs
- src/NServiceBus.Core/Pipeline/RegisterStep.cs
- src/NServiceBus.Core/Pipeline/ReplaceStep.cs
fixes #3574 
When replacing behaviors it didn't replace the behavior factory method of the original behavior registration. When the RegisterStep should create the instance of the behavior, it would fallback to the original factory instead of resolving the new behavior.
* Replacing factory method on `RegisterStep` properly
* Allowing Replacements to define a behavior instance or a behavior factory the same way as `pipeline.Register` does
* Added an acceptance test
@Particular/nservicebus-maintainers @indualagarsamy please review
> Fix replacing behaviors

- src/NServiceBus.AcceptanceTests/Mutators/When_using_outgoing_tm_mutator.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
Original test only mutated the header and assumed XML serializer.
Not XML serializer is force in test and also the body of the message is modified and asserted in the test.
> Force XML in mutator test & mutate body in test

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Pipeline/Incoming/InvokeHandlerTerminatorTest.cs
- src/NServiceBus.Core/Sagas/ActiveSagaInstance.cs
- src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
Connects to https://github.com/Particular/PlatformDevelopment/issues/677
Moving SagaAudit to utilize strongly typed stages for it's behaviors [instead of `InsertBefore` and `InsertAfter`](https://github.com/Particular/NServiceBus/issues/3582) the handler is no longer exposed to one of the behaviors. Removing `obsolete` allows us to access the saga `Instance` in the plugin.
Likewise the `InsertBefore`/`InsertAfter` were used to try to measure the Saga lifespan as part of the auditing process. Adding the `DateTime` properties `Created` and `Modified` along with `MarkAsModified` give us those metrics without the need to specify specific ordering in the pipeline and are more accurate.
> ActiveSagaInstance enhancements

- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_handler_exists_but_routing_information_is_missing.cs
- src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_Audit_OverrideTimeToBeReceived_set_and_native_receive_tx.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_TimeToBeReceivedOnForwardedMessages_set_and_tx_scope_receives.cs
Fixes #3596
Also fixes the behavior of AT framework when one of the endpoints fail to start (adding a missing `await`)
> Do not autosubscribe unless there is routing info when using unicast transports

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Pipeline/Incoming/MessageHandler.cs
MessageHandler constructor needs to have a public since it's a public property on `IInvokeHandlerContext` and we need to be able to provide our own instances for testing purposes.
@Particular/nservicebus-maintainers @hmemcpy please review
> Make MessageHandler constructor public

- src/NServiceBus.AcceptanceTests/Persistence/When_a_persistence_does_not_provide_ISynchronizationContext.cs
- src/NServiceBus.Core/Pipeline/Incoming/ReceiveFeature.cs
A fix was previously made to cater for scenarios where a Storage was used that wasn't a `ISynchronizedStorage`.
This change used a static instance of `Task<CompletableSynchronizedStorageSession>` as a helper, but this change meant that the instance was shared within the same AppDomain.
If one of the threads disposed of the `CompletableSynchronizedStorageSession` then the other threads will receive an `ObjectDisposedException`
The fix is simply to return a new instance of `Task<CompletableSynchronizedStorageSession>` each time it is requested instead of using a static instance.
An alternative fix is to configure the `IContainer` in `InitializableEndpoint.RegisterContainerAdapter()` to use `ReceiveFeature.NoOpSynchronizedStorage` by default. This will then be overridden by future …
> Remove shared instance of completable synch storage session

- src/NServiceBus.AcceptanceTests/Mutators/When_incoming_mutator_changes_message_type.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/DataBus/When_applying_the_databus_message_mutator_to_incoming_messages.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Sagas/InvokeSagaNotFoundBehaviorTests.cs
- src/NServiceBus.Core.Tests/Unicast/LoadHandlersBehaviorTests.cs
- src/NServiceBus.Core/Encryption/DecryptBehavior.cs
- src/NServiceBus.Core/Pipeline/Incoming/IIncomingLogicalMessageContext.cs
- src/NServiceBus.Core/Pipeline/Incoming/IncomingLogicalMessageContext.cs
- src/NServiceBus.Core/Pipeline/Incoming/LogicalMessage.cs
- src/NServiceBus.Core/Pipeline/Incoming/LogicalMessageFactory.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehavior.cs
- src/NServiceBus.Core/Serialization/SerializationFeature.cs
- src/NServiceBus.Core/Unicast/Messages/MessageMetadata.cs
Since LogicalMessage is a public property on `IIncomingLogicalMessageContext` users must be able to create their own instances in order to setup the context properly.
The whole logic around LogicalMessage and especially it's type & type hierarchy is pretty complicated. That's why I went for the straight forward solution. I wish I could do more, but it seems improving the situation will require a non-trivial refactoring and understanding message types & message hierarchy handling. I don't want to go down that rabbit hole right now since this blocks finishing the update of NServiceBus.Testing.
Also added a mutator acceptance tests to verify certain assumptions.
> Make LogicalMessage ctor public

- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_a_message_is_audited.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_dispatching_forwarded_messages.cs
@Particular/nservicebus-maintainers please take a look. These tests were failing for persistences that do not support the outbox.
> Added missing repeat clause to two outbox tests

- src/NServiceBus.AcceptanceTesting/Support/FailTestOnErrorMessageFeature.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_Subscribing_to_errors.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_doing_flr_with_dtc_on.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_doing_flr_with_native_transactions.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_fails_with_retries_set_to_0.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_message_fails_retries.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_and_counting.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_min_policy.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_non_min_policy.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_regular_exception.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_serialization_exception.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs
- src/NServiceBus.Core/InitializableEndpoint.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Notifications.cs
- src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs
- src/NServiceBus.Core/obsoletes.cs
fix #3425
Rename `BusNotifications` to `Notifications`
I moved over the obsolete property to `Notifications` to provide more help to migrating users. Should we do that or keep it on the obsolete class?
WIP doc PR: https://github.com/Particular/docs.particular.net/pull/1342
> Rename BusNotifications to Notifications

- src/NServiceBus.Core/Serialization/SerializationFeature.cs
Technically I think you could hack it today by changing it in a feature that has `DependsOn("SerializationFeature")` but with this change ASB/ASQ can change it in `TransportDefinition.Initialize` using `settings.SetDefault<SerializerDefinition>(new JsonSerializer())` which seems more resonable.
> Allow default serializer to be changed

- src/NServiceBus.Core/EndpointConfiguration.cs
- src/NServiceBus.Core/InitializableEndpoint.cs
This means that we can add endpoint config calls that allows users to subscribe to notifications.
Note that there is no public api yet so this just paves the way.
The reason I changed this now is that it will allow @kbaley to cleanup #3611 to not use features to hook up to the existing notifications but instead (yes sort of a backdoor) do: `config.GetSettings().Get<Notifications>.xyz`
> Notifications can now be accessed from endpoint config calls

- src/NServiceBus.AcceptanceTests/ConventionEnforcementTests.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Persistence/When_a_persistence_does_not_provide_ISynchronizationContext.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists_and_context_information_added.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists_and_found_saga.cs
- src/NServiceBus.AcceptanceTests/SelfVerification/When_running_saga_tests.cs
- src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_transactionscope_enabled.cs
- src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_using_timeout_greater_than_machine_max.cs
- src/NServiceBus.AcceptanceTests/UnitOfWork/When_a_subscription_message_arrives.cs
- src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj
- src/NServiceBus.Msmq.AcceptanceTests/When_distributing_a_command.cs
* Fixes `When_distributing_a_command` test and moves it to MSMQ project because in V6 time frame it is relevant almost exclusively to MSMQ
* Added missing base class declarations to tests that were missing them. Without that declaration tests would not be executed if specific transport or persistence need to be enforced
* Added a meta-test that enforces proper base class for all acceptance tests
> Fix acceptance tests

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Unicast/RunningEndpointInstanceTest.cs
- src/NServiceBus.Core/InitializableEndpoint.cs
- src/NServiceBus.Core/StartableEndpoint.cs
- src/NServiceBus.Core/Transports/TransportInfrastructure.cs
- src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs
Ability to perform, as a transport, actions before starting an endpoint and after stopping it (e.g. initialize and close connection to the broker).
The scenario where I discovered this missing extension point was the EventStore transport. ES uses "intelligent" thread-safe connections. Such connection should be initialized when starting the endpoint and closed when stopping it.
> Start and stop TransportInfrastructure

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/EndpointConfiguration.cs
- src/NServiceBus.Core/obsoletes.cs
This will better guide users upgrading.
@indualagarsamy ran into a problem with vierd compiler errors related to `.EndpointName` when upgrading. This should solve that.
cc @SimonCropp
> Moved obsoleted methods from BusConfig to EndpointConfig

- packaging/nuget/nservicebus.acceptancetests.nuspec
Per https://github.com/Particular/NServiceBus/pull/3591#issuecomment-200950452 this removes the Persistence tests from the source package.
There was [one test](https://github.com/Particular/NServiceBus/blob/excludePersistenceTests/src/NServiceBus.AcceptanceTests/Persistence/When_a_persistence_does_not_provide_ISynchronizationContext.cs) in there that wasn't added as part of #3591, but looking at it, it seemed ok to me to also not include downstream.
Thoughts?
> Exclude Persistence tests from source package

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/ConventionsBuilder.cs
Connects to https://github.com/Particular/ProductionTests/pull/57
This is needed to define custom Conventions without EndpointConfiguration. For use in SerializationTests.
> Making the ctor of ConventionsBuilder public

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Routing/RoutingToDispatchConnectorTests.cs
- src/NServiceBus.Core/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutRecoverabilityBehavior.cs
- src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs
Allow fo custom routing strategies that modify the headers (the built-in ones don't do it).
> Minor fixes to usages of RoutingStrategy and AddressTag

- src/NServiceBus.Core/Pipeline/PipelineCache.cs
The current state of `ConnectorContextExtensions` does not provide extension methods for creating contexts in the forks. This PR addresses this issue for the dispatch pipeline but I believe there needs to be some other extensions e.g. for the routing pipeline.
> Allow creating IDispatchContext from a ForkConnector.

- packaging/nuget/nservicebus.testing.fakes.nuspec
- src/NServiceBus.Testing.Fakes/FakeBuilder.cs
- src/NServiceBus.Testing.Fakes/OutgoingMessage.cs
- src/NServiceBus.Testing.Fakes/OutgoingMessageExtensions.cs
- src/NServiceBus.Testing.Fakes/TestableAuditContext.cs
- src/NServiceBus.Testing.Fakes/TestableBatchDispatchContext.cs
- src/NServiceBus.Testing.Fakes/TestableBehaviorContext.cs
- src/NServiceBus.Testing.Fakes/TestableDispatchContext.cs
- src/NServiceBus.Testing.Fakes/TestableFaultContext.cs
- src/NServiceBus.Testing.Fakes/TestableForwardingContext.cs
- src/NServiceBus.Testing.Fakes/TestableIncomingContext.cs
- src/NServiceBus.Testing.Fakes/TestableIncomingLogicalMessageContext.cs
- src/NServiceBus.Testing.Fakes/TestableIncomingPhysicalMessageContext.cs
- src/NServiceBus.Testing.Fakes/TestableInvokeHandlerContext.cs
- src/NServiceBus.Testing.Fakes/TestableMessageProcessingContext.cs
- src/NServiceBus.Testing.Fakes/TestableOutgoingContext.cs
- src/NServiceBus.Testing.Fakes/TestableOutgoingLogicalMessageContext.cs
- src/NServiceBus.Testing.Fakes/TestableOutgoingPhysicalMessageContext.cs
- src/NServiceBus.Testing.Fakes/TestableOutgoingPublishContext.cs
- src/NServiceBus.Testing.Fakes/TestableOutgoingReplyContext.cs
- src/NServiceBus.Testing.Fakes/TestableOutgoingSendContext.cs
- src/NServiceBus.Testing.Fakes/TestablePipelineContext.cs
- src/NServiceBus.Testing.Fakes/TestableRoutingContext.cs
- src/NServiceBus.Testing.Fakes/TestableSatelliteProcessingContext.cs
- src/NServiceBus.Testing.Fakes/TestableSubscribeContext.cs
- src/NServiceBus.Testing.Fakes/TestableTransportReceiveContext.cs
- src/NServiceBus.Testing.Fakes/TestableUnsubscribeContext.cs
* Move source files to `App_Packages` folder. Used `NSB.Testing.Fakes` instead of the package id similar to acceptance test and container test sources. Fixes #3645  /cc @SimonCropp 
* Ran a code cleanup on all classes (mainly namespace cleanup)
* Added some missing default values for some context properties
@Particular/nservicebus-maintainers @hmemcpy please review
> Testing.Fakes cleanup

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehaviorTests.cs
- src/NServiceBus.Core.Tests/DeliveryConstraintContextExtensions/DeliveryConstraintContextExtensionsTests.cs
- src/NServiceBus.Core.Tests/Routing/RoutingToDispatchConnectorTests.cs
- src/NServiceBus.Core/DelayedDelivery/DelayedDeliveryFeature.cs
- src/NServiceBus.Core/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManagerRoutingStrategy.cs
- src/NServiceBus.Core/DeliveryConstraints/DeliveryConstraintContextExtensions.cs
- src/NServiceBus.Core/Headers.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Pipeline/Incoming/PendingTransportOperations.cs
...in order to remove a hack/technical debt introduced by https://github.com/Particular/PlatformDevelopment/issues/133.
The previous code did change the routing information in-place before calling the next behaviors.
The new code forks directly to the dispatch pipeline. That leaves a question if we really should allow for modification of the routing information in-place. For now I've left it as-was (and not used). 
This PR also adds tests for both RouteDeferredMessageToTimeoutManagerBehavior and RoutingToDispatchConnector behaviors that verify their behaviors in terms of immediate/batch dispatching.
Connects to https://github.com/Particular/NServiceBus/issues/3657
> Redesigned RouteDeferredMessageToTimeoutManagerBehavior to be a fork

- src/NServiceBus.Testing.Fakes/DefaultTestingLoggerFactory.cs
- src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj
- src/NServiceBus.Testing.Fakes/NamedLogger.cs
- src/NServiceBus.Testing.Fakes/TestingLoggerFactory.cs
- src/NServiceBus.Testing.Fakes/TextWriterLogger.cs
Connects to https://github.com/Particular/NServiceBus.Testing/issues/29
While reviewing the [NServiceBus.Host PR which introduces the logger warning ](https://github.com/Particular/NServiceBus.Host/pull/72) @colin-higgins had to pull in Moq to be able to properly test the log warnings. This PR introduces a simple basic infrastructure to be able to pass in a text writer into a logger factory specifically designed for testing.
I first had the reaction to introduce more than a text writer. For example we could strongly typed capture all log messages, exceptions etc. I decided to not do this for now since the string based version fits the majority of use cases.
Because of the static nature of the logging infrastructure there is always a caveat associated when you use the logging …
> Testing logger factory which allows to log to a text writer

- src/NServiceBus.Core.Tests/Encryption/RijndaelEncryptionServiceTest.cs
small code refactoring to simplify the complex ctor logic (`encryptionKeyIdentifier, encryptionKeyIdentifier != null ? keys ?? new Dictionary<string, byte[]> { { encryptionKeyIdentifier, encryptionKey } } : null, expiredKeys`) to make the tests more understandable.
+ code reformat
Note: can be further simplified when https://github.com/Particular/NServiceBus/pull/3658 is merged. (remove overrides and use testable context instead)
@Particular/nservicebus-maintainers ping
> Encryption service tests

- src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj
- src/NServiceBus.Testing.Fakes/TestingLoggerFactory.cs
* Added a missing xml doc to `TestingLoggerFactory`
* Enabled xml docs for this project. This is needed because this option is enabled on NServiceBus.Testing which pulls in these classes as a source and may run into compilation errors because the source files don't provide the required documentation.
* Changed binary output bath to /binaries instead of bin/debug to align with the rest of the projects.
@Particular/nservicebus-maintainers ping
> Added missing xml docs to Testing.Fakes

- src/NServiceBus.Core.Tests/Fakes/TestableMessageSessionTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj
- src/NServiceBus.Testing.Fakes/Subscription.cs
- src/NServiceBus.Testing.Fakes/TestableEndpointInstance.cs
- src/NServiceBus.Testing.Fakes/TestableMessageSession.cs
- src/NServiceBus.Testing.Fakes/Unsubscription.cs
testable implementation for `IMessageSession` and `IEndpointInstance` (implementing `IMessageSession`) aligned with the implementation for `TestableMessageHandlerContext`
> Add TestableMessageSession and TestableEndpointInstance

- src/NServiceBus.Core.Tests/Fakes/TestableContextChecker.cs
- src/NServiceBus.Core.Tests/Fakes/TestableMessageHandlerContextTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
These are some tests relating to the `NServiceBus.Testing.Fakes` that were originally in the `NServicebus.Testing` repository. They would be better suited to being in the core solution as that is where the fakes reside.
Connects to https://github.com/Particular/NServiceBus.Testing/issues/29
> Moving Fake tests from NServicebus.Testing to core tests

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Faults/AddExceptionHeadersBehaviorTests.cs
- src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Recoverability/When_message_is_deferred_by_slr.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Pipeline/ConnectorContextExtensions.cs
- src/NServiceBus.Core/Recoverability/Faults/AddExceptionHeadersBehavior.cs
- src/NServiceBus.Core/Recoverability/Faults/FaultContext.cs
- src/NServiceBus.Core/Recoverability/Faults/FaultToDispatchConnector.cs
- src/NServiceBus.Core/Recoverability/Faults/IFaultContext.cs
- src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs
- src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs
- src/NServiceBus.Core/Utils/ExceptionHeaderHelper.cs
- src/NServiceBus.Testing.Fakes/TestableFaultContext.cs
Connects to https://github.com/Particular/NServiceBus.Gateway/issues/41
Let FaultContext track the error queue and set failure headers to enable reuse of it outside the core. (GW for example)
Alternative for https://github.com/Particular/NServiceBus/pull/3688
> Move responsibility for error queue and fault exception headers into fault context

- src/NServiceBus.AcceptanceTests/ScenarioDescriptors/Persistence.cs
- src/NServiceBus.AcceptanceTests/ScenarioDescriptors/Transports.cs
I ran into this today. Acceptance tests were failing until I saw that we do not use the `EnvironmentHelper` consistently.
> Using EnvironmentHelper consistently in persistence and transport descriptor

- src/NServiceBus.AcceptanceTesting/ContextAppender.cs
- src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_auto_correlated_property_is_changed.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_forgetting_to_set_a_corr_property.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_id_changed.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_updating_existing_correlation_property.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_TimeToBeReceived_set_and_native_receivetransaction.cs
Done checks in Acceptance Tests using `.Done(c => c.Exceptions.Any())` are not safe. `ScenarioContext.Exceptions` is a list of all exceptions being logged (even if catched and handled internally). Therefore I renamed the property to make this a bit more apparent. Tests can easily become flaky (on downstreams) if some exceptions are logged and the tests may end too soon therefore I removed all usages in `Done` checks.
> Removed ScenarioContext.Exception checks in Done conditions

- src/NServiceBus.AcceptanceTests/DelayedDelivery/TimeoutManager/When_timeout_dispatch_fails.cs
Connects to https://github.com/Particular/PlatformDevelopment/issues/723
Timeout dispatch tests: the test `When_timeout_dispatch_fails` is flaky and uses a different strategy for testing failures than `When_timeout_dispatch_fails_on_timeout_data_removal`. Align it to the latter.
When this is merged, PR should be merged as well: https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/104
\cc @WojcikMike @andreasohlund
> Timeout dispatch tests: potentially flaky assert fixed

- src/NServiceBus.AcceptanceTests/Recoverability/When_message_is_moved_to_error_queue.cs
Connects to https://github.com/Particular/PlatformDevelopment/issues/732
The `Should_not_send_outgoing_messages` test should not be run for `TransportTransactionMode.ReceiveMode`. This is because in such case send and receive operations are not performed atomically. This has not been spotted until `SqlServer` has been updated because `MSMQ` shares the same implementation for `AtomicSendWithReceive` and `ReceiveOnly` transaction modes.
`ReceiveOnly` and `None` need to be treated in the same way.
/cc: @Particular/nservicebus-maintainers
> Fixing `when_message_is_moved_to_error_queue` test

- src/NServiceBus.Core/Support/RuntimeEnvironment.cs
While working on https://github.com/Particular/NServiceBus.RabbitMQ/pull/136, I was profiling some code that was doing a lot of sends, and I saw that the call to `Environment.MachineName` was taking up a lot of time. In fact, it was the 2nd most expensive function in the entire profile run!
Now it only gets called once and we use the cached value instead.
> Cache value instead of repeatedly calling Environment.MachineName

- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_flr_disabled.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_auto_correlated_property_is_changed.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_updating_existing_correlation_property.cs
temporary fix for `When_auto_correlated_property_is_changed` reported by #3711 :+1: - changed done condition to `FailedMessages.Any()`. Because of the changed mechanism how we send messages to error queues, it's possible that the done condition is met and the endpoint is shut down before the message to be sent to the error queue is consumed again by the endpoint. The new condition ends the test only if a (any) message has been sent to the error queue. This test also seemed to fail for RabbitMQ PR https://github.com/Particular/NServiceBus.RabbitMQ/pull/136
Also fixes `When_performing_slr_with_flr_disabled` which failed on https://github.com/Particular/NServiceBus.RabbitMQ/pull/136 too. I can't remember why the test assumes only 2 retries? Maybe @MarcinHoppe remembers?
/cc @johnsimons …
> Fix flaky Acceptance Tests

- src/NServiceBus.AcceptanceTesting/Support/FailTestOnErrorMessageFeature.cs
- src/NServiceBus.AcceptanceTesting/Support/MessagesFailedException.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
Instead of relying on the notifications API we can use a custom behavior to capture unhandled message processing exceptions before the "MoveToErrorQueueBehavior" handles them.
This should resolve race conditions where fast endpoint shutdowns prevent the error message to notify the ATT framework properly as described in #3714
> Use behavior instead of notifications to capture failed messages

- src/NServiceBus.AcceptanceTesting/Support/RunSettings.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.AcceptanceTests/EndpointTemplates/DefaultServer.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_receiving_a_message.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_doing_request_response_between_sagas_with_timeout.cs
The default value caused a bug which resulted in the the configured timeout to be overwritten by the default when merging two RunSettings. E.g. here: https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs#L27
Merging RunSettings seems to be quite dangerous.
/cc @johnsimons
> Remove default TestExecutionTimeout value from RunSettings

- src/NServiceBus.Core/Utils/ElevateChecker.cs
R# constantly yells at me for this unnecessary check. Since R# is right and the result can never be null, we can safely remove the check and get rid of the warning.
(see http://referencesource.microsoft.com/#mscorlib/system/security/principal/windowsidentity.cs,797 [note that `threadOnly` is always false when called using `WindowsIdentity.GetCurrent()`])
> remove unnecessary null check for WindowsIdentity.GetCurrent()

- src/NServiceBus.AcceptanceTests/Hosting/When_feature_overrides_hostid.cs
- src/NServiceBus.AcceptanceTests/Hosting/When_feature_overrides_hostinfo.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Features/FeatureDifferingOnlyByNamespaceTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core/Features/Feature.cs
- src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayPersistence.cs
I found this because i had a feature named "Outbox" in different namespace in a downstream. which causes a cyclic dependency fail. 
Connects to #3702
> respect full type name of features

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_using_assembly_level_message_mapping_for_pub_sub.cs
- src/NServiceBus.Core.Tests/Routing/UnicastRouterTests.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/Routing/UnicastPublishRouter.cs
- src/NServiceBus.Core/Routing/UnicastRouter.cs
- src/NServiceBus.Core/Routing/UnicastSendRouter.cs
Fixes https://github.com/Particular/NServiceBus/issues/3670
Splits the existing `UnicastRouter` into dedicated routers for publishes and sends where the `UnicastPublishRouter` only consults the subscription storage whereas the `UnicastSendRouter` only consults the routingtable.
> Use separate routers for unicast sends and publishes

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Routing/SingleInstanceRoundRobinDistributionStrategyTests.cs
- src/NServiceBus.Core.Tests/Routing/UnicastRouterTests.cs
- src/NServiceBus.Core/Routing/AllInstancesDistributionStrategy.cs
- src/NServiceBus.Core/Routing/DistributionStrategy.cs
- src/NServiceBus.Core/Routing/Routers/UnicastSendRouterConnector.cs
- src/NServiceBus.Core/Routing/SingleInstanceRoundRobinDistributionStrategy.cs
- src/NServiceBus.Core/Routing/UnicastRouter.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_distributing_a_command.cs
Connects to Particular/Platformdevelopment#814
Fix round robin distribution strategy to work properly when the strategy is used with different endpoints.
Added unit tests for `SingleInstanceRoundRobinDistributionStrategyTests` and @SzymonPobiega acceptance test with slight modifications.
> Fix round robin distribution

- src/NServiceBus.Core/Routing/RoutingFeature.cs
it is not used by anything and is abstract
> remove UnicastRouter from DI

- src/NServiceBus.AcceptanceTesting/ContextAppender.cs
- src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
- src/NServiceBus.AcceptanceTests/Recoverability/When_message_is_moved_to_error_queue.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_id_changed.cs
`When_saga_id_changed` has a race condition when using transactions because it verifies on a log message which is written when the message is handled by the `MoveFaultsToErrorQueueBehavior`. But since the test is done on the first failed message, it is possible that the error queue behavior never gets invoked when using transactions (because the endpoint is already shut down) and therefore the log entry isn't written.
This is fixed by verifying the exception message on the failed message instead from the log (better anyway).
further changes:
* removed `ScenarioContextLoggedExceptions `: this one was ugly anyway, since it only contained exceptions using the exception parameter overload (which we sometimes can't use when logging exceptions). This test was the only usage of it, so it could …
> Fix logging race condition

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj
- src/NServiceBus.sln
Some of the test projects had this already, so this lets all of them work with the VS Test Explorer.
> Add nunit test VS test runner setting to project files

- src/NServiceBus.Core.Tests/Encryption/RijndaelEncryptionServiceTest.cs
For certain (ciphertext, IV) pairs, both decryption keys resulted in plaintexts that contained valid padding. This resulted in "garbage" being recovered from the ciphertext by using the unexpected key. The fix is to identify both keys using unique identifiers so that the algorithm can precisely identify keys to use.
Fixes #3365
> Fix flaky encryption test

- src/NServiceBus.Core.Tests/Routing/UnicastRouterTests.cs
- src/NServiceBus.Core/Routing/UnicastRoutingTable.cs
The static routes seem to be evaluated every time the routes for a message are resolved. The static rules seemed to be unnecessary complex (using the context) and most rules wouldn't apply for a single message type. The changes eliminate LINQ calls on the `UnicastRouter` and try to move "computation" of the routes per type to startup time.
@SzymonPobiega @bording please have a look.
> Reduce routing hot path evaluations

- src/NServiceBus.AcceptanceTests/Basic/When_depending_on_typed_feature.cs
- src/NServiceBus.AcceptanceTests/Basic/When_depending_on_untyped_feature.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core.Tests/Features/FeatureDependencyTests.cs
- src/NServiceBus.Core/Features/Feature.cs
We provide a `DependsOn` overload which accepts a string parameter for features to define a dependency on a feature whose type is not available at compile time (e.g. Gateway for many persistence packages).
https://github.com/Particular/NServiceBus/commit/1da5619bfab3450166bff15c8d80ab7abc1fe87d changed the parameter to require the full type name instead of the simple type name. But we actually didn't really expect the simple type name when the dependency feature had a "Feature" postfix (then this part was stripped away when using the **typed** `DependsOn` API and for internal feature representation.
`When_depending_on_untyped_feature` reproduces a bug where a feature wasn't loaded although it's dependency which was correctly defined according to the API (using the full type name) and …
> Fix untyped DependsOn

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Persistence/PersistenceStartupTests.cs
- src/NServiceBus.Core/Persistence/PersistenceStartup.cs
This makes sure `HasSupportFor` will return false if being called when the `ResultingSupportedStorages` setting hasn't been set, which happens when an endpoint is SendOnly.
I haven't included a test around this, wasn't sure if it needed one. If it does, what would be the best approach for testing it?
@Particular/nservicebus-maintainers 
Connects to #3748
> Prevent HasSupportFor from throwing when SendOnly endpoint

- src/NServiceBus.AcceptanceTests/Routing/When_broadcasting_a_command.cs
- src/NServiceBus.AcceptanceTests/Routing/When_using_instance_ids.cs
- src/NServiceBus.AcceptanceTests/Routing/when_replying_to_a_message_sent_to_specific_instance.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/EndpointInstancesTests.cs
- src/NServiceBus.Core.Tests/Routing/UnicastRouterTests.cs
- src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
- src/NServiceBus.Core/Routing/EndpointInstances.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_replying_to_a_message_sent_via_a_distributor.cs
Extracts (cherry picked) the changes cleaning up the endpoint instance configuration from https://github.com/Particular/NServiceBus/pull/3767 without the removal of `EndpointName` (to be addressed in another PR), so these changes aren't blocked by the discussion around `EndpointName`.
Changes:
* Remove EndpointName param where EndpointInstance is also passed (because EndpointInstance contains already the information about the name)
* rewrote EndpointInstances.FindInstances to not use LINQ converting to a List->Set->Array and instead just use a HashSet.
ping @bording @SzymonPobiega @distantcam
> Remove redundant EndpointName parameters from instance configuration

- src/NServiceBus.Core.Tests/Msmq/MsmqMessagePumpTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
Connects to #3787
Validation of the input queue is causing valid remote error queue to be discarded and skipping real input queue validation rule (must be local).
> Cannot set error queue on a remote server for MSMQ

- src/NServiceBus.AcceptanceTesting/ContextAppender.cs
- src/NServiceBus.AcceptanceTesting/ContextAppenderFactory.cs
- src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
- src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
- src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.AcceptanceTests/Licensing/When_a_message_is_audited.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_Subscribing_to_errors.cs
- src/NServiceBus.AcceptanceTests/Tx/ImmediateDispatch/When_requesting_immediate_dispatch_using_scope_suppress.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_a_corrupted_message_is_received.cs
The idea is to be able to specify the log level for individual loggers so that some acceptance tests will be allowed to output additional information in case it is needed.
> Acceptance test logging improvements.

- src/NServiceBus.Core.Tests/Routing/EndpointInstancesTests.cs
- src/NServiceBus.Core/Routing/EndpointInstances.cs
tried to refactor the FindInstances query which is invoked from the routing during the outgoing message pipeline.
Goal: Moving time consuming operations for static instance routing configuration to startup time
* Splitting static and dynamic rules: static rules no longer need any async operations.
* Reducing number of loops by checking whether static or dynamic rules even exist.
* use array instead of `NonEmptyEnumerable`
* static rules are computed when adding new instances to a "ready-to-consume" `Dictionary<string, HashSet<EndpointInstance>>`
@Particular/nservicebus-maintainers @SzymonPobiega @DavidBoike please review
> Refactor FindInstances query

- src/NServiceBus.Core/InitializableEndpoint.cs
- src/NServiceBus.Core/StartableEndpoint.cs
This moves the `RunInstallers` method to `InitializableEndpoint` instead of `StartableEndpoint`, which will let the installers be run from `Endpoint.Create` instead of `Endpoint.Start`
Fixes #3807 
Connects to #3807
> Move RunInstallers to Initialize

- src/NServiceBus.Core.Tests/Routing/FileRoutingTableParserTests.cs
- src/NServiceBus.Core.Tests/Routing/FileRoutingTableTests.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTable.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTableParser.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/endpoints.xsd
This adds XML schema validation to the FileBasedDynamicRouting parser. The schema file is loaded as an embedded resource.
I did start out with the schema defined as as string in the class, so it maybe it makes sense to squash some of these commits before merging?
While getting the schema working, I did end up making a tweak to the version currently on the docs page. I've made it require at least once instance if their is an endpoint defined, because otherwise there's no point in the endpoint being defined in the file in the first place.
@timbussmann See anything else you'd want to add to this?
> File routing xml schema

- src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists_and_found_saga.cs
By ensuring the instance returned by a custom finder has been stored in the store prior to returning. This is because saga persisters expect this instance to be persistence when they save the changes.
> Fixes the saga finder test 

- src/NServiceBus.AcceptanceTests/Routing/When_broadcasting_a_command.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Routing/DistributionPolicyTests.cs
- src/NServiceBus.Core.Tests/Routing/Routers/UnicastPublishRouterConnectorTests.cs
- src/NServiceBus.Core.Tests/Routing/Routers/UnicastSendRouterConnectorTests.cs
- src/NServiceBus.Core.Tests/Routing/UnicastRouterTests.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Routing/DistributionPolicy.cs
- src/NServiceBus.Core/Routing/IDistributionPolicy.cs
- src/NServiceBus.Core/Routing/IUnicastRouter.cs
- src/NServiceBus.Core/Routing/Routers/UnicastPublishRouterConnector.cs
- src/NServiceBus.Core/Routing/Routers/UnicastSendRouterConnector.cs
- src/NServiceBus.Core/Routing/RoutingMappingSettings.cs
- src/NServiceBus.Core/Routing/SpecificInstanceDistributionPolicy.cs
- src/NServiceBus.Core/Routing/UnicastRouter.cs
enables to configure a custom `DistributionStrategy` per endpoint instead of per type.
@SzymonPobiega @bording @DavidBoike what do you think?
> Configure distribution strategy per endpoint

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Routing/RoutingPolicyTests.cs
- src/NServiceBus.Core.Tests/Routing/SingleInstanceRoundRobinDistributionStrategyTests.cs
- src/NServiceBus.Core/Routing/DistributionPolicy.cs
- src/NServiceBus.Core/Routing/SingleInstanceRoundRobinDistributionStrategy.cs
Replaces #3817 
Moved the responsibility for making strategy state per-endpoint based to the policy (from each strategy).
> Distribution strategy per endpoint singleton

- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.AcceptanceTests/FakeTransport/FakeTransportInfrastructure.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Performance/MessageDurability/When_disabling_durable_messages_on_durable_transport.cs
- src/NServiceBus.AcceptanceTests/Performance/MessageDurability/When_sending_a_non_durable_message.cs
- src/NServiceBus.AcceptanceTests/Performance/MessageDurability/When_using_non_durable_messages_on_durable_only_transport.cs
- src/NServiceBus.Core.Tests/Faults/AddExceptionHeadersBehaviorTests.cs
- src/NServiceBus.Core/Headers.cs
- src/NServiceBus.Core/Performance/MessageDurability/DetermineMessageDurabilityBehavior.cs
- src/NServiceBus.Core/Performance/MessageDurability/MessageDurabilityFeature.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqTransportInfrastructure.cs
Adds the missing `NonDurableDelivery` to the list of supported constraints for MSMQ transport.
fixes https://github.com/Particular/NServiceBus/issues/3236
also fixes  #3820 
@Particular/nservicebus-maintainers it seems like the `MessageDurabilityFeature` is enabled by default and does not check whether the transport actually supports non durable messages. I think we should either:
* disable the feature (and the behavior) when the transport does not support non durable delivery or
* throw an exception when a message is configured to be non durable but the transport doesn't support it
what do you think?
> add NonDurableDelivery to msmq supported delivery constraints

- src/NServiceBus.Core/Performance/Counters/PerformanceMonitorUsersInstaller.cs
Basic grammar in a message that shows up regularly when developing locally.
@Particular/nservicebus-maintainers should be an easy review.
> PerformanceMonitorUsersInstaller info message

- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_custom_policy.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_min_policy.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_non_min_policy.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/DefaultRetryPolicyTests.cs
- src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs
- src/NServiceBus.Core.Tests/Recoverability/When_message_is_deferred_by_slr.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Recoverability/SecondLevelRetries/Config/SecondLevelRetriesSettings.cs
- src/NServiceBus.Core/Recoverability/SecondLevelRetries/CustomSecondLevelRetryPolicy.cs
- src/NServiceBus.Core/Recoverability/SecondLevelRetries/DefaultSecondLevelRetryPolicy.cs
- src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetries.cs
- src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs
- src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetryContext.cs
- src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetryPolicy.cs
fixes https://github.com/Particular/NServiceBus/issues/3831 by adding additional overloads for the custom retry policy which also grants access to the causing exception and the retry attempt.
There are now 3 overloads available:
* `Func<IncomingMessage, TimeSpan> customPolicy`
* `Func<IncomingMessage, Exception, TimeSpan> customPolicy`
* `Func<IncomingMessage, Exception, int, TimeSpan> customPolicy`
I made one only using the exception with the int parameter because I think the int value not very intuitive (should probably a custom type called `SlrRetryAttempt` to make more sense).
Also fixed the acceptance test which missed that bug all the time.
@Particular/nservicebus-maintainers @mauroservienti please review
docs PR: https://github.com/Particular/docs.particular.net/pull/1602
> add more parameters to custom retry policy

- src/NServiceBus.Core/Audit/InvokeAuditPipelineBehavior.cs
Otherwise any modification of header in the audit pipe affect the `IncomingMessage` as well which comes as a nasty surprise to behaviors which do processing after calling `next()`
> Copy headers when auditing.

- src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
- src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
- src/NServiceBus.AcceptanceTesting/Support/FailTestOnErrorMessageFeature.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_custom_policy.cs
- src/NServiceBus.Core/Transports/TransportReceiver.cs
Connects to Particular/PlatformDevelopment#832
With the change of the pipeline/transport seam the acceptance test can no longer "inject" `CaptureExceptionBehavior ` between retries and the error queue handling to intercept & track failed messages. Therefore we need another approach. I can currently come up with two solutions:
* Solely listen to the events raised by FLR/SLR/ErrorQ and fail the test if a `MessageFailed` event is raised (message moved to the errorqueue). This has the disadvantage of possible race conditions since the event may only be fired after the message is consumed the second time (in transactional scenarios) and we may miss that because tests can stop the endpoint before if the done condition is already met, resulting in us not reliably detecting failed messages.
* …
> Tracking unhandled failed messages before endpoint shutdown.

- src/NServiceBus.Core/Features/FeatureActivator.cs
- src/NServiceBus.Core/Serializers/XML/XmlSerializerCache.cs
Reduces unnecessary enumerations. 
We still have two of those
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MsmqUtilities.cs#L133
https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/Msmq/MsmqUtilities.cs#L137
The bigger question we would need to ask ourselves is: Why does https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Transports/UnicastTransportOperation.cs#L36 need to be an `IEnumerable` since this is a really low-level API we should optimize it for the fast path?
@Particular/nservicebus-maintainers thoughts?
> Avoid multiple enumerations

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_handles_unmapped_message.cs
- src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
Connects to https://github.com/Particular/Stories/pull/339
We added startup validation for `IAmStartedByMessages` mappings, making sure they would exist. `IAmHandledBy` is a little more tricky. It could be an auto-correlated reply message that contains SagaId in a header.
However...
If a saga handles a message type, and that message comes in with:
* No SagaId header
* No ConfigureHowToFindSagas mapping
* No custom finder
Then there's really no way we can successfully map the message to a saga at all, but the message we're currently providing is:
> INFO  NServiceBus.InvokeSagaNotFoundBehavior Could not find a started saga for 'TestV6Saga.SendBack' message type. Going to invoke SagaNotFoundHandlers.
That's just wrong. Isn't it?
@Particular/nservicebus-maintainers this PR isn't complete (no …
> Throw when saga handles message, but message is unmapped+uncorrelated

- src/NServiceBus.Core.Tests/Routing/FileRoutingTableTests.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/AsyncTimer.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTable.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTableFeature.cs
Previous design of file instance mapping attached itself to the routing in the `FeatureStartupTask` (FST). That meant that other FST that happened to be run before (e.g. AutoSubscribe), when sending out messages, would not go through the file instance map.
In case of AutoSubscribe it meant that all subscriptions are routed using default instance mapping (to local machine).
The new design load the file when it is first accessed.
> Fixed file instance mapping to be available when running FSTs.

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/obsoletes.cs
Closes #3855 
```
class MySaga: Saga<MySaga.MyEntity>, IAmStartedByMessages<Message1>
{
public async Task Handle(Message1 message, IMessageHandlerContext context) {
Bus.SendLocal(new MyMessage());
}
protected override void ConfigureHowToFindSaga(SagaPropertyMapper<MySaga.MyEntity> mapper)
{
}
}
```
will now lead to
> Properly obsoleting Bus property on Saga base class

- src/NServiceBus.AcceptanceTesting/Support/FailTestOnErrorMessageFeature.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_TimeToBeReceived_set_and_native_receivetransaction.cs
by registering the intercept behavior at the right place in the pipeline
Closes https://github.com/Particular/NServiceBus/issues/3877
> Attempt to fix When_TimeToBeReceived_set_and_native_receivetransaction

- src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
- src/NServiceBus.AcceptanceTests/BestPractices/When_publishing_command_bestpractices_disabled.cs
- src/NServiceBus.AcceptanceTests/BestPractices/When_publishing_command_bestpractices_disabled_on_endpoint.cs
- src/NServiceBus.AcceptanceTests/BestPractices/When_sending_events_bestpractices_disabled.cs
- src/NServiceBus.AcceptanceTests/BestPractices/When_sending_events_bestpractices_disabled_on_endpoint.cs
- src/NServiceBus.AcceptanceTests/BestPractices/When_subscribing_to_command_bestpractices_disabled_on_endpoint.cs
- src/NServiceBus.AcceptanceTests/BestPractices/When_unsubscribing_to_command_bestpractices_disabled_on_endpoint.cs
- src/NServiceBus.AcceptanceTests/Config/When_injecting_message_session_into_handlers.cs
- src/NServiceBus.AcceptanceTests/Config/When_only_abstract_config_override_is_found.cs
- src/NServiceBus.AcceptanceTests/FakeTransport/ProcessingOptimizations/When_using_concurrency_limit.cs
- src/NServiceBus.AcceptanceTests/Performance/MessageDurability/When_disabling_durable_messages_on_durable_transport.cs
- src/NServiceBus.AcceptanceTests/Performance/MessageDurability/When_using_non_durable_messages_on_durable_only_transport.cs
- src/NServiceBus.AcceptanceTests/Routing/When_handler_exists_but_routing_information_is_missing.cs
- src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_default_transaction_mode.cs
- src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_transport_scopes.cs
- src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_using_timeout_greater_than_machine_max.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_using_scope_timeout_greater_than_machine_max.cs
Makes `ScenarioContext` no longer abstract which allows to remove the many empty subclasses we have.
@Particular/nservicebus-maintainers what do you think?
> Remove abstract modifier from ScenarioContext

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Unicast/MessageHandlerRegistry.cs
Will add more details soonish
```ini
BenchmarkDotNet=v0.9.7.0
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-3615QM CPU 2.30GHz, ProcessorCount=8
Frequency=2240999 ticks, Resolution=446.2296 ns, Timer=TSC
HostCLR=MS.NET 4.0.30319.42000, Arch=32-bit RELEASE
JitModules=clrjit-v4.6.1080.0
Type=TypeAllocations  Mode=Throughput  
```
Method |     Median |    StdDev |    Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
---------------------------- |----------- |---------- |--------- |------ |------ |------------------- |
StructWithRuntimeTypeHandle | 13.9590 ns | 0.5826 ns |        - |     - |     - |               0,00 |
StructWithTypeHandle |  6.9124 ns | 0.2468 ns |        - |     - |     - |               0,00 |
ClassWithRuntimeTypeHandle |  9.9213 ns | 0.1792 ns | 1 611,00 | …
> Optimize Message handler registry hot path

- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_clearing_saga_timeouts.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Reliability/Outbox/TransportReceiveToPhysicalMessageProcessingConnectorTests.cs
- src/NServiceBus.Core/Persistence/InMemory/Outbox/InMemoryOutboxStorage.cs
- src/NServiceBus.Core/Pipeline/Incoming/PendingTransportOperations.cs
- src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageProcessingConnector.cs
- src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs
- src/NServiceBus.Core/Reliability/Outbox/OutboxMessage.cs
Removes unnecessary allocations on PendingTransportOperations and OutboxMessage
This time it is possible to use array. So we are not consistent on the lower level interfaces. But I think we should strive for right type for the use case on this low-level abstractions.
Changing the OutboxMessage has downstream implications for the persisters. When we agree with the proposal of this PR I'll link the downstream PRs.
* [RavenDB](https://github.com/Particular/NServiceBus.RavenDB/pull/251)
* [NHibernate](https://github.com/Particular/NServiceBus.NHibernate/pull/204)
> PendingTransportOperations and OutboxMessage use array instead of IEnumerable or IList

- src/NServiceBus.AcceptanceTests/EndpointTemplates/DefaultServer.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Serialization/When_configuring_custom_xml_namespace.cs
- src/NServiceBus.AcceptanceTests/Serialization/When_registering_additional_deserializers.cs
- src/NServiceBus.AcceptanceTests/Serialization/When_registering_custom_serializer.cs
- src/NServiceBus.AcceptanceTests/Serialization/When_sanitizing_xml_messages.cs
- src/NServiceBus.AcceptanceTests/Serialization/When_skip_wrapping_xml.cs
- src/NServiceBus.AcceptanceTests/Serialization/When_wrapping_is_not_skipped.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Serializers/XML/Config/XmlSerializationExtensions.cs
- src/NServiceBus.Core/Serializers/XML/XmlSerializer.cs
- src/NServiceBus.Core/Settings/SettingsHolder.cs
- src/NServiceBus.Core/obsoletes.cs
fixes https://github.com/Particular/NServiceBus/issues/3852
Turns out that all xml serializer config settings don't work.
Todo:
@Particular/nservicebus-maintainers while it shouldn't be a big deal to fix this, I'm a bit worried about the impact on ASQ in case they use the `XmlSerializer` and are these config extensions. The settings are currently shared on all instances of the serializer, although that probably shouldn't have an impact? Even `DontWrapRawXml` shouldn't be an issue as long as the wrapper message doesn't use XContainer properties, right?
> Fix XmlSerializer config

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Routing/FileBasedDynamicRouting/FileRoutingTableFeatureTests.cs
- src/NServiceBus.Core.Tests/Routing/FileRoutingTableParserTests.cs
- src/NServiceBus.Core.Tests/Routing/FileRoutingTableTests.cs
- src/NServiceBus.Core/Routing/EndpointInstances.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTable.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTableFeature.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTableParser.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTableSettings.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/RoutingFileAccess.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/endpoints.xsd
- src/NServiceBus.Core/Transports/Msmq/MsmqConfigurationExtensions.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs
- src/NServiceBus.Msmq.AcceptanceTests/ConfigureMsmqTransport.cs
- src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj
- src/NServiceBus.Msmq.AcceptanceTests/NServiceBusAcceptanceTest.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_customizing_scope_isolation_level.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_distributing_a_command.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_not_using_instance_mapping_file.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_starting_with_invalid_instance_mapping_file.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_using_empty_instance_mapping_file.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_using_instance_mapping_file.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_using_scope_timeout_greater_than_machine_max.cs
Changes:
* Change schema to allow empty `endpoints` and `endpoint` elements
* Only use one attempt to read instance mapping file. If it fails it will blow at startup or try again after the configured checkInterval. Is there a valid scenario which requires the `maxLoadAttempts` configuration?
* Load mapping file initially during feature setup for validation and initial data purpose
* uses AppDomain.CurrentDomain.BaseDirectory as root path for relative mapping file paths
* remove `FileBasedEndpointInstanceMapping`
* Auto-enables the mapping file when using Msmq transport
* it will not read the file and not set up dynamic rules when there is no file at startup time (can be empty though)
* if a file is found, the dynamic rule is added and a timer will …
> Auto enable instance mapping

- src/NServiceBus.AcceptanceTests/Routing/When_publishing_to_scaled_out_subscribers_on_unicast_transports.cs
- src/NServiceBus.AcceptanceTests/UnicastPubSubExtensions.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/MessageDrivenSubscribeTerminatorTests.cs
- src/NServiceBus.Core.Tests/Routing/MessageDrivenUnsubscribeTerminatorTests.cs
- src/NServiceBus.Core.Tests/Routing/SubscriptionRouterTests.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensions.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/Publishers.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_distributing_an_event.cs
Makes publisher API have the same signatures as the routing API, e.g.
`routing.RouteToEndpoint(typeof(MyMessage), "myEndpoint");`
`routing.RegisterPublisherForType(typeof(MyMessage), "myPublisher");`
And makes the namespace configuration when configuring messages for assembly non-optional but added a new overload, one accepting a namespace, one not.
@SzymonPobiega @bording @DavidBoike 
we talked about not using different methods but only overloads for types/assembly/namespace config., e.g. instead of 
```
routing.RegisterPublisherForType(typeof(MyMessage), "myPublisher");
routing.RegisterPublisherForAssembly(eventAssembly, "eventnamespace", "myPublisher");
```
this:
```
routing.RegisterPublisherFor(typeof(MyMessage), "myPublisher"); …
```
> Align register publisher API

- src/NServiceBus.Msmq.AcceptanceTests/When_starting_with_invalid_instance_mapping_file.cs
Test doesn't have any awaits, so no need for `async Task`.
> Remove unneeded async keyword from test

- src/NServiceBus.AcceptanceTests/Basic/When_sending_with_conventions.cs
- src/NServiceBus.AcceptanceTests/Basic/When_using_a_greedy_convention.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Unicast/MessageOperationsTests.cs
- src/NServiceBus.Core/Unicast/MessageOperations.cs
Sends and replies set the message type of the generated proxy class instead of the interface which resulted in issues during message metadata lookup and the message conventions in case they were based on the type name.
repro was raised by @ramonsmits https://github.com/ramonsmits/docs.particular.net/pull/1 and this will be working correctly with these changes (tested locally).
@Particular/nservicebus-maintainers @ramonsmits please review
> Set correct message types when using proxy interfaces

- src/NServiceBus.AcceptanceTests/Routing/When_subscribing_to_a_polymorphic_event.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Routing/RoutingSettingsTests.cs
- src/NServiceBus.Core/Routing/RoutingSettings.cs
- src/NServiceBus.Msmq.AcceptanceTests/NServiceBusAcceptanceTest.cs
Add the following two overloads for the routing API:
```
public void RouteToEndpoint(System.Reflection.Assembly assembly, string destination) { }
public void RouteToEndpoint(System.Reflection.Assembly assembly, string messageNamespace, string destination) { }
```
Open questions:
* The RegisterPublisherForAssembly does the namespace comparison using `StringComparison.InvariantCultureIgnoreCase`, we should align these, but should we really ignore cases instead of going for case sensitive equality?
> Allow assembly and namespace based routing

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Routing/MessageDrivenSubscriptions/PublishersTests.cs
- src/NServiceBus.Core.Tests/Routing/SubscriptionRouterTests.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/Publishers.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/SubscriptionRouter.cs
Refactoring of the `Publisher` class + some additional tests
* dedicated overloads for assembly + namespace configuration to avoid optional parameter on the public API.
* reduce the amount of publisher routing rules which need to be invoked at runtime by "compiling" static rules into a dictionary, reducing the effort to a lookup instead of invoking every single rule.
@Particular/nservicebus-maintainers @SzymonPobiega  please review
> Publisher cleanup

- src/NServiceBus.AcceptanceTests/Serialization/When_registering_additional_deserializers.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Serialization/SerializationConfigExtensions.cs
Closes #3919 
@dloukola rightfully pointed out that our `AddDeserializer` API is restrictive since it doesn't allow to use the normal configuration extension points you'd normally expect when configuring a serializer. This PR would add those. 
* Not necessary
The API (has always been like that) doesn't restrict doing things like
```
config.UseSerializer<SomeSerializer>().;
config.AddDeserializer<SomeSerializer>();
```
but since we now enable settings over the `SettingsHolder` in theory the last call would override the settings of both the main serializer and the deserializer. I.ex.
```
config.UseSerializer<JSon>().Settings("foobar");
config.AddDeserializer<Json>().Settings("bar");
```
The serializer would see `bar` as the configured last value. Should we address this? If yes then I think …
> Enables extension points for additional deserializers

- src/NServiceBus.Core.Tests/Utils/ExceptionHeaderHelperTests.cs
- src/NServiceBus.Core/Utils/ExceptionHeaderHelper.cs
Connects to https://github.com/Particular/V6Launch/issues/69
This is a clean-up that was originally part of the [PR](https://github.com/Particular/NServiceBus/pull/3929). The PR was closed but this clean-up should still be be merged.
> removing legacy stacktrace support from failure headers

- src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists_and_found_saga.cs
- src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs
With the new recoverability seam we detected that the `When_a_finder_exists_and_found_saga` test is always failing with the InMemorySagaPersister. @tmasternak and I tried to fix the persister. Just before our heads exploded we could (hopefully, fingers crossed, wish us luck) come up with a potential fix for the persistence. 
Start shooting holes into it @Particular/nservicebus-maintainers
> Attempt to fix in-memory saga persistence

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/RoutingSettingsTests.cs
- src/NServiceBus.Core/Routing/UnicastPublishRouter.cs
- src/NServiceBus.Core/Routing/UnicastRouter.cs
- src/NServiceBus.Core/Routing/UnicastRoutingTable.cs
- src/NServiceBus.Core/Routing/UnicastSendRouter.cs
UnicastRoutingTable allows to define async rules to resolve routes. Since this is an advanced API which isn't used by default, we can try to avoid the async overhead when possible.
Also changing some parameters to an array to make the read-only nature a bit more apparent.
Question: do we really want to allow async rules to be defined? this can result in a major performance hit when someone tries to lookup these data on a database on every outgoing message, a better approach would usually be to read the database from time to time and keep the read data in memory for faster lookups?
@Particular/nservicebus-maintainers @SzymonPobiega @DavidBoike
> Avoid async calls in UnicastRoutingTable

- src/NServiceBus.AcceptanceTests/DelayedDelivery/TimeoutManager/When_timeout_dispatch_fails.cs
- src/NServiceBus.AcceptanceTests/DelayedDelivery/TimeoutManager/When_timeout_dispatch_fails_on_timeout_data_removal.cs
- src/NServiceBus.AcceptanceTests/DelayedDelivery/TimeoutManager/When_timeout_storage_fails.cs
- src/NServiceBus.AcceptanceTests/Timeout/CyclingOutageTimeoutPersister.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/Persistence/TimeoutsChunk.cs
- src/NServiceBus.Core/Persistence/InMemory/TimeoutPersister/InMemoryTimeoutPersister.cs
@Particular/nhibernate-persistence-maintainers @Particular/ravendb-persistence-maintainers This would introduce a breaking change towards the persisters. The benefit of this is that we would produce less Gen 0 garbage due to enumerator boxing/unboxing as well as the timeout data being a struct (it only wraps a string and a datetime). Thoughts?
https://github.com/Particular/NServiceBus.RavenDB/pull/253
https://github.com/Particular/NServiceBus.NHibernate/pull/205
// cc @Particular/nservicebus-maintainers
> TimeoutsChunk uses array for timeouts and timeouts is a struct to reduce garbage

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Serialization/When_registering_deserializers_with_settings.cs
- src/NServiceBus.Core.Tests/Settings/SettingsHolderTests.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Serialization/SerializationConfigExtensions.cs
- src/NServiceBus.Core/Serialization/SerializationFeature.cs
- src/NServiceBus.Core/Serialization/SerializationSettingsExtensions.cs
- src/NServiceBus.Core/Settings/SettingsHolder.cs
Based on https://github.com/Particular/NServiceBus/pull/3923
As outlined in the other PR the following problem exists
The API (has always been like that) doesn't restrict doing things like
```
config.UseSerializer<SomeSerializer>().;
config.AddDeserializer<SomeSerializer>();
```
but since we now enable settings over the `SettingsHolder` in theory the last call would override the settings of both the main serializer and the deserializer. I.ex.
```
config.UseSerializer<JSon>().Settings("foobar");
config.AddDeserializer<Json>().Settings("bar");
```
The serializer would see `bar` as the configured last value. This PR attempts to fix this by introducing a settings holder per serializer. Extensions will set the extended settings on that specific settings holder. When the serialization feature …
> Settings per serializer

- src/NServiceBus.Core/TaskEx.cs
- src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
@bording and I verified that using Task.StartNew with state overload on hot paths always leads to less garbage. See https://github.com/danielmarbach/MicroBenchmarks/pull/1
This small PR addresses this for the `MessagePump` and the `AsyncTimer`. There are still a few more `Task.Run` which I haven't touched. Especially the `ExpiredTimeoutsPoller` is a bit more involved since it modifies a `DateTime` field in the body of the execution logic.
> Replace Task.Run in MessagePump

- src/NServiceBus.Core.Tests/Routing/Routers/UnicastSendRouterConnectorTests.cs
- src/NServiceBus.Core.Tests/Serializers/SerializeMessagesBehaviorTests.cs
- src/NServiceBus.Core.Tests/Unicast/Messages/DefaultMessageRegistryTests.cs
- src/NServiceBus.Core/Encryption/Encryptor.cs
- src/NServiceBus.Core/EndpointConfiguration.cs
- src/NServiceBus.Core/Performance/MessageDurability/MessageDurabilityFeature.cs
- src/NServiceBus.Core/Performance/TimeToBeReceived/TimeToBeReceived.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/Serialization/SerializationFeature.cs
- src/NServiceBus.Core/Serializers/XML/XmlSerializer.cs
- src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs
> Replaced GetAvailableTypes().Where(Conventions.IsMessageType) with MessageMetadataRegistry

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehaviorTests.cs
- src/NServiceBus.Core/Routing/UnicastRouter.cs
- src/NServiceBus.Core/Unicast/Messages/MessageMetadata.cs
- src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs
A few small optimizations to UnicastRouter
* MessageMetadata.Hierarchy is now an array which makes creating the hierachy and iterating it faster and cheaper.
* No longer use `Distinct` on the hierarchy. The hierachy shouldn't contain duplicates in the first place (not sure this can even occur)
* Use a HashSet when resolving the UnicastRoutes since they are comparable and deduplicating them avoids weird behavior on the distribution strategy. -> this change is questionable, the HashSet will come with much higher Add costs for cases where multiple routes for the same type are found. We could also stay with the faster list at the risk of the round-robin strategy behaving not entirely correct because the same destination may be passed multiple times to the distribution strategy (especially in …
> Unicast router optimizations

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Recoverability/RecoverabilityExecutorTests.cs
- src/NServiceBus.Core/Recoverability/DelayedConfig.cs
- src/NServiceBus.Core/Recoverability/FailedConfig.cs
- src/NServiceBus.Core/Recoverability/ImmediateConfig.cs
- src/NServiceBus.Core/Recoverability/Recoverability.cs
- src/NServiceBus.Core/Recoverability/RecoverabilityConfig.cs
Connects to https://github.com/Particular/V6Launch/issues/69
* RecoverabilityConfig should not be a struct because it is larger than 16 bytes (currently 32 bytes) see #3963 
* Making ctors public for better testability of custom recoverability policies
// @tmasternak
> Making RecoverabilityConfig a class

- src/NServiceBus.Core/Unicast/MessageHandlerRegistry.cs
The delegate holder is essentially a singleton per message handler. It is larger than 16 bytes and mutable. We are not gaining anything by making it a struct. See #3963
> DelegateHolder should be a class

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_subscribing_to_scaled_out_publisher_on_unicast_transport.cs
- src/NServiceBus.AcceptanceTests/Routing/When_using_assembly_level_message_mapping_for_pub_sub.cs
Tests that we send a subscription message to each instance of a logical endpoint and that we do not use a distribution strategy.
@Particular/nservicebus-maintainers @SzymonPobiega @DavidBoike please review
> Add subscription behavior acceptance test

- src/NServiceBus.Core/Transports/Msmq/EndpointInstanceExtensions.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqTransportInfrastructure.cs
since we currently map they attributes 1:1 into dictionary key/value pairs, this changes the machine key to be lowercase to align with the rest of the instance mapping settings.
e.g. instead of 
```
<endpoints>
<endpoint name="Routing.Receiver">
<instance discriminator="1" Machine="machine1" />
</endpoint>
</endpoints>
```
this becomes:
```
<endpoints>
<endpoint name="Routing.Receiver">
<instance discriminator="1" machine="machine1" />
</endpoint>
</endpoints>
```
this does not address any of the ideas of changing the xsd to be more restrictive.
ping @Particular/nservicebus-maintainers @DavidBoike @SzymonPobiega
> Make machine property key lowercase

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Recoverability/MoveToErrorsExecutorTests.cs
- src/NServiceBus.Core/Pipeline/Incoming/IncomingPhysicalMessageContext.cs
- src/NServiceBus.Core/Transports/IncomingMessage.cs
- src/NServiceBus.Testing.Fakes/TestableIncomingPhysicalMessageContext.cs
Prevents that `IncomingMessage` body can be set by something from the outside. Only core infrastructure can update the body.
@tmasternak this would mean we could remove the `RevertMessageBody` from the `MoveToErrorExecutor`.
> Incoming message body can only be updated from the core

- src/NServiceBus.Core.Tests/Pipeline/HeaderOptionExtensionsTests.cs
- src/NServiceBus.Core/Extensibility/ExtendableOptions.cs
- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPhysicalToRoutingConnector.cs
Connects to #3907 
This is a simple counter proposal to #3940 
In my point of view there is no real reason why the header needs to be set in the `OutgoingPhysicalToRoutingConnector`. The message id provided on the context cannot be changed. So the simplest possible solution which is backwards compatible is to early assign the header. If a user decides to override the message id header those changes will not be reflected on the pipeline contexts. We don't want to reflect those changes since it is an advanced use case when a user decides to fiddle with this header. We do not keep context properties in sync with other headers. So this approach is consistent.
It is the simpler solution because it is backwards compatible with the guidance we gave in the past (raised by @johnsimons  in …
> ExtendableOptions sets the message id header.

- src/NServiceBus.Testing.Fakes/TestableIncomingPhysicalMessageContext.cs
@danielmarbach this fails the build locally. Not sure why it doesn't do that on the build server. Please merge
> Add missing xml comment on TestableIncomingPhysicalMessageContext

- src/NServiceBus.Core.Tests/Routing/FileRoutingTableParserTests.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTable.cs
- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/endpoints.xsd
- src/NServiceBus.Msmq.AcceptanceTests/When_using_empty_instance_mapping_file.cs
Adds logging of added/removed instances on the instance-mapping file as suggested by @DavidBoike 
Example log outputs:
* Changing an instance value (e.g. changing the discriminator or machine attribute): `Updated endpoint 'test': +1 instance, -1 instance`
* Adding a new endpoint with instance: `Added endpoint 'test2' with 1 instance`
* Removing an endpoint: `Removed endpoint 'test2' with all instances`
all entries are a single log-entry (with line breaks)
Not handled:
* Adding a logical endpoint without instances will not show up in the logging because we don't have an EndpointInstance. I think it's probably not worth to change the code to handle that, but I don't have a strong opinion on this and happy to discuss this on this PR.
I went with LINQ …
> Log changes to instance mapping file

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Causation/AttachCausationHeadersBehaviorTests.cs
- src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/DispatchTimeoutBehaviorTest.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Recoverability/DefaultRecoverabilityPolicyTests.cs
- src/NServiceBus.Core.Tests/Recoverability/DelayedRetryExecutorTests.cs
- src/NServiceBus.Core.Tests/Recoverability/MoveToErrorsExecutorTests.cs
- src/NServiceBus.Core.Tests/Recoverability/RecoverabilityExecutorTests.cs
- src/NServiceBus.Core.Tests/Reliability/Outbox/TransportReceiveToPhysicalMessageProcessingConnectorTests.cs
- src/NServiceBus.Core.Tests/Routing/ApplyReplyToAddressBehaviorTests.cs
- src/NServiceBus.Core.Tests/Routing/DetermineRouteForReplyBehaviorTests.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs
- src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
- src/NServiceBus.Core/Transports/ErrorContext.cs
- src/NServiceBus.Core/Transports/IncomingMessage.cs
- src/NServiceBus.Core/Transports/MessageContext.cs
- src/NServiceBus.Core/Transports/Msmq/ReceiveStrategy.cs
- src/NServiceBus.Testing.Fakes/TestableIncomingPhysicalMessageContext.cs
- src/NServiceBus.Testing.Fakes/TestableSatelliteProcessingContext.cs
- src/NServiceBus.Testing.Fakes/TestableTransportReceiveContext.cs
- src/NServiceBus.TransportTests/When_message_is_available.cs
- src/NServiceBus.TransportTests/When_on_message_throws.cs
@bording brought up a good point that for some transports the transport gets a byte array, turns that into a memory stream to pass it into the core just so that incoming message turns that again into a byte array. That doesn't make sense. Let's face it, core is not ready to properly handle streams. This PR backtracks that. WIP PRs all submitted to transports to show the influence.
* Azure Service Bus influence https://github.com/Particular/NServiceBus.AzureServiceBus/pull/285
* Azure Storage Queue influence https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/137
* Sql Server influence https://github.com/Particular/NServiceBus.SqlServer/pull/282
* RabbitMQ influence https://github.com/Particular/NServiceBus.RabbitMQ/pull/186
> Removing the stream from MessageContext and ErrorContext

- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageBehaviorTests.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageContext.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageContext.cs
For #3956 I was debugging acceptance tests and found out that we always update the message body although not mutator has changed anything. This PR fixes it and adds more test coverage to the mutator behaviors.
@Particular/nservicebus-maintainers please review 
// cc @SimonCropp
> Incoming and outgoing transport mutator contexts indiciate message has changed although there was no change

- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
and align check logic with when done condition check
@MarcinHoppe and I found a bug with contentions on the UnfinishedFailedMessages dictionary. When a test shuts down quicker than the CatchExceptionBehavior added by the acceptance test framework then the tight while loop on the dictionary will prevent the AddOrUpdate method call from succeeding. Therefore the tests will fail with an indication that there were unfinished failed messages (which is a obviously false).
> Reduce contention on UnfinishedFailedMessages dictionary

- src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeDispatcher.cs
- src/NServiceBus.AcceptanceTests/Core/FakeTransport/ProcessingOptimizations/When_using_concurrency_limit.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/DispatchTimeoutBehaviorTest.cs
- src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/RecordingFakeDispatcher.cs
- src/NServiceBus.Core.Tests/Msmq/MsmqMessageDispatcherTests.cs
- src/NServiceBus.Core.Tests/Recoverability/DelayedRetryExecutorTests.cs
- src/NServiceBus.Core.Tests/Recoverability/MoveToErrorsExecutorTests.cs
- src/NServiceBus.Core.Tests/Recoverability/RecoverabilityExecutorTests.cs
- src/NServiceBus.Core.Tests/Routing/MessageDrivenSubscribeTerminatorTests.cs
- src/NServiceBus.Core.Tests/Routing/MessageDrivenUnsubscribeTerminatorTests.cs
- src/NServiceBus.Core.Tests/Timeout/FakeMessageDispatcher.cs
- src/NServiceBus.Core.Tests/Unicast/LoadHandlersBehaviorTests.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs
- src/NServiceBus.Core/Pipeline/Outgoing/ImmediateDispatchTerminator.cs
- src/NServiceBus.Core/Recoverability/DelayedRetryExecutor.cs
- src/NServiceBus.Core/Recoverability/MoveToErrorsExecutor.cs
- src/NServiceBus.Core/Routing/Legacy/ReadyMessageSender.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenUnsubscribeTerminator.cs
- src/NServiceBus.Core/Transports/IDispatchMessages.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqMessageDispatcher.cs
- src/NServiceBus.Core/Transports/Msmq/ReceiveWithTransactionScope.cs
- src/NServiceBus.Core/Transports/TransportTransaction.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_receiving_control_message_with_body.cs
- src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
- src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
Quick recap
* The dispatcher gets a context bag which will contain everything that is available in the pipeline that was explicitly added to the contexts. This is our back door for extensibility.
* The transport transaction is an explicit concept which allows floating transaction relevant state into the dispatcher. 
In the current design, an implementor of a dispatcher needed to know that a transport transaction might be added to the context bag and do a try get on the context bag. After discussions with @yvesgoeleven from @Particular/azure-service-bus-maintainers we came to the conclusion that this is not really intention revealing.
This PR changes that and makes the transport transaction an explicit concept. In order to do that, I needed to seal the type (inheritance was anyway not …
> Making the transport transaction an explicit concept on the dispatcher

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/UnicastSendRouterTests.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/Routing/RoutingSettings.cs
- src/NServiceBus.Core/Routing/UnicastRoutingTable.cs
replaces the three RouteToAddress RouteToEndpoint and RouteToInstance overloads with RouteTo which just accepts a `IUnicastRoute`
RouteToXYZ already internally created a UnicastRoute and the methods were mapped 1:1 (for every unicastroute option there was a method on the routing table). Additionally, users were already able to provide a `IUnicastRoute` when using the dynamic overloads, so I think this aligns the API better.
This will also make testing of the routing table a lot more easier since it will be possible to compare references instead of having to resolve the routes which are created internally.
@Particular/nservicebus-maintainers @DavidBoike @SzymonPobiega please review
> Reduce RouteTo overloads in UnicastRoutingTable

- src/NServiceBus.Core/Routing/FileBasedDynamicRouting/FileRoutingTableFeature.cs
- src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj
- src/NServiceBus.Msmq.AcceptanceTests/When_starting_with_missing_instance_mapping_file.cs
Resolves https://github.com/Particular/NServiceBus/issues/3998
> Throwing when explicitly configured instance mapping file is missing

- src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
- src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
- src/NServiceBus.TransportTests/TypeScanner.cs
This change makes the new transport tests project work more like the acceptance tests in how it chooses which transport to use to run the tests.
Instead of requiring the "Transport.UseSpecific" environment variable to be set to select something other than MSMQ, it now looks for types that implement `TransportDefinition` and picks the first non-MSMQ definition it finds, falling back to MSMQ if there aren't any. The environment variable can still be used to override the automatic selection if need be.
The `TypeScanner` class was copied from the AcceptanceTests project.
@tmasternak What do you think?
// cc @adamralph
> Select transport for TransportTests based on available TransportDefinitions

- src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
Removes the inheritance on subscription routes as suggested by #3911. This means that a route for a child event will not be applicable when trying to resolve a route for a base event. 
so the follow scenario will no longer work:
```
routingConfig.RegisterPublisher(typeof(Cat), "CatPublisher");
endpoint.Subscribe<Animal>(); // will no longer "inherit" the route from Cat
```
> Subscription route inheritance

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/LogicalAddress.cs
Small improvement without big impact on usages. Since we have to wrap an EndpointInstance in a LogicalAddress every time we want to resolve it's transport address this should improve allocations a bit.
@Particular/nservicebus-maintainers @SzymonPobiega @Scooletz please review
> Make LogicalAddress a struct

- src/NServiceBus.AcceptanceTests/Encryption/When_using_Rijndael_with_unobtrusive_mode.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Encryption/ConfigureRijndaelEncryptionService.cs
- src/NServiceBus.Core/Encryption/Encryption.cs
- src/NServiceBus.Core/Encryption/EncryptionInspector.cs
- src/NServiceBus.Core/Encryption/Encryptor.cs
- src/NServiceBus.Core/Encryption/StringConversions.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/obsoletes.cs
Closes #3990 
The encryption feature will no longer be enabled by default and silently disable itself when there is nothing to decrypt. The feature is now opt-in by using the following approach:
When you call `RegisterEncryptionService` or `RijndaelEncryptionService` the feature will get enabled. 
If I understood the logic flow correctly it was always required to call `RegisterEncryptionService` or `RijndaelEncryptionService` anyway. The previous feature would throw configuration exceptions if you didn't.
See https://github.com/Particular/NServiceBus/pull/3991/files#diff-095bc316e056d2a288aa5e4839fd9a06L31
> Property encryption is enabled via the configuration API.
http://docs.particular.net/nservicebus/security/encryption
Since we cannot properly rely on message types being included in …
> Property encryption does not work with unobtrusive mode

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Performance/TimeToBeReceived/When_TimeToBeReceived_has_expired_convention.cs
- src/NServiceBus.AcceptanceTests/Performance/TimeToBeReceived/When_TimeToBeReceived_used_with_unobtrusive_mode.cs
- src/NServiceBus.Core.Tests/Performance/TimeToBeReceived/TimeToBeReceivedAttributeTests.cs
- src/NServiceBus.Core/Performance/TimeToBeReceived/TimeToBeReceived.cs
- src/NServiceBus.Core/Performance/TimeToBeReceived/TimeToBeReceivedMappings.cs
Closes https://github.com/Particular/NServiceBus/issues/3989
This fixes the time to be received for unobtrusive mode. The current design still tries to precache time to be received for known messages. If types are not known they will be added during runtime.
Previous version did only cache time to be received for messages when TTBR was less than `TimeSpan.Max`. This code changes it slightly to also cache TimeSpan.Max values. I think this is a reasonable trade off which allows us to use the more atomic `GetOrAdd` overloads of the concurrent dictionary instead of doing a `TryGet` and then a `TryAdd`.
And alternative approach could be to store Timespan? (Nullable) instead of `Timespan.Max` but I think this is unnecessary optimizations.
> TimeToBeReceived does not work with unobtrusive mode

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Routing/RoutingSettingsTests.cs
- src/NServiceBus.Core.Tests/Routing/UnicastRoutingTableTests.cs
- src/NServiceBus.Core.Tests/Routing/UnicastSendRouterTests.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/Routing/UnicastRoutingTable.cs
- src/NServiceBus.Core/Routing/UnicastSendRouter.cs
No longer allow multiple static route for a message type. This PR addresses https://github.com/Particular/NServiceBus/issues/3909 
A command can no longer have multiple routes registered and therefore no longer be sent to multiple receivers when registering multiple routes for the same message type.
Changes:
* when registering multiple routes  using the (legacy) message endpoint mapping config, the last route for a specific type overrides the current route. This should align with the v5 behavior.
* when registering multiple static routes for the same type, it will throw an exception
* the advanced routing table API provides an overload where you can define whether you want to allow a static route or not.
* You can no longer add multiple dynamic routes. There is a single (async) "fallback" …
> Single route for commands

- src/NServiceBus.Core/Routing/UnicastSendRouter.cs
that HashSet was previously used for deduplication of equivalent routingtargets resolved by different routes. Since there is now only a single route, the routingTargets come from a single route and therefore shouldn't require filtering duplicate values.
Need to address some further refactorings before making more changes to UnicastSendRouter (I'm coming for you, GroupBy!)
@Particular/nservicebus-maintainers @SzymonPobiega please review
> Remove unnecessary collection

- src/NServiceBus.Core/Routing/SingleInstanceRoundRobinDistributionStrategy.cs
we should avoid race conditions by using the returned value from the increment operation instead of using the index variable directly.
addresses @danielmarbach comment here: https://github.com/Particular/NServiceBus/pull/4011#discussion_r73677488
@danielmarbach please review
> Make index threadsafe

- src/NServiceBus.AcceptanceTests/DataBus/When_sending_databus_properties_with_unobtrusive.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core/Conventions.cs
We had several issues around unobtrusive conventions. This verifies whether the data bus still works with unobtrusive and "optimized" assembly scanning with v6.
> Verify databus still works with unobtrusive mode

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/DistributionPolicyTests.cs
- src/NServiceBus.Core.Tests/Routing/RoutingPolicyTests.cs
- src/NServiceBus.Core.Tests/Routing/SingleInstanceRoundRobinDistributionStrategyTests.cs
- src/NServiceBus.Core/Routing/DistributionStrategy.cs
- src/NServiceBus.Core/Routing/SingleInstanceRoundRobinDistributionStrategy.cs
- src/NServiceBus.Core/Routing/SpecificInstanceDistributionPolicy.cs
- src/NServiceBus.Core/Routing/UnicastPublishRouter.cs
- src/NServiceBus.Core/Routing/UnicastSendRouter.cs
DistributionStrategies can now only return a single result instead of multiple. Since we allow commands only to be sent to a single receiver, it would be invalid for a distributionstrategy to return multiple instances. For events there is currently also no realistic scenario to publish the same event to multiple instances of the same logical endpoint.
@Particular/nservicebus-maintainers @SzymonPobiega please review
> Distribution strategy refactoring

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_configure_routes_for_unobtrusive_messages.cs
- src/NServiceBus.AcceptanceTests/Routing/When_registering_publishers_unobtrusive_messages.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensionsTests.cs
- src/NServiceBus.Core.Tests/Routing/RoutingSettingsTests.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensions.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/Routing/RoutingSettings.cs
Assembly based routing and publisher APIs no longer use known message types of the metadata registry since this will miss unobtrusive messages which aren't initially scanned and are added lazily during runtime. This requires the routing APIs which allow registration of routes for a whole assembly to scan the assemblies types itself at startup to configure the static routes.
Added specific tests for the expected behavior. Some of those already were green before (publisher registration API, because of the existing handlers which cause the unobtrusive messages to be included at startup), others were failing (Commands).
Also made the ctors of the routing API settings class public for the acceptance tests to have access to the routing API (which contains the assembly scanning logic), otherwise …
> Fix unobtrusive assembly routing

- src/NServiceBus.Core/Transports/Msmq/MsmqTransportInfrastructure.cs
- src/NServiceBus.Core/Transports/Msmq/ReceiveWithTransactionScope.cs
This change should not change code behavior in any way but should express the intent of starting the top level transaction scope more clearly. A similar change has already been implemented in the SQL Server transport.
> Set the transport transaction scope as top-level

- src/NServiceBus.AcceptanceTests/Basic/When_receiving_unobtrusive_message_without_handler.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs
With unobtrusive and assembly scanning which excludes assemblies that don't reference NServiceBus we can no longer rely on messages being registered during bootstrapping. This PR aligns the string overload of `GetMessageMetadata` to runtime register the type when it could be loaded in the current app domain.
I had a hard time to come up with ATTs. So this change comes in without tests. If someone is willing to help out I would appreciate your help. Maybe there is a simple way to test it. If not I'll propose to pull it in as is.
> MessageMetadataRegistry GetMessageMetadata with strings registers type if it matches the message conventions

- src/NServiceBus.AcceptanceTests/Basic/When_sending_interface_message_with_conventions.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_publishing_an_interface_with_unobtrusive.cs
- src/NServiceBus.AcceptanceTests/Routing/When_replying_to_message_with_interface.cs
I added these tests for verifying that sending, publishing and replying with proxy types works even though the assembly scanning didn't pick up the message type (it works because the message mapper gets initialized lazily)
> Added acceptance test for unobtrusive sending, publishing and replying with proxy

- src/NServiceBus.AcceptanceTests/Satellites/When_a_message_is_available.cs
- src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/DispatchTimeoutBehaviorTest.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs
- src/NServiceBus.Core/Pipeline/satellitePipelineExecutor.cs
Satellites now also use explicit transport transaction from the message context when dispatching.
Fixes #4047
> Put transport transaction in the context for satellites

- src/NServiceBus.AcceptanceTests/Hosting/When_overriding_input_queue_name.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Transports/ReceiveSettingsExtensions.cs
- src/NServiceBus.Core/obsoletes.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_distributing_an_event.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_overriding_address_translation.cs
We talked about renaming `OverrideInputQueueName` back to it's v5 naming to make migrations easier at the cost of the slightly more accurate naming. There seems to be no difference in behavior between v5 and v6.
@Particular/nservicebus-maintainers @SzymonPobiega @DavidBoike ping
> Rename OverrideInputQueueName back to OverrideLocalAddress

- src/NServiceBus.Core/Timeout/Hosting/Windows/TimeoutPersisterReceiver.cs
Fixes #4015
Only interfere with next timeout retrieval if pushed timeout is earlier than previously planned retrieval to prevent tight query loops when ingesting timeouts
> Don't query TimeoutPersisterReceiver in tight loop when ingesting timeouts

- src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
10s is to short for ASB. Just to get it going. We can consider making this configurable by the transport in the future if needed
> Default transport test timeouts to 30s

- src/NServiceBus.AcceptanceTests/MessageDrivenPubSubRoutingExtensions.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_registering_publishers_unobtrusive_messages.cs
- src/NServiceBus.AcceptanceTests/Routing/When_subscribing_to_multiple_publishers.cs
@SzymonPobiega noticed that we don't have an att to verify that we support registration of multiple publishers on the same message type for message driven pubsub transports (as brokered transports already support).
/cc @SzymonPobiega @DavidBoike
> ATT for subscribing to multiple publishers

- src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_immediate_retries_with_native_transactions.cs
This test worked for all transports without native deferral capabilities since the tests disable the TimeoutManager by default. On ASB (which has native delayes) the count is no longer correct since the test requested 3 delayed retries.
Delayed retries is now disabled for the test.
Note: I removed the ID check since the ATT framework does that check behind the scenes anyway
Side note: I think the test should have failed on MSMQ since we explicitly disables the TM AND explicitly requests delayed retries, issue raised: https://github.com/Particular/NServiceBus/issues/4058
> Disable delayed retries in test to make the count correct

- src/NServiceBus.AcceptanceTests/Versioning/When_multiple_versions_of_a_message_is_published.cs
Since interfaces breaks the json serializer and interfaces isn't needed for this test.
The json bug is tracked in https://github.com/Particular/NServiceBus/pull/4060
> Use class instead of interface in the multi version test

- src/NServiceBus.Core.Tests/GlobalTestSetup.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/RedirectHelper.cs
Some unit tests make assertions on exception messages. When these test are executed on operating systems using a culture that is different than one of the English variants, they fail because the exception messages are localized.
The easiest solution to this problem that I found is to run all the tests with invariant culture (English without any other culture specific modifications).
> Set invariant culture in core tests

- src/NServiceBus.AcceptanceTests/Routing/When_extending_command_routing.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/DistributionPolicyTests.cs
- src/NServiceBus.Core.Tests/Routing/Routers/UnicastSendRouterConnectorTests.cs
- src/NServiceBus.Core.Tests/Routing/RoutingPolicyTests.cs
- src/NServiceBus.Core.Tests/Routing/SingleInstanceRoundRobinDistributionStrategyTests.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Routing/DistributionPolicy.cs
- src/NServiceBus.Core/Routing/DistributionStrategy.cs
- src/NServiceBus.Core/Routing/DistributionStrategyScope.cs
- src/NServiceBus.Core/Routing/IDistributionPolicy.cs
- src/NServiceBus.Core/Routing/Routers/UnicastSendRouterConnector.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/Routing/SingleInstanceRoundRobinDistributionStrategy.cs
- src/NServiceBus.Core/Routing/SpecificInstanceDistributionPolicy.cs
- src/NServiceBus.Core/Routing/UnicastPublishRouter.cs
- src/NServiceBus.Core/Routing/UnicastSendRouter.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqConfigurationExtensions.cs
based on top of #4065 
Please do not merge. Let's merge #4065 first and then change the base of this PR.
Changes the distribution strategy according to @SzymonPobiega proposal to always accept resolved addresses instead of `EndpointInstance` to have the same API for publishes and sends.
We still need to differentiate publishes and sends because of the received parameters in the resolved strategies. Therefore adding/resolving strategies requires a scope parameter, which defines whether that strategy is used for publishes or sends.
ping @SzymonPobiega @DavidBoike @bording 
Todo:
> Distinct distribution strategies between sends and publishes

- src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs
While doing some profiling, I noticed that the `MessageMetadataRegistry.GetMessageMetadata` method that takes a string was showing up as being very expensive.
This optimizes the method by caching the result of the `Type.GetType` call instead of calling it every time.
For the scenario I was profiling, (seeding 200K messages, and then running an endpoint to receive all of them) this reduces the total time spent in this method from around 2,000 ms to about 70ms.
I also went ahead and removed the LINQ usage from the method to prevent the capture allocation for each call. 
I'm not sure when we'd actually hit the scenario where `messageType` would be null. Is it possible that we don't need this test at all now?
> Optimize MessageMetadataRegistry

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_overriding_local_address.cs
- src/NServiceBus.AcceptanceTests/Satellites/When_a_message_is_available.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs
- src/NServiceBus.Core/LogicalAddress.cs
- src/NServiceBus.Core/Routing/RoutingFeature.cs
- src/NServiceBus.Core/SettingsExtensions.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqConfigurationExtensions.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqTransportInfrastructure.cs
- src/NServiceBus.Core/Transports/Receiving.cs
- src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj
- src/NServiceBus.Msmq.AcceptanceTests/When_overriding_local_address.cs
Refactors the override local address code so that now it uses a `queue` property on the endpoint instance class. 
Removes the `OverrideAddressTranslation` API from MSMQ
Adds a `AddEndpointInstances` API to MSMQ which can be used in conjunction with `WithQueue` instance extension method to define routing to instances that have overridden queue name.
TODO:
> Queue override via endpoint instance property

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Transports/PushRuntimeSettingsTests.cs
- src/NServiceBus.Core/Transports/PushRuntimeSettings.cs
I went with logical processor count since that seems to be close enough and much easier to get at
http://stackoverflow.com/questions/1542213/how-to-find-the-number-of-cpu-cores-via-net-c
Doco PR - https://github.com/Particular/docs.particular.net/pull/1814
Closes #4089
> Default concurrency to max(2,LogicalProcessorCount)

- src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
This is needed as some of the transport e.g. SqlServer depend on `EndpointInstances` being always registered by the `Core` when transport gets initialized.
> Add EndpointInstances in fake message pump setup

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_registering_publishers_unobtrusive_messages_code.cs
- src/NServiceBus.AcceptanceTests/Routing/When_registering_publishers_unobtrusive_messages_config.cs
Because it breaks persistences which are not cleaned up between the test methods.
> Split the test into two classes.

- src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
backports fixes related to https://github.com/Particular/NServiceBus/issues/2722 to latest v5.
This hasn't been tested yet.
> Avoid exceptions when FileName not set on FileLoadException

- src/NServiceBus.Core.Tests/DateTimeExtensionsTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core/DateTimeExtensions.cs
`DateTimeExtensions.ToUtcDateTime` is another method that's been showing up as very expensive in my profiling.
For my test case (seeding 200K messages, and then receiving all of them) this method was taking over 1,100 ms of total execution time.
With this change, it now takes 75 ms.
One difference in the output for this approach is that the "ffffff" part of the date format can't be used directly from any of the DateTime constructors, so I've had to round it down to milliseconds instead of microseconds. Given the [note](https://msdn.microsoft.com/en-us/library/8kb3ddd4(v=vs.110).aspx#Anchor_9) about this format string option, the microsends are likely a false level of precision anyway, so I didn't think losing this would be a big deal.
> Improve ToUtcDateTime performance

- src/NServiceBus.AcceptanceTests/Core/Routing/AutomaticSubscriptions/When_handling_local_event.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_handling_local_event.cs
- src/NServiceBus.Core/StartableEndpoint.cs
- src/NServiceBus.Core/Transports/TransportReceiver.cs
Fixes https://github.com/Particular/NServiceBus/pull/3891 (stole the acceptance test from @ramonsmits ) by spliting initialization time from startup of the `TransportReceiver` allowing to purge queues before running FeatureStartupTasks.
@Particular/nservicebus-maintainers @ramonsmits please have a look. Although there were some conversations about ASB I think this is still the right approach in general (not only related to autosubscriptions, but to local sends in general).
> Fix local autosubscribe

- src/NServiceBus.ContainerTests/When_building_components.cs
- src/NServiceBus.ContainerTests/When_registering_components.cs
- src/NServiceBus.ContainerTests/When_using_nested_containers.cs
Based on the discussion [here](https://github.com/Particular/NServiceBus/issues/4075), there is no value in keeping these tests around - and in fact it makes it harder for community ports to other containers. This PR will remove these non-tests as well as update the list of comments that are making incorrect assumptions about Spring and Castle Windsor support.
Ping @Particular/nservicebus-maintainers and @Particular/container-maintainers
> Remove false tests and incorrect comments about spring

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_unsubscribing_to_scaled_out_publisher.cs
- src/NServiceBus.AcceptanceTests/Routing/SubscriptionBehavior.cs
- src/NServiceBus.AcceptanceTests/Routing/SubscriptionBehaviorExtensions.cs
noticed this missing test. Required to change the existing infrastructure to support notification on unsubscribe (actually, `OnEndpointSubscribed` also fired for unsubscribe).
> Add test to verify unscubribe using scaled out publishers

- src/NServiceBus.AcceptanceTests/Serialization/When_configuring_custom_xml_namespace.cs
- src/NServiceBus.Core/Licensing/LicenseExpiredForm.cs
- src/NServiceBus.Core/Licensing/LicenseManager.cs
Relates to https://github.com/Particular/V6Launch/issues/119
URL now includes trial date info.
Things to do:
> Url change for license expiration

- src/NServiceBus.Core/Performance/ReceiveStatisticsFeature.cs
- src/NServiceBus.Core/Performance/Statistics/ReceivePerformanceDiagnosticsBehavior.cs
Fixes https://github.com/Particular/NServiceBus/issues/4165
This approach also works when configuring an input queue different from the endpoints logical name, using `OverrideLocalAddress` (then performance counters have the overridden name).
> Use endpoints logical address to generate performance counters

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_handles_messages_concurrently.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_started_concurrently.cs
- src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs
InMemoryPersistence will create saga duplicates under the following scenario:
All users using InMemorySagaPersister 
1. Persistence selected as InMemoryPersistence (obviously)
1. Usage of sagas which are started multiple message types with `IAmStartedByMessages`
1. Concurrency set to greater than one (default in v6)
1. Sending out two messages which can start the saga at the same time
Two saga instances are created which leads to incorrect business behavior.
> In-memory persister does not throw concurrency exceptions

- src/NServiceBus.Core/Licensing/LicenseExpiredForm.Designer.cs
- src/NServiceBus.Core/Licensing/LicenseExpiredForm.cs
- src/NServiceBus.Core/Licensing/LicenseManager.cs
Related to https://github.com/Particular/OptimizeTrialExtensions/issues/10 with wordings suggested by task force consisting of @DavidBoike @adamralph @alxrz @ryansteinparticular.
Make all the wording related to licensing more clear so that customers aren't put off thinking that the trial period is _only_ 14 days and that they have options. Also, seek to remove clutter and only use the minimum words necessary, since people commonly don't fully read dialogs.
The purpose of this PR is to start with the suggested wording from the Task Force, engage @Particular/nservicebus-maintainers first, and then RFC the changes company-wide.
Every time an endpoint in the initial trial would run, you would see:
> INFO Trial for Particular Service Platform is still active, trial expires on {expirationDate}. …
> Licensing wording for better clarity

- src/NServiceBus.Core/Routing/MessageEndpointMappingCollection.cs
Relates to https://github.com/Particular/NServiceBus/issues/1939. An exception is raised when two entries with the same key (but different values) are configured to avoid accidental misconfiguration.  The raised exception is not very helpful because it doesn't give any information what this configuration issue is about and the given values are not understandable because we the entries key is an aggregate string of different properties, not helpful to users.
We can catch that exception though an provide a more helpful message. What do you think about the message @SimonCropp ? Sadly, I don't think there is a good way of giving more details about the conflicting key, but not sure this is absolutely necessary?
> Provide a more helpful exception message

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Persistence/InMemory/InMemorySubscriptionStorageTests.cs
- src/NServiceBus.Core.Tests/Persistence/Msmq/MsmqSubscriptionStorageTests.cs
- src/NServiceBus.Core/Unicast/Subscriptions/MessageDrivenSubscriptions/MessageType.cs
- src/NServiceBus.sln.DotSettings
Subscribers no longer receive events published if the publisher changes the `Major` assembly version part on the contract assembly without subscribers being updated at the same time.
All users on a transport using [message driven pub/sub](https://docs.particular.net/nservicebus/messaging/publish-subscribe/#mechanics-persistence-based-message-driven) that have a message contract versioning strategy that increases the `Major` assembly version part for changes that are not to be considered breaking for subscribers.
Related to  https://github.com/Particular/NServiceBus/issues/1394
> Remove subscription versioning for MSMQ and InMemory subscriptions

- src/NServiceBus.Core/IdGeneration/CombGuid.cs
CombGuid was using `DateTime.Now` which is much slower due to timezone conversions but also causes sorting issues due to DST offsets.
Applied the same fix as I did for NHibernate (https://github.com/nhibernate/nhibernate-core/pull/440)
> CombGuid now using DateTime.UtcNow to resolve DST ordering issues

- src/NServiceBus.Core/Recoverability/Faults/ErrorsNotifications.cs
Early return to avoid the full message copy with no eventhandlers registered.
> Avoid allocating a complete copy of the message on every failure unless it is necessary

- README.md
Doesn't make any sense, user install via nuget and we don't have to teach them that?
> Remove running section from readme

- src/NServiceBus.Core/Impersonation/Windows/WindowsIdentityEnricher.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqDequeueStrategy.cs
- src/NServiceBus.Core/Unicast/Queuing/QueueNotFoundException.cs
- src/NServiceBus.Core/Utils/ElevateChecker.cs
Rebased after v6 merge to master. Made some relevant comments here https://github.com/Particular/NServiceBus/pull/4189
* Fixes deadlock when MSMQ service restarts with native transaction, closes #4188 
* Reduces allocations on hot path for the dequeue strategy
* Removes the long running flag and replaces Task.Factory.StartNew with Task.Run, fixes #3251
> Hotfix-5.2.18

- src/NServiceBus.AcceptanceTesting/Support/FailTestOnErrorMessageFeature.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
@Scooletz and I noted that the ATT may swallow the exception which is thrown in case the test doesn't complete in the given time. The scenario works as follows:
* Test doesn't complete in the specified time because messages are still processed. An exception is thrown.
* A finally block will shut down the endpoints
* In the shutdown procedure we wait for messages which are marked for retries to complete
* After 30 seconds, there are still messages (possibly new messages) scheduled for retries. A new exception is thrown from the finally block.
* The new exception hides the first exception and hides some valuable information that the done condition was not hit within the specified time.
I think we can solve this by moving this check before actually shutting down the endpoints in the finally …
> Do not swallow timeout exceptions in Acceptance Tests

- src/NServiceBus.Core/Transports/Msmq/MsmqUnitOfWork.cs
Closes #4215 
HasActiveTransaction of `MsmqUnitOfWork` needs to check the `currentTransaction.Value` for non-null
`currentTransaction.IsValueCreated` will always return true when a thread already assigned the slot although the value is null.
* When handling an incoming message, an MSMQ transaction is set on the `MsmqUnitOfWork`.
* After the processing, `ClearTransaction` is called which set the ThreadLocal variable value to null ( `currentTransaction.Value = null;`)
* When a message is sent on the bus outside the pipeline, it checks `MsmqUnitOfWork.HasActiveTransaction()` which uses the following implementation: `return currentTransaction.IsValueCreated;`
Sadly, `IsValueCreated` will remain true even after setting the current transaction to null. This makes the sender think it needs to …
> Hotfix-5.2.19

- src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
- src/NServiceBus.TransportTests/When_transaction_level_TransactionScope.cs
Adds a new transport test to verify correct behavior of `Transaction.Current` and `TransportTransactions.Get<Transaction>()` when using the TransactionScope transaction level.
@Particular/nservicebus-maintainers @Particular/sqlserver-transport-maintainers thoughts?
> Verify correct transaction scope sharing

- src/NServiceBus.Core/Transports/Msmq/NoTransactionStrategy.cs
- src/NServiceBus.Core/Transports/Msmq/ReceiveOnlyNativeTransactionStrategy.cs
- src/NServiceBus.Core/Transports/Msmq/ReceiveStrategy.cs
- src/NServiceBus.Core/Transports/Msmq/SendsAtomicWithReceiveNativeTransactionStrategy.cs
- src/NServiceBus.Core/Transports/Msmq/TransactionScopeStrategy.cs
> ReceiveStrategy.TryProcessMessage now uses the body stream and the messageId only

- src/NServiceBus.AcceptanceTests/Config/When_multiple_configuration_providers.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core/SettingsExtensions.cs
Fixes #4214 
throw an exception when we find more than one implementation of `IProvideConfiguration<X>`
> Throw exception on ambiguous configuration providers

- src/NServiceBus.ContainerTests/When_registering_components.cs
The `Setter_injection_should_be_enabled_by_default` and `Setter_dependencies_should_be_supported_when_resolving_interfaces` tests are testing a valid core assumption, but they are doing so by using different lifecycles for the properties.
The tests are intended to check that the instance of `ClassWithSetterDependencies` has it's properties set correctly by asserting that the instances of the `SomeClass` property is populated by the container.
The inconsistency is that `ClassWithSetterDependencies` is declared as a single instance type, while `SomeClass` is currently declared as an `InstancePerCall` type. There can never be a scenario in these tests where the instance of `SomeClass` can be a different lifecycle when compared to the instance of `ClassWithSetterDependencies`.
This problem …
> Use a consistent lifecyle for testing

- src/NServiceBus.AcceptanceTests/Routing/SubscriptionBehavior.cs
- src/NServiceBus.AcceptanceTests/Routing/SubscriptionBehaviorExtensions.cs
- src/NServiceBus.Msmq.AcceptanceTests/SubscriptionBehavior.cs
- src/NServiceBus.Msmq.AcceptanceTests/SubscriptionBehaviorExtensions.cs
- src/NServiceBus.TransportTests/When_on_error_throws.cs
fixes #4199
Looks like there should be no issue by moving the subscription detection behavior on the transportreceive stage to avoid InsertBefore.
> Move subscription behaviors to TransportReceive stage to avoid InsertBefore

- packaging/nuget/nservicebus.acceptancetests.nuspec
- packaging/nuget/nservicebus.containertests.nuspec
- packaging/nuget/nservicebus.transporttests.nuspec
We build our acceptance tests source package against nUnit 3.2.1. 3.2 introduces `ThrowsAsync` which isn't available in 3.0 but the nuspec dependency states a dependency on 3.0 of nUnit which can cause compilation errors when downloading the package as `ThrowsAsync` isn't available.
Also updates the dependency on the container and transport tests although they don't use any 3.2 features but are compiled against 3.2.1 too.
> Update nUnit dependency in nuspecs

- src/NServiceBus.AcceptanceTests/DelayedDelivery/TimeoutManager/When_using_external_timeout_manager.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists_and_found_saga.cs
* Fixing the saga finder test
* Fixing the condition in the timeout test
Resolves #4178
> Fix saga and timeout ATs

- src/NServiceBus.AcceptanceTests/Correlation/When_using_a_custom_correlation_id.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Correlation/CorrelationContextExtensions.cs
relates to https://github.com/Particular/NServiceBus/issues/4170
Should we also add a warning for the getter method? I left that one out since it doesn't really apply to the the "we want to avoid usage of that API" in the same way as the setter does.
> Add obsolete warning for SetCorrelationId

- src/NServiceBus.AcceptanceTests/Routing/When_publishing_an_interface.cs
- src/NServiceBus.AcceptanceTests/Routing/When_publishing_an_interface_with_unobtrusive.cs
- src/NServiceBus.AcceptanceTests/Routing/When_publishing_using_root_type.cs
Publisher classes that are required to be accessible by downstream ATTs for testing pub/sub for ASB
Here's an [example](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/master/src/AcceptanceTests/ConfigureEndpointAzureServiceBusTransport.cs#L54) where ASB transport needs to wire the publishers for one of the topologies and requires the class to be internally visible.
> ATT Publisher that are required to be accessible by ASB

- src/NServiceBus.Core/Performance/Statistics/ProcessingStatisticsBehavior.cs
Fixes #4249 
It is just awesome when you work with folks like @bording 
He pointed me to 
> Stopwatch ticks are different from DateTime.Ticks. Each tick in the DateTime.Ticks value represents one 100-nanosecond interval. Each tick in the ElapsedTicks value represents the time interval equal to 1 second divided by the Frequency.
https://msdn.microsoft.com/en-us/library/system.diagnostics.stopwatch.elapsedticks(v=vs.110).aspx
and the answer is to use `Elapsed.Ticks `instead of `ElapsedTicks`.
> Switching from ElapsedTicks to Elapsed.Ticks on stopwatch

- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/UnitOfWork/UnitOfWorkBehaviorTests.cs
- src/NServiceBus.Core/Pipeline/Incoming/ReceiveFeature.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPipelineFeature.cs
- src/NServiceBus.Core/UnitOfWork/UnitOfWorkBehavior.cs
After doing some profiling, I saw that calling `BuildAll` is expensive, and we are doing it three times per message on the incoming pipeline and two times out the outgoing pipeline.
This updates the following behaviors to bypass `BuildAll` if nothing has been registered for them to do:
- UnitOfWorkBehavior
- MutateIncomingTransportMessageBehavior
- MutateIncomingMessageBehavior
- MutateOutgoingMessageBehavior
- MutateOutgoingTransportMessageBehavior
The reason I chose to bypass the logic instead of skipping registration of the behaviors altogether is that when talking with the other @Particular/nservicebus-maintainers, we decided that it would be safer to always have them registered. This way any sort of InsertBefore/After calls would not be impacted.
Should I add tests that register a …
> Optimize behaviors that call BuildAll by skipping logic if nothing is registered

- src/NServiceBus.Msmq.AcceptanceTests/When_using_instance_mapping_file.cs
I happened to be looking at the MSMQ tests for the instance mapping xml file, and I noticed one of the tests was using the wrong class name for the mapping file path.
> Fix test to use correct class name for mappingFilePath

- src/NServiceBus.AcceptanceTests/Core/FakeTransport/ProcessingOptimizations/When_using_concurrency_limit.cs
- src/NServiceBus.Core/StartableEndpoint.cs
Fixes #4213 
as mentioned in that issue, this will change the behavior of our satellite pipelines:
> fixing this also means that core satellites (timeout manager) ignores configured concurrency settings and always will use the default concurrency as of now. Since this code is under own control, I'd say that's no issue but not sure whether I'm missing something?
comment by @andreasohlund 
> That was the plan, to decouple that setting from the user one.
> 
> If the the default (max(2,virtualcores) is suitable for the TM satellites can be discussed though
should we make this discussion part of this PR?
First thoughts:
- the timeout receiver receiver can be concurrent without issues
- dispatcher may reduce duplicates by using a concurrency of 1 (but also limiting the TMs throughput of course) …
> Pass satellite runtime settings to satellite receiver

- src/NServiceBus.Core.Tests/App.config
- src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/packages.config
@danielmarbach This gets almost everything working. I brought in https://bitbucket.org/zastrowm/nunit.applicationdomain/ which make it easy to run each test in its own AppDomain. This along with the Setup and Teardown makes it easy to clean up the scannerassemblies folder without problems. The issues around removing the files previously was because the assemblies were loaded in the AppDomain and still in use when trying to delete them
Accessing the result.CompiledAssembly property causes the assembly to be loaded, so I moved that to after the `fakeIdentity` assembly rewrite, which avoids the exception that was happening there.
At this point the `Assemblies_which_reference_older_nsb_version_are_included` is still failing, but now it's just a failing assert, and not throwing an exception. …
> Fix assembly scanner tests

- src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_TimeoutManager_is_disabled.cs
- src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_timeout_dispatch_fails.cs
- src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_timeout_dispatch_fails_on_timeout_removal_using_dtc.cs
- src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_timeout_dispatch_fails_on_timeout_removal_using_sendsatomicwithreceive.cs
- src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_timeout_storage_fails.cs
- src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_using_external_timeout_manager.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/ScenarioDescriptors/AllTransports.cs
- src/NServiceBus.AcceptanceTests/Tx/When_receiving_with_native_multi_queue_transaction.cs
fixes #4244 
- Split test based on tx level
- Move tests to core folder which excludes them from moving to downstreams
> Split timeout dispatcher test based on tx level

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManagerConfiguration.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManagerConfigurationExtensions.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
addresses https://github.com/Particular/NServiceBus/issues/4264
Adds a configuration API for the timeout manager's satellite queues concurrency settings, to override the default concurrency settings.
usage:
`endpointConfiguration.TimeoutManager().LimitMessageProcessingConcurrencyTo(5);`
@Particular/nservicebus-maintainers the above API is just a suggestion based on the current API design. Tbh I don't think it's very good but I'm lacking better ideas. The only alternative I see would be similar to the recoverability APIs, e.g:
`endpointConfiguration.TimeoutManager(tm => tm.LimitMessageProcessingConcurrencyTo(5));`
thoughts?
Also, I tried to write some tests for it, but this becomes ridiculously complicated as unit tests are nearly impossible and acceptance tests require a full fake …
> Add configuration for TimeoutManager concurrency settings

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_unsubscribing_from_event.cs
- src/NServiceBus.AcceptanceTests/Routing/NativePublishSubscribe/When_unsubscribing_from_event.cs
relates to https://github.com/Particular/NServiceBus/issues/4254
Adds tests to verify unsubscribing from an event works as there were no tests for this behavior yet. There is a test for message driven subscriptions and one for native pubsub.
The native test hasn't been tested with a native pubsub transport yet.
/cc @SeanFeldman
> Adding acceptance tests for unsubscribe

- src/NServiceBus.Core.Tests/Encryption/RijndaelEncryptionServiceTest.cs
relates to https://github.com/Particular/NServiceBus/issues/4295
temporarily ignore the flaky test so it can be addressed later on.
> Ignore flaky test for now

- packaging/nuget/tools/init.ps1
Relates to: 
https://github.com/Particular/OptimizeTrialExtensions/issues/114
https://github.com/Particular/NServiceBus/pull/4262
https://github.com/Particular/Operations.Website.Backend/pull/237
Pros:
- Makes sure this metric report is only done inside a development environment.
- Can continue to use the pre-existing google analytics that tracks installs as opposed to first time execution
Cons:
- We are continuing to use and add more stuff to init.ps1 when we are actually trying to get rid of it.
- Creates more problems, see: https://github.com/Particular/NServiceBus/issues/4235 
- This approach is bad for the long term. The latest nuget has already deprecated install/uninstall scripts
- While the init script is technically still supported for now, the future remains unclear.
- When …
> Report first-time install metric to Particular when a user installs NServiceBus

- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
#4306 increased the timeout value but failed to make the corresponding change in the error message.
> Adjust error message to match timeout value

- src/NServiceBus.AcceptanceTests/Timeout/When_timeout_storage_is_unavailable_temporarily.cs
- src/NServiceBus.Core.Tests/Msmq/MsmqQueueCreatorTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core/Transports/Msmq/MsmqTransportInfrastructure.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqUtilities.cs
- src/NServiceBus.Core/Transports/Msmq/QueueCreator.cs
- src/NServiceBus.Core/Transports/Msmq/QueuePermissions.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_starting_up_the_endpoint.cs
@ramonsmits I inlined the code to check for existence/create queues so that we can use `using` properly.
What do you think?
Targets #4304
> Inlined the msmq create/open code to allows us to dispose properly

- src/NServiceBus.Core/Routing/UnicastSubscriberTable.cs
The recalculating algorithm made simpler, possibly running the same computations a few times. Having a multiple writers and handling them would be easier with a custom data structure.
/cc @SzymonPobiega for our concurrency discussion on #4316
> [SPIKE] UnicastSubscriberTable - updated

- src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
- src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
Based on top of #4257 
* Tracks already processed assemblies per scan and fast tracks if it can
* Removed the `IsRuntimeAssembly `check after[ !ReferencesNServiceBus](url) since `ReferencesNServiceBus` already checks whether the assembly is a runtime assembly and tracks / skips those. I was contemplating about letting the check there and just move it before `ReferencesNServiceBus`. But I think this would be the wrong tradeoff to make. The likelihood that you have a runtime assembly (we only know 4 types) deployed in the bin folder is quite small and then we would do the check and the additional name loading from the file multiple times.
The new algo is slightly slower because of the tracking in the collection. This is suprising because I expected the reflection part to be much more …
> Track already processed assemblies in Assembly Scanner

- src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_dispatch_fails_on_removal_SendsAtomicWithReceive.cs
- src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_dispatch_fails_on_removal_TXScopes.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/When_saga_message_goes_through_delayed_retries.cs
- src/NServiceBus.AcceptanceTests/Timeout/When_timeout_storage_is_unavailable_temporarily.cs
- src/NServiceBus.Core.Tests/Msmq/MsmqQueueCreatorTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Transports/Msmq/MsmqQueueCreator.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqTransportInfrastructure.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqUtilities.cs
- src/NServiceBus.Core/Transports/Msmq/QueueCreator.cs
- src/NServiceBus.Core/Transports/Msmq/QueuePermissions.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_starting_up_the_endpoint.cs
Fixes #4266 and #4323 
Changes:
* Only set permissions if we created the queue
* Only suppress .SetPermissions issues that is caused by to long queue names
* Added better test coverage
> Don't change MSMQ permissions on existing queues

- src/NServiceBus.Core/Pipeline/PipelineCache.cs
Solves #4354 
Added an exception when retrieval of a custom pipeline is attempted.
Ready for review @Particular/nservicebus-maintainers
> Add exception for registration of custom pipelines

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Routing/EndpointInstances.cs
- src/NServiceBus.Core/Routing/IDistributionPolicy.cs
These APIs need to be public in order for FileBasedRouting to apply sender-side distribution to the configured logical routes.
ping @SzymonPobiega @Scooletz 
please review @Particular/nservicebus-maintainers
> Make sender-side distribution APIs public

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Serialization/When_serializing_a_message.cs
- src/NServiceBus.Core.Tests/Serializers/Json/JsonMessageSerializerTest.cs
- src/NServiceBus.Core/Serializers/Json/JsonMessageSerializer.cs
addresses the behavior described in https://github.com/Particular/NServiceBus/issues/4355 for v6 by removing the `IsoDateTimeConverter`. Since 4.5 Json.net seems to use the ISO format by default so that shouldn't be necessary, but the used converter doesn't seem to be able to preserve timezone information.
Note that this change doesn't set the `DateParseHandling.DateTimeOffset` on the settings, as it seems this isn't necessary when the property type is defined as a DateTimeOffset (seems to be relevant when using dynamics I guess?)
Should we also add acceptance tests for that behavior so other serializers can verify that behavior too?
> Preserve DateTimeOffset timezone information when deserializing

- src/NServiceBus.AcceptanceTests/Timeout/CyclingOutageTimeoutPersister.cs
- src/NServiceBus.AcceptanceTests/Timeout/When_timeout_storage_is_unavailable_temporarily.cs
Closes #3531 
Will bring the test execution time down from > 45 seconds to somewhere around 7 seconds
> Timeout storage unavailable optimizations

- src/NServiceBus.Core/Features/Feature.cs
Features are scanned and loaded. This marks features as implicitly used similarly to `IHandleMessages`
> Features marked as implicitly used

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_subscribing_to_event_with_routes_to_base_and_specific_events.cs
This is a test with a very long name which causes downstreams to exceed file path limitations when trying to extract this test on the nuget packages folder, failing the package update.
> Rename test to shorten path

- src/NServiceBus.AcceptanceTests/Core/Stopping/When_pump_throws_on_stop.cs
Fixes #4387 
The assertion could randomly fail because the the pump for the legacy retries satellite will fail additionally to the main pump. This causes multiple log entries matching the LINQ filter in the result where it can switch randomly between the main and the legacy retries satellite to be the first.
Switched the log filter to be more specific on the log filter to avoid this race condition.
An alternative would be to disable the legacy retries satellite for this test but then any other satellite receiver could introduce the same race condition again.
> Fixing randomly failing log assertion

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_complex_types.cs
- src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_complex_types_full_copy_is_created.cs
- src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs
After this PR `InMemorySagaPersister` allocates less memory for sagas that have only fields of following types: primitive types, strings, Guids. This is provided by using [MemberwiseClone](https://msdn.microsoft.com/en-us/library/system.object.memberwiseclone(v=vs.110).aspx) instead of the JSON serializer.
This gem enables **not calling any serializer** for getting sagas that types consist of fields with following types:
- [primitive types](https://msdn.microsoft.com/en-us/library/system.type.isprimitive(v=vs.110).aspx?query=memberwiseclone): Boolean, Byte, SByte, Int16, UInt16, Int32, UInt32, Int64, UInt64, IntPtr, UIntPtr, Char, Double, and Single
- string
- Guid
For the following saga
```
public class SagaWithGuid : ContainSagaData
{
public Guid Guid;
}
```
initialized before tests …
> InMemorySagaPerister allocates less for saga with fields of simple types.

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/When_handling_message_with_handler_and_timeout_handler.cs
- src/NServiceBus.Core.Tests/Handlers/MessageHandlerRegistryTests.cs
- src/NServiceBus.Core/Pipeline/Incoming/MessageHandler.cs
- src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
- src/NServiceBus.Core/Unicast/MessageHandlerRegistry.cs
NServiceBus Version 6 users with sagas reusing one or more of the incoming messages as timeout messages.
When the saga is processed both the message handler and the timeout handler is invoked for the incoming message.  Any logic in the timeout handler would be invoked immediately and not when the timeout is due. 
Example of a problematic saga:
```
public class MySaga: Saga<MySagaData>, 
IAmStartedByMessages<StartSagaMessage>, 
IHandleTimeouts<StartSagaMessage>
{
public Task Handle(StartSagaMessage message, IMessageHandlerContext context)
{
//will be invoked again incorrectly after 10 seconds
return RequestTimeout(context, TimeSpan.Seconds(10), message); //note that the incoming message is reused
}
public Task Timeout(StartSagaMessage message, IMessageHandlerContext context)
{
//this will …
```
> Reuse of incoming message as saga timeout message causes duplicate handler invocations

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/When_handling_message_with_handler_and_timeout_handler.cs
- src/NServiceBus.Core.Tests/Handlers/MessageHandlerRegistryTests.cs
- src/NServiceBus.Core/Pipeline/Incoming/MessageHandler.cs
- src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
- src/NServiceBus.Core/Unicast/MessageHandlerRegistry.cs
@bording this is a cherry pick of the 6.1.1/6.0.5 fix that should be correct.
Would we prefer this over https://github.com/Particular/NServiceBus/pull/4404 ?
> Invoke proper handler for sags that reuse messages as timeouts

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Sagas/ActiveSagaInstance.cs
addresses https://github.com/Particular/NServiceBus/issues/4322
this would theoretically allow users to replace the `ActiveSagaInstance` on the context but I don't really see this as something we need to actively prevent as there isn't any realistic scenario to do this.
cc @SimonCropp
> Make ActiveSagaInstance ctor public

- MAINTAINERS.md
As discussed as an outcome of [this](https://github.com/Particular/PlatformDevelopment/issues/1067#issuecomment-267957647) retrospective, we concluded that we should document the process more clearly to avoid failing downstreams not blocking a release.
Open questions: Should we limit this rule for minor & majors to not delay patch releases unnecessarily?
> Add smoke test guidance to MAINTAINERS.md

- src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
- src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
- src/NServiceBus.TransportTests/When_failure_happens_after_isolated_send.cs
Added test to verify that messages are emitted after a failure when running in isolated dispatch.
As per #4392
> Add isolated dispatch on failure test

- src/NServiceBus.Core/Transports/Msmq/MsmqFailureInfoStorage.cs
- src/NServiceBus.Core/Transports/Msmq/ReceiveOnlyNativeTransactionStrategy.cs
- src/NServiceBus.Core/Transports/Msmq/SendsAtomicWithReceiveNativeTransactionStrategy.cs
- src/NServiceBus.Core/Transports/Msmq/TransactionScopeStrategy.cs
- src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
- src/NServiceBus.TransportTests/When_scope_complete_throws.cs
- src/NServiceBus.TransportTests/When_scope_dispose_throws.cs
- src/NServiceBus.TransportTests/When_scope_throws_after_successful_message_processing.cs
This addresses a problem that @andreasohlund found where it was possible to get into what appeared to be an infinite loop #4419. This was being caused by the failure info counter not incrementing as expected. The problem wasn't with the incrementing, but instead the inconsistent clearing of the cached failure info that held the increment value. It was possible for the cached failure information to be removed on "success" only to have transactionscope fail on `scope.Complete()`, creating an exception and attempting to increment the counter in the failure info. Because the cached value had been removed a new cached failure info object was created with the incrementer set to 1.
> Move failure info clearing for more consistency

- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs
Closes https://github.com/Particular/NServiceBus/issues/4415
The old generated code
```
public void Dispose()
{
if (Interlocked.Exchange(ref this.disposeSignaled, 1) != 0)
return;
if (this.tokenSource != null)
{
this.tokenSource.Dispose();
this.tokenSource = (CancellationTokenSource) null;
}
if (this.timeoutPollerTask != null)
{
this.timeoutPollerTask.Dispose();
this.timeoutPollerTask = (Task) null;
}
this.disposed = true;
}
```
to
```
public void Dispose()
{
if (Interlocked.Exchange(ref this.disposeSignaled, 1) != 0)
return;
if (this.tokenSource != null)
{
this.tokenSource.Dispose();
this.tokenSource = (CancellationTokenSource) null;
}
this.disposed = true;
}
```
https://blogs.msdn.microsoft.com/pfxteam/2012/03/25/do-i-need-to-dispose-of-tasks/
> Skip weaving the timeoutPollerTask

- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/packages.config
1.2.2 does no longer dispose tasks. Therefore we can remove the [SkipWeaving] again.
ping @danielmarbach
> Update Janitor to 1.2.2

- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.AcceptanceTests/Basic/When_sending_from_a_send_only.cs
When messages are moved to the error queue, the acceptance testing framework throws a `MessagesFailedException` containing a set of all failed messages. Since multiple messages can fail per test run, there is not a 1:1 relationship between the exception and the message, which results in no further details shown in the exceptions message. This causes some pain to investigate failed tests because the root cause exceptions are only accessible when explicitly handling the exception type or using the debugger.
This PR logs every failed (moved to error queue) message in the test output. E.g.:
> Message: c6e824c7-7e40-4338-940c-a701008bbecb failed to process and was moved to the error queue: System.Exception: test
note that there are other approaches on improving the exception thrown but this …
> Log failed messages in acceptance tests

- src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.AcceptanceTesting/Support/TaskExtensions.cs
This introduced a few changes to the acceptance testing library:
* The Timebox method uses [AggregateException.GetBaseException ](https://referencesource.microsoft.com/#mscorlib/system/AggregateException.cs,308) instead of InnerException
* When condition will yield the context to not starve resources
* Done condition yields as well
The when condition yield was introduced to remove a starvation issue we saw with ASQ and ASB. Since the when condition checks are very likely to execute synchronously as long as the condition is not reached we might be starving the thread that is entering wich then leads to timeouts of the tests.
Fixes the hanging build see https://builds.particular.net/viewLog.html?buildId=204512&buildTypeId=NServiceBus_Transports_NServiceBusAzureStorageQueues_1Build&tab=testsI …
> Acceptance testing

- src/NServiceBus.AcceptanceTesting/Support/TaskExtensions.cs
Connects to #4402 
This will prevent timeouts, when debugging, during `StartEndpoints`, `StopEndpoints` and `ExecuteWhens`.
> Prevent debugging timeouts on all endpoint activities

- src/NServiceBus.Core/Serializers/XML/XmlMessageSerializer.cs
Connects to https://github.com/Particular/PlatformDevelopment/issues/1082
`EncryptedValue` is added to the message types to initialize the XML Serializers cache. We can't do that any longer in the external encryption package. We could keep this code until we remove the core encryption code but at that point I don't see what that code is for. It also looks like the type could be initialized on demand but I wasn't able to reproduce a situation where this type needs to be initialized in the first place.
Maybe @andreasohlund or @SimonCropp have a bit more background about this?
ping @Particular/nservicebus-maintainers @kbaley
> Remove EncryptedValue usage from XmlMessageSerializer

- src/NServiceBus.Core/Persistence/PersistenceStartup.cs
Fixes https://github.com/Particular/NServiceBus/issues/4422
I ran the following test cases after the change, and the following exceptions where thrown at startup:
The selected persistence doesn't have support for timeout storage. Select another persistence or disable the timeout manager feature using endpointConfiguration.DisableFeature<TimeoutManager>()
The selected persistence doesn't have support for subscription storage. Select another persistence or disable the message-driven subscriptions feature using endpointConfiguration.DisableFeature<MessageDrivenSubscriptions>()
The selected persistence doesn't have support for saga storage. Select another persistence or disable the sagas feature using endpointConfiguration.DisableFeature<Sagas>()
The selected persistence doesn't have support …
> No longer require persistence to be configured

- src/NServiceBus.Core/Transports/ErrorContext.cs
Raised from [Feedback in Docs](https://github.com/Particular/docs.particular.net/issues/2412).
> Spelling error in tooltip text

- src/NServiceBus.Msmq.AcceptanceTests/Distributor/DistributorEndpointTemplate.cs
just noticed that we get a compiler warning because we're using an API with an obsoletion warning in the MSMQ acceptance tests. The transaction scope parameter should be removed from the satellite registration.
> Avoid obsolete satellite API

- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageBehaviorTests.cs
- src/NServiceBus.Core.Tests/UnitOfWork/UnitOfWorkBehaviorTests.cs
- src/NServiceBus.Core/Pipeline/Incoming/ReceiveFeature.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageBehavior.cs
- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPipelineFeature.cs
- src/NServiceBus.Core/UnitOfWork/UnitOfWorkBehavior.cs
- src/NServiceBus.Testing.Fakes/FakeBuilder.cs
Closes https://github.com/Particular/NServiceBus/issues/4463
Instead of caching whether there are mutators during the setup phase the behaviors are made stateful and toogle the state after first message execution. So when there are no mutators registered the internal state flag toggles and future calls will no longer try to resolve mutators. This change makes the following assumptions:
- Container registrations cannot change after the first resolve (that is true for most containers) and also baked into our container abstraction
- Concurrent message handling might end up "unnecessarily" trying to resolve mutators but eventually the flag will toggle. Which is good enough
> Mutator behaviors cache the outcome of the builder call and will no longer call it if no mutators were returned

- src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_config.cs
- src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_custom.cs
- src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_multikey.cs
- src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_unobtrusive_mode.cs
- src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_without_incoming_key_identifier.cs
- src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_encryption_with_custom_service.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Conventions.cs
- src/NServiceBus.Core/ConventionsBuilder.cs
- src/NServiceBus.Core/Encryption/ConfigureRijndaelEncryptionService.cs
- src/NServiceBus.Core/Encryption/EncryptedValue.cs
- src/NServiceBus.Core/Encryption/IEncryptionService.cs
- src/NServiceBus.Core/Encryption/KeyFormat.cs
- src/NServiceBus.Core/Encryption/RijndaelEncryptionServiceConfig.cs
- src/NServiceBus.Core/Encryption/RijndaelExpiredKey.cs
- src/NServiceBus.Core/Encryption/RijndaelExpiredKeyCollection.cs
- src/NServiceBus.Core/Encryption/WireEncryptedString.cs
Connects to https://github.com/Particular/PlatformDevelopment/issues/1082
Add an obsolete warning to the public encryption APIs to point at the newly available package.
> Add obsolete warning to property encryption APIs

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_doing_content_based_routing_with_commands.cs
- src/NServiceBus.AcceptanceTests/Routing/When_using_custom_routing_strategy.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/Routing/Routers/UnicastPublishRouterConnectorTests.cs
- src/NServiceBus.Core.Tests/Routing/Routers/UnicastSendRouterConnectorTests.cs
- src/NServiceBus.Core.Tests/Routing/RoutingPolicyTests.cs
- src/NServiceBus.Core.Tests/Routing/SingleInstanceRoundRobinDistributionStrategyTests.cs
- src/NServiceBus.Core.Tests/Routing/UnicastPublisherRouterTests.cs
- src/NServiceBus.Core.Tests/Routing/UnicastSendRouterTests.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Routing/DistributionContext.cs
- src/NServiceBus.Core/Routing/DistributionStrategy.cs
- src/NServiceBus.Core/Routing/IUnicastPublishRouter.cs
- src/NServiceBus.Core/Routing/IUnicastSendRouter.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs
- src/NServiceBus.Core/Routing/Routers/UnicastPublishRouterConnector.cs
- src/NServiceBus.Core/Routing/Routers/UnicastSendRouterConnector.cs
- src/NServiceBus.Core/Routing/UnicastPublishRouter.cs
- src/NServiceBus.Core/Routing/UnicastSendRouter.cs
Related to https://github.com/Particular/PlatformDevelopment/issues/1135
Doco PR https://github.com/Particular/docs.particular.net/pull/2445
Endpoints hosted in Service Fabric stateful services are partition affine. This is required because an endpoint can only access data inside reliable collections that are local to the partition of the stateful service. So if you have a service A with 26 partitions that hosts an endpoint the endpoint effectively is hosted/scaled out 26 times. 
To commands and events with message driven pub-sub to the right instance sticky to a given partition we need to be able to make sender side routing decisions based on the content. This PR extends the distribution strategy in a non-breaking way to be able to support content based sender side distribution that is …
> Context-aware distribution strategy

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Routing/When_routing_reply_to_any_instance.cs
- src/NServiceBus.AcceptanceTests/Routing/When_routing_reply_to_specific_address.cs
- src/NServiceBus.AcceptanceTests/Routing/When_routing_reply_to_specific_instance.cs
Because of https://github.com/Particular/NServiceBus/issues/4476 I checked for existing acceptance tests to verify the sendoptions work in v6 but I didn't found any, so I added them.
ping @Particular/nservicebus-maintainers @SzymonPobiega
> Add acceptance tests for RouteReply... options

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
- src/NServiceBus.Core/EndpointConfiguration.cs
- src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
- src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerConfiguration.cs
- src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerConfigurationExtensions.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
relates to https://github.com/Particular/NServiceBus/issues/4472
This PR contains a set of changes related to the AssemblyScanner:
* The AssemblyScanner can be configured to also scan AppDomain assemblies instead of just assemblies in the basepath folder. This is an opt-in behavior which is disabled by default.
* This might resolve issues when applications run with a different base path which does not contain the required assemblies although the assemblies are already loaded into the AppDomain.
* When NServiceBus.Core is loaded into the AppDomain (which is very likely), it is very important to also scan the already loaded assembly. Scanning an NServiceBus assembly from a different location, will not fail but it will internally fail type comparison checks and fail to setup features which …
> Allow AppDomain assemblies to be scanned

- src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerConfiguration.cs
we should throw exceptions by default. Seems like I've missed this in the original PR (https://github.com/Particular/NServiceBus/pull/4485).
> Fix default behavior to throw exceptions

- src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_unsubscribing_from_event.cs
Currently there is a race condition in Subscriber1 handler when incrementing receive counter https://github.com/Particular/NServiceBus/blob/acd527adec92900413ae47de12bf2c61616beb0d/src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_unsubscribing_from_event.cs#L100. 
This leads to the test timing out due to unmet done condition.
> Limiting concurrency on Subscriber1

- src/NServiceBus.AcceptanceTests/Basic/When_handling_current_message_later.cs
- src/NServiceBus.AcceptanceTests/Core/Feature/When_depending_on_typed_feature.cs
- src/NServiceBus.AcceptanceTests/Core/Feature/When_depending_on_untyped_feature.cs
- src/NServiceBus.AcceptanceTests/Core/Pipeline/When_aborting_the_behavior_chain.cs
- src/NServiceBus.AcceptanceTests/Core/Pipeline/When_extending_behavior_context.cs
- src/NServiceBus.AcceptanceTests/Core/Pipeline/When_extending_sendoptions.cs
- src/NServiceBus.AcceptanceTests/Core/Pipeline/When_extending_the_publish_api.cs
- src/NServiceBus.AcceptanceTests/Core/Pipeline/When_handling_message_with_several_messagehandlers.cs
- src/NServiceBus.AcceptanceTests/Core/Pipeline/When_replacing_behavior.cs
- src/NServiceBus.AcceptanceTests/Core/Pipeline/When_using_per_uow_component_in_the_pipeline.cs
- src/NServiceBus.AcceptanceTests/DelayedDelivery/When_Deferring_a_message.cs
- src/NServiceBus.AcceptanceTests/DelayedDelivery/When_deferring_to_non_local.cs
- src/NServiceBus.AcceptanceTests/MessageId/When_message_has_empty_id_header.cs
- src/NServiceBus.AcceptanceTests/MessageId/When_message_has_no_id_header.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/NonTx/When_sending_inside_ambient_tx.cs
- src/NServiceBus.AcceptanceTests/Recoverability/When_message_is_moved_to_error_queue.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_a_message_is_audited.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_blowing_up_just_after_dispatch.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_dispatching_forwarded_messages.cs
- src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga.cs
- src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga_autosubscribe_disabled.cs
- src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_autoSubscribe.cs
- src/NServiceBus.AcceptanceTests/Routing/SubscriptionBehavior.cs
- src/NServiceBus.AcceptanceTests/Routing/When_multiple_mappings_exists.cs
- src/NServiceBus.AcceptanceTests/Routing/When_publishing_an_interface.cs
- src/NServiceBus.AcceptanceTests/Routing/When_publishing_an_interface_with_unobtrusive.cs
- src/NServiceBus.AcceptanceTests/Sagas/When_adding_state_to_context.cs
- src/NServiceBus.AcceptanceTests/Serialization/When_no_content_type.cs
This is the first bit of work that @timbussmann and I have finished for #4457. Most of the changes are moving tests to better folders. Some of those moves included putting tests into the /Core folder so as not to be pushed to downstreams any longer.
There is also a small amount of test code cleanup for some tests that were either not Asserting what the test name claimed or running deferral checks using unrealistic times.
> Move acceptance tests

- src/NServiceBus.Core/DetectObsoleteConfigurationSettings.cs
Connects to Particular/PlatformDevelopment#1153
Connects to #4492
Logs a warning about the use of the `TimeToBeReceivedOnForwardedMessages` config section. This section will be removed in the next major.
Paging @timbussmann and @Particular/nservicebus-maintainers
> Warn on use of TimeToBeReceivedOnForwardedMessages

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Performance/ReceiveStatisticsFeature.cs
- src/NServiceBus.Core/Performance/ReceiveStatisticsPerformanceCounterFeature.cs
- src/NServiceBus.Core/Performance/ReceiveStatisticsPerformanceCounters.cs
To allow the external package to disable it
Note: The feature needs to be obsoleted in the same way as the other perf counter features (separate pull to come)
> Isolate receive statistic perf counters in separate feature

- src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_using_external_timeout_manager_code_first.cs
- src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_using_external_timeout_manager_xml_config.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/DelayedDelivery/DelayedDeliveryFeature.cs
- src/NServiceBus.Core/DelayedDelivery/ExternalTimeoutManagerConfigurationExtensions.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
relates to https://github.com/Particular/PlatformDevelopment/issues/1153
provides a code first API to configure an external timeout manager using:
`config.UseExternalTimeoutManager(timeoutManagerAddress);`
@WilliamBZA @Particular/nservicebus-maintainers thoughts?
> Provide code first api to configure external TM

- src/NServiceBus.Core/DetectObsoleteConfigurationSettings.cs
TimeSpan will be `TimeSpan.Zero` as it's non-nullable in case a unicastBufConfig instance exists.
This will cause a warning about the usage of this attribute although it isn't configured.
> Fix TimeSpan check

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/When_sagas_share_timeout_messages.cs
- src/NServiceBus.Core/Sagas/SagaMetadataCollection.cs
- src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
We currently try to invoke all available saga types if there is a saga id header present. This change does a best effort to only invoke the saga that was actually targeted (indicated by the `NServiceBus.SagaType` header). The SagaType header is used for timeouts and [autocorrelation for sagas](https://docs.particular.net/nservicebus/sagas/#sagas-and-requestresponse)
If the type can't be found we'll fallback to the existing behavior of calling the persister for all saga types available.
This improves performance but also allow saga persisters to have saga ids that are only unique within the scope of a given saga type. (see the acpt test added)
The InMemory persister didn't not handle this properly but this change makes this work.
We contemplated to throw if the saga type in the header …
> Only invoke saga type indicated by NServiceBus.SagaType header if present

- src/NServiceBus.AcceptanceTesting/EndpointConfigurationBuilder.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioConfigSource.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Audit/AuditConfig.cs
- src/NServiceBus.Core/DetectObsoleteConfigurationSettings.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqTimeToBeReceivedOverrideCheck.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_Audit_OverrideTimeToBeReceived_set_and_native_receive_tx.cs
Connects to Particular/PlatformDevelopment#1153
Adds an obsolete on the use of the config properties on `AuditConfig` as well logs a warning on the use of the `AuditConfig` config section. This section will be removed in the next major.
Paging @timbussmann and @Particular/nservicebus-maintainers
> Obsolete audit config properties

- src/NServiceBus.AcceptanceTesting/Customization/EndpointConfigurationExtensions.cs
- src/NServiceBus.AcceptanceTesting/EndpointConfigurationBuilder.cs
- src/NServiceBus.AcceptanceTesting/Support/EndpointCustomizationConfiguration.cs
- src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioConfigSource.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.AcceptanceTests/Audit/When_a_message_is_audited.cs
- src/NServiceBus.AcceptanceTests/Audit/When_a_replymessage_is_audited.cs
- src/NServiceBus.AcceptanceTests/Audit/When_auditing.cs
- src/NServiceBus.AcceptanceTests/Audit/When_auditing_message_with_TimeToBeReceived.cs
- src/NServiceBus.AcceptanceTests/Causation/When_a_message_is_audited.cs
- src/NServiceBus.AcceptanceTests/Hosting/When_a_message_is_audited.cs
- src/NServiceBus.AcceptanceTests/Licensing/When_a_message_is_audited.cs
- src/NServiceBus.AcceptanceTests/Performance/When_message_is_audited.cs
- src/NServiceBus.AcceptanceTests/Performance/When_message_is_faulted.cs
- src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_a_message_is_audited.cs
It becomes much cleaner if we just use the `EndpointConfiguration` API instead. added a little extension method which does the type -> address translation.
> Remove audit configuration API in acceptance testing framework

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/When_overriding_saga_id_creation.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Extensibility/ContextBag.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/Sagas/DefaultSagaIdGenerator.cs
- src/NServiceBus.Core/Sagas/ISagaIdGenerator.cs
- src/NServiceBus.Core/Sagas/PropertySagaFinder.cs
- src/NServiceBus.Core/Sagas/SagaIdGeneratorContext.cs
- src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
- src/NServiceBus.Core/Sagas/Sagas.cs
Closes #2445 
This enables:
- Simple sagas
- [A filebased development saga persister](https://github.com/Particular/NServiceBus/pull/4496)
Currently the core doesn't make assumptions that all messages need to have a message property which can be always mapped to an existing saga instance. When a new saga instance is created by default a new comb GUID is generated and then messages going out from that saga will contain the saga id header to be able to be correlated back. To ensure partition affinity with Service Fabric we need a deterministic way of creating from a message which started a saga a saga ID based on business identifiers. With that approach it is possible to route messages that need to be sent to an existing saga instance to the endpoint that is living on the partition that …
> Make saga id generation pluggable

- src/NServiceBus.AcceptanceTests/Satellites/When_a_message_is_available.cs
- src/NServiceBus.AcceptanceTests/Satellites/When_satellite_txmode_does_not_match_endpoints_txmode.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs
- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs
- src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
- src/NServiceBus.Core/Pipeline/SatellitePipelineExecutor.cs
- src/NServiceBus.Core/Recoverability/Recoverability.cs
- src/NServiceBus.Core/Transports/MessageContext.cs
Aligning context with what has been proposed by @andreasohlund in #4468 
According to https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/breaking-change-rules.md this is a non-breaking change
> Adding an interface implementation to a type
> This is acceptable because it will not adversely affect existing clients. Any changes which could be made to the type being changed in this situation, will have to work within the boundaries of acceptable changes defined here, in order for the new implementation to remain acceptable. Extreme caution is urged when adding interfaces that directly affect the ability of the designer or serializer to generate code or data, that cannot be consumed down-level. An example is the ISerializable interface.
> MessageContext inherits from IExtendable

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Logging/Logging.cs
- src/NServiceBus.Core/Recoverability/Faults/MessageForwardingInCaseOfFaultConfig.cs
Adding `TreatAsErrorFromVersion ` to avoid compilation errors.
Switched the removal version to 8, as it seems to be rather useless to have them both at the same value and we can keep them around just without the ConfigSection base class.
> Add TreatAsErrorFromVersion attribute

- src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
- src/NServiceBus.AcceptanceTesting/Support/IEndpointSetupTemplate.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioConfigSource.cs
- src/NServiceBus.AcceptanceTests/Core/Config/When_multiple_configuration_providers.cs
- src/NServiceBus.AcceptanceTests/Core/Config/When_only_abstract_config_override_is_found.cs
- src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_config.cs
- src/NServiceBus.AcceptanceTests/EndpointTemplates/DefaultPublisher.cs
- src/NServiceBus.AcceptanceTests/EndpointTemplates/DefaultServer.cs
- src/NServiceBus.AcceptanceTests/EndpointTemplates/ServerWithNoDefaultPersistenceDefinitions.cs
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/ConfigurationSource/IConfigurationSource.cs
- src/NServiceBus.Msmq.AcceptanceTests/Distributor/DistributorEndpointTemplate.cs
- src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj
- src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_subscription_exists_for_non_tx_endpoint.cs
- src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_subscription_exists_for_tx_endpoint.cs
- src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_using_subscription_store_on_non_tx_endpoint.cs
- src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_using_subscription_store_on_tx_endpoint.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_TimeToBeReceivedOnForwardedMessages_set_and_tx_scope_receives.cs
- src/NServiceBus.Msmq.AcceptanceTests/When_subscribing_with_address_containing_host_name.cs
relates to https://github.com/Particular/PlatformDevelopment/issues/1153
I added TreatWarnignsAsErrors in some testing related projects as it helps to locate usages of obsoleted APIs.
> Obsolete IProvideConfiguration

- src/NServiceBus.AcceptanceTesting/EndpointConfigurationBuilder.cs
- src/NServiceBus.AcceptanceTesting/Support/EndpointCustomizationConfiguration.cs
- src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
- src/NServiceBus.AcceptanceTests/Core/Feature/When_registering_a_startup_task.cs
- src/NServiceBus.AcceptanceTests/Core/Pipeline/When_sending_from_a_send_only.cs
- src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_publishing_from_sendonly.cs
a few more lines which are easy to remove from the ATT framework as it is redundant since the endpoint can be made readonly via the `EndpointConfiguration` directly.
> Remove SendOnly from EndpointConfigurationBuilder

- src/NServiceBus.Core/Logging/DefaultLog.cs
Incorrect log level written, written as ERROR instead of FATAL.
> Incorrect log level for FATAL

- src/NServiceBus.TransportTests/When_on_error_throws.cs
The two assertions that were added to this test later on aren't valid for all transports. For example, we've been commenting them out for RabbitMQ.
I wanted to go ahead and get this change in before the 6.2 release.
CC: @Particular/rabbitmq-transport-maintainers @Particular/azure-maintainers
> Remove incorrect assertions from transport test

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs
- src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs
- src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs
- src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs
- src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs
- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPublishContext.cs
- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingReplyContext.cs
- src/NServiceBus.Core/Routing/SubscribeContext.cs
- src/NServiceBus.Core/Routing/UnsubscribeContext.cs
Connected to #4573
Fixes a bug [reported in Google Groups](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/particularsoftware/cCudnYmX55g/qr8FFzHfCAAJ) where sendoptions was being incorrectly merged into the parent context instead of the current one.
Could not write tests to verify this since the `ContextBag.TryGet` method first attempts to get the value from the current context and, if not found there, it will try to get the value from the parent context. As such any test written would pass, incorrectly, for the bug'd code.
> Merge Publish|Reply|SubscribeOptions into current ContextBag not parent one

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Transports/MessageContext.cs
reverts breaking change introduced here
https://github.com/Particular/NServiceBus/commit/dc1ad7358735bd1b80520929bcbb65e8094ce67d
> rename MessageContext param back to "context" and fix obsolete

- guidelines/design-guidelines.md
This is a copy paste from https://github.com/Particular/PlatformDevelopment/tree/master/designprinciples/nservicebus but some level of bike shedding and "Adam'isation" of the take place I guess.
I choose to put it all in the same doc , we can always split later if needed
> Migrate design guidelines from platdev

- src/NServiceBus.Core/Properties/AssemblyInfo.cs
While this doesn't actually impact the 3.2.0 release, I noticed yesterday that the second parameter of the `ReleaseDate` attribute wasn't updated correctly.
Before merging yesterday, I verified that only the first parameter actually matters from the standpoint of the licensing code.
Looking back at how GitVersion used to automatically update the values, the first parameter is the date of the commit tagged with X.Y.0, and the second value is the date of the current commit being built.
So the first parameter should be updated for each new minor release, and the second parameter should be updated for each build, assuming we want to mimic the old behavior perfectly.
> Fix release date attribute

- src/NServiceBus.Core.Tests/Sagas/SagaMetadataCreationTests.cs
- src/NServiceBus.Core/Sagas/SagaMetadata.cs
use fullname when "member type on the message and the saga property must match
> use fullname on saga message mapping exception

- src/NServiceBus.AcceptanceTests/Tx/When_receiving_with_native_multi_queue_transaction.cs
As pointed out by daniel in https://github.com/Particular/NServiceBus.AzureServiceBus/pull/519#discussion_r109610824 the transaction config is not matching the tests description.
cc @danielmarbach
> Fix transaction configuration for acceptance test

- src/NServiceBus.AcceptanceTests/Core/CoreTestSuiteConstraints.cs
- src/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
- src/NServiceBus.AcceptanceTests/EndpointTemplates/TestSuiteConstraints.cs
After looking at the code with @bording we concluded that the properties for the transport and persistence configuration are quite risky as some implementation expect a dedicated instance of the configuration class for each endpoint spinned up (mostly for the cleanup logic).
currently, this does not cause issues (besides unnecessary created instances) in the MSMQ implementation (which relies on the per-endpoint behavior) as we're implementing a custom getter which always returns a new instance, but when using `public IConfigureEndpointTestExecution TransportConfiguration {get;} = new ConfigureEndpointMsmqTransport();`, the framework would no longer work correctly.
> Switch from property to factory method in TestSuiteConstraints 

- src/NServiceBus.Core/Pipeline/Outgoing/OutgoingSendContext.cs
Fixes typo introduced in #4614 
We'll manually deal with any versioning problems this introduces.
> Fix typo in OutgoingSendContext

- src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_unsubscribing_from_event.cs
It was failing in NH persistence + SQL transport combo dues to the fact that SQL spawns processing threads immediately.
> Fixed concurrency issue in one of the ATs

- src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
- src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj.DotSettings
When "inlining" assemblies with Costura, those assemblies are loaded into the AppDomain but even when the assembly scanner is configured to include AppDomain assemblies, those assemblies are not loaded.
This is caused by the current implementation which always tries to load assemblies from disk even when already loaded. As the assemblies inlined via costura show the path of the "host" assembly, it's not possible to load the correct assembly via file path, therefore those assemblies aren't scanned. But in case the assembly is already loaded into the appdomain, we do not need to load the assembly again.
This is WIP and misses some functionaility, as AppDomain assemblies are currently always scanned, regardless whether they are referencing NSB or not.
@Particular/nservicebus-maintainers I …
> Support assemblies inlined via Costura

- src/NServiceBus.AcceptanceTesting/Support/MessageFailedException.cs
helps to debug failed message as this will also print the inner exception which was the original cause of a failed message.
> Use original exception as inner exception

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Serialization/When_receiving_interface_message_where_child_is_excluded.cs
- src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/MessageMapper.cs
- src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs
- src/NServiceBus.Core/Serialization/SerializationFeature.cs
This means that we can still deserialize and process messages not found during scanning but we have handlers for
Replaces #4584
Replaces #4606
Fixes #4452
Fixes #4567
Fixes #4129
> Make the message mapper discover types at runtime

- src/NServiceBus.Core.Tests/Msmq/MsmqExtensionsTests.cs
- src/NServiceBus.Core.Tests/Msmq/MsmqQueueCreatorTests.cs
- src/NServiceBus.Core.Tests/Msmq/MsmqSubscriptionStorageIntegrationTests.cs
- src/NServiceBus.Core.Tests/Msmq/QueuePermissionsTests.cs
- src/NServiceBus.Core/Transports/Msmq/MsmqQueueCreator.cs
- src/NServiceBus.Core/Transports/Msmq/QueuePermissions.cs
There were some unit tests that wasn't deleting the test queues that it created, leaving a bunch of queues behind after the tests have been run polluting the environment. 
@Particular/msmq-transport-maintainers - please review
cc / @Particular/nservicebus-maintainers
> Cleanup: MSMQ unit tests should delete the queues that it creates.

- src/NServiceBus.Core.Tests/StructConventionsTests.ApproveStructsWhichDontFollowStructGuidelines.approved.txt
- src/NServiceBus.Core.Tests/StructConventionsTests.cs
Build fails from time to time with reordered LogicalAddress
https://builds.particular.net/viewLog.html?buildId=214731&buildTypeId=NServiceBusCore_Build
This now sorts the fields, properties and types ascending
> Stabilize struct conventions

- src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
- src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
fixes https://github.com/Particular/NServiceBus/issues/4633 and adds two related unit tests.
Had to adjust the assembly generation code slightly to allow generating exe files.
cc @danielmarbach
> Skip exe files from scanning when excluded

- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Transports/Learning/AsyncFileTests.cs
- src/NServiceBus.Core/Transports/Learning/AsyncFile.cs
- src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
The previous approach had a good chance to corrupt the input content once the content is larger than the buffer size. I used a `StreamReader` as it is able to deal with encoding internally and read the correct utf-8 blocks.
It might be an option use `StreamWriter` in WriteText too.
ping @SimonCropp @andreasohlund @danielmarbach 
(this PR is targeting https://github.com/Particular/NServiceBus/pull/4550)
> Fix reading large text files

- src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
- src/NServiceBus.AcceptanceTesting/Support/MessageFailedException.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs
- src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenUnsubscribeTerminator.cs
Two changes which could improve exceptions occuring during acceptance testing:
* MessageFailedException show the stacktrace of the original exception.
* When exceptions are rethrown by the framework, it uses ExceptionDispatchInfo to restore the stack trace. This should help to idenfity the cause of an exception in case the acceptance testing framework itself threw it (e.g. couldn't start an endpoint).
Thoughts? Imho I'm not sure about the value of change number two, as essentially all exceptions are thrown by the acceptance testing framework anyway (that's why MessageFailedException overrides the stack trace, as you would still see the stacktrace from the acceptance testing framework) but it points at a more specific point potentially helping to detect the original cause.
> Improve acceptance testing exceptions

- packaging/nuget/nservicebus.acceptancetests.nuspec
- packaging/nuget/nservicebus.containertests.nuspec
- packaging/nuget/nservicebus.testing.fakes.nuspec
- packaging/nuget/nservicebus.transporttests.nuspec
This adjusts all of the source packages to also include the source files in the `contentFiles` folder, which will be used when consuming the package in SDK-style csproj via PackageReference.
In an attempt to shorten the path to the file, I've removed the `App_Package` subfolder and the version.
This results in the following view from inside VS:
The test files end up on disk inside the NuGet package cache folder. The paths end up looking something like:
````
C:\Users\Brandon\.nuget\packages\nservicebus.acceptancetests.sources\6.3.0-alpha0085\contentFiles\cs\any\NSB.AcceptanceTests\Audit\When_a_message_is_audited.cs
````
If we wanted to shorten things further, we could get rid of the remaining grouping folder ("NSB.AcceptanceTests" in the example above), but I'm not sure that would be a …
> Add contentFiles section to source packages

- src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs
- src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
Adds basic transaction recoverability to the learning transport. This mostly makes sure that users debugging won't  loose messages if they stop endpoints in the middle of debugging
> Add basic tx recovery for the learning transport

- src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
noticed this during testing. ExceptionDispatchInfo doesn't provide a useful ToString().
> Fix exception reporting

- src/NServiceBus.Core/Transports/Learning/DelayedMessagePoller.cs
- src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
- src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
To allow for graceful shutdowns.
We've seen 
```
"Failed to trigger delayed messages System.IO.DirectoryNotFoundException: Could not find a part of the path 'c:\\temp\\att_tests\\BlowingUpJustAfterDispatch.NonDtcReceivingEndpoint\\Retries\\.delayed'.\r\n   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileSystemEnumerableIterator`1.CommonInit()\r\n   at System.IO.DirectoryInfo.EnumerateDirectories()\r\n   at NServiceBus.DelayedMessagePoller.MoveDelayedMessagesToMainDirectory(Object state) in C:\\Projects\\NServiceBus\\src\\NServiceBus.Core\\Transports\\Learning\\DelayedMessagePoller.cs:line 24"
```
In the logs, this should fix that
> Wait for the expired message poller to stop

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Pipeline/When_a_message_is_faulted.cs
- src/NServiceBus.AcceptanceTests/packages.config
- src/NServiceBus.Core/CriticalError/CriticalError.cs
- src/NServiceBus.Core/NServiceBus.Core.csproj
- src/NServiceBus.Core/packages.config
After seeing https://github.com/Particular/NServiceBus/pull/4673 I added the Particular.CodeRules package to the acceptance tests too and disabled the `missing ConfigureAwait` warning to find missing awaits which is now supported with the 0.2 version of the package.
It found an additional test with a missing await which I fixed right away. cc @andreasohlund
> Update Particular.CodeRules package

- src/NServiceBus.Core/InitializableEndpoint.cs
- src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs
- src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs
- src/NServiceBus.sln.DotSettings
It seems it would be easier if we are more consistent with our usage of delegates vs. method groups and try to avoid method groups as they bring lower performance due to missing caching (which might be supported one day: https://github.com/dotnet/roslyn/issues/5835)
I also disabled the resharper rule to hint at potential method group usage.
Thoughts @Particular/nservicebus-maintainers @SimonCropp ?
> Do not use method groups

- src/NServiceBus.AcceptanceTests/Core/Pipeline/When_setting_conversation_id.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core.Tests/Causation/AttachCausationHeadersBehaviorTests.cs
- src/NServiceBus.Core/Causation/AttachCausationHeadersBehavior.cs
relates to https://groups.google.com/forum/#!topic/particularsoftware/k3cz3qKWJUc
user defined Conversation id headers will always be overwritten by the pipeline to be either:
* the conversation id of the incoming message
* a new conversation id otherwise
while the first behavior seems to be correct, users should be able to specify their custom conversation ids for new outgoing messages which are not triggered from incoming messages. The scenario behind this according to @andreasohlund is the ability to link a new message (e.g. a status update message, follow up message, etc.) to an existing conversation so that it will be shown properly by SI.
This PR changes the described behavior to the following:
* always use the conversation id of the incoming message if available
* use a user …
> Allow user defined conversation ids

- src/NServiceBus.AcceptanceTests/Core/LearningTransport/When_disabling_payload_restrictions.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core.Tests/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehaviorTests.cs
- src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
- src/NServiceBus.Core.Tests/Transports/Learning/LearningTransportDispatcherTests.cs
- src/NServiceBus.Core/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehavior.cs
- src/NServiceBus.Core/Transports/Learning/LearningTransportConfigurationExtensions.cs
- src/NServiceBus.Core/Transports/Learning/LearningTransportDispatcher.cs
- src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs
Just a quick sanity check before I add a configuration option to override.
Do you like the `.UseTransport<LearningTransport>().NoPayloadSizeRestriction()` proposal?
Fixes #4664
> Enforce message size limit

- src/NServiceBus.sln
Since we now have C# 7 features, we need VS 2017 to build, so this updates the solution file to avoid opening with VS 2015.
> Update VS Solution version

- src/NServiceBus.Core/Persistence/Learning/SagaPersister/SagaManifest.cs
- src/NServiceBus.Core/Persistence/Learning/SagaPersister/SagaManifestCollection.cs
- src/NServiceBus.Core/Persistence/Learning/SagaPersister/SagaStorageFile.cs
For most of the things we use NewtonSoftJsonSerializer which is ILMerged into the core. Many other packages have newtonsoft also ILMerged. I see no reason not to use newtonsoft json for the learning saga persister as well since the data contract serializer has to many restrictions. Thoughts?
> Removing DataContractSerializer from Learning Saga Persister

- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/When_correlating_on_special_characters.cs
Adds an acceptance tests which uses special characters in the correlation property value. This should help ensure that there is no potential message loss or other conflicts due to improper persistence of those characters.
> Add special character saga correlation property acceptance test

- src/NServiceBus.AcceptanceTests/Routing/NativePublishSubscribe/When_publishing_to_scaled_out_subscribers.cs
- src/NServiceBus.AcceptanceTests/Routing/NativePublishSubscribe/When_unsubscribing_from_event.cs
- src/NServiceBus.AcceptanceTests/Serialization/When_registering_deserializers_with_settings.cs
- src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs
- src/NServiceBus.Core/Transports/Learning/ILearningTransportTransaction.cs
- src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs
- src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
- src/NServiceBus.Core/Transports/Learning/NoTransaction.cs
- src/NServiceBus.Core/Utils/AsyncTimer.cs
This makes sure that we always log errors during transaction Rollback, Commit and Complete
> Make sure exceptions when reading file triggers CircuitBreaker

- src/NServiceBus.Core/Transports/Learning/AsyncFile.cs
async not required in dev persistence since json.net does not support it
> remove Redundant Todo

- src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
- src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
- src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
* Sets the default log level to `Debug`. The log entries are not used for anything by default. It does mean higher memory consumption though.
* When a test fails, it automatically dumps the full log
* Removed the "trace" category from the context. Tests can still add trace (not sure about it's value though), those entries will now just be added to the logs instead.
> Print log entries when acceptance test fails

- src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ConfigurationTimeoutExtensions.cs
fixes https://github.com/Particular/NServiceBus/issues/4708
decided to not mention the default value as it seems very likely to be incorrect again in case of a change.
> Remove incorrect default value in method summary

- src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs
- src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
- src/NServiceBus.Core/Transports/Learning/NoTransaction.cs
Fixes https://github.com/Particular/NServiceBus/issues/4720
This PR:
* Makes sure that we deal with all IOExceptions not only file not found
* That we always release the semaphore during failures in BeginTransaction
* That we shutdown the endpoint properly should something go horribly wrong (like not being able to create the transaction directory)
> Handle file locked issues

- src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
- src/NServiceBus.Core/Extensibility/ContextBag.cs
- src/NServiceBus.Core/Extensibility/ReadonlyContextBag.cs
Had a customer call today and couldn't explain why they had to use TryGet if the key was a string and not a type.
This PR exposes the string key verion of ContextBag.Get
WIP until develop is targeting v7 since this is a breaking change
> Expose the context get that takes a string key

- releasing.md
@Particular/nservicebus-maintainers repo for wire compat tests renamed like discussed in slack
> Rename of wire compat test repo

- src/NServiceBus.AcceptanceTests/Core/Sagas/When_using_ReplyToOriginator.cs
- src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
- src/NServiceBus.AcceptanceTests/Sagas/When_using_ReplyToOriginator.cs
@bording here's the test I promised. I've verified that it fails if the [correlation id override](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Sagas/Saga.cs#L110) is commented out
> Test that correlation id flows when replying to originator

- src/NServiceBus.AcceptanceTests/Sagas/When_correlating_on_special_characters.cs
to prevent getting table too long in downstreams
> shorten saga name

- src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/ConcreteProxyCreator.cs
`AppDomain.CurrentDomain.DefineDynamicAssembly` is not supported in .net core 2.0 but `AssemblyBuilder.DefineDynamicAssembly` is. As this API also seems to be available in net452 we can always use this API if(!) there is no different behavior.
> Create proxy assembly with .NET Core compatible API

- README.md
This isn't needed since the code has been removed and the notice has been added to its [new home](https://github.com/Particular/NServiceBus.Encryption.MessageProperty/blob/develop/README.md).
> Remove encryption section from README

- src/NServiceBus.Core/NServiceBus.Core.csproj
The 0.1.62 package includes a change to the GenerateReleaseDate target to ensure it doesn't cause problems with Visual Studio's design-time builds.
> Update Particular.Licensing.Sources to 0.1.62
