src/NServiceBus.Core.Tests/Encryption/skip_props_and_fields_that_cannot_be_set.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/Encryption/EncryptionMutator.cs
=> Skip properties and fields that cannot be set.

src/NServiceBus.Core.Tests/Utils/Reflection/ExtensionMethodsTests.cs, src/NServiceBus.Core/Utils/Reflection/ExtensionMethods.cs
=> Use ConcurrentDictionary for TypeToNameLookup

src/NServiceBus.Core/Persistence/InMemory/SubscriptionStorage/InMemorySubscriptionStorage.cs
* Thread safety issues with the underlying lists of client Addresses
* Better performance with key lookups - O(1) vs O(n) for most ops
=> InMemorySubscriptionStorage: Fixed thread safety and performance issues

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Persistence/InMemory/When_property_is_null.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_saving_a_null_unique_property.cs, src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs, src/NServiceBus.Core/Sagas/SagaMetadata.cs
=> fix InMemorySagaPersister throws null reference for null property

src/NServiceBus.Core/Serializers/XML/Deserializer.cs, src/NServiceBus.Core/Serializers/XML/Serializer.cs, src/NServiceBus.Core/Serializers/XML/XmlMessageSerializer.cs
I quickly discussed this with @johnsimons, here is my attempt to make the deserializer more expressive by using descriptive method names.
=> Xml serializer refactoring part II

src/NServiceBus.Core/Conventions.cs, src/NServiceBus.Core/Encryption/EncryptionMutator.cs, src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/MessageMapper.cs, src/NServiceBus.Core/Unicast/MessageHandlerRegistry.cs, src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs, src/NServiceBus.Core/Utils/Reflection/ExtensionMethods.cs
Trying to reduce our memory footprint by being smarter on what we cache.
See http://www.bryancook.net/2009/07/runtimetypehandle-performance-memory.html
Todo:
=> Reduce our memory footprint

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/SecondLevelRetries/SecondLevelRetriesTests.cs, src/NServiceBus.Core.Tests/Timeout/When_deferring_a_message.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/SecondLevelRetries/SecondLevelRetriesBehavior.cs, src/NServiceBus.Core/Timeout/Core/TimeoutManagerDeferrer.cs, src/NServiceBus.Core/Timeout/TimeoutManagerBasedDeferral.cs, src/NServiceBus.Core/Transports/IDeferMessages.cs, src/NServiceBus.Core/Transports/TransportDeferOptions.cs, src/NServiceBus.Core/Unicast/Behaviors/DispatchMessageToTransportBehavior.cs
To give us full control over the seam towards the transport for defer operations
=> Introducing `TransportDeferOptions`

src/NServiceBus.AcceptanceTesting/Support/IBusAdapter.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Fakes/FakeBus.cs, src/NServiceBus.Core/CompletionResult.cs, src/NServiceBus.Core/IBus.cs, src/NServiceBus.Core/IBusExtensions.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/ReplyOptions.cs, src/NServiceBus.Core/SendOptions.cs, src/NServiceBus.Core/Unicast/ContextualBus.cs, src/NServiceBus.Core/Unicast/UnicastBus_IBusImpl.cs
To allow extensions to hook into bus.Reply.
@johnsimons I believe this one will allow me to fix #1974 , I'll send a pull for that shortly
=> Introducing reply options

src/NServiceBus.Core.Tests/Unicast/MessagingBestPracticesTests.cs, src/NServiceBus.Core/MessagingBestPractices/Validations.cs, src/NServiceBus.Core/Unicast/ContextualBus.cs
Sanity checks for combinations of postponed messages and TTBR, see https://github.com/Particular/Requirements/issues/193.
=> Enforce best practice of not postponing messages combined with TTBR set.

src/NServiceBus.AcceptanceTests/Audit/When_audit_is_everriden_in_code.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Audit/Audit.cs, src/NServiceBus.Core/Audit/AuditConfigReader.cs, src/NServiceBus.Core/Audit/ConfigureAudit.cs, src/NServiceBus.Core/Config/AuditConfig.cs, src/NServiceBus.Core/NServiceBus.Core.csproj
add ability to configure audit config with code
=> Auditconfig

src/NServiceBus.AcceptanceTests/Config/When_IWantToRunWhenBusStartsAndStops_Start_throws.cs
in When_IWantToRunWhenBusStartsAndStops_Start_throws
back ported from https://github.com/Particular/NServiceBus.RabbitMQ/commit/13da1dfde66ef0db73d930ff8414e90e07b9d078
=> fix race condition in acceptance tests

src/NServiceBus.AcceptanceTests/Encryption/EndpointTemplates/ContextAppender.cs
=> also log fatals

src/NServiceBus.AcceptanceTests/ScaleOut/When_individualization_is_enabled.cs, src/NServiceBus.AcceptanceTests/ScaleOut/When_individualization_is_enabled_for_msmq.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Routing/ApplyReplyToAddressBehaviorTests.cs, src/NServiceBus.Core/Configure.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Routing/ApplyReplyToAddressBehavior.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs, src/NServiceBus.Core/Routing/RoutingFeature.cs, src/NServiceBus.Core/Unicast/ContextualBus.cs, src/NServiceBus.Core/Unicast/IContextualBus.cs, src/NServiceBus.Core/Unicast/Queuing/Installers/EndpointInputQueueCreator.cs, src/NServiceBus.Core/v6-obsoletes.cs
@SimonCropp here's the pull that deals with the TODO's in #2761
=> Moves setting of the reply to address to a behavior

src/NServiceBus.AcceptanceTests/Basic/When_deferring_to_non_local.cs, src/NServiceBus.AcceptanceTests/DelayedDelivery/When_Deferring_a_message.cs, src/NServiceBus.AcceptanceTests/Encryption/EndpointTemplates/DefaultServer.cs, src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_Subscribing_to_errors.cs, src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_fails_flr.cs, src/NServiceBus.AcceptanceTests/Sagas/Issue_1819.cs, src/NServiceBus.AcceptanceTests/Sagas/When_doing_request_response_between_sagas.cs, src/NServiceBus.AcceptanceTests/Sagas/When_sagas_cant_be_found.cs, src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_handle.cs, src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_timeout.cs, src/NServiceBus.AcceptanceTests/Sagas/When_started_by_event_from_another_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_timeout_hit_not_found_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_using_ReplyToOriginator.cs, src/NServiceBus.AcceptanceTests/Sagas/When_using_a_received_message_for_timeout.cs, src/NServiceBus.AcceptanceTests/Sagas/When_using_contain_saga_data.cs, src/NServiceBus.AcceptanceTests/Scheduling/When_scheduling_a_recurring_task.cs
Before this change: 6m:31s
After this change: 4m:05s
fixes https://github.com/Particular/NServiceBus/issues/2479
=> dont create redundant queues in AT

src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Conventions/ArgumentExceptionTests.cs, src/NServiceBus.Core.Tests/Conventions/DocumentationTests.cs, src/NServiceBus.Core.Tests/ExceptionTests.cs, src/NServiceBus.Core.Tests/StandardsTests.cs, src/NServiceBus.Core/IBus.cs, src/NServiceBus.Core/ISendOnlyBus.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Pipeline/BehaviorContextStacker.cs, src/NServiceBus.Core/Unicast/Config/UnicastBus.cs, src/NServiceBus.Core/Unicast/IRealBus.cs, src/NServiceBus.Core/Unicast/Messages/DeserializeLogicalMessagesConnector.cs, src/NServiceBus.Core/Unicast/UnicastBus.cs, src/NServiceBus.Core/Unicast/UnicastBusInternal.cs, src/NServiceBus.Core/Unicast/UnicastBusInternal_IBusImpl.cs, src/NServiceBus.Core/Unicast/UnicastBusInternal_RemoveInV7.cs, src/NServiceBus.Core/v6-obsoletes.cs, src/NServiceBus.PerformanceTests/PubSub/PubSubTestCase.cs
You served us well dear `UnicastBus` but now it is time to be banned away from public. In your honor I brought here a little poem.
**A Happy Man By Edwin Arlington Robinson**
> When these graven lines you see, 
> Traveller, do not pity me; 
> Though I be among the dead, 
> Let no mournful word be said.
> Children that I leave behind, 
> And their children, all were kind; 
> Near to them and to my wife, 
> I was happy all my life.
> My three sons I married right, 
> And their sons I rocked at night; 
> Death nor sorrow never brought 
> Cause for one unhappy thought.
> Now, and with no need of tears, 
> Here they leave me, full of years,-- 
> Leave me to my quiet rest 
> In the region of the blest.
>
> http://www.familyfriendpoems.com/poem/a-happy-man-by-edwin-arlington-robinson
The purpose …
=> Exitus `UnicastBus`

src/NServiceBus.AcceptanceTests/Sagas/When_sagas_cant_be_found.cs, src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_handle.cs
This should be a very easy review.
=> NHibernate doesn't appreciate these missing virtual keywords

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Serializers/XML/Issue_2796.cs, src/NServiceBus.Core/Serializers/XML/Serializer.cs, src/NServiceBus.Core/Unicast/Queuing/Installers/ForwardReceivedMessagesToQueueCreator.cs
Users of containers that don't support private property setter injection (such as StructureMap and Ninject)
An exception occurs during creation of `ForwardReceivedMessagesToQueueCreator`:
InvalidOperationException was unhandled by user code… IWantQueueCreated implementation NServiceBus.Unicast.Queuing.Installers.ForwardReceivedMessagesToQueueCreator returned a null address
See this comment by @danielmarbach https://github.com/Particular/NServiceBus/issues/2621#issuecomment-120139636
none
**NB: Working off the develop branch**
When running `NServiceBus.Host.exe /install` from the command-line I receive the following error, but can't see that I'm missing anything in app.config related to `UnicastBus` configuration. Can you clarify if anything specific is required in moving from v4 to v5 in …
=> ForwardReceivedMessagesToQueueCreator can be created using any supported container

src/NServiceBus.AcceptanceTests/Mutators/When_using_outgoing_tm_mutator.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core/OutgoingPipeline/Mutators/MutateOutgoingPhysicalMessageBehavior.cs
=> Fixes a bug introduced in v6 where mutators couldn't change the message

src/NServiceBus.AcceptanceTests/Routing/When_publishing_from_sendonly.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Persistence/InMemory/SubscriptionStorage/InMemorySubscriptionStorage.cs, src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorage.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/IQuerySubscriptions.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/ISubscriptionStorage.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/SubscriptionReceiverBehavior.cs, src/NServiceBus.Core/Routing/StorageDrivenPublishing/StorageDrivenDispatcher.cs, src/NServiceBus.PerformanceTests/PubSub/PubSubTestCase.cs
@Particular/tf-asyncawait Please review
=> SubscriptionStorage and Query Subscriptions async

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Persistence/InMemory/When_completing_a_saga_with_the_InMemory_persister.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_completing_a_saga_with_unique_property_with_InMemory_persister.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_multiple_workers_retrieve_same_saga.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_the_same_unique_property_as_a_completed_saga.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_the_same_unique_property_as_another_saga.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_the_same_unique_property_as_the_original_value_of_another_saga_before_updating.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_different_sagas_with_unique_properties.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_property_is_null.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_saga_not_found_return_default.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_updating_a_saga_with_the_same_unique_property_as_another_saga.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_updating_a_saga_with_the_same_unique_property_value.cs, src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs, src/NServiceBus.Core/Saga/ISagaPersister.cs, src/NServiceBus.Core/Sagas/LoadSagaByIdWrapper.cs, src/NServiceBus.Core/Sagas/PropertySagaFinder.cs, src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
@Particular/tf-asyncawait Please review
=> ISagaPersister is now async

src/NServiceBus.Core/Persistence/InMemory/SubscriptionStorage/InMemorySubscriptionStorage.cs, src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorage.cs, src/NServiceBus.Core/Unicast/BackwardCompatibility/MutateMessageContentTypeOfIncomingTransportMessages.cs, src/NServiceBus.Core/Unicast/Transport/TransportReceiver.cs, src/NServiceBus.Core/WindowsIdentityEnrichment/WindowsIdentityEnricher.cs
@SimonCropp using your `TaskEx` where possible (good change btw.)
=> Using TaskEx where possible

src/NServiceBus.ContainerTests/When_registering_components.cs, src/NServiceBus.ContainerTests/When_using_nested_containers.cs
=> Spring now supports those scenarios if you have at least 6.0

src/NServiceBus.AcceptanceTests/Sagas/When_an_endpoint_replies_to_a_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_message_has_a_saga_id.cs, src/NServiceBus.AcceptanceTests/Sagas/When_sagas_cant_be_found.cs, src/NServiceBus.AcceptanceTests/Sagas/When_timeout_hit_not_found_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/when_receiving_multiple_timeouts.cs, src/NServiceBus.AcceptanceTests/Sagas/when_reply_from_saga_not_found_handler.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Sagas/IHandleSagaNotFound.cs, src/NServiceBus.Core/Unicast/Behaviors/InvokeSagaNotFoundBehavior.cs
=> IHandleSagaNotFound is async

src/NServiceBus.AcceptanceTests/DataBus/When_using_custom_IDataBus.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/DataBus/FileShare/AcceptanceTests.cs, src/NServiceBus.Core.Tests/DataBus/InMemoryDataBus.cs, src/NServiceBus.Core.Tests/DataBus/When_applying_the_databus_message_mutator_to_incoming_messages.cs, src/NServiceBus.Core.Tests/DataBus/When_applying_the_databus_message_mutator_to_outgoing_messages.cs, src/NServiceBus.Core/DataBus/DataBusReceiveBehavior.cs, src/NServiceBus.Core/DataBus/DataBusSendBehavior.cs, src/NServiceBus.Core/DataBus/FileShareDataBusImplementation.cs, src/NServiceBus.Core/DataBus/IDataBus.cs
This PR is part of the work to make the core async enabled. 
`IDataBus` is async
=> Converting DataBus to async

src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_regular_exception.cs, src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_performing_slr_with_serialization_exception.cs, src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs, src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs
=> reverting message body when dispatching to SLR

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Pipeline/PipelineBase.cs, src/NServiceBus.Core/Pipeline/PipelineConfiguration.cs, src/NServiceBus.Core/Pipeline/PipelineSettings.cs, src/NServiceBus.Core/Pipeline/RegisterStep.cs, src/NServiceBus.Core/Unicast/UnicastBusInternal.cs
Was added in v6 so not a breaking change
=> Custom registrations from within a step not needed anymore

src/NServiceBus.AcceptanceTesting/Support/IBusAdapter.cs, src/NServiceBus.AcceptanceTests/Audit/When_a_replymessage_is_audited.cs, src/NServiceBus.AcceptanceTests/Routing/When_dynamic_routing.cs, src/NServiceBus.AcceptanceTests/Routing/When_overriding_public_return_address.cs, src/NServiceBus.AcceptanceTests/Sagas/When_an_endpoint_replies_to_a_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_doing_request_response_between_sagas.cs, src/NServiceBus.AcceptanceTests/Sagas/When_replies_to_message_published_by_a_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_reply_from_a_finder.cs, src/NServiceBus.AcceptanceTests/Sagas/when_reply_from_saga_not_found_handler.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Fakes/FakeBus.cs, src/NServiceBus.Core.Tests/Unicast/MessagingBestPracticesTests.cs, src/NServiceBus.Core/IBus.cs, src/NServiceBus.Core/IBusExtensions.cs, src/NServiceBus.Core/IBusExtensions_obsolete.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Routing/MessagingBestPractices/Validations.cs, src/NServiceBus.Core/Sagas/Saga.cs, src/NServiceBus.Core/StaticHeaders/StaticHeadersConfigExtensions.cs, src/NServiceBus.Core/Unicast/ContextualBus.cs, src/NServiceBus.Core/Unicast/UnicastBusInternal_IBusImpl.cs, src/NServiceBus.Core/obsoletes.cs
=> IBus.Reply is async

src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_receiving_messages_already_dispatched.cs
=> Fixed flaky When_receiving_messages_already_dispatched ATT

src/NServiceBus.AcceptanceTests/FakeTransport/FakeDispatcher.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Timeout/FakeMessageDispatcher.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs, src/NServiceBus.Core/Reliability/Outbox/OutboxDeduplicationBehavior.cs, src/NServiceBus.Core/Reliability/Outbox/OutboxDispatchStrategy.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenUnsubscribeTerminator.cs, src/NServiceBus.Core/Routing/StorageDrivenPublishing/StorageDrivenDispatcher.cs, src/NServiceBus.Core/TransportDispatch/DefaultDispatchStrategy.cs, src/NServiceBus.Core/TransportDispatch/DispatchStrategy.cs, src/NServiceBus.Core/TransportDispatch/DispatchTerminator.cs, src/NServiceBus.Core/Transports/IDispatchMessages.cs, src/NServiceBus.Core/Transports/Msmq/MsmqMessageSender.cs, src/NServiceBus.Core/Unicast/ContextualBus.cs
`IDispatchMessage.Dispatch` is now async
=> IDispatchMessages is async

src/NServiceBus.AcceptanceTesting/Support/IBusAdapter.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Fakes/FakeBus.cs, src/NServiceBus.Core/IBus.cs, src/NServiceBus.Core/Unicast/ContextualBus.cs, src/NServiceBus.Core/Unicast/UnicastBusInternal_IBusImpl.cs, src/NServiceBus.Core/obsoletes.cs
`IBus.ForwardCurrentMessageTo` is now async
=> IBus.ForwardCurrentMessageTo is async

src/NServiceBus.Core.Tests/Faults/ForwardFaultsToErrorQueueTests.cs, src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs, src/NServiceBus.Core/Audit/InvokeAuditPipelineBehavior.cs, src/NServiceBus.Core/DelayedDelivery/RequestCancelingOfDeferredMessagesFromTimeoutManager.cs, src/NServiceBus.Core/Faults/MoveFaultsToErrorQueueBehavior.cs, src/NServiceBus.Core/Forwarding/InvokeForwardingPipelineBehavior.cs, src/NServiceBus.Core/Pipeline/BehaviorChain.cs, src/NServiceBus.Core/Pipeline/BehaviorInstance.cs, src/NServiceBus.Core/Pipeline/PipelineBase.cs, src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs, src/NServiceBus.Core/Unicast/ContextualBus.cs, src/NServiceBus.Core/Unicast/Transport/TransportReceiver.cs
Pipeline invocation where possible async
=> Pipeline invocation is async

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/IBusExtensions_obsolete.cs, src/NServiceBus.Core/IWantToRunWhenBusStartsAndStopsExtensions_obsoletes.cs, src/NServiceBus.Core/NServiceBus.Core.csproj
for ForwardCurrentMessageTo, HandleCurrentMessageLater and Start/Stop on IWantToRunWhenBusStartsAndStops
=> Obsoletes 

src/NServiceBus.AcceptanceTests/Sagas/When_doing_request_response_between_sagas.cs, src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_timeout.cs, src/NServiceBus.AcceptanceTests/Sagas/When_started_by_event_from_another_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_timeout_hit_not_found_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_using_ReplyToOriginator.cs, src/NServiceBus.AcceptanceTests/Sagas/When_using_a_received_message_for_timeout.cs, src/NServiceBus.AcceptanceTests/Sagas/When_using_contain_saga_data.cs, src/NServiceBus.AcceptanceTests/Sagas/when_receiving_multiple_timeouts.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Sagas/Saga.cs, src/NServiceBus.Core/Sagas/Saga_obsoletes.cs
=> Better obsoletes for RequestTimeout and ReplyToOriginator

src/NServiceBus.Core/DelayedDelivery/DelayedDeliveryFeature.cs, src/NServiceBus.Core/Forwarding/ForwardReceivedMessages.cs, src/NServiceBus.Core/Unicast/Config/UnicastBus.cs
=> No longer assume that the `UnicastBusConfig` is present 

src/NServiceBus.AcceptanceTests/Basic/When_multiple_mappings_exists.cs, src/NServiceBus.AcceptanceTests/PerfMon/CriticalTime/When_slow_with_CriticalTime_enabled.cs, src/NServiceBus.AcceptanceTests/PerfMon/SLA/When_sending_slow_with_SLA_enabled.cs, src/NServiceBus.Core/CircuitBreakers/RepeatedFailuresOverTimeCircuitBreaker.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs, src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
Circuitbreaker Failure is async and cleanup of some `Thread.Sleep`
@Particular/tf-asyncawait Please review and merge
=> Circuit breaker async

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Installers/PerformanceMonitorUsersInstallerTests.cs, src/NServiceBus.Core/Installation/INeedToInstallSomething.cs, src/NServiceBus.Core/Installation/InstallConfigExtensions.cs, src/NServiceBus.Core/Installation/InstallationSupport.cs, src/NServiceBus.Core/Performance/Counters/PerformanceMonitorUsersInstaller.cs, src/NServiceBus.Core/Unicast/Queuing/QueuesCreator.cs
=> INeedToInstallSomething is async

src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/IStartableBus.cs, src/NServiceBus.Core/IStartableBusExtensions_obsoletes.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Unicast/UnicastBusInternal.cs, src/NServiceBus.Core/obsoletes.cs, src/NServiceBus.PerformanceTests/Program.cs, src/NServiceBus.PerformanceTests/PubSub/PubSubTestCase.cs
=> IStartableBus is async

src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs
=> Remove EndpointName property, closes #2927

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes.cs
=> Fixed obsoletion message on TransportMessage

src/NServiceBus.AcceptanceTests/Sagas/When_doing_request_response_between_sagas.cs
=> Fixing correlation in When_doing_request_response_between_sagas

src/NServiceBus.Core/Pipeline/BehaviorChain.cs, src/NServiceBus.Core/Pipeline/BehaviorContextStacker.cs, src/NServiceBus.Core/Pipeline/PipelineBase.cs, src/NServiceBus.Core/Unicast/Config/UnicastBus.cs, src/NServiceBus.Core/Unicast/Transport/TransportReceiver.cs, src/NServiceBus.Core/Unicast/UnicastBusInternal.cs
Now the only thing we register in the child builder is the contextual bus.
@andreasohlund can you review and merge?
=> Bye bye registering BehaviorContextStacker in the container

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Pipeline/PipelineCollection.cs, src/NServiceBus.Core/Settings/TransactionSettings.cs, src/NServiceBus.Core/Transports/Msmq/ReceiveWithNativeTransaction.cs, src/NServiceBus.Core/Transports/Msmq/ReceiveWithNoTransaction.cs, src/NServiceBus.Core/Transports/Msmq/ReceiveWithTransactionScope.cs, src/NServiceBus.Core/Transports/PushContext.cs, src/NServiceBus.Core/Transports/TransportConfig.cs, src/NServiceBus.Core/Transports/TransportReceiver.cs, src/NServiceBus.Core/Unicast/UnicastBusInternal.cs, src/NServiceBus.Core/obsoletes.cs
And not relying on `IncomingMessage`
Connects to https://github.com/Particular/PlatformDevelopment/issues/182
=> Making the push context more explicit

src/NServiceBus.AcceptanceTests/Sagas/When_forgetting_to_set_a_corr_property.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Persistence/InMemory/SagaMetadataHelper.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_completing_a_saga_with_the_InMemory_persister.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_completing_a_saga_with_unique_property_with_InMemory_persister.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_multiple_workers_retrieve_same_saga.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_the_same_unique_property_as_a_completed_saga.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_the_same_unique_property_as_another_saga.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_the_same_unique_property_as_the_original_value_of_another_saga_before_updating.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_different_sagas_with_unique_properties.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_property_is_null.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_saga_not_found_return_default.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_saving_a_null_unique_property.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_updating_a_saga_with_the_same_unique_property_as_another_saga.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_updating_a_saga_with_the_same_unique_property_value.cs, src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs, src/NServiceBus.Core/Sagas/ActiveSagaInstance.cs, src/NServiceBus.Core/Sagas/ISagaPersister.cs, src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
Depends on #3007 and needs to be rebased once that one is pulled in
=> Pass corr props and values to persister

src/NServiceBus.AcceptanceTests/Encryption/When_using_encryption.cs, src/NServiceBus.AcceptanceTests/Encryption/When_using_encryption_with_multikey.cs, src/NServiceBus.Core.Tests/Encryption/ConfigureRijndaelEncryptionServiceTests.cs, src/NServiceBus.Core.Tests/Encryption/EncryptionServiceTests.cs, src/NServiceBus.Core.Tests/Encryption/RijndaelEncryptionServiceConfigValidationsTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/Config/RijndaelEncryptionServiceConfig.cs, src/NServiceBus.Core/Config/RijndaelExpiredKey.cs, src/NServiceBus.Core/ConfigureRijndaelEncryptionService.cs, src/NServiceBus.Core/Encryption/Rijndael/EncryptionService.cs, src/NServiceBus.Core/Encryption/RijndaelEncryptionServiceConfigValidations.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.PerformanceTests/Program.cs, src/NServiceBus/Headers.cs
Connects to Particular/PlatformDevelopment#423
Fixes: #3017 #3018
=> Rijndael encryption service: Possible data corruption when using rotating encryption keys v4.7.x

src/NServiceBus.AcceptanceTests/Encryption/When_using_Rijndael_with_config.cs, src/NServiceBus.AcceptanceTests/Encryption/When_using_Rijndael_with_custom.cs, src/NServiceBus.AcceptanceTests/Encryption/When_using_Rijndael_without_incoming_key_identifier.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/Encryption/ConfigureRijndaelEncryptionServiceTests.cs, src/NServiceBus.Core.Tests/Encryption/RijndaelEncryptionServiceTest.cs, src/NServiceBus.Core.Tests/Encryption/ValidationFixture.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/Encryption/ConfigureRijndaelEncryptionService.cs, src/NServiceBus.Core/Encryption/EncryptionMutator.cs, src/NServiceBus.Core/Encryption/KeyFormat.cs, src/NServiceBus.Core/Encryption/RijndaelEncryptionService.cs, src/NServiceBus.Core/Encryption/RijndaelEncryptionServiceConfig.cs, src/NServiceBus.Core/Encryption/RijndaelEncryptionServiceConfigValidations.cs, src/NServiceBus.Core/Encryption/RijndaelExpiredKey.cs, src/NServiceBus.Core/Headers.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.PerformanceTests/Program.cs
Connects to Particular/PlatformDevelopment#423
Fixes: #2994 #3017 #3018 #3019
=> Rijndael encryption service: Possible data corruption when using rotating encryption keys v5.1.x

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/Timeouts/TemporarilyUnavailableTimeoutPersister.cs, src/NServiceBus.AcceptanceTests/Timeouts/When_timeout_storage_is_unavailable_temporarily.cs, src/NServiceBus.Core/Timeout/Hosting/Windows/TimeoutPersisterReceiver.cs, src/NServiceBus.Core/Timeout/TimeoutManager.cs
Connects to #2994
This is the corresponding PR for support-5.1. It has the same commits as https://github.com/Particular/NServiceBus/pull/3013
=> Circuit breaker timeout fix for 5.1.x

src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
Fixes https://github.com/Particular/NServiceBus/issues/3033
=> Tracking receiveTasks earlier in MessagePump

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_clearing_saga_timeouts.cs, src/NServiceBus.AcceptanceTests/Sagas/When_a_base_class_message_hits_a_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_an_endpoint_replies_to_a_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_auto_correlated_property_is_changed.cs, src/NServiceBus.AcceptanceTests/Sagas/When_doing_request_response_between_sagas.cs, src/NServiceBus.AcceptanceTests/Sagas/When_forgetting_to_set_a_corr_property.cs, src/NServiceBus.AcceptanceTests/Sagas/When_message_has_a_saga_id.cs, src/NServiceBus.AcceptanceTests/Sagas/When_saga_is_mapped_to_complex_expression.cs, src/NServiceBus.AcceptanceTests/Sagas/When_two_sagas_subscribe_to_the_same_event.cs, src/NServiceBus.AcceptanceTests/Sagas/When_updating_existing_correlation_property.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Persistence/InMemory/When_property_is_null.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/When_saga_not_found_return_default.cs, src/NServiceBus.Core.Tests/Sagas/SagaModelTests.cs, src/NServiceBus.Core.Tests/Sagas/When_saga_is_correlated_on_a_unsupported_property_type.cs, src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs, src/NServiceBus.Core/Sagas/ActiveSagaInstance.cs, src/NServiceBus.Core/Sagas/CorrelationProperty.cs, src/NServiceBus.Core/Sagas/PropertySagaFinder.cs, src/NServiceBus.Core/Sagas/SagaMetadata.cs, src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs, src/NServiceBus.Core/Sagas/SagaToMessageMap.cs
=> Setting correlated property values automatically

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes.cs
=> Better obsolete message for TransportMessage.Body

src/NServiceBus.AcceptanceTesting/Support/FailTestOnErrorMessageFeature.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Features/FeatureConfigurationContext.cs
Related to https://github.com/Particular/NServiceBus/pull/3051 especially [this comment](https://github.com/Particular/NServiceBus/pull/3051#issuecomment-153493226)
=> Remove IBuilder from FeatureConfigurationContext

src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
http://blog.i3arnon.com/2015/07/02/task-run-long-running/
thx @andreasohlund for pointing this out
Connects to Particular/PlatformDevelopment#182
=> Removed TaskContinuationOptions.LongRunning in the MessagePump

src/NServiceBus.AcceptanceTests/FakeTransport/FakeReceiver.cs, src/NServiceBus.AcceptanceTests/Performance/ProcessingOptimizations/When_using_concurrency_limit.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Transports/IPushMessages.cs, src/NServiceBus.Core/Transports/Msmq/MessagePump.cs, src/NServiceBus.Core/Transports/TransportReceiver.cs
As per discussion with @danielmarbach
=> public api has to indicate that stop method is async

src/NServiceBus.Core.Tests/Persistence/InMemory/InMemoryOutboxPersisterTests.cs, src/NServiceBus.Core/Persistence/InMemory/Outbox/InMemoryOutboxStorage.cs, src/NServiceBus.Core/Persistence/InMemory/Outbox/InMemoryOutboxTransaction.cs, src/NServiceBus.Core/Reliability/Outbox/OutboxTransaction.cs
I couldn't come up with a reason why you'd `await` a `BeginTransaction`. Thoughts?
Particular/PlatformDevelopment#182
=> InMemoryOutboxTransaction behaves like a transaction

src/NServiceBus.Core/Pipeline/BehaviorChain.cs
=> No longer capture context in closure of BehaviorChain

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes.cs
=> More transport message fixes

src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/API/APIApprovals.cs, src/NServiceBus.Core.Tests/Conventions/ArgumentExceptionTests.cs, src/NServiceBus.Core.Tests/Conventions/DocumentationTests.cs, src/NServiceBus.Core.Tests/ExceptionTests.cs, src/NServiceBus.Core.Tests/Scheduler/ScheduleTests.cs, src/NServiceBus.Core.Tests/StandardsTests.cs, src/NServiceBus.Core/CriticalError/CriticalError.cs, src/NServiceBus.Core/Endpoint.cs, src/NServiceBus.Core/IBusContextFactory.cs, src/NServiceBus.Core/IEndpoint.cs, src/NServiceBus.Core/IEndpointInstance.cs, src/NServiceBus.Core/ISendOnlyBusExtensions_obsoletes.cs, src/NServiceBus.Core/IStartableEndpoint.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/StartableEndpoint.cs, src/NServiceBus.Core/Unicast/Config/UnicastBus.cs, src/NServiceBus.Core/Unicast/RunningEndpoint.cs, src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs, src/NServiceBus.Core/Unicast/UnicastBusInternal_RemoveInV7.cs, src/NServiceBus.Core/obsoletes.cs
* `IBusContext` -> `ICommunicationSession`
* `IBusInterface` -> `ICommunicationSessionFactory`
* `IEndpoint` -> `IEndpointInstance`
* `BusConfiguration` -> `EndpointConfiguration`
=> Finalizing top level API revamp

src/NServiceBus.AcceptanceTests/Msmq/When_setting_msmq_label_generator.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/IWantToRunBeforeConfigurationIsFinalized.cs, src/NServiceBus.Core/InitializableEndpoint.cs, src/NServiceBus.Core/Installation/INeedToInstallSomething.cs, src/NServiceBus.Core/Installation/InstallConfigExtensions.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Performance/Counters/PerformanceMonitorUsersInstaller.cs, src/NServiceBus.Core/Persistence/PersistenceStartup.cs, src/NServiceBus.Core/StartableEndpoint.cs, src/NServiceBus.Core/Unicast/Queuing/QueuesCreator.cs, src/NServiceBus.Core/obsoletes.cs
@SimonCropp @Particular/nservicebus plase review.
=> Renamed back INeedToInstallSomething and IWantToRunBeforeConfigurationIsFinalized

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Routing/DetermineRouteForSendBehaviorTests.cs, src/NServiceBus.Core.Tests/Routing/UnicastRouterTests.cs, src/NServiceBus.Core/Routing/IUnicastRouter.cs, src/NServiceBus.Core/Routing/Routers/UnicastPublishRouterConnector.cs, src/NServiceBus.Core/Routing/Routers/UnicastSendRouterConnector.cs, src/NServiceBus.Core/Routing/RoutingFeature.cs, src/NServiceBus.Core/Routing/UnicastRouter.cs, src/NServiceBus.Core/Routing/UnicastRoutingTable.cs
First go at https://github.com/Particular/NServiceBus/issues/3116
=> Async all the way for dynamic route rules.

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/CriticalError/ConfigureCriticalErrorAction.cs, src/NServiceBus.Core/CriticalError/CriticalError.cs, src/NServiceBus.Core/CriticalError/CriticalErrorAction.cs, src/NServiceBus.Core/InitializableEndpoint.cs, src/NServiceBus.Core/NServiceBus.Core.csproj
brings critical error inline with msmq label and SubscriptionAuthorizer
=> use delegate for critical error

src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs
=> replace recursion with while loop

src/NServiceBus.Core/InitializableEndpoint.cs
-build up a local copy of concrete types and reuse them
-no need to process abstract types to WireUpConfigSectionOverrides
-make code more explicit. less foralltypes helpers
=> cache and only scan concrete type in endpoint init

src/NServiceBus.Core/Routing/UnicastRouter.cs, src/NServiceBus.Core/Routing/UnicastRoutingTable.cs
* Moved `Distinct` to proper place in the routing pipe
* Refactored instance selection to be more readable
=> Minor tweaks to routing

src/NServiceBus.AcceptanceTests/FakeTransport/FakeReceiver.cs, src/NServiceBus.AcceptanceTests/Performance/ProcessingOptimizations/When_using_concurrency_limit.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Transports/IPushMessages.cs, src/NServiceBus.Core/Transports/Msmq/MessagePump.cs, src/NServiceBus.Core/Transports/TransportReceiver.cs
This is needed to enable queue purging in sql transport. [see](https://github.com/Particular/NServiceBus.SqlServer/pull/108/files?diff=unified#diff-7699ae3c475c6f3261c50c3b69adec1eR35)
=> Make init method on IPushMessages async

src/NServiceBus.Core/Routing/Legacy/ProcessedMessageCounterBehavior.cs, src/NServiceBus.Core/Routing/Routers/UnicastPublishRouterConnector.cs, src/NServiceBus.Core/StartableEndpoint.cs, src/NServiceBus.Core/Transports/Receiving.cs, src/NServiceBus.Core/Transports/Sending.cs, src/NServiceBus.Core/UnitOfWork/UnitOfWorkBehavior.cs
=> Missing `ConfigureAwait(false)`

src/NServiceBus.Core.Tests/DeliveryConstraintContextExtensions/DeliveryConstraintContextExtensionsTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/DeliveryConstraints/DeliveryConstraintContextExtensions.cs
Comparison should be based on inheritance, not equality.
=> Delivery constraint extensions bug

src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs, src/NServiceBus.Core/Serialization/SerializeMessageConnector.cs
* Adding logging, in debug mode, of message before it is serialized
* Adding logging, in debug mode, of destination of message (unicast only) and headers
connects to #3186
=> Log all publishes at debug level

src/NServiceBus.AcceptanceTesting/Support/EndpointBehavior.cs, src/NServiceBus.AcceptanceTesting/Support/EndpointBehaviorBuilder.cs, src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
=> Add context to CustomConfig call

src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_autoSubscribe.cs
Modified to allow transports with native pub/sub to work
=> tests supported by message-driven subscription transports only

src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs
=> Removed unnecessary await in RoutingToDispatchConnector

src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_clearing_saga_timeouts.cs
=> Test only works for transports w/o native deferral

src/NServiceBus.AcceptanceTests/Causation/When_a_message_is_audited.cs, src/NServiceBus.AcceptanceTests/Causation/When_a_message_is_faulted.cs, src/NServiceBus.AcceptanceTests/Hosting/When_a_message_is_faulted.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Faults/ForwardFaultsToErrorQueueTests.cs, src/NServiceBus.Core/Hosting/FaultHostInformationBehavior.cs, src/NServiceBus.Core/Hosting/HostInformationFeature.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Recoverability/Faults/FaultContext.cs, src/NServiceBus.Core/Recoverability/Faults/FaultToDispatchConnector.cs, src/NServiceBus.Core/Recoverability/Faults/IFaultContext.cs, src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs, src/NServiceBus.Core/Recoverability/Faults/StoreFaultsInErrorQueue.cs
=> Adding RelatedTo and ConversationId header to audit message.

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Pipeline/StageConnector.cs, src/NServiceBus.Core/Satellites/SatelliteBehavior.cs, src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs
=> Cleanup RunningEndpointInstance, rename context in StageConnector

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes.cs
Made the message more meaningful even when it appears outside the context of message handlers such as IWantToRunWhenBusStartsAndStops
=> Clarified the IBus obsolete message.

src/NServiceBus.AcceptanceTests/Sagas/When_forgetting_to_set_a_corr_property.cs, src/NServiceBus.Core.Tests/Sagas/SagaMetadataCreationTests.cs, src/NServiceBus.Core/Sagas/SagaMetadata.cs
Fix for incorrect types being used when searching for sagas.
Connects to https://github.com/Particular/NServiceBus/issues/3291
=> Check that saga find type matches the actual saga Type

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Faults/ForwardFaultsToErrorQueueTests.cs, src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs, src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs, src/NServiceBus.Core.Tests/Reliability/Outbox/TransportReceiveToPhysicalMessageProcessingConnectorTests.cs, src/NServiceBus.Core.Tests/Routing/DetermineRouteForReplyBehaviorTests.cs, src/NServiceBus.Core.Tests/UnitOfWork/UnitOfWorkBehaviorTests.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Pipeline/Incoming/ITransportReceiveContext.cs, src/NServiceBus.Core/Pipeline/Incoming/MessageProcessingAbortedException.cs, src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveContext.cs, src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs, src/NServiceBus.Core/Recoverability/FirstLevelRetries/FirstLevelRetriesBehavior.cs, src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs, src/NServiceBus.Core/Transports/Msmq/MessagePump.cs, src/NServiceBus.Core/Transports/Msmq/ReceiveStrategy.cs, src/NServiceBus.Core/Transports/Msmq/ReceiveWithNativeTransaction.cs, src/NServiceBus.Core/Transports/Msmq/ReceiveWithNoTransaction.cs, src/NServiceBus.Core/Transports/Msmq/ReceiveWithTransactionScope.cs, src/NServiceBus.Core/Transports/PushContext.cs, src/NServiceBus.Core/Transports/TransportReceiver.cs
Partly implements #3242 
- Go through the upgrade guide for v6
=> [WIP] Abort receives using cancellation token

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Pipeline/IPipelineTerminator.cs
=> IPipelineTerminator made internal

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/BusNotifications.cs, src/NServiceBus.Core/Recoverability/Faults/ErrorsNotifications.cs
=> Removed IDisposable and double null check in BusNotifications

src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPollerTests.cs, src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/RecordingFakeDispatcher.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/CircuitBreakers/ICircuitBreaker.cs, src/NServiceBus.Core/CircuitBreakers/RepeatedFailuresOverTimeCircuitBreaker.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Persistence/InMemory/TimeoutPersister/InMemoryTimeoutPersister.cs
Tests covering the actual behavior of poller.
=> ExpiredTimeoutsPoller tests

src/NServiceBus.Core/Licensing/AuditInvalidLicenseBehavior.cs
Full discussion here - https://github.com/Particular/NServiceBus/pull/2964/files#r41599377
=> Use hardcoded true to avoid culture issues

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/NonDTC/When_sending_a_message_with_a_ttbr.cs, src/NServiceBus.Core/Outbox/OutboxDeduplicationBehavior.cs, src/NServiceBus.Core/Outbox/OutboxSendBehavior.cs
This makes sure that the Outbox honors TTBR if used
Closes #3350
=> Outbox now honors TTBR

src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_autoSubscribe.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs, src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribeSettings.cs, src/NServiceBus.Core/obsoletes.cs
Related to this issue : https://github.com/Particular/NServiceBus/issues/2318
Doco PR: https://github.com/Particular/docs.particular.net/pull/997
=> Removed AutoSubscribePlainMessages as settings option

src/NServiceBus.AcceptanceTests/Encryption/When_using_encryption_with_custom_service.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Encryption/ConfigureRijndaelEncryptionService.cs, src/NServiceBus.Core/Encryption/DecryptBehavior.cs, src/NServiceBus.Core/Encryption/EncryptBehavior.cs, src/NServiceBus.Core/Encryption/Encryptor.cs, src/NServiceBus.Core/obsoletes.cs
[Doco PR](https://github.com/Particular/docs.particular.net/pull/1092)
=> Removed builder access from encryption service factory

packaging/nuget/nservicebus.acceptancetests.nuspec
Since they are not relevant to run in the downstreams.
@SeanFeldman like we discussed. Please review and merge
=> Exclude uow tests from the source package

src/NServiceBus.Core/Routing/FileBasedDynamicRouting/AsyncTimer.cs
=> Dispose the cancellation token source in the async timer

src/NServiceBus.Core/BusConfiguration.cs
=> Removed some dead code.

src/NServiceBus.Core/FodyWeavers.xml, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/packages.config
=> Update Fody and plugins

src/NServiceBus.AcceptanceTesting/Customization/EndpointConfigurationExtensions.cs, src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Scheduling/Schedule.cs
@Particular/nservicebus-maintainers ping
=> minor renamings

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Msmq/MsmqMessageDispatcherTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Transports/Msmq/MsmqConnectionStringBuilder.cs, src/NServiceBus.Core/Transports/Msmq/MsmqMessageDispatcher.cs, src/NServiceBus.Core/Transports/Msmq/MsmqSettings.cs, src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs, src/NServiceBus.Core/Transports/Msmq/QueueCreator.cs, src/NServiceBus.Core/obsoletes.cs
This makes `MsmqMessageSender` and `MsmqSettings` internal
Doco pull:  https://github.com/Particular/docs.particular.net/pull/1138
=> Reduced msmq surface area

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs, src/NServiceBus.Core/Satellites/SatelliteBehavior.cs
=> remove SatelliteBehavior

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/DetectObsoleteConfigurationSettings.cs, src/NServiceBus.Core/Unicast/UnicastBusConfig.cs
Connects to https://github.com/Particular/NServiceBus/issues/3426
Doco pull: https://github.com/Particular/docs.particular.net/pull/1155
@timbussmann can you please check this is correct
=> Obsoleting unused distributor config properties from UnicastBusConfig

src/NServiceBus.Core/Features/FeatureActivator.cs
Connects to #3448
Aligns with [Lifecycle of startable and stoppable components](https://github.com/Particular/PlatformDevelopment/pull/616)
@andreasohlund and I went through the `FeatureStartupTasks` and came to the conclusion that the order of stopping the tasks should not matter. And if we change the core to concurrently stop the tasks and hit an issue where it matters, then it is probably a design smell in the feature dependencies which needs to be solved.
=> Stop FeatureStartupTasks concurrently, closes #3448

src/NServiceBus.Core/Pipeline/PipelineCollection.cs
Connects to #3447
Aligns with [Lifecycle of startable and stoppable components](https://github.com/Particular/PlatformDevelopment/pull/616)
=> Stop pipelines concurrently

src/NServiceBus.Core/Transports/Msmq/MsmqMessageDispatcher.cs, src/NServiceBus.Core/Transports/Msmq/ReceiveWithNativeTransaction.cs
@SzymonPobiega @danielmarbach @janovesk please review
=> Msmq now uses the correct transport transaction

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Routing/RoutingOptionExtensionsTests.cs, src/NServiceBus.Core/Routing/RoutingOptionExtensions.cs
Reverts Particular/NServiceBus#3484
=> Revert "Adding GetDestination extension method for sendoptions"

src/NServiceBus.Core/Routing/Legacy/ProcessedMessageCounterBehavior.cs, src/NServiceBus.Core/Routing/Legacy/ReadyMessageSender.cs
@Particular/nservicebus-maintainers can you have a look?
=> Sending ready messages to Distributor is no longer fire & forget 

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Settings/SettingsHolderTests.cs, src/NServiceBus.Core.Tests/Unicast/RunningEndpointInstanceTest.cs, src/NServiceBus.Core/Settings/SettingsHolder.cs, src/NServiceBus.Core/StartableEndpoint.cs, src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs
@bording That would be my idea to https://github.com/Particular/NServiceBus/pull/3428
@Particular/nservicebus-maintainers Thoughts?
=> SettingsHolder can be cleared

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Transports/TransportDefinition.cs, src/NServiceBus.Core/Transports/TransportInfrastructure.cs, src/NServiceBus.Core/obsoletes.cs
=> Adjusting obsolets for the transport definition change

src/NServiceBus.AcceptanceTests/DelayedDelivery/TimeoutManager/When_timeout_dispatch_fails_on_timeout_data_removal.cs, src/NServiceBus.AcceptanceTests/ScenarioDescriptors/AllTransports.cs
* piggybacked a small refactoring in UnicastReplyRouterConnector
=> Introduced a AT transport group that supports atomic send and receive

src/NServiceBus.AcceptanceTests/Performance/When_message_is_audited.cs, src/NServiceBus.Core/Audit/Audit.cs, src/NServiceBus.Core/Performance/AuditProcessingStatisticsBehavior.cs, src/NServiceBus.Core/Performance/ReceiveStatisticsFeature.cs, src/NServiceBus.Core/Performance/Statistics/ProcessingStatisticsBehavior.cs
Connects to #3450
@WojcikMike @johnsimons thoughts?
=> Properly setting ProcessedAt

src/NServiceBus.Core.Tests/Sagas/SagaMetadataCreationTests.cs, src/NServiceBus.Core/Sagas/SagaMetadata.cs, src/NServiceBus.Core/Utils/Reflection/Reflect.cs
Resolves #3480 and fixes another exception that wasn't necessarily valid.
=> Improve exceptions when saga messages are mapped improperly

src/NServiceBus.AcceptanceTests/FakeTransport/FakeTransport.cs, src/NServiceBus.AcceptanceTests/FakeTransport/FakeTransportInfrastructure.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_transport_scopes.cs
This makes the test pass even if the default transport isn't supporting DTC (like msmq does)
=> Use fake transport to verify uow startup check

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/DispatchTimeoutBehaviorTest.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs, src/NServiceBus.Core/Features/FeatureConfigurationContext.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Pipeline/ConnectorContextExtensions.cs, src/NServiceBus.Core/Pipeline/Incoming/ISatelliteProcessingContext.cs, src/NServiceBus.Core/Pipeline/Incoming/SatelliteProcessingContext.cs, src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToSatelliteConnector.cs
@weralabaj this should fix the timeouts issue you were facing.
=> Disabled outbox in satellites by giving them their own connector.

src/NServiceBus.sln.DotSettings
But keep it as a warn for now until we have formatted the codebase
Will add this to repo standards when agreed and pulled
=> Use implicit namespace declarations

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes.cs
changed IManageMessageFailures` extension now obsolete message to point people to our upgrade documentation
=> IManageMessageFailures` extension now obsolete message

src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs
=> VersionedSagaEntity uses public field instead of property

packaging/nuget/nservicebus.acceptancetesting.nuspec
fixes #2817 
* title should represent the package id more appropriately
* add a note that this isn't an officially supported package
=> AdjustedNServiceBus.AcceptanceTesting nuspec

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/Persistence/When_a_persistence_does_not_support_gateway_dedup.cs, src/NServiceBus.AcceptanceTests/Persistence/When_a_persistence_does_not_support_outbox.cs, src/NServiceBus.AcceptanceTests/Persistence/When_a_persistence_does_not_support_saga.cs, src/NServiceBus.AcceptanceTests/Persistence/When_a_persistence_does_not_support_subscriptions.cs, src/NServiceBus.AcceptanceTests/Persistence/When_a_persistence_does_not_support_timeouts.cs, src/NServiceBus.Core.Tests/Config/When_no_custom_configuration_source_is_specified.cs, src/NServiceBus.Core.Tests/Config/When_users_override_the_configuration_source.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs, src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayPersistence.cs, src/NServiceBus.Core/Pipeline/Incoming/IncomingLogicalMessageContext.cs, src/NServiceBus.Core/Reliability/Outbox/Outbox.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs, src/NServiceBus.Core/Sagas/Sagas.cs
Fixes https://github.com/Particular/NServiceBus/issues/3588
@Particular/nservicebus-maintainers 
// cc @indualagarsamy
=> Throw an exception of a feature requires a specific storage type and the persistence doesn't support it

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes.cs
=> Updated the obsolete message

src/NServiceBus.Core/Properties/AssemblyInfo.cs
Connects to https://github.com/Particular/PlatformDevelopment/issues/706
=> Removed copyright year

src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs, src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs, src/NServiceBus.Core/Recoverability/Faults/MoveFaultsToErrorQueueBehavior.cs, src/NServiceBus.Core/Recoverability/SecondLevelRetries/SecondLevelRetriesBehavior.cs
Connects to #3032 
Links to https://github.com/Particular/NServiceBus/pull/3673
=> Fixing slr and errors race condition

src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
Connects to https://github.com/Particular/EndToEnd/issues/3
* Reduced task scheduling to dispose cancellation token source
* Receive task doesn't need to bomb when inner cancellation token source is canceled
Strangely the token source was used to pass the token to the receive task. Which means the receive task would transition into the cancelled stated depending on the token. Why would we require that? It means that when we await it when shutting down an OperationCancelledException would be thrown. I don't think this is desired.
I send in another PR which might be preferred over this one.
=> Reduced task scheduling to dispose cancellation token source

src/NServiceBus.Core/FodyWeavers.xml, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/packages.config
https://github.com/Fody/Janitor/issues/16
=> Update Fody.Janitor to resolve IDisposable[] issues

src/NServiceBus.AcceptanceTests/DelayedDelivery/TimeoutManager/When_timeout_dispatch_fails.cs
A squashed cherry pick of https://github.com/Particular/NServiceBus/pull/3676 for release-6.0.0.0
Ping @timbussmann
=> Timeout dispatch tests: flakiness fixed

src/NServiceBus.Core/Features/DisplayDiagnosticsForFeatures.cs, src/NServiceBus.Core/Features/FeatureActivator.cs, src/NServiceBus.Core/Features/FeatureDiagnosticData.cs
=> FeatureDiagnosticData: Spelling of DependenciesAreMet

src/NServiceBus.Core/Logging/RollingLogger.cs
=> swallow and log when log file purging fails

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/Sagas/When_auto_correlated_property_is_changed.cs, src/NServiceBus.AcceptanceTests/Sagas/When_saga_id_changed.cs, src/NServiceBus.AcceptanceTests/Sagas/When_updating_existing_correlation_property.cs, src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_transport_scopes.cs, src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_using_timeout_greater_than_machine_max.cs, src/NServiceBus.AcceptanceTests/packages.config, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.ContainerTests/packages.config, src/NServiceBus.Core.Tests.x86/NServiceBus.Core.x86.Tests.csproj, src/NServiceBus.Core.Tests.x86/packages.config, src/NServiceBus.Core.Tests/Faults/MoveFaultsToErrorQueueTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Recoverability/FirstLevelRetries/FirstLevelRetriesTests.cs, src/NServiceBus.Core.Tests/Recoverability/SecondLevelRetries/SecondLevelRetriesTests.cs, src/NServiceBus.Core.Tests/Recoverability/When_message_is_deferred_by_slr.cs, src/NServiceBus.Core.Tests/RedirectHelper.cs, src/NServiceBus.Core.Tests/packages.config, src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj, src/NServiceBus.Msmq.AcceptanceTests/When_TimeToBeReceived_set_and_native_receivetransaction.cs, src/NServiceBus.Msmq.AcceptanceTests/When_using_scope_timeout_greater_than_machine_max.cs, src/NServiceBus.Msmq.AcceptanceTests/packages.config
Attempt to update nunit to v3.
fixes #3723
=> [WIP] Nunit update

src/NServiceBus.Core.Tests/Persistence/InMemory/InMemoryOutboxPersisterTests.cs
=> Fix flaky Outbox storage unit test

src/NServiceBus.Core/Performance/Statistics/SLA/SLAMonitoring.cs
* `DataPoint` can be a struct since we are only saving `TimeSpan` and `DateTime` which are also structs to a list which saves us allocations
* Minimizes the number of enumerations on the collection
* Avoid unnecessary boxing by not using `IList`
The assumption was that we can save the 
```
//need at least 2 data points to be able to calculate
if (snapshots.Count < 2)
{
return double.MaxValue;
}
```
Since if there is nothing in the list then 
criticalTimeDelta = TimeSpan.Zero is used and then the 
if (criticalTimeDelta.TotalSeconds <= 0.0)
{
return double.MaxValue;
}
kicks in
if there is only one element in the list then there is no previous element set and therefore `criticalTimeDelta` is not incremented which means again the above if statement kicks in
When there are more than two …
=> Minimize enumerations and allocations in SLA breach calculations

src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_InMemory_and_an_escalated_DTC_transaction.cs, src/NServiceBus.Core/Persistence/InMemory/InMemoryTransactionalSynchronizedStorageAdapter.cs
=> In memory storage adapter cleanup

src/NServiceBus.AcceptanceTests/Mutators/When_incoming_mutator_changes_message_type.cs, src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga.cs, src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga_autosubscribe_disabled.cs, src/NServiceBus.AcceptanceTests/Sagas/When_a_finder_exists_and_found_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_started_by_base_event_from_other_saga.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Persistence/InMemory/SagaWithUniquePropertyData.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/SimpleSagaEntitySaga.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/TestSagaData.cs, src/NServiceBus.Core.Tests/Pipeline/Incoming/InvokeHandlerTerminatorTest.cs, src/NServiceBus.Core.Tests/Sagas/SagaMetadataCreationTests.cs, src/NServiceBus.Core.Tests/Sagas/SagaModelTests.cs, src/NServiceBus.Core/Sagas/SagaFinderDefinition.cs, src/NServiceBus.Core/Sagas/SagaMessage.cs, src/NServiceBus.Core/Sagas/SagaMetadata.cs
=> Throw when saga contains no mappings

src/NServiceBus.Core.Tests/Sagas/SagaModelTests.cs, src/NServiceBus.Core/Sagas/SagaMetadata.cs
=> Filter out abstract saga classes

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes.cs
fixes #3725
@Particular/nservicebus-maintainers @indualagarsamy ping
=> Improve obsolete message for SetMessageHeader

src/NServiceBus.Core/Routing/RoutingFeature.cs, src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj, src/NServiceBus.Msmq.AcceptanceTests/When_subscribing_with_address_containing_host_name.cs
Connects to https://github.com/Particular/PlatformDevelopment/issues/814
Fixes https://github.com/Particular/NServiceBus/issues/3799
=> Fixing problem with subscribing to host-qualified subscriber address.

src/NServiceBus.Core.Tests/Encryption/RijndaelEncryptionServiceTest.cs, src/NServiceBus.Core/Encryption/RijndaelEncryptionService.cs
=> Fix IV used in encryption unit test

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Routing/EndpointInstances.cs
This is a followup to #3804 to add a single instance Add overload.
=> Add single instance Add overload to EndpointInstances

src/NServiceBus.Core/Routing/RoutingFeature.cs
Reduces the number of ConfigureComponent invocations inside the routing feature to absolute minimum. Usage of ISubscriptionStorage and IDispatchMessages is a blocker for further removal.
=> Reduced DI footprint of the routing feature. 

src/NServiceBus.AcceptanceTests/UnicastPubSubExtensions.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenPubSubExtensions.cs, src/NServiceBus.Core/Routing/RoutingMappingSettings.cs, src/NServiceBus.Core/Routing/RoutingSettings.cs, src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs, src/NServiceBus.Core/Settings/SettingsHolder.cs
Since `GetOrCreate` was implemented at multiple places I thought we can add it on the `SettingsHolder` class anyway?
/cc @SzymonPobiega
=> Add GetOrCreate to SettingsHolder

src/NServiceBus.AcceptanceTests/FakeTransport/FakeTransportInfrastructure.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/UnitOfWork/TransactionScope/When_used_with_default_transaction_mode.cs, src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWork.cs
=> Scope UoW should handle default tx mode to be used

src/NServiceBus.AcceptanceTesting/Support/FailTestOnErrorMessageFeature.cs
There are two race-conditions in current error message tracking ATT:
* There can be messages being processed that did not fail yet but ATT check for failed messages before waiting for all messages to finish. This is fixed by behavior change
* ATT check if run was successful by first waiting on `UnfinishedFailedMessages` to have zero elements or zero counter for each element and than checking `FailedMessages` if it contains any elements. So was possible to meet first and second condition because `FailedMessages` where not updated yet. This is fixed in lines 47 and 48.
=> Fixing failed message tracking in ATT

src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs, src/NServiceBus.Core/Transports/Msmq/MsmqUtilities.cs, src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs
=> Use Length or Count instead of Count()

src/NServiceBus.Core/Serializers/XML/XmlDeserialization.cs, src/NServiceBus.Core/Serializers/XML/XmlSerializerCache.cs, src/NServiceBus.Core/Transports/Msmq/MsmqUtilities.cs
Replaces #3876
This replaces string concatenation with string interpolation. It does not address the issue of GC pressure because of strings! We can do this at a later time
=> Replace string concatenation with string interpolation

src/NServiceBus.Msmq.AcceptanceTests/When_TimeToBeReceived_set_and_native_receivetransaction.cs
Connects to https://github.com/Particular/NServiceBus/issues/3877
=> Temporarely disable When_TimeToBeReceived_set_and_native_receivetransaction

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Persistence/PersistenceExtensions.cs
=> Better obsoletes for storage type persistence extension

src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
=> Avoiding allocations with Task.ContinueWith by opting-in for delegate caching

src/NServiceBus.Core/Extensibility/ContextBag.cs
Is this OK or am I missing something subtle?
=> remove redundant conditional

src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
Connects to Particular/V6Launch#69
=> Transport tests stop message pump

src/NServiceBus.TransportTests/When_on_message_throws_after_delayed_retry.cs, src/NServiceBus.TransportTests/When_requesting_immediate_retry.cs, src/NServiceBus.TransportTests/When_sending_from_on_error.cs, src/NServiceBus.TransportTests/When_user_aborts_processing.cs
Connects to Particular/V6Launch#69
=> Fix async send in transport tests when sending during error handling

src/NServiceBus.AcceptanceTests/Routing/When_publishing_to_scaled_out_subscribers_on_unicast_transports.cs, src/NServiceBus.AcceptanceTests/UnicastPubSubExtensions.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensionsTests.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensions.cs, src/NServiceBus.Core/Routing/RoutingSettings.cs, src/NServiceBus.Msmq.AcceptanceTests/When_distributing_an_event.cs
Connects to https://github.com/Particular/V6Launch/issues/68
=> RegisterPublisherFor* methods replaced with simple RegisterPublisher

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes.cs
=> Fixed misleading obsolete for ISatellite

src/NServiceBus.Core.Tests/EndpointConfigurationTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/EndpointConfiguration.cs
fixes https://github.com/Particular/NServiceBus/issues/3906
Should we provide better exception messages here?
=> Check endpoint name for invalid @ characters

packaging/nuget/nservicebus.transporttests.nuspec, src/NServiceBus.TransportTests/ConfigureMsmqTransportInfrastructure.cs, src/NServiceBus.TransportTests/IConfigureTransportInfrastructure.cs, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj, src/NServiceBus.TransportTests/NServiceBusTransportTest.cs, src/NServiceBus.TransportTests/TransportConfigurationResult.cs, src/NServiceBus.TransportTests/When_on_error_throws.cs
Connects to https://github.com/Particular/V6Launch/issues/69
This PR includes changes requested by downstream maintainers when doing WIP PR for new recoverability. Those are necessary to enable proper configuration of transport infrastructure and deal with transports that do not support queue purging.
/cc: @danielmarbach
=> Transport Test changes after transport maintainers feedback

src/NServiceBus.Core/Transports/Msmq/ReceiveStrategy.cs
connects to https://github.com/Particular/V6Launch/issues/69
=> fixed typo: "reverability" -> "recoverability"

src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs
=> Removed unnecessary ToList and Any from LoadHandlersConnector

src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs
This came out while investigating into https://github.com/Particular/NServiceBus/issues/4000
=> Reduced DeserializeLogicalMessagesConnector to one last linq statement

src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/SubscriptionRouter.cs
Small refactoring to remove unnecessary LINQ calls.
@Particular/nservicebus-maintainers @SzymonPobiega please review
=> Remove LINQ in SubscriptionRouter

src/NServiceBus.Core.Tests/Routing/UnicastPublisherRouterTests.cs, src/NServiceBus.Core/Routing/RoutingFeature.cs, src/NServiceBus.Core/Routing/UnicastPublishRouter.cs
Removing unnecessary code.
@Particular/nservicebus-maintainers @SzymonPobiega please review
=> Refactor UnicastPublishRouter

src/NServiceBus.AcceptanceTests/Core/MessageDurability/When_sending_a_non_durable_message_with_conventions.cs, src/NServiceBus.AcceptanceTests/Core/MessageDurability/When_using_non_durable_messages_on_durable_only_transport.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core/Performance/MessageDurability/DetermineMessageDurabilityBehavior.cs, src/NServiceBus.Core/Performance/MessageDurability/MessageDurabilityFeature.cs
=> NonDurableMessages do not work with unobtrusive mode in v6

src/NServiceBus.Core.Tests/Pipeline/Incoming/SerializeMessageConnectorTests.cs, src/NServiceBus.Core.Tests/Serializers/MessageDeserializerResolverTests.cs, src/NServiceBus.Core/Serializers/MessageDeserializerResolver.cs
fixes #4031 
@Particular/nservicebus-maintainers @SimonCropp please review (especially the exception message).
=> Improve exception on ambiguous deserializers

src/NServiceBus.Core.Tests/Scheduler/DefaultSchedulerTests.cs, src/NServiceBus.Core.Tests/Scheduler/ScheduleTests.cs, src/NServiceBus.Core/Scheduling/DefaultScheduler.cs
While doing #4035 I split this change out
=> Made Scheduled tasks dictionary private

src/NServiceBus.AcceptanceTests/ApiExtension/When_extending_sendoptions.cs, src/NServiceBus.AcceptanceTests/ApiExtension/When_extending_the_publish_api.cs, src/NServiceBus.AcceptanceTests/Basic/When_extending_behavior_context.cs, src/NServiceBus.AcceptanceTests/MessageId/When_message_has_empty_id_header.cs, src/NServiceBus.AcceptanceTests/MessageId/When_message_has_no_id_header.cs, src/NServiceBus.AcceptanceTests/NonTx/When_sending_inside_ambient_tx.cs, src/NServiceBus.AcceptanceTests/Pipeline/When_replacing_behavior.cs, src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_a_message_is_audited.cs, src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_blowing_up_just_after_dispatch.cs, src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_dispatching_forwarded_messages.cs, src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga.cs, src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga_autosubscribe_disabled.cs, src/NServiceBus.AcceptanceTests/Routing/AutomaticSubscriptions/When_starting_an_endpoint_with_autoSubscribe.cs, src/NServiceBus.AcceptanceTests/Routing/When_publishing_an_interface.cs, src/NServiceBus.Core/Causation/MessageCausation.cs, src/NServiceBus.Core/Correlation/MessageCorrelation.cs, src/NServiceBus.Core/Hosting/HostInformationFeature.cs, src/NServiceBus.Core/Licensing/LicenseReminder.cs, src/NServiceBus.Core/Pipeline/Incoming/ReceiveFeature.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPipelineFeature.cs, src/NServiceBus.Core/Reliability/Outbox/Outbox.cs, src/NServiceBus.Core/Routing/Legacy/WorkerFeature.cs, src/NServiceBus.Core/Sagas/AutoCorrelationFeature.cs, src/NServiceBus.Core/Sagas/Sagas.cs, src/NServiceBus.Core/Scheduling/Scheduler.cs, src/NServiceBus.Core/StaticHeaders/StaticHeaders.cs, src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWork.cs, src/NServiceBus.Msmq.AcceptanceTests/When_receiving_control_message_with_body.cs
Closes https://github.com/Particular/NServiceBus/issues/4034
Paves the way to https://github.com/Particular/NServiceBus/issues/3844
=> Replaced usages of Pipeline.Register(string, type, string)

src/NServiceBus.AcceptanceTests/Serialization/When_registering_additional_deserializers.cs, src/NServiceBus.AcceptanceTests/Serialization/When_registering_custom_serializer.cs, src/NServiceBus.AcceptanceTests/Serialization/When_registering_deserializers_with_settings.cs
Based on the work in ASQ: https://github.com/Particular/NServiceBus.AzureStorageQueues/pull/127
=> Serialization tests used context classes instead of passing values in messages

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Routing/MessageEndpointMappingTests.cs, src/NServiceBus.Core.Tests/Routing/RoutingSettingsTests.cs, src/NServiceBus.Core/Routing/MessageEndpointMappingCollection.cs, src/NServiceBus.Core/Routing/RoutingFeature.cs
=> Fixed MessageEndpointMapping interpretation to honor the proper ordering

src/NServiceBus.AcceptanceTests/Core/Feature/When_feature_startup_task_fails.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/Features/FeatureStartupTests.cs
I added a test to verify the behavior @andreasohlund
=> Verify failing feature startup tasks stop endpoint startup

src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensions.cs, src/NServiceBus.Core/Routing/RoutingSettings.cs, src/NServiceBus.Core/Routing/UnicastRoutingTable.cs, src/NServiceBus.Msmq.AcceptanceTests/When_publishing_with_authorizer.cs
=> Minor changes to routing related api docs

src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPollerTests.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs
May address #4078 
@ramonsmits @Particular/nservicebus-maintainers
=> Pay more attention to cancellationToken around timeout polling and dispatch

src/NServiceBus.AcceptanceTests/Forwarding/When_forwarding_is_configured_for_endpoint.cs, src/NServiceBus.AcceptanceTests/Forwarding/When_requesting_message_to_be_forwarded.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
Me and @SzymonPobiega thought that headers where not preserved on forwarded messages but this change proves that they are
=> Verify that headers are preserved on forwarded messages

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/Serialization/When_xml_serializer_used_with_unobtrusive_mode.cs, src/NServiceBus.Core.Tests/Serializers/XML/SerializerFactory.cs, src/NServiceBus.Core.Tests/Serializers/XML/SerializerTests.cs, src/NServiceBus.Core/Serializers/XML/XmlDeserialization.cs
Closes https://github.com/Particular/NServiceBus/issues/3975
=> XmlSerializer with unobtrusive messages should propagate properties of message

src/NServiceBus.Core.Tests/Routing/MessageEndpointMappingTests.cs, src/NServiceBus.Core/Routing/MessageEndpointMappingCollection.cs, src/NServiceBus.Core/Routing/RoutingFeature.cs
Relates to https://github.com/Particular/NServiceBus/pull/4084
Addresses https://github.com/Particular/NServiceBus/pull/4084#discussion_r76755596
@SzymonPobiega @Particular/nservicebus-maintainers thoughts?
=> Not relying on GetAvailableTypes for message endpoint mapping

src/NServiceBus.Core.Tests/Unicast/MessagingBestPracticesTests.cs, src/NServiceBus.Core/Routing/MessagingBestPractices/Validations.cs
Closes https://github.com/Particular/NServiceBus/issues/4083
=> Fixing mentioning of bus in best practices validation

src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_subscribing_to_multiple_publishers.cs
=> Fixing When_subscribing_to_multiple_publishers test

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes.cs
=> Add missing node property

src/NServiceBus.Core/Recoverability/RecoverabilityExecutor.cs
=> Fix spelling error in log statement

src/NServiceBus.Core.Tests/Msmq/MsmqSubscriptionStorageQueueTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Persistence/InMemory/InMemorySubscriptionStorageTests.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageType.cs
Fixes  https://github.com/Particular/NServiceBus/issues/1394
=> Remove subscription versioning

src/NServiceBus.Core/Persistence/PersistenceExtensions.cs, src/NServiceBus.Core/Unicast/Transport/Config/TransportExtensions.cs
Copy-paste errors in the summaries.
=> Cleaned up summary of PersistenceExtensions and TransportExtensions

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Recoverability/Settings/RecoverabilitySettings.cs
=> Remove ObsoleteEx attribute from DisableLegacyRetriesSatellite

src/NServiceBus.Core/Performance/Statistics/ProcessingStatisticsBehavior.cs
=> Make processing statistics not vulnerable to server time changes

src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs, src/NServiceBus.Core.Tests/AssemblyScanner/When_directory_with_handler_dll_is_scanned.cs, src/NServiceBus.Core.Tests/AssemblyScanner/When_directory_with_no_reference_dlls_is_scanned.cs, src/NServiceBus.Core.Tests/AssemblyScanner/When_directory_with_non_dot_net_dll_is_scanned.cs, src/NServiceBus.Core.Tests/AssemblyScanner/When_scanning_for_dlls_only.cs, src/NServiceBus.Core.Tests/AssemblyScanner/When_told_to_scan_app_domain.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
I had a longer conversation with myself and we agreed to revert the PR and have a closer look at the problem based on @bording comments. 
Reverts Particular/NServiceBus#4243
=> Revert "Assembly scanning cleanup & improvements"

CONTRIBUTING.md
@Particular/nservicebus-maintainers as discussed in today's call here is the proposed change
=> Allocations

src/NServiceBus.Core/Licensing/LicenseManager.cs
=> Using http client one time only, replaced async void with task returning and ignore

src/NServiceBus.Core.Tests/Persistence/InMemory/When_multiple_workers_retrieve_same_saga.cs
Updated some tests for InMemorySagaPersister to:
- use the configured correlation property when retrieving sagas by correlation value
- use `Update` instead of `Save` when modifying or re-saving an existing saga
=> Fix InMemorySagaPersister tests

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Scheduling/Messages/ScheduledTask.cs, src/NServiceBus.Core/Scheduling/ScheduleExtensions.cs
=> make ScheduledTask public

src/NServiceBus.Core/Performance/Counters/PerformanceCounterHelper.cs
=> Fixed bad missing performance counters error message

src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
Let's try a simple approach first, as discussed with @timbussmann.
=> Increase When timeout to 60s

src/NServiceBus.Core/Unicast/Transport/Config/OutboundTransport.cs, src/NServiceBus.Core/Unicast/Transport/Config/UseTransportExtensions.cs
=> Remove IsDefaultFlag from outbound transport

src/NServiceBus.AcceptanceTests/Routing/When_overriding_local_address.cs
Closes https://github.com/Particular/NServiceBus/issues/4321
// cc @SimonCropp
=> Moves When_overriding_local_address into correct namespace

src/NServiceBus.Core/Recoverability/Faults/ErrorQueueSettings.cs
"Take one" instead of "take on"
=> spelling fix

src/NServiceBus.AcceptanceTests/Sagas/when_receiving_multiple_timeouts.cs
When_receiving_multiple_timeouts
=> correct mapping on When_receiving_multiple_timeouts

src/NServiceBus.AcceptanceTests/Satellites/When_satellite_txmode_does_not_match_endpoints_txmode.cs
Should fix the breaking build
@Particular/nservicebus-maintainers please review asap
=> Fix exception assert in When_satellite_txmode_does_not_match_endpoints_txmode

src/NServiceBus.AcceptanceTests/Sagas/When_saga_message_goes_through_delayed_retries.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Persistence/InMemory/AnotherSagaWithUniquePropertyData.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/SagaWithUniquePropertyData.cs, src/NServiceBus.Core.Tests/Persistence/InMemory/SagaWithoutUniquePropertyData.cs, src/NServiceBus.Core.Tests/Sagas/SagaMetadataCreationTests.cs, src/NServiceBus.Core.Tests/Serializers/XML/FirstSerializableMessage.cs, src/NServiceBus.Core.Tests/Serializers/XML/IFirstSerializableMessage.cs, src/NServiceBus.Core.Tests/Serializers/XML/ISecondSerializableMessage.cs, src/NServiceBus.Core.Tests/Serializers/XML/SecondSerializableMessage.cs, src/NServiceBus.Core.Tests/Serializers/XML/SerializerTests.cs, src/NServiceBus.Core.Tests/Serializers/XML/Using_Infer_Type_With_Mixed_Namespace.cs, src/NServiceBus.Core.Tests/Serializers/XML/Using_Infer_Type_With_Non_Nested_Class.cs
Cleanup poorly named helper classes like 'M1'
=> Rename testing helper classes

src/NServiceBus.AcceptanceTests/ConventionEnforcementTests.cs, src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_clearing_saga_timeouts.cs, src/NServiceBus.AcceptanceTests/Sagas/When_adding_state_to_context.cs, src/NServiceBus.AcceptanceTests/Sagas/When_saga_started_concurrently.cs
since some downstream persistences need public saga datas to be able to
serialize
=> make saga datas public

src/NServiceBus.Core.Tests/Msmq/MsmqSubscriptionStorageIntegrationTests.cs, src/NServiceBus.Core.Tests/Msmq/MsmqSubscriptionStorageTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionPersistence.cs, src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorageQueue.cs, src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs, src/NServiceBus.Core/Transports/Msmq/MsmqTransportInfrastructure.cs, src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj, src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_subscription_exists_for_non_tx_endpoint.cs, src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_subscription_exists_for_tx_endpoint.cs, src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_using_subscription_store.cs, src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_using_subscription_store_on_non_tx_endpoint.cs, src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_using_subscription_store_on_tx_endpoint.cs
Forward port of 6.0.2 into develop
=> Hotfix 6.0.2

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs, src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs, src/NServiceBus.AcceptanceTesting/Support/TaskExtensions.cs
=> Acceptance tests start and stop improvements

src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeReceiver.cs, src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportInfrastructure.cs, src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportSetingsExtensions.cs, src/NServiceBus.AcceptanceTests/Core/Stopping/When_feature_startup_task_throws_on_stop.cs, src/NServiceBus.AcceptanceTests/Core/Stopping/When_pump_throws_on_stop.cs, src/NServiceBus.AcceptanceTests/Core/Stopping/When_transport_infrastructure_throws_on_stop.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/Features/FeatureStartupTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Transports/TransportReceiverTests.cs, src/NServiceBus.Core/Features/FeatureStartupTaskController.cs, src/NServiceBus.Core/Transports/TransportReceiver.cs, src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs
=> Clean Endpoint shutdown

src/NServiceBus.AcceptanceTests/Serialization/When_serializing_a_message.cs
This fixes When_serializing_a_message assertions
=> Fixing assertions for When_serializing_a_message

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/App_Packages/PublicApiGenerator.6.0.0/ApiGenerator.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/packages.config
Based upon #4273 
Needs a merge of https://github.com/JakeGinnivan/ApiApprover/pull/26 first
=> Api approval async methods

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
Noticed that this test is not included in the project but checked into git. I assume this is some kind of mistake/merging issue.
@danielmarbach since you added those tests, can you have a quick look and merge?
=> Add test to project file

src/NServiceBus.Core.Tests/Timeout/InMemoryTimeoutPersisterTests.cs
=> Switching DateTime.Now to DateTime.UtcNow

src/NServiceBus.Core/StartableEndpoint.cs, src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
Addresses #4410 
Added WARN level logging when a queue is purged that reads:
> The {QueueName} queue was purged.
=> Added logging when PurgeOnStartup is performed

src/NServiceBus.TransportTests/When_scope_dispose_throws.cs
@bording @dbelcham this repros the issue. Should we make this a separate test instead?
Should we have similar tests for the other txmodes?
=> Repro issue with infinite loop if enlistment throws

src/NServiceBus.TransportTests/When_transaction_level_TransactionScope.cs
Add TestCase to test that had hard coded transaction scope
=> Add TestCase to transport test

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTesting/Support/ActiveRunner.cs, src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
stumbled upon this ActiveRunner class in AcceptanceTesting and couldn't figure out what it was good for.
=> Remove ActiveRunner class from AcceptanceTesting

src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
=> Dsable ATT test timeouts when debugger is attached

src/NServiceBus.AcceptanceTests/Core/Outbox/When_dispatching_transport_operations.cs, src/NServiceBus.AcceptanceTests/Core/Outbox/When_outbox_double_optin_found.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Reliability/Outbox/Outbox.cs, src/NServiceBus.Core/Transports/Msmq/MsmqTransportInfrastructure.cs, src/NServiceBus.Core/Transports/TransportInfrastructure.cs, src/NServiceBus.Core/obsoletes.cs
=> Double opt-in for outbox is no longer needed

src/NServiceBus.Core.Tests/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPollerTests.cs, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/ExpiredTimeoutsPoller.cs
fixes https://github.com/Particular/NServiceBus/issues/4436 in develop
=> Adjust start slice after successful dispatch

src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_config.cs, src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_custom.cs, src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_multikey.cs, src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_unobtrusive_mode.cs, src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_without_incoming_key_identifier.cs, src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_encryption_with_custom_service.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
So they won't be shared with downstreams using the att source package.
relates to https://github.com/Particular/NServiceBus/issues/4457
ping @danielmarbach
=> Move encryption acceptance tests to core tests

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Msmq/MsmqMessageDispatcherTests.cs, src/NServiceBus.Core/Transports/Msmq/MsmqConfigurationExtensions.cs, src/NServiceBus.Core/Transports/Msmq/MsmqMessageDispatcher.cs, src/NServiceBus.Core/Transports/Msmq/MsmqSettings.cs, src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs, src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj, src/NServiceBus.Msmq.AcceptanceTests/When_requesting_dlq_for_ttbr_messages.cs, src/NServiceBus.Msmq.AcceptanceTests/When_sending_message_with_ttbr.cs
=> Default DLQ off for MSMQ messages with TTBR set

releasing.md
=> Create releasing document

src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehaviorTests.cs, src/NServiceBus.Core.Tests/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehaviorTests.cs, src/NServiceBus.Core.Tests/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageBehaviorTests.cs, src/NServiceBus.Core.Tests/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageBehaviorTests.cs, src/NServiceBus.Core.Tests/UnitOfWork/UnitOfWorkBehaviorTests.cs, src/NServiceBus.Core/Pipeline/Incoming/ReceiveFeature.cs, src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateIncomingMessageBehavior.cs, src/NServiceBus.Core/Pipeline/MutateInstanceMessage/MutateOutgoingMessageBehavior.cs, src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateIncomingTransportMessageBehavior.cs, src/NServiceBus.Core/Pipeline/MutateTransportMessage/MutateOutgoingTransportMessageBehavior.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPipelineFeature.cs, src/NServiceBus.Core/UnitOfWork/UnitOfWorkBehavior.cs, src/NServiceBus.Testing.Fakes/FakeBuilder.cs
Backports https://github.com/Particular/NServiceBus/pull/4466 to release 6.1 to address https://github.com/Particular/NServiceBus/issues/4463
ping @Particular/nservicebus-maintainers 
anything added in 6.2 which could be an issue for this cherry pick?
=> Hotfix 6.1.3

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Recoverability/Settings/RecoverabilitySettings.cs
I would like there to be a generic overload for the business user that gets the benefit of a generic type constraint
=> add generic overload for AddUnrecoverableException

src/NServiceBus.AcceptanceTests/ApiExtension/When_extending_the_publish_api.cs, src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_multikey.cs, src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_without_incoming_key_identifier.cs, src/NServiceBus.AcceptanceTests/Core/FakeTransport/CriticalError/When_registering_custom_critical_error_handler.cs, src/NServiceBus.AcceptanceTests/PerfMon/CriticalTime/When_CriticalTime_enabled.cs, src/NServiceBus.AcceptanceTests/PerfMon/CriticalTime/When_deferring_a_message.cs, src/NServiceBus.AcceptanceTests/PerfMon/CriticalTime/When_slow_with_CriticalTime_enabled.cs, src/NServiceBus.AcceptanceTests/PerfMon/SLA/When_sending_slow_with_SLA_enabled.cs, src/NServiceBus.AcceptanceTests/PerfMon/SLA/When_sending_with_SLA_enabled.cs, src/NServiceBus.AcceptanceTests/Recoverability/Retries/When_immediate_retries_with_default_settings.cs, src/NServiceBus.AcceptanceTests/Recoverability/Retries/when_immediate_retries_fail.cs, src/NServiceBus.AcceptanceTests/Routing/When_publishing.cs, src/NServiceBus.AcceptanceTests/Routing/When_publishing_using_root_type.cs, src/NServiceBus.AcceptanceTests/Routing/When_publishing_with_overridden_local_address.cs, src/NServiceBus.AcceptanceTests/Sagas/When_receiving_that_completes_the_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_receiving_that_should_start_a_saga_with_interception.cs, src/NServiceBus.AcceptanceTests/Sagas/When_receiving_that_should_start_a_saga_without_interception.cs, src/NServiceBus.AcceptanceTests/Sagas/When_replies_to_message_published_by_a_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_saga_message_goes_through_delayed_retries.cs, src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_handle.cs, src/NServiceBus.AcceptanceTests/Sagas/When_sending_from_a_saga_timeout.cs, src/NServiceBus.AcceptanceTests/Sagas/When_started_by_base_event_from_other_saga.cs, src/NServiceBus.AcceptanceTests/Sagas/When_started_by_event_from_another_saga.cs, src/NServiceBus.AcceptanceTests/Scheduling/When_scheduling_a_recurring_task.cs
Another small step towards removing `Repeat`.
=> Remove Transports.Default repeat configurations in att

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Msmq/MsmqMessageDispatcherTests.cs, src/NServiceBus.Core/Transports/Msmq/MsmqConfigurationExtensions.cs, src/NServiceBus.Core/Transports/Msmq/MsmqMessageDispatcher.cs, src/NServiceBus.Core/Transports/Msmq/MsmqSettings.cs, src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs, src/NServiceBus.Msmq.AcceptanceTests/When_requesting_dlq_for_ttbr_messages.cs
See https://github.com/Particular/docs.particular.net/pull/2437#discussion_r101884863 for the reasoning
=> Better name for the DLQ override

src/NServiceBus.Core/Routing/UnicastPublishRouter.cs
Stumbled over the UnicastPublishRouter over the weekend and did a mental exercise to see if I could refactor it. The outcome is a slightly more complex code which seems to have less memory footprint and is overall much faster. Would we want this despite the complexity?
Scenarios used for benchmarking
https://github.com/danielmarbach/MicroBenchmarks/blob/master/MicroBenchmarks/NServiceBus/UnicastPublishRouter.cs#L26
``` ini
BenchmarkDotNet=v0.10.1, OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Core(TM) i7-4980HQ CPU 2.80GHz, ProcessorCount=8
Frequency=2728067 Hz, Resolution=366.5599 ns, Timer=TSC
[Host]     : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1586.0
DefaultJob : Clr 4.0.30319.42000, 32bit LegacyJIT-v4.6.1586.0
```
Method |                                    Scenario | …
=> UnicastPublishRouter no longer uses LINQ in SelectDestinationsForEachEndpoint

src/NServiceBus.AcceptanceTesting/Support/ScenarioConfigSource.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/DetectObsoleteConfigurationSettings.cs, src/NServiceBus.Core/Logging/Logging.cs
relates to https://github.com/Particular/PlatformDevelopment/issues/1153
cc @WilliamBZA
=> Warn about logging config section removal.

src/NServiceBus.AcceptanceTesting/Support/ScenarioConfigSource.cs, src/NServiceBus.AcceptanceTests/Config/When_only_abstract_config_override_is_found.cs, src/NServiceBus.AcceptanceTests/EndpointTemplates/DefaultServer.cs, src/NServiceBus.AcceptanceTests/EndpointTemplates/ServerWithNoDefaultPersistenceDefinitions.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/DetectObsoleteConfigurationSettings.cs, src/NServiceBus.Core/Recoverability/Faults/MessageForwardingInCaseOfFaultConfig.cs
relates to https://github.com/Particular/PlatformDevelopment/issues/1153
cc @WilliamBZA @timbussmann
=> Obsolete with WARN MessageForwardingInCaseOfFaultConfig

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Routing/DistributionContext.cs
Aligning context with what has been proposed by @andreasohlund in #4468
=> DistributionContext implements IExtendable

src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_using_external_timeout_manager_xml_config.cs, src/NServiceBus.AcceptanceTests/Core/Encryption/When_using_Rijndael_with_custom.cs, src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_subscribing_to_a_base_event_with_a_route_for_a_derived_event.cs, src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_subscribing_to_event_with_routes_to_base_and_specific_events.cs, src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_using_assembly_level_message_mapping_for_pub_sub.cs, src/NServiceBus.AcceptanceTests/Routing/When_sending_a_base_command.cs, src/NServiceBus.AcceptanceTests/Routing/When_sending_non_message_with_routing_configured_via_mappings.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Audit/AuditConfig.cs, src/NServiceBus.Core/DetectObsoleteConfigurationSettings.cs, src/NServiceBus.Core/Unicast/UnicastBusConfig.cs
based on top of https://github.com/Particular/NServiceBus/pull/4529
=> Obsolete MessageEndpointMappings

src/NServiceBus.Core/DataBus/DataBusProperty.cs
fixes https://github.com/Particular/NServiceBus/issues/4547
=> Fix DataBusProperty.HasValue behavior

src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerConfiguration.cs
@SimonCropp this is targeting your PR, so feel free to merge this if you want.
=> Remove default value

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerConfiguration.cs, src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerConfigurationExtensions.cs
=> make AssemblyScannerConfigurationExtensions return a config instance

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Performance/ReceiveStatisticsPerformanceCounters.cs, src/NServiceBus.Core/Performance/Statistics/CriticalTime/CriticalTimeMonitoring.cs, src/NServiceBus.Core/Performance/Statistics/CriticalTime/CriticalTimeMonitoringConfig.cs, src/NServiceBus.Core/Performance/Statistics/SLA/SLAMonitoring.cs, src/NServiceBus.Core/Performance/Statistics/SLA/SLAMonitoringConfig.cs
The name of the performance counters repo will be changing shortly. Marking this as WIP as the final namespace is still under discussion.
=> Update obsolete message for perf counters to reflect new namespace

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs, src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs, src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPublishContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingReplyContext.cs, src/NServiceBus.Core/Routing/SubscribeContext.cs, src/NServiceBus.Core/Routing/UnsubscribeContext.cs
See https://github.com/Particular/NServiceBus/issues/4573
=> Hotfix 6.1.4

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs, src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs, src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPublishContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingReplyContext.cs, src/NServiceBus.Core/Routing/SubscribeContext.cs, src/NServiceBus.Core/Routing/UnsubscribeContext.cs
See https://github.com/Particular/NServiceBus/issues/4573
=> Hotfix 6.0.7

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Extensibility/ContextBag.cs
see https://github.com/Particular/NServiceBus/pull/4578#discussion_r108341226
=> Rename ContextBag ctor param back to original name

src/NServiceBus.Core/Properties/AssemblyInfo.cs
This is needed to pick up the release date change.
=> Merge release-6.2 into develop again

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTesting/packages.config, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/packages.config, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.ContainerTests/packages.config, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/packages.config, src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj, src/NServiceBus.Testing.Fakes/packages.config, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj, src/NServiceBus.TransportTests/packages.config
Update to latest NugetPackager and GitVersionTask.
=> Update development dependencies

src/NServiceBus.Core/Serializers/XML/XmlDeserialization.cs
Making it super confusing to look at
=> Condition and code was inverted

.gitattributes
see https://github.com/Particular/RepoStandards/pull/6
cc @bording
=> Update .gitattributes from repo standards

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_reusing_sendoptions.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/Pipeline/HeaderOptionExtensionsTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs, src/NServiceBus.Core.Tests/Routing/RoutingToDispatchConnectorTests.cs, src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs, src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs, src/NServiceBus.Core.Tests/Unicast/MessageOperationsTests.cs, src/NServiceBus.Core/Extensibility/ExtendableOptions.cs, src/NServiceBus.Core/Pipeline/Outgoing/MessageIdExtensions.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPublishContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingReplyContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingSendContext.cs, src/NServiceBus.Core/Routing/SubscribeContext.cs, src/NServiceBus.Core/Routing/UnsubscribeContext.cs, src/NServiceBus.Core/Unicast/MessageOperations.cs
relates to https://github.com/Particular/PlatformDevelopment/issues/1224
=> Hotfix 6.2.1

src/NServiceBus.Core.Tests/Msmq/MsmqExtensionsTests.cs, src/NServiceBus.Core.Tests/Msmq/MsmqQueueCreatorTests.cs, src/NServiceBus.Core.Tests/Msmq/QueuePermissionsTests.cs, src/NServiceBus.Core/Transports/Msmq/QueuePermissions.cs, src/NServiceBus.Core/Utils/MessageQueueExtensions.cs, src/NServiceBus.Msmq.AcceptanceTests/When_starting_up_the_endpoint.cs
Fixes: https://github.com/Particular/NServiceBus/issues/4526
Also fixes #4610
=> Warn for queue permissions for everyone and anonymous only if access rights are set to allow

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_reusing_sendoptions.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/Pipeline/HeaderOptionExtensionsTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs, src/NServiceBus.Core.Tests/Routing/RoutingToDispatchConnectorTests.cs, src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs, src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs, src/NServiceBus.Core.Tests/Unicast/MessageOperationsTests.cs, src/NServiceBus.Core/Extensibility/ExtendableOptions.cs, src/NServiceBus.Core/Pipeline/Outgoing/MessageIdExtensions.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPublishContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingReplyContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingSendContext.cs, src/NServiceBus.Core/Routing/SubscribeContext.cs, src/NServiceBus.Core/Routing/UnsubscribeContext.cs, src/NServiceBus.Core/Unicast/MessageOperations.cs
relates to https://github.com/Particular/NServiceBus/issues/4613
=> MessageID is reused when reusing SendOptions

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_reusing_sendoptions.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/Pipeline/HeaderOptionExtensionsTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs, src/NServiceBus.Core.Tests/Routing/RoutingToDispatchConnectorTests.cs, src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs, src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs, src/NServiceBus.Core.Tests/Unicast/MessageOperationsTests.cs, src/NServiceBus.Core/Extensibility/ExtendableOptions.cs, src/NServiceBus.Core/Pipeline/Outgoing/MessageIdExtensions.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPublishContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingReplyContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingSendContext.cs, src/NServiceBus.Core/Routing/SubscribeContext.cs, src/NServiceBus.Core/Routing/UnsubscribeContext.cs, src/NServiceBus.Core/Unicast/MessageOperations.cs
relates to https://github.com/Particular/NServiceBus/issues/4613
=> do not generate message id when creating options

src/NServiceBus.Core/Serializers/XML/XmlDeserialization.cs
relates to https://github.com/Particular/NServiceBus/issues/4620
not sure whether this can ever be null tbh, but it makes more sense anyway
=> Reorder checks to check against null first

src/NServiceBus.AcceptanceTesting/Customization/EndpointConfigurationExtensions.cs, src/NServiceBus.Msmq.AcceptanceTests/DefaultServer.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_replying_to_message_sent_from_worker.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_worker_processes_a_message.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_worker_sends_a_message_to_the_error_queue.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_worker_sends_delayed_message.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_worker_sends_to_local_endpoint.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_worker_uses_delayed_retries.cs, src/NServiceBus.Msmq.AcceptanceTests/EndpointCustomizationConfigurationExtensions.cs, src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj, src/NServiceBus.Msmq.AcceptanceTests/NServiceBusAcceptanceTest.cs, src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_subscription_exists_for_non_tx_endpoint.cs, src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_subscription_exists_for_tx_endpoint.cs, src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_using_subscription_store.cs, src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_using_subscription_store_on_non_tx_endpoint.cs, src/NServiceBus.Msmq.AcceptanceTests/SubscriptionStorage/When_using_subscription_store_on_tx_endpoint.cs, src/NServiceBus.Msmq.AcceptanceTests/When_publishing_with_authorizer.cs, src/NServiceBus.Msmq.AcceptanceTests/When_subscribing_from_a_worker.cs, src/NServiceBus.Msmq.AcceptanceTests/When_subscribing_with_address_containing_host_name.cs, src/NServiceBus.Msmq.AcceptanceTests/When_unsubscribing_with_authorizer.cs
Decouples the msmq acceptance tests from the acceptance tests project.
ping @andreasohlund
=> Decouple MSMQ tests from AcceptanceTests project

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Config/When_no_custom_configuration_source_is_specified.cs, src/NServiceBus.Core.Tests/Config/When_users_override_the_configuration_source.cs, src/NServiceBus.Core/Recoverability/Faults/ConfigureError.cs, src/NServiceBus.Core/Recoverability/Faults/ErrorQueueSettings.cs, src/NServiceBus.Core/Recoverability/Recoverability.cs, src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs, src/NServiceBus.Msmq.AcceptanceTests/BasicServer.cs, src/NServiceBus.Msmq.AcceptanceTests/DefaultServer.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/DefaultDistributor.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_replying_to_message_sent_from_worker.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_worker_processes_a_message.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_worker_sends_a_message_to_the_error_queue.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_worker_sends_delayed_message.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_worker_sends_to_local_endpoint.cs, src/NServiceBus.Msmq.AcceptanceTests/Distributor/When_worker_uses_delayed_retries.cs, src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj, src/NServiceBus.Msmq.AcceptanceTests/When_no_explicit_error_queue_is_configured.cs, src/NServiceBus.TransportTests/ConfigureMsmqTransportInfrastructure.cs
But have msmq require an explicitly configured value
Closes https://github.com/Particular/NServiceBus/issues/3647
=> Default error queue name to "error"

src/NServiceBus.AcceptanceTests/Core/Recoverability/When_Subscribing_to_errors.cs, src/NServiceBus.AcceptanceTests/Core/Recoverability/When_message_is_moved_to_error_queue_with_header_customizations.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_a_duplicate_message_arrives.cs, src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_a_message_is_audited.cs
Small one this time. Moved a few tests to be Core only. Tweaked a couple of test names and verified some assertions
=> Acceptance test refactoring

src/NServiceBus.AcceptanceTests/Recoverability/When_transactions_off.cs
When_transactions_off.Should_not_do_any_retries should be an && condition
=> Fix att done condition check

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Transports/Learning/HeaderSerializerTests.Can_round_trip_headers.approved.txt, src/NServiceBus.Core.Tests/Transports/Learning/HeaderSerializerTests.cs, src/NServiceBus.Core/Transports/Learning/HeaderSerializer.cs
=> pretty print learning transport headers

src/NServiceBus.Core/Transports/Learning/LearningTransportDispatcher.cs
Makes it easier to document and easier to debug for people using it
=> Learning Transport: distinguish between message body and message metadata txt files

src/NServiceBus.AcceptanceTests/ConfigureEndpointLearningTransport.cs
We're now cleaning up after the test runs
=> Cleanup of the att tests

src/NServiceBus.Core/Features/FeatureStartupTask.cs
fixes https://github.com/Particular/NServiceBus/issues/4657
=> Fix FeatureStartupTask documentation

src/NServiceBus.Core/Transports/Learning/LearningTransportSubscriptionManager.cs
Seems like just a Yield  5 times was not enough
=> Use a delay for the learning transport submanager retries

src/NServiceBus.AcceptanceTests/Reliability/Outbox/When_blowing_up_just_after_dispatch.cs
@dbelcham and I noticed this test during our review and something was fishy as the PlaceOrder message should have gone to the error queue and fail the test as we don't have retries enabled, but it didn't and the test was green.
turns out, that the SimulatedException was never thrown because of this part: https://github.com/Particular/NServiceBus/compare/fix-outbox-att?expand=1#diff-43c731311ef2f2fbbbffccf08a00be2dL49 which seems to be an incorrect `!`. Also, this stage is never called for the `PlaceOrder` command, so the check isn't necessary at all.
Also the `called` flag is not necessary as the expected behavior is, that `PlaceOrder` fails but the outgoing messages are still dispatched because of the immediate-dispatch nature of outgoing messages when using the outbox.
cc @dbelcham
=> Fix outbox acceptance test

src/NServiceBus.Core/DetectObsoleteConfigurationSettings.cs
Connects to #4508 
Changes the logging level for TimeToBeReceivedOnForwardedMessages to Error for more visibility
=> Update logging entry for TimeToBeReceivedOnForwardedMessages

src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
Repro for https://github.com/Particular/NServiceBus/issues/4634
=> Reproduce scanner issue where messages can't be detected during scanning

MAINTAINERS.md
Update the Review Guidelines to reflect our policy on merging PRs
=> Update PR merge policy

src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs
=> Make learning transport disable legacy retries

src/NServiceBus.Core/Transports/Learning/DelayedMessagePoller.cs, src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs, src/NServiceBus.Core/Transports/Learning/LearningTransportDispatcher.cs, src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs, src/NServiceBus.Core/Transports/Learning/NoTransaction.cs
and also create the dirs at startup.
Note: Switched to using the same pending dir for both transaction types
cc @SimonCropp
=> Centralize directory creation

src/NServiceBus.Core/StartableEndpoint.cs
The DetectObsoleteConfigurationSettings feature throws on any use of TransportConfig long before this code has a chance to run.
=> Remove unreachable code from StartableEndpoint.

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_reusing_sendoptions.cs
Fixes https://builds.particular.net/viewLog.html?buildId=216671&buildTypeId=NServiceBusCore_Build
=> Switch to queue to avoid races in test

src/NServiceBus.Core/Routing/Routers/UnicastPublishRouterConnector.cs, src/NServiceBus.Core/Routing/Routers/UnicastSendRouterConnector.cs
=> Remove MEM from routing exception messages

src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
Since we don't need the robustness and its better to surface issues
immediately.
@danielmarbach is it ok to throw out of the continuation like done here?
=> Remove circuit breaker from learning transports

src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga.cs, src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga_autosubscribe_disabled.cs, src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_starting_an_endpoint_with_autosubscribe.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_publishing_from_sendonly.cs, src/NServiceBus.AcceptanceTests/Routing/NativePublishSubscribe/When_publishing_from_sendonly.cs, src/NServiceBus.AcceptanceTests/Routing/NativePublishSubscribe/When_subscribing_to_a_base_event.cs, src/NServiceBus.AcceptanceTests/Routing/NativePublishSubscribe/When_subscribing_to_a_derived_event.cs
Not many changes to tests, one moved to core only, and the copying of some tests from Message Driven Pub/Sub to Native Pub/Sub
=> Acceptance refactoring

src/NServiceBus.AcceptanceTests/Sagas/When_saga_started_concurrently.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/Persistence/Learning/LearningSynchronizedStorageSession.cs, src/NServiceBus.Core/Persistence/Learning/SagaPersister/CompleteAction.cs, src/NServiceBus.Core/Persistence/Learning/SagaPersister/LearningSagaPersistence.cs, src/NServiceBus.Core/Persistence/Learning/SagaPersister/LearningSagaPersister.cs, src/NServiceBus.Core/Persistence/Learning/SagaPersister/LearningSagaPersisterConcurrencyException.cs, src/NServiceBus.Core/Persistence/Learning/SagaPersister/SagaStorageFile.cs, src/NServiceBus.Core/Persistence/Learning/SagaPersister/SaveAction.cs, src/NServiceBus.Core/Persistence/Learning/SagaPersister/StorageAction.cs, src/NServiceBus.Core/Persistence/Learning/SagaPersister/UpdateAction.cs
Saga files seems to corrupt due to concurrency, this fixes it
https://builds.particular.net/viewLog.html?buildId=216634&tab=buildResultsDiv&buildTypeId=NServiceBusCore_Build
=> Lock saga file to avoid corruption

src/NServiceBus.AcceptanceTests/ConfigureEndpointLearningTransport.cs, src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs, src/NServiceBus.TransportTests/NServiceBusTransportTest.cs, src/NServiceBus.TransportTests/TransportConfigurationResult.cs
WIP until we get alignment if we should do this.
Closes #4711
=> Run learning transport with concurrency 1 by default

src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs, src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs, src/NServiceBus.Core/Transports/Learning/NoTransaction.cs
And also make sure to release the concurrency limiter during failures
=> Handle file locked issues

src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs, src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
Closes https://github.com/Particular/NServiceBus/issues/4724
=> Learning transport dispatch can fail to dispatch multiple messages

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/Outbox/When_headers_contain_special_characters.cs
https://github.com/Particular/PlatformDevelopment/issues/1256
=> test unicode chars in headers for outbox

src/NServiceBus.AcceptanceTests/DelayedDelivery/When_using_special_characters_in_headers.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/Recoverability/When_using_special_characters_in_headers.cs
One test for using delayed retries and one for delayed sends.
ping @weralabaj
=> Add acceptance tests to verify special character handling in timeout storages

src/NServiceBus.Core.Tests/MessageMapper/MessageMapperTests.cs, src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/MessageMapper.cs, src/NServiceBus.Core/Serialization/SerializationFeature.cs
fixes https://github.com/Particular/NServiceBus/issues/4750
=> MessageMapper does not call default constructor

src/NServiceBus.Core.Tests/MessageMapper/MessageMapperTests.cs, src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/MessageMapper.cs, src/NServiceBus.Core/Serialization/SerializationFeature.cs
merges hotfix 6.3.2 into develop
=> Hotfix 6.3.2

src/NServiceBus.Core.Tests/MessageMapper/MessageMapperTests.cs, src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/MessageMapper.cs, src/NServiceBus.Core/Serialization/SerializationFeature.cs
Since I screwed up the 6.3.2 hotfix mergeback with a squash instead of a merge
=> Merge master back into develop

src/NServiceBus.AcceptanceTesting/Customization/EndpointConfigurationExtensions.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Audit/AuditConfigReaderTests.cs, src/NServiceBus.Core/Audit/AuditConfigReader.cs, src/NServiceBus.Core/Audit/ConfigureAudit.cs
Since the external msmq transport needs it
=> Expose audit expiration setting

src/NServiceBus.Core/Transports/Msmq/MsmqDequeueStrategy.cs
Connects to https://github.com/Particular/NServiceBus/issues/4792
=> Poison message in MSMQ fails to be sent to remote error queue and is retried indefinitely

src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs, src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj, src/NServiceBus.Msmq.AcceptanceTests/When_no_explicit_error_queue_configured_for_sendonly_endpoint.cs
=> MSMQ requires error queue configuration for send-only endpoints

src/NServiceBus.AcceptanceTests/AssemblyInfo.cs, src/NServiceBus.AcceptanceTests/ConfigureEndpointLearningPersistence.cs, src/NServiceBus.AcceptanceTests/ConfigureEndpointLearningTransport.cs
Replaces https://github.com/Particular/NServiceBus/pull/4783
=> Enable parallel acceptance tests

src/NServiceBus.Core/NServiceBus.Core.csproj
Updates the licensing code to support .NET Core.
=> Update Particular.Licensing.Sources to 1.0.0-alpha0001

src/NServiceBus.AcceptanceTests/Core/Routing/When_sending_non_message_with_routing_configured_by_assembly.cs, src/NServiceBus.AcceptanceTests/Core/Routing/When_sending_non_message_with_routing_configured_by_type.cs, src/NServiceBus.AcceptanceTests/Routing/When_making_endpoint_uniquely_addressable.cs, src/NServiceBus.AcceptanceTests/Routing/When_replying_to_message.cs, src/NServiceBus.AcceptanceTests/Routing/When_using_custom_routing_strategy.cs
More review results. Two tests moved to Core instead of downstreams, couple of renames, added a new scenario, no major/significant changes to existing test functionality.
=> Acceptance tests 11

src/NServiceBus.AcceptanceTests/Audit/When_a_replymessage_is_audited.cs, src/NServiceBus.AcceptanceTests/Pipeline/When_sending_to_another_endpoint.cs, src/NServiceBus.AcceptanceTests/Routing/When_publishing.cs, src/NServiceBus.AcceptanceTests/Sagas/When_saga_is_mapped_to_complex_expression.cs, src/NServiceBus.TransportTests/When_message_is_available.cs
=> No longer using Assert outside of unit test thread

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/NServiceBus.Core.csproj
This just cleans up a few things by simplifying them with no other changes.
=> misc cleanup of project files

src/NServiceBus.Testing.Fakes/TestablePipelineContext.cs, src/NServiceBus.Testing.Fakes/TimeoutMessage.cs
Addresses https://github.com/Particular/NServiceBus.Testing/issues/90#issuecomment-312208904
=> Intercepting timeout messages on the testable pipeline context

src/NServiceBus.Core/Unicast/Config/RegisterHandlersInOrder.cs
Removes dead and no longer used code
=> Removed no longer used property injection code

src/NServiceBus.Core/ObjectBuilder/LightInject/LightInjectObjectBuilder.cs
Should fix 
```
NServiceBus.AcceptanceTesting.Support.MessageFailedException : A message has been moved to the error queue.
----> System.InvalidOperationException : Attempt to end a scope before all child scopes are completed.
at LightInject.ScopeManager.EndScope(Scope scope)
at LightInject.Scope.OnCompleted()
at LightInject.Scope.Dispose()
at NServiceBus.LightInjectObjectBuilder.Dispose()
at NServiceBus.CommonObjectBuilder.Dispose()
at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at …
```
=> Using PerLogicalCallContextScopeManagerProvider instead of default per thread scope provider

src/NServiceBus.AcceptanceTests/DataBus/When_sending_databus_properties.cs
This updates a test that was missed in #4836.
=> Use RegisterMessageMutator API

src/NServiceBus.Core/ObjectBuilder/LightInject/LightInject.g.cs
applies https://github.com/seesharper/LightInject/commit/eada2b6d3d29b958cbcc511e410ac6d3a363c7b7 to our code to fix https://github.com/Particular/NServiceBus/issues/4838
=> Do not dispose multiple times

src/NServiceBus.Core/JanitorSettings.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/ObjectBuilder/LightInject/LightInject.g.cs
=> exclude LightInject from weaving

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingLogicalMessageContextTests.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingLogicalMessageContext.cs
=> MessageType of interface events is incorrectly changed during outgoing processing

src/NServiceBus.AcceptanceTests/Core/Sagas/When_finder_cant_find_saga_instance.cs, src/NServiceBus.Core/Sagas/ActiveSagaInstance.cs, src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
fixes https://github.com/Particular/NServiceBus/issues/4888
=> Verify saga correlation property against current value

src/NServiceBus.AcceptanceTests/Core/Sagas/When_finder_cant_find_saga_instance.cs, src/NServiceBus.Core/Sagas/ActiveSagaInstance.cs, src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
=> CustomFinder that starts a saga throws exception

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj, src/NServiceBus.sln
Look what just showed up! Stable releases of all the new System packages!
=> Update to stable System packages

src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs
Closes https://github.com/Particular/NServiceBus/issues/4897
Targets master, can be retargeted to patch or minor (would prefer patch to get the user unstuck). Does not require backporting.
=> AutoSubscribe subscribes concurrently

src/NServiceBus.AcceptanceTests/Core/Installers/When_installer_behavior_not_specified.cs, src/NServiceBus.AcceptanceTests/Core/Installers/When_installers_disabled.cs, src/NServiceBus.AcceptanceTests/Core/Installers/When_installers_enabled.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/InitializableEndpoint.cs, src/NServiceBus.Core/Installation/InstallConfigExtensions.cs
Allows to disable installers to address #4893
=> Disable installers

src/NServiceBus.AcceptanceTests/Core/Conventions/When_receiving_unobtrusive_message_without_handler.cs, src/NServiceBus.AcceptanceTests/Core/CriticalError/When_raising_critical_error_at_startup.cs, src/NServiceBus.Core.Tests/Transports/Learning/AsyncFileTests.cs, src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
A few small test changes based on some randomly failing tests
=> Test refactorings

src/NServiceBus.AcceptanceTests/Core/Installers/When_installer_behavior_not_specified.cs, src/NServiceBus.AcceptanceTests/Core/Installers/When_installers_disabled.cs, src/NServiceBus.AcceptanceTests/Core/Installers/When_installers_enabled.cs, src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/InitializableEndpoint.cs, src/NServiceBus.Core/Installation/InstallConfigExtensions.cs, src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs
This is an intermediary branch to verify the results and run the tests before merging this into develop.
This branch should be merged via regular merge commit to ensure correct commit history.
TODO:
=> Merge 6.4 into develop

src/NServiceBus.AcceptanceTesting/EndpointConfigurationBuilder.cs, src/NServiceBus.AcceptanceTesting/Support/EndpointCustomizationConfiguration.cs
Since its no longer relevant with custom config source removed from core
=> Remove WithConfig

guidelines/coding-guidelines.md
Talking to @SimonCropp and @timbussmann we propose the following guidelines for dependency management
=> Dependency guidelines

src/NServiceBus.AcceptanceTests/EndpointTemplates/DefaultServer.cs
it doesn't seem this setting is used anywhere? ping @andreasohlund
=> Remove usage of scaleout config

src/NServiceBus.Core.Tests/Timeout/TimeoutMessageReceiverTests.cs, src/NServiceBus.Core/Persistence/InMemory/TimeoutPersister/InMemoryTimeoutPersister.cs, src/NServiceBus.Core/Timeout/Hosting/Windows/TimeoutPersisterReceiver.cs
Use fields instead of lambda ctors
Fixes #4955
=> Lambda constructors added in version 5.2.23 breaks StructureMap support

src/NServiceBus.AcceptanceTests/DelayedDelivery/When_using_special_characters_in_headers.cs, src/NServiceBus.AcceptanceTests/Recoverability/When_message_is_deferred_by_delayed_retries_using_dtc.cs, src/NServiceBus.AcceptanceTests/Recoverability/When_using_special_characters_in_headers.cs, src/NServiceBus.AcceptanceTests/Sagas/When_sagas_share_timeout_messages.cs, src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_expired.cs, src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_expired_convention.cs, src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_used_with_unobtrusive_mode.cs
Rolling back some changes made in https://github.com/Particular/NServiceBus/pull/4963 which are affecting downstreams and cause them to fail.
=> Partial revert of TTBR test changes

src/NServiceBus.Core/DataBus/DataBus.cs
replace property injection with ctor injection
relates to https://github.com/Particular/NServiceBus/issues/4968
=> Remove property injection from DataBusInitializer

src/NServiceBus.AcceptanceTests/Core/Routing/When_extending_command_routing_with_thisinstance.cs, src/NServiceBus.AcceptanceTests/Routing/When_extending_command_routing.cs, src/NServiceBus.AcceptanceTests/Routing/When_using_custom_routing_strategy.cs, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Routing/DistributionPolicyTests.cs, src/NServiceBus.Core/Routing/DistributionStrategy.cs, src/NServiceBus.Core/Routing/SingleInstanceRoundRobinDistributionStrategy.cs
addresses https://github.com/Particular/NServiceBus/issues/4951
cc @danielmarbach
=> Remove DistributionStrategy compatibility layer

src/NServiceBus.Core/Sagas/ContainSagaData.cs, src/NServiceBus.Core/Sagas/IContainSagaData.cs
part of https://github.com/Particular/NServiceBus/issues/4344
not sure, but I assumed that it would probably also make sense to have those attributes on the interface?
=> Add EditorBrowsable attribute to ContainSagaData

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/Pipeline/PipelineTests.cs, src/NServiceBus.Core/InitializableEndpoint.cs, src/NServiceBus.Core/Pipeline/Pipeline.cs, src/NServiceBus.Core/Pipeline/PipelineCache.cs, src/NServiceBus.Core/Pipeline/PipelineConfiguration.cs, src/NServiceBus.Core/Pipeline/RegisterStep.cs, src/NServiceBus.Core/StartableEndpoint.cs, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
Closes #4118 
Will do upgrade guide once merged
=> Remove RegisterStep.IsEnabled

src/NServiceBus.AcceptanceTesting/EndpointConfigurationBuilder.cs, src/NServiceBus.AcceptanceTests/Audit/When_a_message_is_audited.cs, src/NServiceBus.AcceptanceTests/Audit/When_a_replymessage_is_audited.cs, src/NServiceBus.AcceptanceTests/Core/Mutators/When_defining_outgoing_message_mutators.cs, src/NServiceBus.AcceptanceTests/Core/Pipeline/When_registering_handlers_explicitly.cs, src/NServiceBus.AcceptanceTests/Core/Recoverability/When_delayed_retries_with_regular_exception.cs, src/NServiceBus.AcceptanceTests/Core/Recoverability/When_failing_mutated_message.cs, src/NServiceBus.AcceptanceTests/Correlation/When_replying_to_received_message_without_correlationid.cs, src/NServiceBus.AcceptanceTests/Serialization/When_configuring_custom_xml_namespace.cs, src/NServiceBus.AcceptanceTests/Serialization/When_no_content_type.cs, src/NServiceBus.AcceptanceTests/Serialization/When_sanitizing_xml_messages.cs, src/NServiceBus.AcceptanceTests/Serialization/When_skip_wrapping_xml.cs, src/NServiceBus.AcceptanceTests/Serialization/When_wrapping_is_not_skipped.cs
To prep for https://github.com/Particular/NServiceBus/issues/4982
=> Use new mutator api instead of DI

src/NServiceBus.Core/CriticalError/ConfigureCriticalErrorAction.cs, src/NServiceBus.Core/CriticalError/CriticalError.cs
Instead of stopping the endpoint.
=> Change default critical error behavior to keep on retrying

src/NServiceBus.AcceptanceTests/Routing/NativePublishSubscribe/When_publishing_to_scaled_out_subscribers.cs
noticed that the tests assertions are written weirdly as this test was failing on the buildserver.
=> Minor code cleanup

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_handling_current_message_later.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core/Unicast/MessageOperationsInvokeHandlerContext.cs
fixes https://github.com/Particular/NServiceBus/issues/4993
=> HandleCurrentMessageLater causes message loss when using Outbox

src/NServiceBus.Core/Licensing/LicenseManager.cs
Connects to https://github.com/Particular/DotNetCoreLaunch/issues/16
=> New license dialog URL

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes.cs
This solves #5006 by clarifying that these APIs are not "discouraged", but instead not possible.
=> Update obsolete wording to be clearer

src/NServiceBus.Core/InitializableEndpoint.cs
Output:
```
"Transport":{
"Type":"NServiceBus.LearningTransport",
"Version":"7.0.0"
}
```
=> Add transport diagnostics

src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeQueueCreator.cs, src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeReceiver.cs, src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransport.cs, src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportInfrastructure.cs, src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportSettingsExtensions.cs, src/NServiceBus.AcceptanceTests/Core/Transport/When_initializing_transport.cs, src/NServiceBus.AcceptanceTests/Core/TransportSeam/When_initializing_transport.cs
=> Add tests to verify startup sequence

src/NServiceBus.Core/InitializableEndpoint.cs
Adds the following output:
```
"Endpoint":{
"Name":"EndpointStarts.MyEndpoint",
"SendOnly":false,
"NServiceBusVersion":"7.0.0"
}
```
=> Add endpoint diagnostics

src/NServiceBus.AcceptanceTests/NServiceBusAcceptanceTest.cs, src/NServiceBus.AcceptanceTests/Tx/When_receiving_with_dtc_enabled.cs
fixes https://github.com/Particular/NServiceBus/issues/5040
=> enable workaround for other framework versions

src/NServiceBus.AcceptanceTests/Routing/When_overriding_local_address.cs, src/NServiceBus.Core/Receiving/ReceiveConfigurationBuilder.cs, src/NServiceBus.Core/Transports/ReceiveSettingsExtensions.cs
Since that is not a valid configuration option
=> Do not allow a custom local address for send only endpoints

src/NServiceBus.AcceptanceTests/Outbox/When_headers_contain_special_characters.cs
=> remove redundant state machine

src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
relates to https://github.com/Particular/NServiceBus/issues/5082
=> ObjectDisposedException when trying to load saga finder

src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
=> Remove vulnerable field in SagaPersistenceBehavior

src/NServiceBus.AcceptanceTests/Retries/When_sending_to_slr.cs
Related to: https://github.com/Particular/NServiceBus.SqlServer/pull/430
=> Ignore a flaky test Should_raise_FinishedMessageProcessing_event

LICENSE.md
Should we also include a file with the license details?
=> License location fixed

src/NServiceBus.Core.Tests/Serializers/SimpleJsonTests.cs, src/NServiceBus.Core.Tests/SimpleJsonTests.cs, src/NServiceBus.Core/Serializers/SimpleJson/SimpleJson.g.cs
* provides basic `Dictionary` support
* changes DateTime serialization
=> simpleJson improvements

README.md
relates to https://github.com/Particular/NServiceBus/pull/5132
=> Add net-object-deep-copyto readme

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Serializers/XML/XmlSerializerCacheTests.cs, src/NServiceBus.Core/Serializers/XML/XmlDeserialization.cs, src/NServiceBus.Core/Serializers/XML/XmlSerialization.cs, src/NServiceBus.Core/Serializers/XML/XmlSerializerCache.cs
=> Make XmlSerializerCache initialization threadsafe for 6.x

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core.Tests/Serializers/XML/XmlSerializerCacheTests.cs, src/NServiceBus.Core/Serializers/XML/XmlDeserialization.cs, src/NServiceBus.Core/Serializers/XML/XmlSerialization.cs, src/NServiceBus.Core/Serializers/XML/XmlSerializerCache.cs
Backports https://github.com/Particular/NServiceBus/issues/5122 to 6.4
Includes #5162
=> XML serializer's type initialization is vulnerable to concurrency

src/NServiceBus.Core.Analyzer/AwaitOrCaptureTasksAnalyzer.cs
You probably won't be happy about the suggested changes, therefore the PR @adamralph but I added a few optimizations, e.g.
* Remove method invocations
* Replace tail calls with while loops (my fp heart is bleeding)
* Remove LINQ usage (general coding guideline for hot path code in nsb.core)
* Avoid traversing up the whole syntax tree when the method declaration is not async
comparison:
before:
after:
comparison of test results using https://github.com/Particular/NServiceBus/pull/5161 (comparing best seen results)
before:
Average:   00:00:00.4381364
50% Percentile: 00:00:00.4114119
80% Percentile: 00:00:00.4461185
95% Percentile: 00:00:00.6655526
after:
Average:   00:00:00.3269772
50% Percentile: 00:00:00.3186249
80% Percentile: 00:00:00.3522399
95% Percentile: 00:00:00.5384207
=> optimize analyzer

src/NServiceBus.Core.Analyzer/AwaitOrCaptureTasksAnalyzer.cs, src/NServiceBus.Core.Analyzer/SymbolExtensions.cs
Not sure why the code adds the arity in the first place, but it doesn't seem to be necessary. Thoughts @adamralph ?
=> Remove arity from filter criteria

src/NServiceBus.Core.Analyzer/AwaitOrCaptureTasksAnalyzer.cs
=> Refactor AwaitOrCaptureTasksAnalyzer.Analyze()

src/NServiceBus.sln.DotSettings
Those are automatic changes coming up after every reset.
=> Update DotSettings file

packaging/nuget/nservicebus.core.nuspec, src/NServiceBus.Core.Analyzer.Tests/AwaitOrCaptureTasksAnalyzerTests.cs, src/NServiceBus.Core.Analyzer.Tests/Helpers/DiagnosticResult.cs, src/NServiceBus.Core.Analyzer.Tests/Helpers/DiagnosticResultLocation.cs, src/NServiceBus.Core.Analyzer.Tests/Helpers/DiagnosticVerifier.cs, src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj, src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj.DotSettings, src/NServiceBus.Core.Analyzer.Tests/UniformSessionStubs/IUniformSession.cs, src/NServiceBus.Core.Analyzer.Tests/UniformSessionStubs/IUniformSessionExtensions.cs, src/NServiceBus.Core.Analyzer/AwaitOrCaptureTasksAnalyzer.cs, src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj, src/NServiceBus.Core.Analyzer/SymbolExtensions.cs, src/NServiceBus.Core.Analyzer/tools/install.ps1, src/NServiceBus.Core.Analyzer/tools/uninstall.ps1, src/NServiceBus.sln, src/NServiceBus.sln.DotSettings
backports the async analyzer to v6
=> Backport async analyzer

src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs
fixes https://github.com/Particular/NServiceBus/issues/5185 by using `TryGet`.
=> Reduce dictionary lookups for control message header

src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportSettingsExtensions.cs, src/NServiceBus.AcceptanceTests/Serialization/When_registering_custom_serializer.cs, src/NServiceBus.AcceptanceTests/Serialization/When_registering_deserializers_with_settings.cs, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt, src/NServiceBus.Core.Tests/Audit/AuditConfigReaderTests.cs, src/NServiceBus.Core.Tests/DeliveryConstraintContextExtensions/DeliveryConstraintContextExtensionsTests.cs, src/NServiceBus.Core/Audit/Audit.cs, src/NServiceBus.Core/Audit/ConfigureAudit.cs, src/NServiceBus.Core/DelayedDelivery/DelayedDeliveryFeature.cs, src/NServiceBus.Core/EndpointConfiguration.cs, src/NServiceBus.Core/InitializableEndpoint.cs, src/NServiceBus.Core/Performance/MessageProcessingOptimizations/MessageProcessingOptimizationExtensions.cs, src/NServiceBus.Core/Performance/TimeToBeReceived/TimeToBeReceivedConventionExtensions.cs, src/NServiceBus.Core/Reliability/Outbox/OutboxConfigExtensions.cs, src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribeSettings.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs, src/NServiceBus.Core/Sagas/Sagas.cs, src/NServiceBus.Core/Settings/SettingsHolder.cs, src/NServiceBus.Core/StaticHeaders/StaticHeadersConfigExtensions.cs, src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs, src/NServiceBus.Core/Unicast/Transport/Config/TransportExtensions.cs, src/NServiceBus.Core/Unicast/Transport/Config/UseTransportExtensions.cs, src/NServiceBus.Core/UnitOfWork/UnitOfWorkSettings.cs, src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
Fixes #5182 by adding generic overloads
=> Add a generic Set and SetDefault to SettingsHolder

src/NServiceBus.AcceptanceTesting/Support/EndpointBehavior.cs, src/NServiceBus.AcceptanceTests/Core/SelfVerification/EndpointNameEnforcementTests.cs
=> Queue length check

src/NServiceBus.Core/Audit/Audit.cs
fixes https://github.com/Particular/NServiceBus/issues/3651
=> Add log entry for configured audit queue

src/Directory.Build.props, src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Persistence.InMemory.AcceptanceTests/NServiceBus.Persistence.InMemory.AcceptanceTests.csproj, src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
The primary update is to the new version of Particular.Packaging, which now includes the Microsoft SourceLink package.
=> Package updates

src/NServiceBus.Core/Pipeline/Outgoing/SerializeMessageConnector.cs
the previous code always added a new, empty line to the log file, which seems to be unnecessary to me?
=> Remove line break to avoid empty lines in log file

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_autosubscribe_with_missing_publisher_information.cs, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Persistence.InMemory.AcceptanceTests/NServiceBus.Persistence.InMemory.AcceptanceTests.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
* target .net core 2.1 in test projects
* shorten test name
=> Merge Release 7.1 into develop

src/NServiceBus.Core.Analyzer/GitVersion.yml, src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj, src/NServiceBus.sln
Sign and version the analyzer assembly to allow multiple versions of the analyzer to load correctly into the same solution.
=> Hotfix 7.1.1

src/NServiceBus.Core.Analyzer.Tests/AwaitOrCaptureTasksAnalyzerTests.cs, src/NServiceBus.Core.Analyzer/AwaitOrCaptureTasksAnalyzer.cs
adds the `ScheduleEvery` API on the list of APIs to check by the analyzer
=> Hotfix 7.1.3

src/NServiceBus.AcceptanceTests/Core/Mutators/When_defining_outgoing_message_mutators.cs, src/NServiceBus.Core.Tests/MessageMutators/MutateInstanceMessage/MutateIncomingMessageBehaviorTests.cs, src/NServiceBus.Core.Tests/MessageMutators/MutateInstanceMessage/MutateOutgoingMessageBehaviorTests.cs, src/NServiceBus.Core.Tests/MessageMutators/MutateTransportMessage/MutateIncomingTransportMessageBehaviorTests.cs, src/NServiceBus.Core.Tests/MessageMutators/MutateTransportMessage/MutateOutgoingTransportMessageBehaviorTests.cs, src/NServiceBus.Core.Tests/MessageMutators/MutatorRegistrationExtensionsTests.cs, src/NServiceBus.Core/MessageMutators/MutateInstanceMessage/MutateIncomingMessageBehavior.cs, src/NServiceBus.Core/MessageMutators/MutateInstanceMessage/MutateOutgoingMessageBehavior.cs, src/NServiceBus.Core/MessageMutators/MutateTransportMessage/MutateIncomingTransportMessageBehavior.cs, src/NServiceBus.Core/MessageMutators/MutateTransportMessage/MutateOutgoingTransportMessageBehavior.cs, src/NServiceBus.Core/MessageMutators/MutatorRegistrationExtensions.cs, src/NServiceBus.Core/MessageMutators/Mutators.cs
=> When using the explicit registration API only the last registered mutator is invoked

src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
=> Typo in test name

src/NServiceBus.Core/NServiceBus.Core.csproj
While the original issue has been fixed, there is new problem in VS 15.8 that still needs the workaround.
This workaround should finally be able to be removed when 15.9 is out.
=> Update workaround comment to point to new issue

src/NServiceBus.Core/AllAssemblies.cs, src/NServiceBus.Core/BusConfiguration.cs, src/NServiceBus.Core/Logging/DefaultFactory.cs
ignore false positives to make the code inspections pass
=> ignore false positives

src/NServiceBus.AcceptanceTesting/Support/RunSettings.cs, src/NServiceBus.AcceptanceTests/Core/Diagnostics/When_feature_overrides_hostid.cs, src/NServiceBus.AcceptanceTests/Core/Diagnostics/When_license_expired.cs, src/NServiceBus.Core.Tests/DeliveryConstraintContextExtensions/DeliveryConstraintContextExtensionsTests.cs, src/NServiceBus.Core.Tests/Msmq/MsmqQueueCreatorTests.cs, src/NServiceBus.Core.Tests/Performance/TimeToBeReceived/TimeToBeReceivedAttributeTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs, src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs, src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs, src/NServiceBus.Core/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehavior.cs, src/NServiceBus.Core/EndpointConfiguration.cs, src/NServiceBus.Core/Logging/DefaultFactory.cs, src/NServiceBus.Core/Persistence/InMemory/Outbox/InMemoryOutboxStorage.cs, src/NServiceBus.Core/Persistence/Msmq/SubscriptionStorage/MsmqSubscriptionStorage.cs, src/NServiceBus.Core/Recoverability/Recoverability.cs, src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs, src/NServiceBus.Core/Transports/Msmq/MessagePump.cs, src/NServiceBus.Core/Transports/Msmq/MsmqAddress.cs, src/NServiceBus.Core/Transports/Msmq/MsmqMessageDispatcher.cs, src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs, src/NServiceBus.Core/Transports/Msmq/MsmqTransportInfrastructure.cs, src/NServiceBus.Core/Transports/Msmq/MsmqUtilities.cs, src/NServiceBus.Core/Utils/MessageQueueExtensions.cs
Fixing the failing support branch build for the 6.5 support branch due to
=> Fix code inspection errors

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Persistence.InMemory.AcceptanceTests/NServiceBus.Persistence.InMemory.AcceptanceTests.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
This includes the update to the test adapter package that finally fixes the conflict with Mono.Cecil.
=> Update test packages

src/NServiceBus.AcceptanceTesting/Support/TaskExtensions.cs
I have not touched this code for a while. Tonight I had a good discussion with David Fowler on Twitter about the usage of TaskCompletionSource and he asked my why I wrote this code the way I wrote it. After reflecting over it I knew that at the time I tended to write more TPL code but nowadays I know that the async statemachine so optimized that it is not worth the complexity. Especially not considering this is an acceptance test helper. Another plus of this solution is that it gets rid of the TaskCompletionSource that did not use `RunContinuationsAsynchronously`.
To verify before and after I wrote tests but I didn't know where to place those since we don't have a test project for the acceptance test support assembly. So I copy paste them here for future reference
```
[TestFixture]
public …
```
=> Simplify timebox extension method

src/NServiceBus.AcceptanceTesting/AcceptanceTestingContainer/AcceptanceTestingContainer.cs, src/NServiceBus.AcceptanceTests/EndpointTemplates/DefaultServer.cs, src/NServiceBus.Core/InitializableEndpoint.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.cs
=> Enabling installers cause endpoints to fail during startup when the container used is immutable

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Persistence.InMemory.AcceptanceTests/NServiceBus.Persistence.InMemory.AcceptanceTests.csproj, src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
This updates development tooling on the `support-7.0` branch.
Note: It is okay for this to be squashed.
=> Update development tooling

src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
This fixes the failing assembly scanner test introduced in #5316.
=> Fix assembly scanner test

src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj
Ideally, this would stop it from being published as a source package.
=> Remove packaging from the project 

CONTRIBUTING.md
Not necessary after new CLA process
=> Removed link to CLA signing

src/NServiceBus.AcceptanceTests/Core/Routing/When_replying_with_pre_created_interface.cs, src/NServiceBus.AcceptanceTests/Core/Routing/When_routing_interface_message.cs, src/NServiceBus.AcceptanceTests/Routing/When_publishing_pre_created_interface.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs, src/NServiceBus.Core.Tests/Routing/RoutingToDispatchConnectorTests.cs, src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs, src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs, src/NServiceBus.Core.Tests/Unicast/MessageOperationsTests.cs, src/NServiceBus.Core.Tests/Unicast/RunningEndpointInstanceTest.cs, src/NServiceBus.Core/InitializableEndpoint.cs, src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs, src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs, src/NServiceBus.Core/Pipeline/RootContext.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.cs, src/NServiceBus.Core/Serialization/SerializationFeature.cs, src/NServiceBus.Core/Unicast/MessageOperations.cs
=> Interface messages created with IMessageCreator can't be routed

src/NServiceBus.Core/InitializableEndpoint.cs
=> Remove unnecessary self-registration of InitializableEndpoint

src/NServiceBus.AcceptanceTests/Core/Routing/When_callbacks_are_used_to_reply_with_int_or_enum.cs, src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/MessageMapper.cs
=> Using callbacks to reply with Int or Enums is broken

src/NServiceBus.Core/Pipeline/PipelineExecutionExtensions.cs
Replaces https://github.com/Particular/NServiceBus/pull/5388
=> Done delegate should accept outContextType

src/NServiceBus.Core.Tests/Persistence/InMemory/InMemoryGatewayDeduplicationTests.cs, src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs, src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayPersistence.cs
Refactored in memory gateway deduplication implementation to be LRU based where LRU cache size can be configured by a code API.
=> Hotfix 6.5.8

src/NServiceBus.Core.Tests/Persistence/InMemory/InMemoryGatewayDeduplicationTests.cs, src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs, src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayPersistence.cs
Refactored in memory gateway deduplication implementation to be LRU based where LRU cache size can be configured by a code API.
=> Hotfix 7.1.10

src/NServiceBus.Core.Tests/Persistence/InMemory/InMemoryGatewayDeduplicationTests.cs, src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs, src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayPersistence.cs
Replaces https://github.com/Particular/NServiceBus/pull/5394
=> Hotfix 7.1.10 to develop

src/NServiceBus.Core/Routing/MessagingBestPractices/Validations.cs
From @zlepper as feedback in LiveChat.
This is a low hanging fruit so I PRed it directly.
We could also consider improving the exception messages in this class but I figured it would be a different PR to not distract from the scope of this PR
=> Improve log message in AssertIsValidForPubSub

src/NServiceBus.Core.Tests/Unicast/MessagingBestPracticesTests.cs, src/NServiceBus.Core/Routing/MessagingBestPractices/Validations.cs
Follow up of https://github.com/Particular/NServiceBus/pull/5402
=> Improve best practice validation exception message

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
Changes see https://github.com/JakeGinnivan/ApiApprover/releases/tag/9.3.0
=> Update to PublicApiGenerator 9.3

src/NServiceBus.Core/Routing/MessagingBestPractices/Validations.cs
=> Log as warning when publishing a non IEvent message

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Persistence.InMemory.AcceptanceTests/NServiceBus.Persistence.InMemory.AcceptanceTests.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
This PR updates all the testing packages to the latest versions.
=> Update testing packages

GitVersion.yml
Since we already have beta packages on myget
=> Switch to beta

src/NServiceBus.Core/Extensibility/ExtendableOptions.cs, src/NServiceBus.Core/PublishOptions.cs, src/NServiceBus.Core/ReplyOptions.cs, src/NServiceBus.Core/Routing/SubscribeOptions.cs, src/NServiceBus.Core/Routing/UnsubscribeOptions.cs, src/NServiceBus.Core/SendOptions.cs
=> Document SendOptions

src/NServiceBus.AcceptanceTests/Outbox/When_clearing_saga_timeouts.cs, src/NServiceBus.Core.Tests/Persistence/PersistenceStartupTests.cs, src/NServiceBus.Core.Tests/Persistence/PersistenceStorageMergerTests.cs, src/NServiceBus.Core/Persistence/PersistenceStartup.cs
=> Add check to verify if outbox and sagas use same persistence

src/NServiceBus.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt, src/NServiceBus.Core/Pipeline/Incoming/ReceiveFeature.cs, src/NServiceBus.Persistence.InMemory.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt
Since we are changing this part, I figured I can try remove some of these behaviors from DI
=> Remove internal behaviors from the DI

src/NServiceBus.Core/Licensing/LicenseManager.cs
Fixes https://github.com/Particular/NServiceBus/issues/5239
I did not find any other occurrence of that problem (looking at the code)
=> Fix redundant new lines in log

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_modifying_headers_during_forwarding.cs, src/NServiceBus.Core/Forwarding/InvokeForwardingPipelineBehavior.cs
fixes https://github.com/Particular/NServiceBus/issues/5256
=> Prevent forwarding header manipulations to leak into main pipeline

src/NServiceBus.Core/Transports/TransportReceiveInfrastructure.cs, src/NServiceBus.Core/Transports/TransportSendInfrastructure.cs
Fixes https://github.com/Particular/NServiceBus/issues/5207
=> Clarify PreStartupCheck XML documentation

src/NServiceBus.Core/EndpointCreator.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.cs, src/NServiceBus.Core/StartableEndpoint.cs
This just renames some methods and switches to a static factory method
=> Better align receive component with guidelines

src/NServiceBus.Core/EndpointConfiguration.cs, src/NServiceBus.Core/EndpointCreator.cs, src/NServiceBus.Core/Installation/InstallationComponent.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.cs, src/NServiceBus.Core/StartableEndpoint.cs, src/NServiceBus.Core/Transports/TransportComponent.cs
Created a new PR to get TC to pick it up
=> Move queue bindings into the transport component

src/NServiceBus.Core/EndpointConfiguration.cs, src/NServiceBus.Core/EndpointCreator.cs, src/NServiceBus.Core/Hosting/HostingComponent.cs, src/NServiceBus.Core/Pipeline/PipelineCache.cs, src/NServiceBus.Core/Pipeline/PipelineComponent.cs, src/NServiceBus.Core/Pipeline/PipelineSettings.cs, src/NServiceBus.Core/Routing/RoutingComponent.cs, src/NServiceBus.Core/StartableEndpoint.cs
aligns the pipeline component better with the component design guidelines.
=> Rework pipeline component

src/NServiceBus.Core.Tests/Routing/RoutingSettingsTests.cs, src/NServiceBus.Core/EndpointConfiguration.cs, src/NServiceBus.Core/EndpointCreator.cs, src/NServiceBus.Core/Routing/RoutingComponent.cs, src/NServiceBus.Core/Routing/RoutingSettings.cs
based on the component design guidelines.
* Switching to static ctor
* Introducing configuration class
=> Rework routing component

src/NServiceBus.Core.Tests/Routing/RoutingSettingsTests.cs, src/NServiceBus.Core/EndpointConfiguration.cs, src/NServiceBus.Core/EndpointCreator.cs, src/NServiceBus.Core/Features/FeatureConfigurationContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/SendComponent.cs, src/NServiceBus.Core/Routing/RoutingComponent.cs, src/NServiceBus.Core/Routing/RoutingFeatureSettingsExtensions.cs, src/NServiceBus.Core/Routing/RoutingSettings.cs
Adjust the RoutingComponent to the Settings/Configuration approach and moving some part back from the SendComponent into routing (stuff that isn't relevant to build the pipelines)
=> Adjust RoutingComponent

src/NServiceBus.Core/Hosting/HostingComponent.Configuration.cs, src/NServiceBus.Core/Hosting/HostingComponent.Settings.cs, src/NServiceBus.Core/Hosting/HostingComponent.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.Configuration.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.Settings.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.cs, src/NServiceBus.Core/Routing/RoutingComponent.Configuration.cs, src/NServiceBus.Core/Routing/RoutingComponent.Settings.cs, src/NServiceBus.Core/Routing/RoutingComponent.cs
splits the larger components into separate files using partials to make them easier to read.
=> Split larger components with partials

src/NServiceBus.Core/Hosting/HostInfoSettings.cs
the `DisplayName ` property should do the same thing if I didn't read it incorrectly
=> Remove duplicate assignment

src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/SubscriptionReceiverBehavior.cs
Closes https://github.com/Particular/NServiceBus/issues/5538
=> Remove mention of obsoleted AsA_Publisher role

src/NServiceBus.Core/Hosting/Helpers/AssemblyScanningComponent.cs, src/NServiceBus.Core/Utils/FileVersionRetriever.cs
Closes https://github.com/Particular/NServiceBus/issues/5522
=> Include assembly file version in startup diagnostics

GitVersion.yml, src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Analyzer/GitVersion.yml, src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
=> Update Particular.Packaging in master

GitVersion.yml, src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Analyzer/GitVersion.yml, src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
=> Update Particular.Packaging in release-7.1

GitVersion.yml, src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Analyzer/GitVersion.yml, src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
=> Update Particular.Packaging in release-7.2

src/NServiceBus.Core/StartableEndpoint.cs
=> Set PrincipalPolicy on Windows only

src/NServiceBus.AcceptanceTests/Core/SelfVerification/When_running_saga_tests.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj, src/NServiceBus.Core.Tests/EndpointConfigurationTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/PublisherAddress.cs, src/NServiceBus.Persistence.InMemory.AcceptanceTests/NServiceBus.Persistence.InMemory.AcceptanceTests.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
For your review @mauroservienti
=> Update test projects to netcoreapp3.1 in release-7.1

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj, src/NServiceBus.Core.Tests/EndpointConfigurationTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Persistence.InMemory.AcceptanceTests/NServiceBus.Persistence.InMemory.AcceptanceTests.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
For your review @mauroservienti
=> Update test projects to netcoreapp3.1 in release-7.2

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj, src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj, src/NServiceBus.Core.Tests/EndpointConfigurationTests.cs, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj, src/NServiceBus.Persistence.InMemory.AcceptanceTests/NServiceBus.Persistence.InMemory.AcceptanceTests.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
For your review @mauroservienti
=> Update test projects to netcoreapp3.1 in master

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt, src/NServiceBus.Core.Tests/Recoverability/RecoverabilityExecutorTests.cs, src/NServiceBus.Core/Recoverability/CustomAction.cs, src/NServiceBus.Core/Recoverability/RecoverabilityAction.cs, src/NServiceBus.Core/Recoverability/RecoverabilityComponent.cs, src/NServiceBus.Core/Recoverability/RecoverabilityExecutor.cs, src/NServiceBus.Core/Recoverability/RecoverabilityExecutorFactory.cs
Addition to #5605 
As a proposal the possibility to access the dispatcher
=> Pass dispatcher to custom action

src/NServiceBus.Core.Tests/Licensing/LicenseManagerTests.cs, src/NServiceBus.Core/Licensing/LicenseManager.cs, src/NServiceBus.Core/NServiceBus.Core.csproj
Update license messages to support new license model
=> License message updates

src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
Extract the transport test base fix from https://github.com/Particular/NServiceBus.Transport.Msmq/pull/124 (as this PR proofs it works on downstreams)
=> Use settings from endpoint configuration to avoid having to redeclare default configuration values

src/NServiceBus.AcceptanceTests/Core/Diagnostics/When_endpoint_is_started.cs, src/NServiceBus.Core/Licensing/LicenseManager.cs, src/NServiceBus.Core/Licensing/LicenseReminder.cs
Resolves https://github.com/Particular/NServiceBus/issues/5464
=> License diagnostics

src/NServiceBus.Core.Tests/ApprovalFiles/DiagnosticsWriterTests.ShouldWriteWhenDuplicateEntriesPresent.approved.txt, src/NServiceBus.Core.Tests/Diagnostics/DiagnosticsWriterTests.cs, src/NServiceBus.Core/Hosting/HostingComponent.cs, src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnosticsWriter.cs
=> Fix writing of the diagnostic file when duplicate entries exists

src/NServiceBus.Core.Tests/Unicast/Messages/DefaultMessageRegistryTests.cs, src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs
=> add less restrictive type finding

src/NServiceBus.PersistenceTesting/Sagas/When_worker_tries_to_complete_saga_update_by_another_pessimistic.cs
Moving the Get statement into a Task.Run ensures that it's happening on a seperate thread.
We have run into issues on MySql timing out when not doing so. We have copied the test and excluded this one from the persistence tests until this PR is merged in.
=> Move persister.get into a Task.Run

src/NServiceBus.Core/ObjectBuilder/LightInject/LightInject.g.cs
Updating to LightInject 6.3.4 so we can make use of https://github.com/seesharper/LightInject.Microsoft.DependencyInjection once we reference the MS DI abstractions.
=> Update LightInject source

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt, src/NServiceBus.Core/Forwarding/ConfigureForwarding.cs
Update the obsoleted message in v7.4 branch to reflect the changes done in v8.
=> Obsolete message update to reflect the changes in v8

src/NServiceBus.AcceptanceTests/ConfigureEndpointLearningTransport.cs
Part of https://github.com/Particular/DeveloperExperience.LowPriority/issues/19.
=> Remove temp-path shortening in ATT with learning transport

src/NServiceBus.AcceptanceTests/Sagas/When_correlated_via_message_header.cs
These 2 tests for exceptions are taking the full 90 seconds to run, which adds 3 minutes to the build time. When this test is pulled into the SQL Persistence repo, it runs them agains 5 different SQL Dialects which adds 15 minutes to each test run!
=> Speed up slow tests

src/NServiceBus.TransportTests/ConcurrentQueueExtensions.cs, src/NServiceBus.TransportTests/TransportTestLoggerFactory.cs, src/NServiceBus.TransportTests/When_on_error_throws.cs
=> Fix transport tests to not cause System.InvalidOperationException

src/NServiceBus.Core.Tests/Transports/MulticastTransportOperationTest.cs, src/NServiceBus.Core.Tests/Transports/TransportOperationTest.cs, src/NServiceBus.Core.Tests/Transports/UnicastTransportOperationTest.cs, src/NServiceBus.Core/DeliveryConstraints/DeliveryConstraint.cs, src/NServiceBus.Core/Transports/MulticastTransportOperation.cs, src/NServiceBus.Core/Transports/TransportOperation.cs, src/NServiceBus.Core/Transports/UnicastTransportOperation.cs
Related to: https://github.com/Particular/NServiceBus/issues/5647
=> Removing usage of static List<DependencyConstraint>

src/NServiceBus.Core.Tests/Transports/MulticastTransportOperationTest.cs, src/NServiceBus.Core.Tests/Transports/TransportOperationTest.cs, src/NServiceBus.Core.Tests/Transports/UnicastTransportOperationTest.cs, src/NServiceBus.Core/DeliveryConstraints/DeliveryConstraint.cs, src/NServiceBus.Core/Transports/MulticastTransportOperation.cs, src/NServiceBus.Core/Transports/TransportOperation.cs, src/NServiceBus.Core/Transports/UnicastTransportOperation.cs
Backport of https://github.com/Particular/NServiceBus/issues/5647 for release-7.4 branch
=> Remove static delivery constraint

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/ObjectBuilder/ServiceCollectionExtensions.cs
For people not familiar with Microsoft DependencyInjection mentioned only `.Add` method may be confusing.
=> Extended obsolete exception messages.

src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_failed_message.cs, src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_successful_message.cs, src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_wrap_handlers_in_scope.cs, src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWork.cs, src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWorkBehavior.cs
Backport of UOW ordering fix for release-7.3 branch
=> NServiceBus 7.3 Pipeline UOW ordering fix

src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_failed_message.cs, src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_successful_message.cs, src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_wrap_handlers_in_scope.cs, src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWork.cs, src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWorkBehavior.cs
UOW ordering fix for release-7.4 branch
=> NServiceBus 7.4 Pipeline UOW ordering fix

src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWork.cs
Cherry of https://github.com/Particular/NServiceBus/pull/5828
=> Formatting. Removed unnecessary space.

src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_failed_message.cs, src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_successful_message.cs, src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_wrap_handlers_in_scope.cs, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/UnitOfWork/UnitOfWorkBehaviorTests.cs, src/NServiceBus.Core/UnitOfWork/IManageUnitsOfWork.cs
=> obsolete unit of work

src/NServiceBus.Core/Pipeline/FastExpressionCompiler.g.cs, src/NServiceBus.Core/Pipeline/PipelineExecutionExtensions.cs
Pulled out of https://github.com/Particular/NServiceBus/pull/5862 to make the changes clearer.
=> Update to FastExpressionCompiler 2.0

src/NServiceBus.Core/Transports/Learning/AsyncFile.cs
carving out an unrelated change from https://github.com/Particular/NServiceBus/pull/5877
=> remove redundant code in AsyncFile

src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_used_with_unobtrusive_mode.cs
Moving the `Send` operation and delaying endpoint startup in a single endpoint prevents a race-condition in which `Sender` sends a message to the `Receiver` before the `Receiver`s input queue has been created.
=> Fix TTBR acceptance test race condition on queue creation

src/NServiceBus.AcceptanceTests/Core/Recoverability/When_delayed_retries_enabled_with_no_support.cs, src/NServiceBus.AcceptanceTests/Core/Recoverability/When_transactions_off_and_delayed_retries_enabled.cs, src/NServiceBus.Core/Recoverability/RecoverabilityComponent.cs
Be more helpful on the error message on how to configure the endpoint to make this error go away.
=> Add more details to exception message

src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs, src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
and tweak LearningTransportMessagePump exception message when failing to begin transaction
=> log and abort transports tests for unexpected critical errors

src/NServiceBus.Core/Receiving/ReceiveComponent.cs
I've searched everywhere I could and asked around but I couldn't find a single use case for this scenario unless we want to support replacing the whole message handler registry (which is nothing that we have documented). We should remove this therefore as it causes a tight coupling with the DI containers lifecycle to determine at what point we're able to use the `MessageHandlerRegistry`.
Btw. I tested this against my [Lambda Handlers community package](https://github.com/timbussmann/Community.NServiceBus.LambdaHandlers/pull/1) and it definitely does not require this either.
=> Remove support for providing custom MessageHandlerRegistry via DI

src/NServiceBus.AcceptanceTests/Core/Persistence/When_a_persistence_does_not_support_outbox.cs, src/NServiceBus.AcceptanceTests/Outbox/When_a_duplicate_message_arrives.cs, src/NServiceBus.AcceptanceTests/Outbox/When_a_message_is_audited.cs, src/NServiceBus.AcceptanceTests/Outbox/When_blowing_up_just_after_dispatch.cs, src/NServiceBus.AcceptanceTests/Outbox/When_headers_contain_special_characters.cs, src/NServiceBus.AcceptanceTests/Outbox/When_receiving_a_message.cs, src/NServiceBus.AcceptanceTests/Sagas/When_handling_concurrent_messages.cs, src/NServiceBus.Core/Reliability/Outbox/Outbox.cs, src/NServiceBus.Core/Reliability/Outbox/OutboxConfigExtensions.cs
Changes added to https://github.com/Particular/docs.particular.net/pull/5208
=> Outbox requires explicit `ReceiveOnly` transaction mode setting

src/NServiceBus.AcceptanceTests/Receiving/When_subscribed_to_OnOnMessageReceiveCompleted.cs, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Receiving/ReceiveCompleted.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.Configuration.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.cs, src/NServiceBus.Core/Transports/CompleteContext.cs, src/NServiceBus.Core/Transports/ErrorContext.cs, src/NServiceBus.Core/Transports/IncomingMessage.cs, src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs, src/NServiceBus.Core/Transports/MessageContext.cs
fixup! Introduce OnCompleted to the transport seam (#5936)
=> fixup! Introduce OnCompleted to the transport seam (#5936)

src/NServiceBus.TransportTests/When_transaction_level_TransactionScope.cs
relates to https://github.com/Particular/NServiceBus/pull/5953
=> refactor When_transaction_level_TransactionScope

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes-v9.cs
Adds support for the `Transaction` "extension" method to the shim API.
=> Add Transactions to shim API

src/NServiceBus.Core.Analyzer/GitVersion.yml, src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj
Follow up for #6013 since dependabot auto merged things
=> GitVersion fixes

src/NServiceBus.Core/NServiceBus.Core.csproj
This updates the `master` branch to a version that include the Linux fix.
=> Update Particular.Licensing.Sources to 3.6.0

src/NServiceBus.Core/NServiceBus.Core.csproj
This updates the `release-7.4` branch to a version that includes the Linux fix.
=> Update Particular.Licensing.Sources to 3.3.2

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Support/RuntimeEnvironment.cs
Follow up after: https://github.com/Particular/NServiceBus/pull/6057https://github.com/Particular/NServiceBus/pull/6057
=> Fixing an obsolete message 

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.Core/Licensing/LicenseManager.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.Core/ObjectBuilder/ServiceCollectionExtensions.cs, src/NServiceBus.Core/Routing/UnicastPublishRouter.cs, src/NServiceBus.Core/Routing/UnicastSendRouter.cs, src/NServiceBus.Core/Serializers/SimpleJson/EnumAwareStrategy.cs, src/NServiceBus.Core/Transports/Learning/AsyncFile.cs, src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj
Targetting netcore 3.1 target framework.
=> Update project target framework

src/NServiceBus.Core/Receiving/ReceiveAddresses.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.cs, src/NServiceBus.Core/Routing/ApplyReplyToAddressBehavior.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs, src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenUnsubscribeTerminator.cs, src/NServiceBus.Core/Routing/RoutingComponent.cs, src/NServiceBus.Core/Routing/SubscriptionMigrationMode/MigrationSubscribeTerminator.cs, src/NServiceBus.Core/Routing/SubscriptionMigrationMode/MigrationUnsubscribeTerminator.cs, src/NServiceBus.Core/Routing/SubscriptionMigrationMode/SubscriptionMigrationMode.cs
quick spike to introduce a injectable holder type for the endpoint's receive addresses.
=> ReceiveAddresses

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/obsoletes-v8.cs
The obsolete message was missing the new receive address parameter required by the transport seam changes
=> Update MessageContext obsolete message

src/NServiceBus.Core.Tests/Serializers/XML/SerializerTests.cs, src/NServiceBus.Core.Tests/Serializers/XML/Using_Infer_Type_With_Non_Nested_Class.cs, src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/MessageMapper.cs
adding XML serializer change and tests for security hardening
=> xml serializer sec hardening

src/NServiceBus.Core/FodyWeavers.xml
For your review @andreasohlund @lailabougria @kentdr
=> Update Obsolete.Fody and Weavers.xml in master

src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
Minor refactoring for the `AssemblyScanner` tests to remove the `referencesTheCore` setting, which was initially used to indicate a reference to the core (to ensure the assembly is scanned). This has been consistently replaced by allowing any assembly to represent the "core" assembly via the `CoreAssemblyName` setting.
Also removes an incorrect test (`Should_not_include_child_type_if_only_handler_for_base_exists`) that indicates a "bug" which won't be fixed. The expected behavior has been re-written as a new test which is a bit simpler and captures the same logic.
=> Remove unused referenceTheCore setting in AssemblyScanner tests

src/Custom.Build.props, src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.sln
Brings https://github.com/Particular/NServiceBus/pull/6314 to the `release-7.7` branch
=> Add AnalyzerTargetFramework property

src/NServiceBus.AcceptanceTests/Core/Routing/When_inner_send_with_outer_immediate_dispatch.cs, src/NServiceBus.AcceptanceTests/Core/Routing/When_sending_from_outgoing_pipeline.cs, src/NServiceBus.AcceptanceTests/Core/Sagas/When_using_ReplyToOriginator_and_outgoing_behavior.cs, src/NServiceBus.AcceptanceTests/Routing/When_nested_send_with_outer_replyTo_routing.cs, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt, src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt, src/NServiceBus.Core.Tests/Routing/Routers/ReplyConnectorTests.cs, src/NServiceBus.Core/Causation/AttachCausationHeadersBehavior.cs, src/NServiceBus.Core/Correlation/AttachCorrelationIdBehavior.cs, src/NServiceBus.Core/Extensibility/ExtendableOptions.cs, src/NServiceBus.Core/Extensibility/ExtendableOptionsExtensions.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPublishContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingReplyContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingSendContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs, src/NServiceBus.Core/Routing/ApplyReplyToAddressBehavior.cs, src/NServiceBus.Core/Routing/Routers/ReplyConnector.cs, src/NServiceBus.Core/Routing/SubscribeContext.cs, src/NServiceBus.Core/Routing/UnicastSendRouter.cs, src/NServiceBus.Core/Routing/UnsubscribeContext.cs, src/NServiceBus.Core/Sagas/PopulateAutoCorrelationHeadersForRepliesBehavior.cs, src/NServiceBus.Core/Sagas/Saga.cs, src/NServiceBus.Core/Scheduling/ScheduleBehavior.cs
Backport of #6316 to NServiceBus 7.6
=> Default options from operations in outgoing behaviors might not be applied

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_setting_ttbr_in_outer_publish.cs, src/NServiceBus.AcceptanceTests/DelayedDelivery/When_deferring_outer_send.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs, src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs, src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPublishContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingReplyContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingSendContext.cs, src/NServiceBus.Core/Routing/SubscribeContext.cs, src/NServiceBus.Core/Routing/UnsubscribeContext.cs
backport of https://github.com/Particular/NServiceBus/pull/6356 to release 7.6
=> Backport delivery constraints fix to 7.6

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_setting_ttbr_in_outer_publish.cs, src/NServiceBus.AcceptanceTests/DelayedDelivery/When_deferring_outer_send.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs, src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs, src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs, src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPublishContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingReplyContext.cs, src/NServiceBus.Core/Pipeline/Outgoing/OutgoingSendContext.cs, src/NServiceBus.Core/Routing/SubscribeContext.cs, src/NServiceBus.Core/Routing/UnsubscribeContext.cs
backport of #6356 to release 7.5
=> Backport delivery constraints fix to 7.5

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_skipping_serialization_with_nested_send.cs, src/NServiceBus.Core/Serialization/SerializationContextExtensions.cs
=> Backport SkipSerialization leak fix to 7.6

src/NServiceBus.Core.Analyzer.Tests.Common/Sagas/SagaAnalyzerTests.cs, src/NServiceBus.Core.Analyzer/Sagas/SagaAnalyzer.cs
This is a fix for https://github.com/Particular/NServiceBus/issues/6370
=> Analyzer fix for handlers declared on different partial classes

src/NServiceBus.Core/Licensing/LicenseManager.cs, src/NServiceBus.Core/Licensing/LicenseSources.cs, src/NServiceBus.Core/NServiceBus.Core.csproj
Removes the registry and app/web.config license sources.
=> licensing sources cleanup

src/NServiceBus.AcceptanceTests/Core/Conventions/When_receiving_unobtrusive_message_without_handler.cs, src/NServiceBus.Core.Tests/StructConventionsTests.cs
fixing string formatting for messages in unit tests found when looking at net7.0 testing
=> fixing string formatting for messages in unit tests

src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/TestingActivityListener.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_ambient_trace_in_message_session.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_ambient_trace_in_pipeline.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_incoming_event_has_trace.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_incoming_message_has_baggage_header.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_incoming_message_has_no_trace.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_incoming_message_has_trace.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_processing_fails.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_processing_incoming_message.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_processing_message_with_multiple_handlers.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_publishing_messages.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_retrying_messages.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_sending_messages.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_sending_messages_from_pipeline.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_sending_messages_with_custom_activity.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_sending_replies.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_subscribing.cs, src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_unsubscribing.cs, src/NServiceBus.Core/Diagnostics/ActivityNames.cs
Change activity names:
- OutgoingMessage➡️SendMessage
- IncomingMessage➡️ReceiveMessage
=> Change activity names

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs
As suggested in https://github.com/Particular/NServiceBus/pull/6449
=> Make ctor of MessageMetadataRegistry public

src/NServiceBus.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt, src/NServiceBus.AcceptanceTests/Core/Conventions/When_receiving_unobtrusive_message_without_handler.cs, src/NServiceBus.AcceptanceTests/Core/Pipeline/When_using_per_uow_component_in_the_pipeline.cs, src/NServiceBus.Core.Tests/CommonObjectBuilder/When_using_nested_containers.cs, src/NServiceBus.Core.Tests/StructConventionsTests.cs, src/NServiceBus.Core/Hosting/HostCreator.cs, src/NServiceBus.Core/ObjectBuilder/Common/CommonObjectBuilder.cs, src/NServiceBus.Core/Utils/AsyncLocal.cs, src/NServiceBus.Persistence.InMemory.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt
Backport of #6458 to release-7.6
=> Fix common object builder uow scope

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/ApprovalFiles/ActivityDecoratorTests.Verify_promotable_headers.promoted.approved.txt, src/NServiceBus.Core.Tests/DataBus/When_applying_the_databus_message_mutator_to_outgoing_messages.cs, src/NServiceBus.Core/DataBus/DataBusReceiveBehavior.cs, src/NServiceBus.Core/DataBus/DataBusSendBehavior.cs, src/NServiceBus.Core/DataBus/IDatabusSerializer.cs, src/NServiceBus.Core/DataBus/SystemJsonDataBusSerializer.cs, src/NServiceBus.Core/Headers.cs, src/NServiceBus.Core/OpenTelemetry/Tracing/ActivityDecorator.cs
=> Change DataBus contenttype header key to restore Gateway compatibility (release-8.0)

src/NServiceBus.Core.Tests/OpenTelemetry/ActivityFactoryTests.cs, src/NServiceBus.Core/OpenTelemetry/Tracing/ActivityFactory.cs
backport of https://github.com/Particular/NServiceBus/pull/6582 to the 8.0 branch
=> Don't create handler activity when incoming message activity isn't set - 8.0

src/NServiceBus.Core/Serializers/XML/XmlSerializer.cs
fixes https://github.com/Particular/NServiceBus/issues/6614
=> Fix SanitizeInput configuration key

src/NServiceBus.Core/Serializers/XML/XmlSerializer.cs
Backport of #6615 to release-7.8 branch
=> XmlSerializer SanitizeInput and SkipWrappingRawXml settings use same configuration key

src/NServiceBus.Core.Analyzer.Tests.Common/Sagas/SagaAnalyzerTests.cs, src/NServiceBus.Core.Analyzer/Sagas/SagaAnalyzer.cs, src/NServiceBus.Core.Analyzer/SymbolExtensions.cs
A fix for analyzer bug in https://github.com/Particular/NServiceBus/issues/6714
=> Fix saga analyzer bug when message is mapped by base type

src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
- Backport of: https://github.com/Particular/NServiceBus/pull/6802
=> Replace Yield with Delay to not hammer the CPU

src/NServiceBus.Core.Analyzer.Tests.Common/AwaitOrCaptureTasksAnalyzerTests.cs, src/NServiceBus.Core.Analyzer.Tests.Common/ForwardCancellationToken/ForwardCancellationTokenFixerTests.cs, src/NServiceBus.Core.Analyzer.Tests.Common/ForwardCancellationToken/ForwardCancellationTokenTests.cs, src/NServiceBus.Core.Analyzer.Tests.Common/ForwardCancellationToken/ForwardFromPipelineTests.cs, src/NServiceBus.Core.Analyzer.Tests.Common/Sagas/ConfigureHowToFindSagaTests.cs, src/NServiceBus.Core.Analyzer.Tests.Common/Sagas/RewriteConfigureHowToFindSagaFixerTests.cs, src/NServiceBus.Core.Analyzer.Tests.Common/Sagas/SagaAnalyzerTests.cs, src/NServiceBus.Core.Analyzer.Tests.Roslyn4/NServiceBus.Core.Analyzer.Tests.Roslyn4.csproj, src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj, src/NServiceBus.Core.Tests/Serializers/XML/Pull_819.cs, src/NServiceBus.Core/DateTimeOffsetExtensions.cs, src/NServiceBus.Core/NServiceBus.Core.csproj, src/NServiceBus.TransportTests/NServiceBusTransportTest.cs, src/NServiceBus.TransportTests/TransportTestPolicy.cs
PR also includes some other miscellaneous updates/cleanup.
Follow-up to #6810
=> .NET 8 RC1 package updates

src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs, src/NServiceBus.AcceptanceTesting/Support/IScenarioWithEndpointBehavior.cs
See the remarks https://learn.microsoft.com/en-us/dotnet/api/system.activator.createinstance?view=net-7.0#system-activator-createinstance-1
=> Remove Activator.CreateInstance<T> and add new() constraint instead

src/NServiceBus.PersistenceTests/Sagas/When_persisting_a_saga_with_an_escalated_DTC_transaction.cs
Rewriting the persistence DTC tests to make sure persisters that support DTC are properly participating in distributed transactions.
=> Adjust the DTC persistence tests

src/NServiceBus.Core/DataBus/DataBusProperty.cs
- Backport of https://github.com/Particular/NServiceBus/pull/6880 to `release8.1`
=> DataBus changes in NServiceBus 8 do not work with NewtonsoftJsonSerializer

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.PersistenceTests/NServiceBus.PersistenceTests.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
=> Update NUnit in projects that Dependabot missed

src/NServiceBus.AcceptanceTests/Core/SubscriptionMigration/AcceptanceTestingTransportServer.cs, src/NServiceBus.AcceptanceTests/EndpointTemplates/ServerWithNoDefaultPersistenceDefinitions.cs, src/NServiceBus.AcceptanceTests/Serialization/When_defining_serializer_with_no_content_type.cs, src/NServiceBus.Core.Tests/Config/When_configuring_transport_twice.cs, src/NServiceBus.Core.Tests/Config/When_starting_an_endpoint_with_already_used_configuration.cs, src/NServiceBus.Core.Tests/Config/When_starting_endpoint_without_configuring_serializer.cs, src/NServiceBus.Core.Tests/Serializers/MessageDeserializerResolverTests.cs, src/NServiceBus.Core/Serialization/SerializationFeature.cs, src/NServiceBus.Core/Serialization/SerializationSettingsExtensions.cs, src/NServiceBus.Core/Serializers/MessageDeserializerResolver.cs
=> Stop setting a default serializer

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
Master should get updated by Dependabot but currently blocked due to potential dependabot bug.
Opened to test that https://github.com/PublicApiGenerator/PublicApiGenerator/issues/301 is fixed.
=> PublicApiGenerator 11.1.0 on release branch fixes the netfx issue

src/NServiceBus.AcceptanceTests/DataBus/When_sending_databus_properties_from_different_environments.cs, src/NServiceBus.Core.Tests/DataBus/FileShare/AcceptanceTests.cs
9.0 backport of:
- #7050
Related to:
- #7043
=> FileShareDataBus acceptance and unit tests for multi environments

src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/Metrics/When_retrying_messages.cs, src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj, src/NServiceBus.Core/OpenTelemetry/Metrics/Meters.cs, src/NServiceBus.Core/Pipeline/Incoming/IncomingPipelineMetricTags.cs, src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveContext.cs, src/NServiceBus.Core/Recoverability/RecoverabilityRoutingConnector.cs
=> Add specific meters for recoverability actions with message type and endpoint name tags

src/NServiceBus.Core/NServiceBus.Core.csproj
Addressing security vulnerabilities on transitive dependencies:
- https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
=> Enforce System.Text.Json versions to address security vulnerabilities

src/NServiceBus.Core/NServiceBus.Core.csproj
Addressing security vulnerabilities on transitive dependencies:
- https://github.com/advisories/GHSA-hh2w-p6rv-4g7w
=> Enforce System.Text.Json version to address security vulnerabilities

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
=> [Backport to 9.1] Remove wrongly added RemoveSourceFileFromPackage elements from ATT project

src/NServiceBus.Core.Tests/Pipeline/IncomingPipelineMetricTagsTests.cs, src/NServiceBus.Core/Pipeline/Incoming/IncomingPipelineMetricTags.cs
Backport of https://github.com/Particular/NServiceBus/pull/7129 to 9.1
=> [Backport to 9.1] Fixes the ingestion of physical messages containing multiple logical messages (#7129)

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/ApprovalFiles/NullableAnnotations.ApproveNullableTypes.approved.txt, src/NServiceBus.Core/Conventions/Conventions.cs, src/NServiceBus.Core/Conventions/ConventionsBuilder.cs, src/NServiceBus.Core/DataBus/ConfigureFileShareDataBus.cs, src/NServiceBus.Core/DataBus/DataBus.cs, src/NServiceBus.Core/DataBus/DataBusDefinition.cs, src/NServiceBus.Core/DataBus/DataBusExtensions.cs, src/NServiceBus.Core/DataBus/DataBusProperty.cs, src/NServiceBus.Core/DataBus/FileShareDataBus.cs, src/NServiceBus.Core/DataBus/IDataBus.cs, src/NServiceBus.Core/DataBus/IDataBusProperty.cs, src/NServiceBus.Core/DataBus/IDatabusSerializer.cs, src/NServiceBus.Core/DataBus/SystemJsonDataBusSerializer.cs, src/NServiceBus.Core/DataBus/UseDataBusExtensions.cs, src/NServiceBus.Core/Headers.cs
Cherry-pick of https://github.com/Particular/NServiceBus/pull/7128
=> Obsolete databus API

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj, src/NServiceBus.AcceptanceTests/Recoverability/When_message_fails_retries.cs, src/NServiceBus.PersistenceTests/NServiceBus.PersistenceTests.csproj, src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
#7120 had auto-merge on but was incomplete. This PR catches up with the leftover work.
=> NUnit4 upgrade

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core/Conventions/Conventions.cs, src/NServiceBus.Core/Conventions/ConventionsBuilder.cs, src/NServiceBus.Core/DataBus/ConfigureFileShareDataBus.cs, src/NServiceBus.Core/DataBus/DataBus.cs, src/NServiceBus.Core/DataBus/DataBusDefinition.cs, src/NServiceBus.Core/DataBus/DataBusExtensions.cs, src/NServiceBus.Core/DataBus/DataBusProperty.cs, src/NServiceBus.Core/DataBus/FileShareDataBus.cs, src/NServiceBus.Core/DataBus/IDataBus.cs, src/NServiceBus.Core/DataBus/IDataBusProperty.cs, src/NServiceBus.Core/DataBus/IDatabusSerializer.cs, src/NServiceBus.Core/DataBus/SystemJsonDataBusSerializer.cs, src/NServiceBus.Core/DataBus/UseDataBusExtensions.cs, src/NServiceBus.Core/Headers.cs
=> Rename the replacement package for databus

src/NServiceBus.AcceptanceTests/Core/JsonSerializer/When_using_system_json_serializer_with_options.cs
add additional test for json serializer with options for .net9
=> add additional test for json serializer with options for .net9

src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/Traces/When_incoming_message_was_delayed.cs, src/NServiceBus.Core/OpenTelemetry/Tracing/ActivityFactory.cs
Backport of https://github.com/Particular/NServiceBus/pull/7264 which fixes https://github.com/Particular/NServiceBus/issues/7209 for the 9.2 branch
=> Fix delayed message null activity - v9.2

src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/Traces/When_incoming_message_was_delayed.cs, src/NServiceBus.Core/OpenTelemetry/Tracing/ActivityFactory.cs
Backport of https://github.com/Particular/NServiceBus/pull/7264 which fixes https://github.com/Particular/NServiceBus/issues/7209 for the 9.1 branch
=> Fix delayed message null activity - v9.1

src/NServiceBus.Core.Tests/Hosting/HostInfoSettingsTests.cs, src/NServiceBus.Core/Hosting/HostInfoSettings.cs, src/NServiceBus.Core/Hosting/HostingComponent.Settings.cs
Backport of #7282 which fixes #7026 for the release-8.2 branch
=> Overriding the host name does not work consistently

src/NServiceBus.Core/Notifications/Notification.cs, src/NServiceBus.Core/OpenTelemetry/Tracing/TracingExtensions.cs
Not a lot but still unnecessary
=> Get rid of closures

src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/Traces/When_processing_message_with_multiple_handlers.cs, src/NServiceBus.Core.Tests/OpenTelemetry/ActivityFactoryTests.cs, src/NServiceBus.Core.Tests/Pipeline/Incoming/InvokeHandlerTerminatorTest.cs, src/NServiceBus.Core.Tests/Unicast/LoadHandlersConnectorTests.cs, src/NServiceBus.Core/OpenTelemetry/Tracing/ActivityFactory.cs, src/NServiceBus.Core/OpenTelemetry/Tracing/IActivityFactory.cs, src/NServiceBus.Core/OpenTelemetry/Tracing/NoOpActivityFactory.cs, src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerTerminator.cs, src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs, src/NServiceBus.Core/Receiving/ReceiveComponent.cs, src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
Backport of https://github.com/Particular/NServiceBus/pull/7319 to `release-9.2`
=> Handler trace span not available to handler pipeline behaviors

src/NServiceBus.PersistenceTests/Sagas/When_using_storage_sessions_concurrently.cs
Test to check for issue related to:
- https://github.com/Particular/NServiceBus.Persistence.Sql/issues/1235
=> Test to check disposal storage session behavior

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/ApprovalFiles/NullableAnnotations.ApproveNullableTypes.approved.txt, src/NServiceBus.Core/Hosting/AddHostInfoHeadersBehavior.cs, src/NServiceBus.Core/Hosting/AuditHostInformationBehavior.cs, src/NServiceBus.Core/Hosting/ExternallyManagedContainerHost.cs, src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs, src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerResults.cs, src/NServiceBus.Core/Hosting/Helpers/AssemblyScanningComponent.cs, src/NServiceBus.Core/Hosting/Helpers/AssemblyValidator.cs, src/NServiceBus.Core/Hosting/Helpers/SkippedFile.cs, src/NServiceBus.Core/Hosting/HostInfoConfigurationExtensions.cs, src/NServiceBus.Core/Hosting/HostInfoSettings.cs, src/NServiceBus.Core/Hosting/HostInformation.cs, src/NServiceBus.Core/Hosting/HostingComponent.Configuration.cs, src/NServiceBus.Core/Hosting/HostingComponent.Settings.cs, src/NServiceBus.Core/Hosting/HostingComponent.cs, src/NServiceBus.Core/Hosting/InternallyManagedContainerHost.cs, src/NServiceBus.Core/Hosting/StartupDiagnostics/DiagnosticSettingsExtensions.cs, src/NServiceBus.Core/Hosting/StartupDiagnostics/Host.cs, src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnosticsWriter.cs, src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnosticsWriterFactory.cs, src/NServiceBus.Core/Hosting/StartupDiagnostics/JsonPrettyPrinter.cs, src/NServiceBus.Core/Hosting/StartupDiagnostics/StartupDiagnosticEntries.cs
=> Enable nullable type annotations in the Core Hosting folder

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt, src/NServiceBus.Core.Tests/ApprovalFiles/NullableAnnotations.ApproveNullableTypes.approved.txt, src/NServiceBus.Core.Tests/Logging/RollingLoggerTests.cs, src/NServiceBus.Core/Logging/ColoredConsoleLogger.cs, src/NServiceBus.Core/Logging/DefaultFactory.cs, src/NServiceBus.Core/Logging/DefaultLog.cs, src/NServiceBus.Core/Logging/DefaultLoggerFactory.cs, src/NServiceBus.Core/Logging/ILog.cs, src/NServiceBus.Core/Logging/ILoggerFactory.cs, src/NServiceBus.Core/Logging/LogLevel.cs, src/NServiceBus.Core/Logging/LogManager.cs, src/NServiceBus.Core/Logging/LoggingDefinition.cs, src/NServiceBus.Core/Logging/RollingLogger.cs, src/NServiceBus.Core/Logging/StringBuilderExtensions.cs
=> Enable nullable type annotations in the Core Logging folder
