src/NServiceBus.Core/EndpointConfiguration.cs

Cherry pick of https://github.com/Particular/NServiceBus/pull/4759 on the `EndpointConfiguration` side which doesn't seem to be affected by the ASP.NET app_data issues we have to consider.

Remove system.web usage from EndpointConfiguration

---

src/NServiceBus.Core/Transports/Msmq/ReceiveStrategy.cs

Connects to https://github.com/Particular/NServiceBus/issues/4792

Poison message in MSMQ fails to be sent to remote error queue and is retried indefinitely

---

src/NServiceBus.AcceptanceTesting/AsyncLocal.cs
src/NServiceBus.AcceptanceTesting/ContextAppender.cs
src/NServiceBus.AcceptanceTesting/ContextAppenderFactory.cs
src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs

CallContext flows with the execution context. Meaning even if a Transport internally uses Task.Run the call context set from the acceptance test will float into it.
https://blogs.msdn.microsoft.com/pfxteam/2012/06/15/executioncontext-vs-synchronizationcontext/
Arguably it might be better to use AsyncLocal and upgrade to 4.6 and higher since CallContext might be not Core compliant (haven't checked).  I would prefer the AsyncLocal solution.
With that, we can make sure there is always a ScenarioContext available without being exposed to the inlining of the static context assignment into the factory and then run into races where scenario context is suddenly null.

Use AsyncLocal for ContextAppender

---

guidelines/design-guidelines.md

This will be announced once merged as a reminder to downstream component maintainers

Document "Production ready by default" design principle

---

src/NServiceBus.Core.Tests/Serializers/Json/JsonMessageSerializerTest.cs
src/NServiceBus.Core/Serializers/Json/XContainerJsonConverter.cs

ie when the `XContainer` property value is null

Avoid null ref in XContainerJsonConverter

---

src/NServiceBus.Core.Tests/StandardsTests.cs
src/NServiceBus.Core/Licensing/LicenseExpiredForm.Designer.cs
src/NServiceBus.Core/Licensing/LicenseExpiredForm.cs
src/NServiceBus.Core/Licensing/LicenseExpiredFormDisplayer.cs

This allows the form to find its embedded resource file at run time.
Fixes #4801

Move license form into NServiceBus.Licensing namespace

---

src/NServiceBus.Core/Transports/Learning/LearningTransportDispatcher.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportHeaders.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs

Instead of using the diagnostic TTBR header, the learning transport now uses the `DiscardIfNotReceivedBefore` delivery constraint to determine the message is supposed to have a TTBR value set. This value is transferred to the receiving endpoint in a custom header that is removed by the receiver before passing the message along for processing. The ensures that the header is not propagated incorrectly when if the message is forwarded for any reason.
Addresses the problem described in #4807

Use TTBR delivery constraint & custom header in learning transport

---

src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_publishing_from_sendonly.cs

Fix case of hardcoded queue name to be consistent with case of the created queue
Fixes #4812
Tested with SQS and MSMQ

Fix case of hardcoded queue name

---

src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_publishing_from_sendonly.cs

different attempt to fix https://github.com/Particular/NServiceBus/issues/4812
Should be more reliable instead of hard-coding values.
@ahofman can you verify this resolves the issue as well?

Use conventions to translate endpoint address

---

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj
src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj
src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj

This ensures that the source files included in the package via the contentFiles mechanism have the correct Compile build action instead of Content.
It should be possible to directly use the existing Compile items and update them to set pack=true, but there appears to be a bug right now where doing that breaks if the project is multi-targeted, ending up with no files in the package. 😢

Fix the build action for the source packages

---

src/Directory.Build.props
src/Directory.Build.targets
src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj
src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
src/NServiceBus.sln

This adds some changes related to updating to the .NET Core 2.0 Preview 2 release.
I noticed that the items being included in the project files so they would be packed were actually showing up in Solution Explorer, so I added `<Visible>false</Visible>` to hide them
I also change them from `Content` to `None` items since that's a more correct build action for them, and I verified that the files still show up in the resulting packages. It appears the the problem with Compile items might just be exclusive to that single build action item.
I also had to suppress the newly introduced NU1701 warning, which informs you if a package you're referencing is being referenced via the .NET Framework shim instead of it having a native .NET Core/.NET Standard target.
It would be ideal if we could …

.NET Core 2.0 Preview 2 changes

---

src/Directory.Build.targets
src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.Core/NServiceBus.Core.csproj

This ensures that the PDBs will be included in the package. Before, there was a timing issue about when the item was evaluated and if the file already existed on disk. 
Once we no longer need the workaround for https://github.com/NuGet/Home/issues/4790, we can reenable GeneratePackageOnBuild, which seems to make everything work correctly with needing to be wrapped in the target.
I also went ahead and moved the logic into Directory.Build.targets instead of having it in both locations.

Ensure PDBs are included in package

---

src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
src/NServiceBus.Core.Tests/AssemblyScanner/When_directory_with_handler_dll_is_scanned.cs
src/NServiceBus.Core.Tests/AssemblyScanner/When_scanning_directory_with_nested_directories.cs
src/NServiceBus.Core.Tests/AssemblyScanner/When_scanning_top_level_only.cs
src/NServiceBus.Core.Tests/Config/When_scanning_assemblies.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerConfiguration.cs

As mentioned in https://github.com/Particular/NServiceBus/pull/4818#issuecomment-312367859, we need to scan AppDomain assemblies by default for .NET Core, so this goes ahead and makes it the default for both frameworks.
I suppose we could make this `true` for .NET Core only, but I'd prefer to keep the behavior the same if at all possible.
As part of this change, we'll need to update docs and list it in the upgrade guide.

Scan AppDomain assemblies by default

---

README.md
src/NServiceBus.Core.Tests/StandardsTests.cs
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs
src/NServiceBus.Core/Persistence/Learning/LearningSynchronizedStorageSession.cs
src/NServiceBus.Core/Persistence/Learning/SagaPersister/SagaStorageFile.cs
src/NServiceBus.Core/Serializers/SimpleJson/EnumAwareStrategy.cs
src/NServiceBus.Core/Serializers/SimpleJson/SimpleJson.g.cs

Connects to https://github.com/Particular/PlatformDevelopment/issues/300
Replaces internal `Newtonsoft.Json` usage with `SimpleJson`:
- Learning saga persister doesn't have to be backward compatible therefore we can replace the usage directly. There are no writers and readers available in `SimpleJson` therefore a `StreamWriter` and `StreamReader` is directly used
- `InMemorySagaPersister` stores sagas InMemory of the running endpoint. When a user shuts down the endpoint all the data is gone. Therefore no backward compatibility is needed.

Replace Newtonsoft.Json usage with SimpleJson

---

GitVersion.yml

Changing the prerelease tag to something that sorts higher than "alpha" but lower than "beta" gets us out of needing to tag each release like we're currently needing to do. The lower commit count metadata value won't be a problem this way.

Change develop release tag to alpharelease

---

src/NServiceBus.Core/Logging/ColoredConsoleLogger.cs

While testing some assembly loading scenarios, I tried to run an endpoint on linux, and it blew up about missing kernel32.dll. I had no idea we had a `DllImport` lurking in the code.
From what I can tell, using `Environment.UserInteractive` should be a decent replacement for the previous code that was attempting to see if standard output was available.

Replace P/Invoke with managed equivalent

---

src/NServiceBus.AcceptanceTests/Timeout/When_timeout_storage_is_unavailable_temporarily.cs

Should fix some of the https://github.com/Particular/NServiceBus.Transport.Msmq/pull/29 which result in a dependency not resolvable. This is caused by having multiple implementations of IQueryTimeouts registered and therefore LightInject not able to resolve while Autofac would just pick the latest. I think that test would probably also fail using other containers not using the autofac approach.

Avoid duplicate service registrations

---

src/NServiceBus.Core/Pipeline/Outgoing/ImmediateDispatchTerminator.cs

Remove need to call ToArray() in case when an array is already passed (is the case when batched dispatches are passed to the terminator)
Another option would have been to break the public types but I felt this is unnecessary.

Remove need to call ToArray() in case when an array is already passed

---

src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/Reliability/Outbox/Outbox.cs

Considering the following
* the MSTDC service warning cannot run on  net core
* we dont care if it succeeds
* just because an endpoint is running on a machine with the outbox it is still be valid to have other services on the machine that rely on msdtc
* this would be better handled in guidance https://github.com/Particular/docs.particular.net/pull/2967
* means we can drop the reference to System.ServiceProcess

Remove dtc warning

---

src/Directory.Build.targets

This uses the official TFM-specific content extension point introduced in https://github.com/NuGet/NuGet.Client/pull/1255 to add the PDBs to the packages.
CC: @SimonCropp

Use official extension point to add PDBs

---

src/NServiceBus.Core.Tests/Logging/DefaultFactoryTests.cs
src/NServiceBus.Core/Logging/DefaultFactory.cs
src/NServiceBus.Core/NServiceBus.Core.csproj

Another attempt to get rid of our System.Web dependency. As mentioned in https://github.com/Particular/NServiceBus/pull/4851#issuecomment-315615137, this first checks to see if System.Web is already loaded, and if it is, uses reflection to get access to the parts we need.
This means we'll use AppData for the default log location if we're running in an ASP.NET application, but otherwise we'll use `AppDomain.CurrentDomain.BaseDirectory`.
CC: @SimonCropp

Remove System.Web dependency by using reflection

---

src/NServiceBus.Core.Tests/Causation/AttachCausationHeadersBehaviorTests.cs
src/NServiceBus.Core/Causation/AttachCausationHeadersBehavior.cs

Relates to: https://groups.google.com/forum/#!topic/particularsoftware/gSnIX2VYywg
TL;DR; It's hard for user code to get access to the conversation id because
* The conversation id will be set in the outgoing physical stage if not already present
* there is no guaranteed order of behaviors in the same stage
* the `IRoutingContext` stage is not the best stage to add a behavior interested in conversation ids as there are other messages going through that stage as well (audits, forwarded messages)
It seems like all other behaviors adding headers are already running in the logical phase anyway. So it seems to be a reasonable change to switch this behavior as well, so it is safe to check the headers within the physical stage.
This shouldn't cause breaking changes as it's not really intended to …

Move AttachCausationHeadersBehavior into IOutgoingLogicalMessage stage

---

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.Core/NServiceBus.Core.csproj

Mono.Cecil has fixed its bug around corrupting embedded SourceLink info and Fody has been updated with the fix, so we can actually get working SourceLink support now!

Add SourceLink support

---

src/NServiceBus.ContainerTests/When_building_components.cs

Adds an additional test for verifying container behavior.
The test verifies that when building all items of a type that the result is an empty array in the event that no types have been registered.  This bug was discovered as a result of https://github.com/Particular/NServiceBus.Persistence.Sql/issues/128. The behavior is different between Ninject and other containers so this verifies uniformity.

Add test for building lists of objects

---

src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs

noticed while testing published endpoints outside of a solution folder structure that the exception message is not super helpful regarding how to resolve it.
Thoughts about the wording?

Improve the exception message on how to resolve the issue

---

src/NServiceBus.Core/Hosting/Helpers/AssemblyValidator.cs
src/NServiceBus.Core/NServiceBus.Core.csproj

This simplifies the `AssemblyValidator` logic by using `AssemblyName` to get the public key token instead of using the System.Reflection.Metadata package.

Simplify AssemblyValidator by using AssemblyName

---

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj

It works with NUnit 3.7.1 now, after reaching out to the author to point out that it wasn't working: https://bitbucket.org/zastrowm/nunit.applicationdomain/issues/23/support-nunit-371.

Update NUnit.ApplicationDomain to 11.0.0

---

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.Core/Licensing/Browser.cs
src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/ConcreteProxyCreator.cs
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/ObjectBuilder/LightInject/LightInject.g.cs
src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj

This is all that has to change for us to target .NET Standard instead of .NET Core.
Once #4882 is merged we should be able to drop the Microsoft.CSharp reference as well.

Target .NET Standard 2.0 instead

---

src/NServiceBus.AcceptanceTests/Core/UnitOfWork/TransactionScope/When_using_timeout_greater_than_machine_max.cs
src/NServiceBus.Core.Tests/Settings/SettingsHolderTests.cs
src/NServiceBus.Core/Settings/SettingsHolder.cs
src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWork.cs

This gets us one step closer to having no dependency on `System.Configuration`/`System.Configuration.ConfigurationManager`.
Replaces #4887
docs PR: https://github.com/Particular/docs.particular.net/pull/3043

Remove ConfigurationErrorsException usage

---

src/NServiceBus.Core/Licensing/LicenseManager.cs
src/NServiceBus.Core/Licensing/LicenseSources.cs
src/NServiceBus.Core/NServiceBus.Core.csproj

This cleans up the old, undocumented registry locations, and adds new machine-level and user-level file locations.
It also cleans up the two different per-project locations and has a single location that doesn't need a subfolder.
This also brings in the latest licensing package, which makes the registry license sources completely optional. 
I think there's a case to be made for now being the time to drop the registry license locations altogether. 
If we can agree on doing that, then I can add that to this PR.
CC @DavidBoike @adamralph

Clean up license sources

---

src/NServiceBus.Core/Licensing/LicenseSources.cs
src/NServiceBus.Core/NServiceBus.Core.csproj

This ensures that if the same license is found in more than one location (where same means the same expiration date) then we prefer the API-provided licenses over the convention-based locations.
The package update made a minor tweak the ordering of the file locations to make the precedence order be per-project, per-user, machine-global,
There's an argument to be had that the app config license sources should also come before the standard sources, but if we moved those, then we'd get into the situation mentioned in https://github.com/Particular/NServiceBus/pull/4882#discussion_r132151055 where we'd pick the app config license over the file license and log a warning.

Adjust license source ordering

---

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingLogicalMessageContextTests.cs
src/NServiceBus.Core/Pipeline/Outgoing/OutgoingLogicalMessageContext.cs

This fixes #4860 where updating a message (that is a dynamic proxy type of an interface) in the outgoing pipeline will see the `MessageType` get updated to the proxy'd type. That will cause the message to fail during outbound serialization.

Fix proxy message updates

---

src/NServiceBus.Core/NServiceBus.Core.csproj

While testing a preview3 daily SDK release, I noticed that while the problem of there being too many reference assemblies listed in the package, there was now an issue where some were missing. I filed https://github.com/dotnet/sdk/issues/1469 and discovered that there is a workaround for now until the underlying issue is solved.

Work around reference assembly packaging issue

---

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj

Whenever you reference a package that only has a netfx target, the compat shim is used to allow it to be referenced from netcoreapp2.0 or netstandard2.0. Instead of suppressing the warning globally (and potentially missing it for a newly added package), it's now suppressed per-package.
The warning suppression doesn't currently flow transitively to the package's dependencies, so I had to add a direct reference to ApprovalUtilities to suppress it as well.

Suppress compat shim warning on a per-package basis

---

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
src/NServiceBus.Core.Tests/Timeout/TimeoutMessageReceiverTests.cs
src/NServiceBus.Core/Persistence/InMemory/TimeoutPersister/InMemoryTimeoutPersister.cs
src/NServiceBus.Core/Timeout/Hosting/Windows/TimeoutPersisterReceiver.cs

Connects to https://github.com/Particular/PlatformDevelopment/issues/1388
Update the timeout polling in v5 to act more like v6 by introducing a wait between polls.

Add wait to timeout poller

---

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
src/NServiceBus.AcceptanceTesting/Support/EndpointBehavior.cs
src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
src/NServiceBus.AcceptanceTests/EndpointTemplates/EndpointCustomizationConfigurationExtensions.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs

As we're running tests in parallel, it probably makes more sense to write to the testcontex instead to the console directly.
this has the disadvantage that we have to tie the testing framework to nunit, but afaik, we're using nunit everywhere as of now and we would have to find a better way to enable other testing frameworks instead as the problem is the same on other testing frameworks.
Note: this currently doesn't really seem to change behavior, as TestContext.Write has a bug: https://github.com/nunit/nunit3-vs-adapter/issues/368

Write output to TestContext instead to the console

---

src/NServiceBus.AcceptanceTests/NServiceBusAcceptanceTest.cs
src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/Unicast/Transport/Config/TransportExtensions.cs
src/NServiceBus.Core/Unicast/Transport/TransportConnectionString.cs

This is currently branched on top of #4882, so this needs to be rebased to develop after #4882 is merged.
This is an approach to removing the last dependency on the `System.Configuration.ConfigurationManager` package. At the moment, the `ConnectionStringName` API has been removed from the netstandard2.0 target, which would be the first place where we have public API difference between the two targets. If we're OK with this approach, we could go ahead and add an obsolete for the API that would be specific to the netstandard2.0 target as well.
Alternatively, we could just stop supporting this on net452 also, and then the API would be the same for both targets.
Thoughts?

Remove app config connection string API

---

src/NServiceBus.AcceptanceTesting/Scenario.cs
src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
src/NServiceBus.AcceptanceTests/NServiceBusAcceptanceTest.cs

It seems that certain downstreams (e.g. ASB) have issues with the async-local usage to track the current context which is used for logging. If downstreams run code which for some reason looses the logical call context, it will result in null-ref exceptions when trying to write to the log.
We need the asynclocal approach to run tests in parallel though.
It would be possible to allow downstreams to provide their custom logger factory, so that they can switch to use statics which works as long as tests aren't run in parallel. With the changes in the code, ASB can for example provide a custom logger like this:
```
namespace NServiceBus.AcceptanceTests
{
public partial class NServiceBusAcceptanceTest
{
[OneTimeSetUp]
public void OneTimeSetup()
{
Scenario.GetLoggerFactory = ctx => new …
```

Support custom logger for acceptance tests

---

guidelines/coding-guidelines.md

I find the current header structure difficult to follow. This is an attempt to simplify it.

simplify header structure for dependencies

---

src/NServiceBus.Core/Unicast/Transport/TransportConnectionString.cs

This fixes one inspection that is visible in VS and is related to a NetStandard2_0 `#if`.

Update for NetStandard inspections

---

src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs

This is to help us figure out why the TTBR test (and I suspect others) are sometimes slow.
This causes the TTBR test fail now and then since its time sensitive

Log when learning transport starts to poll

---

src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
src/NServiceBus.TransportTests/TransportTestLoggerFactory.cs

ping @dbelcham 
Configures a simple logger for transport tests to output log statements from the transport tests. Note that all log calls are printed, regardless whether the test succeeds or fails.

Configure logger for transport tests

---

src/NServiceBus.AcceptanceTesting/ContextAppender.cs
src/NServiceBus.AcceptanceTesting/ContextAppenderFactory.cs
src/NServiceBus.AcceptanceTesting/ScenarioContext.cs
src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs

relates to https://github.com/Particular/NServiceBus/issues/4925
Add additional information to the log output for acceptance tests:
* the logger name (trivial)
* timestamp (trivial)
* the endpoint name (non-trivial)
sample log produced by this PR:
```
09:22:05 Debug AMessageIsAudited.EndpointWithAuditOn: Finished message a07ddffb-7927-40cd-a4bd-a7df00796af3
09:22:05 Debug AMessageIsAudited.EndpointWithAuditOn: Completing processing for c:\temp\0-1506\AMessageIsAudited.EndpointWithAuditOn\c849c038-0268-4b2f-94f2-e2362c885e69.metadata.txt(c:\temp\0-1506\AMessageIsAudited.EndpointWithAuditOn\.pending\ed1e0efd-3fa2-4a9e-a602-7ac456fd7677\c849c038-0268-4b2f-94f2-e2362c885e69.metadata.txt), exception (if any): 
09:22:05 Debug AMessageIsAudited.AuditSpyEndpoint: Procesing message …
```

Logging improvements

---

GitVersion.yml

Moving beta creation back to develop in a previous commit missed updating the `GitVertion.yml` file to reflect that `develop` should be beta and `release-*` should be rc

Update GitVersion yml

---

src/NServiceBus.Core/InitializableEndpoint.cs
src/NServiceBus.Core/Unicast/Transport/TransportConnectionString.cs

This makes a few improvements to the transport connection string settings. We now don't try to get a connection string at all if one is not required.
The warning about using a connection string from app.config only shows up if there is actually a named connection string in the file. Otherwise, you'll just get the exception about not having a connection string.
I added the example connection string to the netstandard2.0 version of the message as well.
The net452 error message also got some improvements.

Connection string tweaks

---

src/NServiceBus.Core.Tests/ApprovalTestConfig.cs

this was to work around a bug in an earlier version on approval tests. and is no longer reauired

remove release filter on reporter config

---

src/NServiceBus.Core.Tests/API/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/obsoletes.cs

Can't have the types in both core and in new msmq package unfortunately. Causes "type found in both assemblies bla blah" errors for users.

Remove msmq obsolete messages

---

src/NServiceBus.Core/InitializableEndpoint.cs
src/NServiceBus.Core/Unicast/Transport/TransportConnectionString.cs

A transport connection string will once again always be looked for, even when it's not mandatory.
Fixes #4961

Always try to get a connection string

---

src/NServiceBus.AcceptanceTesting/Support/SubscriptionBehavior.cs
src/NServiceBus.AcceptanceTesting/Support/SubscriptionEventArgs.cs
src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_unsubscribing_from_event.cs
src/NServiceBus.AcceptanceTests/Routing/When_base_event_from_2_publishers.cs
src/NServiceBus.AcceptanceTests/Routing/When_publishing.cs
src/NServiceBus.AcceptanceTests/Routing/When_publishing_an_event_implementing_two_unrelated_interfaces.cs
src/NServiceBus.AcceptanceTests/Routing/When_publishing_an_interface.cs
src/NServiceBus.AcceptanceTests/Routing/When_publishing_an_interface_with_unobtrusive.cs
src/NServiceBus.AcceptanceTests/Routing/When_publishing_using_base_type.cs
src/NServiceBus.AcceptanceTests/Routing/When_publishing_with_overridden_local_address.cs
src/NServiceBus.AcceptanceTests/Sagas/When_started_by_base_event_from_other_saga.cs
src/NServiceBus.AcceptanceTests/Versioning/When_multiple_versions_of_a_message_is_published.cs

While fixing https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/261 we detected that the build started suddenly failing. All tests that used
```
if (s.SubscriberReturnAddress.Contains("Subscriber1"))
```
where subjected to this since ASQ ToTransportAddress lower-cases all queues. Using the `SubscriberReturnAddress `is not a safe way to check whether an endpoint is subscriber with message driven pubsub. This was never detected in the core because the learning transport has native pubsub.
This PR introduces `SubscriberEndpoint `alongside with `SubscriberReturnAddress` since there is one test that still requires `SubscriberReturnAddress`. See more details in the inline comments

SubscriberReturnAddress can be case sensitive since it is changed according to the transports address translation rules

---

src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs

This is just a spike/discussion to decide if we should remove the code in the scanner that looks for message that are referenced by a handler. v6.3 is able to load messages on the fly so its no longer needed.
AutoSubscribe is driven by the `T` in `IHandleMessages<T>` so not needed there either.
Only thing that could break is user code that relies on all messages being available in the scanned types collection? (but that isn't waterproof as proven by: https://github.com/Particular/NServiceBus/pull/4635 )

Remove code to detect unobtrusive messages used by handlers

---

src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_dispatch_fails_on_removal_SendsAtomicWithReceive.cs
src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_dispatch_fails_on_removal_TXScopes.cs
src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_timeout_dispatch_fails.cs
src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_timeout_storage_fails.cs
src/NServiceBus.AcceptanceTests/Core/Timeout/CyclingOutageTimeoutPersister.cs
src/NServiceBus.AcceptanceTests/Core/Timeout/When_timeout_storage_is_unavailable_temporarily.cs
src/NServiceBus.AcceptanceTests/DelayedDelivery/When_using_special_characters_in_headers.cs
src/NServiceBus.AcceptanceTests/Recoverability/When_message_is_deferred_by_delayed_retries_using_dtc.cs
src/NServiceBus.AcceptanceTests/Recoverability/When_using_special_characters_in_headers.cs
src/NServiceBus.AcceptanceTests/Sagas/When_sagas_share_timeout_messages.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_expired.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_expired_convention.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_not_expired.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_used_with_unobtrusive_mode.cs
src/NServiceBus.AcceptanceTests/Timeout/When_timeout_storage_is_unavailable_temporarily.cs

in testing shaves 20-30 secs of an acc test run. 
given sql persistence runs them 4 times (sql server core+net, mysql, oracle), it will speed up sql CI cc @Particular/sqlpersistence-maintainers

speed up some tests

---

src/NServiceBus.Core/NServiceBus.Core.csproj

The 1.0.0 version of the package contains some fixes around the usage of `GetFolderPath` to find license file locations.

Update Particular.Licensing.Sources to 1.0.0

---

src/NServiceBus.TransportTests/NServiceBusTransportTest.cs

We need to stop using `.` in environment variable names because `.` is not a valid character for them on linux and macOS.

Change to unix-compatible environment variable name

---

src/NServiceBus.AcceptanceTests/ConfigureEndpointLearningPersistence.cs
src/NServiceBus.AcceptanceTests/Core/Persistence/When_a_persistence_does_not_support_outbox.cs
src/NServiceBus.AcceptanceTests/Core/Persistence/When_a_persistence_does_not_support_saga.cs
src/NServiceBus.AcceptanceTests/Core/Persistence/When_a_persistence_does_not_support_subscriptions.cs
src/NServiceBus.AcceptanceTests/Core/Persistence/When_a_persistence_does_not_support_timeouts.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/Persistence/PersistenceStartupTests.cs
src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs
src/NServiceBus.Core/Persistence/StorageType.cs
src/NServiceBus.Core/Reliability/Outbox/Outbox.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs
src/NServiceBus.Core/Sagas/Sagas.cs

Closes #3921 
There are still types left in the `NServiceBus.Persistence` namespace so users wouldn't notice this since they would have `using NServiceBus` in the same file. Thinking that we don't need to mention this in the upgrade guide?

Move StorageType to root namespace

---

src/NServiceBus.AcceptanceTests/Core/CriticalError/When_raising_critical_error_from_a_handler.cs

The critical error action is raised on a dedicated thread using `Task.Run`. @bording noticed this test failing from time to time (on the linux builds) and we believe this might be the reason for the failing test.

Avoid race condition due to async critical error action

---

src/NServiceBus.Core/Pipeline/Outgoing/SerializeMessageConnector.cs

fixes https://github.com/Particular/NServiceBus/issues/4794
Decided to not remove the deduplication code altogether at this point as the current behavior is quite hard to follow for certain edge cases related to complex inheritance chains.

Retain order when deduplicating message types

---

src/NServiceBus.AcceptanceTests/Routing/When_extending_command_routing.cs

ASQ had a bug fixed, which was causing transport address not to be returned in correct form (lower case). This ATT is not taking into consideration transport specific nuances, and it shouldn't. What it should do, is use an a transport translated address in the criteria.
This will unblock https://github.com/Particular/NServiceBus.Persistence.AzureStorage/issues/170 and https://github.com/Particular/NServiceBus.AzureStorageQueues/issues/273

Select destination using transport agnostic criteria

---

src/NServiceBus.AcceptanceTests/EndpointTemplates/Requires.cs

At the moment when a transport wants to define additional requires steps it needs to come up with its own name for the requires file. This is what we did it ASB
```
public static class TestRequires
{
public static void ForwardingToplogy()
{
if (!TestSuiteConstraints.Current.IsForwardingTopology)
{
Assert.Ignore("Ignoring this test because it requires the forwarding topology to be configured.");
}
}
public static void EndpointOrientedToplogy()
{
if (!TestSuiteConstraints.Current.IsEndpointOrientedTopology)
{
Assert.Ignore("Ignoring this test because it requires the endpoint oriented topology to be configured.");
}
}
}
```
TestSuiteConstraints is already partial and can be extended customized. Would be nice if Requires could be as well. So that we can add those 'guards' to the requires file

Partial requires

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/DataBus/DataBusProperty.cs

fixes https://github.com/Particular/NServiceBus/issues/4805
@SimonCropp since you mentioned this behavior breaking certain serializers, do you have a sample to verify this PR does solve the issue?

Add default constructor to DataBusProperty

---

src/NServiceBus.AcceptanceTests/Core/Causation/When_overriding_conversation_id_generation.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/Causation/AttachCausationHeadersBehaviorTests.cs
src/NServiceBus.Core/Causation/AttachCausationHeadersBehavior.cs
src/NServiceBus.Core/Causation/CustomConversationIdContext.cs
src/NServiceBus.Core/Causation/MessageCausation.cs
src/NServiceBus.Core/Causation/MessageCausationConfigurationExtensions.cs

After talking to @SimonCropp I realized that the use case for custom conversation ids is not to override the whole thing but rather override certain messages. This API should convey this usage better.
@SimonCropp @weralabaj what do you think?
Relates to #4992

Use a TryGet style API for conversation ids instead

---

src/NServiceBus.Testing.Fakes/TestableInvokeHandlerContext.cs

The properties docs somehow got lost on the PR to deprecate HandleCurrentMessasgeLater. This does cause issues when consuming the testing.fakes package as NServiceBus.Testing does verify the presence of docs on public APIs.

Add missing docs back

---

src/NServiceBus.AcceptanceTests/Core/Hosting/When_endpoint_starts.cs

The tests writes the diagnostics file at `static string basePath = Path.Combine(TestContext.CurrentContext.TestDirectory, TestContext.CurrentContext.Test.ID);`. The test.id is consistent across test runs, which means that there is a very high chance that a json config file already exists there. This wouldn't be an issue in the happy path as we're overwriting the file, but if the serialization/writing of the json file fails for some reason, the test still succeeds because:
* we swallow exceptions when writing the diagnostics file
* the assert only checks the presence of a file
Deleting files before running the tests allows to have the file around for manual inspection after a successful test.

Ensure test fails on diagnostic exceptions

---

src/NServiceBus.Core/Audit/Audit.cs

Adds an audit diagnostics section when an audit queue has been configured.
e.g.
"Audit": {
"AuditQueue": "test",
"AuditTTBR": "42:0:00:00"
},

Add audit diagnostics section

---

src/NServiceBus.AcceptanceTests/Audit/When_auditing_message_with_TimeToBeReceived.cs
src/NServiceBus.AcceptanceTests/Recoverability/When_message_with_TimeToBeReceived_fails.cs

These two tests have been quite flaky. The logs show that the message takes indeed longer than 3 seconds from the send to being received. One potential explanation could be, that parallel running tests could cause this. I suggest to mark this test as non-parallelizable to eliminate that potential cause and see whether the tests still fail from time to time.

Mark flaky test as NonParallelizable

---

src/NServiceBus.Core/Recoverability/Recoverability.cs

Sets the immediate/delayed retry and error queue settings on the diagnostics file.
Note that due to the changes in the feature, there is a slight change in time when we resolve the settings. But as it's not intended to set those values somehow in feature setups (and we don't provide any API to do so), I don't see this as an issue.
Sample output:
"Recoverability": {
"ImmediateRetries": 0,
"DelayedRetries": 0,
"DelayedRetriesTimeIncrease": "0:00:10",
"ErrorQueue": "error",
"UnrecoverableExceptions": ["NServiceBus.MessageDeserializationException"]
}

Add recoverability diagnostics section

---

src/NServiceBus.Core/Transports/Learning/AsyncFile.cs
src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs
src/NServiceBus.Core/Transports/Learning/ILearningTransportTransaction.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
src/NServiceBus.Core/Transports/Learning/NoTransaction.cs

We've seen the acceptance tests fail now and then due to file lock issues. @mikeminutillo ran into this as well while testing the learning transport together with ServiceControl.
This PR makes sure that we don't exit "File.Move" until the file is unlocked.

Make sure File.Move leaves a unlocked file behind

---

src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeQueueCreator.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportInfrastructure.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportSettingsExtensions.cs
src/NServiceBus.AcceptanceTests/Core/Installers/When_creating_queues.cs
src/NServiceBus.AcceptanceTests/Core/Installers/When_installers_enabled.cs
src/NServiceBus.AcceptanceTests/Core/Installers/When_installers_not_enabled.cs
src/NServiceBus.Core/InitializableEndpoint.cs

Create queues only when installer are enabled and queue creation has not been explicitly disabled.
Resolve #5023

Fix queue creation logic

---

src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportInfrastructure.cs
src/NServiceBus.AcceptanceTests/Core/TransportSeam/When_initializing_transport.cs

Looking at #5032, I noticed the TransportSendInfrastructure PreStartupCheck was left out.
While I think this demonstrates that we're currently calling this in a really weird place in the sequence, I think it make sense to include it in the test so we can observe the change when/if we improve it.

Add TransportSendInfrastructure.PreStartupCheck to test

---

src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnostics.cs
src/NServiceBus.Core/Persistence/PersistenceStartup.cs

Outputs:
```
"Persistence":{
"Sagas":{
"Type":"NServiceBus.LearningPersistence",
"Version":"7.0.0"
},
"Timeouts":{
"Type":"NServiceBus.InMemoryPersistence",
"Version":"7.0.0"
},
"Subscriptions":{
"Type":"NServiceBus.InMemoryPersistence",
"Version":"7.0.0"
}
}
```
Note that the selected storage for each storage type is listed but we have no way of knowing if they are actually used. Talking to @timbussmann we decided to live with this for now until we redo the "persistence" concept.
This also orders the section by Name ASC

Emit persistence diagnostics

---

src/NServiceBus.AcceptanceTests/Core/Hosting/When_endpoint_starts.cs
src/NServiceBus.Core.Tests/ConventionsTests.cs
src/NServiceBus.Core.Tests/MessageConventionSpecs.cs
src/NServiceBus.Core.Tests/Pipeline/Incoming/SerializeMessageConnectorTests.cs
src/NServiceBus.Core.Tests/Routing/Routers/UnicastSendRouterConnectorTests.cs
src/NServiceBus.Core.Tests/Routing/UnicastPublisherRouterTests.cs
src/NServiceBus.Core.Tests/Unicast/Messages/DefaultMessageRegistryTests.cs
src/NServiceBus.Core/Conventions.cs
src/NServiceBus.Core/ConventionsBuilder.cs
src/NServiceBus.Core/EndpointConfiguration.cs
src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs

Outputs:
```
"Messages":{
"CustomConventionUsed":false,
"NumberOfMessagesFoundAtStartup":1,
"Messages":[
"NServiceBus.AcceptanceTests.Core.Hosting.When_endpoint_starts+MyMessage"
]
}
```
Made a few changes to the message metadata registry to capture if a custom convention was used our not

Add message diagnostics

---

src/NServiceBus.Core/Hosting/HostInformationFeature.cs

Renames the current section and adds more info, output:
```
"Hosting":{
"HostId":"e3342552-4a13-b662-aa77-4461b333c85b",
"HostDisplayName":"ANDREAS2015",
"MachineName":"ANDREAS2015",
"IsServerGC":true,
"GCLatencyMode":1,
"ProcessorCount":8,
"Is64BitProcess":true,
"CLRVersion":{
"Major":4,
"Minor":0,
"Build":30319,
"Revision":42000,
"MajorRevision":0,
"MinorRevision":-23536
},
"WorkingSet":97325056,
"SystemPageSize":4096,
"HostName":"Andreas2015",
"UserName":"andreas.ohlund",
"PathToExe":"C:\\Users\\andreas.ohlund\\AppData\\Local\\JetBrains\\Installations\\ReSharperPlatformVs15_c3a37fcb_000\\JetBrains.ReSharper.TaskRunner.CLR45.x64.exe"
}
```

Add more hosting/environment related diagnostics

---

src/NServiceBus.Core/EndpointConfiguration.cs

When internal container is used:
```
"Container":{
"Type":"internal"
}
```
When external container is used:
```
"Container":{
"Type":"NServiceBus.StructureMap.StructureMapObjectBuilder",
"Version":"7.0.0"
}
```

Add container diagnostics

---

src/NServiceBus.AcceptanceTests/Core/Hosting/When_endpoint_starts.cs
src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnostics.cs

Since that allows us to change to XML if needed (due to pretty printing issues with simplejson) and it better conveys the fact that we don't promise anything around the format

Use .txt ending on the diagnostics file

---

src/NServiceBus.AcceptanceTests/Routing/When_overriding_local_address.cs
src/NServiceBus.Core/Receiving/ReceiveConfigurationBuilder.cs

Followup to #5045. This tweaks the wording of the error message and changes "send only" to "send-only" to be consistent.

Tweak wording of error message

---

src/NServiceBus.Core/InitializableEndpoint.cs
src/NServiceBus.Core/Routing/RoutingComponent.cs

This PR replaces the `TransportInfrastructure` parameter in `Initialize` with a `Func<LogicalAddress,string>` as only the `ToTransportAddress` method of the infrastructure is being used.

Replace TransportInfrastructure with toTransportAddress Func in RoutingComponent.Initialize

---

src/NServiceBus.Core/InitializableEndpoint.cs

fixes https://github.com/Particular/NServiceBus/issues/5061
currently targeting develop. I suggest to release this as beta11.
This went past all tests because we're using the learning transport locally which doesn't use satellites. I wonder how we can test this to avoid such an issue in the future?

Explicitly specify receiving diagnostic properties

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Hosting/StartupDiagnostics/StartupDiagnosticEntries.cs

We need to let downstreams like NSB.Raw set it to avoid transports etc to blow up.
Closes https://github.com/Particular/NServiceBus/issues/5064

Expose the diagnostics entries

---

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
src/NServiceBus.AcceptanceTests/NonDTC/When_sending_a_durable_message.cs
src/NServiceBus.Core/Outbox/OutboxDeduplicationBehavior.cs
src/NServiceBus.Core/Outbox/OutboxSendBehavior.cs
src/NServiceBus.sln.DotSettings

fixes https://github.com/Particular/NServiceBus/issues/5074
I took the same approach as v6 and above using  a `NonDurable` flag. Since the presense of the flag means non durable there is no migration effort since existing users won't have the flag in storage and we'll default to durable messages.
For users with non durable messages the ones that are in flight will be marked as durable but I'd say we can live with that?

Make the outbox honor message durability

---

src/NServiceBus.Core.Tests/TestApprover.cs

This uses `TestContext.CurrentContext.TestDirectory` to find the correct folder, and it will still be correct even when the test assembly has been shadow copied.

Make TestApprover immune to shadow copying

---

src/NServiceBus.Core/Licensing/LogErrorOnInvalidLicenseBehavior.cs

I found it a bit weird that we're logging a highly visible message from the specific behavior's logger. I'd prefer to not see the behavior as the logger but something like "LicenseManager" or just "Licensing". Thoughts?
example:

Log license warnings with the license manager

---

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj

Followup to https://github.com/Particular/NServiceBus/pull/5079#discussion_r151937863, this adds a version range to the AcceptanceTesting package.
Since the AcceptanceTests source package depends on the AcceptanceTesting package, it can/should rely on the transitive NUnit dependency.

Fix NUnit dependency 

---

src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyValidator.cs
src/NServiceBus.Core/NServiceBus.Core.csproj

I was looking at how Mono.Cecil was getting access to assemblies in NuGet packages to load them properly, and I discovered `AppDomain.CurrentDomain.GetData("TRUSTED_PLATFORM_ASSEMBLIES")`. When this is called from a .NET Core application, you get something like the following:
```
C:\ConsoleApp47\ConsoleApp47\bin\Debug\netcoreapp2.0\ConsoleApp47.dll
C:\Users\Brandon\.nuget\packages\libgit2sharp\0.25.0-preview-0033\lib\netstandard1.3\LibGit2Sharp.dll
C:\Users\Brandon\.nuget\packages\nservicebus\7.0.0-beta0008\lib\netstandard2.0\NServiceBus.Core.dll
C:\Program Files\dotnet\store\x64\netcoreapp2.0\newtonsoft.json\10.0.1\lib\netstandard1.3\Newtonsoft.Json.dll
C:\Program Files\dotnet\store\x64\netcoreapp2.0\system.security.cryptography.xml\4.4.0\lib\netstandard2.0\System.Security.Cryptography.Xm …
```

Teach assembly scanner to find assemblies referenced from NuGet packages

---

src/NServiceBus.AcceptanceTests/Core/SelfVerification/ConventionEnforcementTests.cs
src/NServiceBus.AcceptanceTests/Core/SelfVerification/When_running_saga_tests.cs
src/NServiceBus.AcceptanceTests/Core/SelfVerification/When_using_custom_components.cs

Since it causes issues for downstreams.
Eg. raven and nhibernate needs to exclude them https://github.com/Particular/NServiceBus.NHibernate/pull/317/files#diff-099b6f6bdfd884ef1a6672dfe730b45aR19
Talked to @timbussmann and we concluded that none of the tests where relevant for downstreams since failure to comply with them would just blow up the specific test. We only need this to avoid having the core ship bad tests.

Exclude test convention enforcement for shipped tests

---

MAINTAINERS.md

Noticed that there were a lot of references to labels and other things that we don't use in our process anymore.

Update contents of the maintainers docs

---

src/NServiceBus.Core/NServiceBus.Core.csproj

The 2.0.0 version of the package includes a fix to make sure the license file can be found properly when running in a Windows container.
It also improves license verification to avoid thrown unnecessary exceptions.

Update Particular.Licensing.Sources to 2.0.0

---

src/NServiceBus.Core.Tests/StandardsTests.cs
src/NServiceBus.Core/DeepCopy.cs
src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs

During a review of https://github.com/Particular/NServiceBus/pull/5131, we concluded that it would make sense to see whether we could use a deep copy approach which doesn't rely on serialization.
This spike removes the SimpleJson usage from the InMemorySagaPersister and uses a deep copy approach from here: https://github.com/Burtsev-Alexey/net-object-deep-copy
The in memory acceptance tests pass with these changes. I'm not sure what kind of limitations this deep copy mechanism has though or what the difference in performance looks like.
Another solution which might be worth looking at can be found here: https://www.codeproject.com/Articles/1111658/Fast-Deep-Copy-by-Expression-Trees-C-Sharp

Remove SimpleJson usage from in memory saga persistence

---

src/NServiceBus.Core/Logging/ColoredConsoleLogger.cs

This change ensures that when running on linux as a background job, if the terminal is closed, the process won't crash from an unhandled `IOException` bubbling up from `ColoredConsoleLogger`.

Ensure ColoredConsoleLogger doesn't crash process when terminal is lost

---

src/NServiceBus.Core.Tests/ApprovalTestConfig.cs

When ApprovalTests is trying to report that it found a problem with the approval file, `DiffReporter` fails with an exception about not being able to load System.Drawing when the test is being run locally on .NET Core.
This can be avoided by switching to `NUnitReporter` reporter instead. The test will now fail with an actual Assert error message. It does mean that it won't pop up a diff window in that case, but the received approval file is created as usual.

Update ApprovalTests reporter for .NET Core

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus__NET452.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus__NETSTANDARD2_0.approved.txt
src/NServiceBus.Core/Headers.cs

seems the applicate headers concept seems to come from the Gateway as the `HeaderName` property is only used by the gateway as a prefix.
We have no internal usage of the obsoleted header in core, so we should be able to move it to the gateway, I don't think this is supposed to by used by users directly.
based on this doco feedback: https://github.com/Particular/docs.particular.net/issues/3752

remove applicative header comments

---

src/Directory.Build.props
src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.Core.Analyzer.Tests/Helpers/DiagnosticVerifier.cs
src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj
src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.sln

* Adds a project reference to ensure the analyzer is built when building core
* `SkipGetTargetFrameworkProperties` is used to avoid the build error due to target framework incompatibility (analyzer targets netstandard 1.3 which isn't supported by net452)
* copies analyzer and install scripts into the nuget package
please have a look @bording

Include analyzer in core package

---

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
src/NServiceBus.Core.Tests/Serializers/XML/XmlSerializerCacheTests.cs
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/Serializers/XML/Deserializer.cs
src/NServiceBus.Core/Serializers/XML/Serializer.cs
src/NServiceBus.Core/Serializers/XML/XmlSerializerCache.cs

This PR backports XmlSerializer #5166 fix to version 5.
I did the backporting manually, please review it carefully.

XML serializer's type initialization is vulnerable to concurrency

---

src/NServiceBus.Core.Analyzer.Tests/AwaitOrCaptureTasksAnalyzerTests.cs
src/NServiceBus.Core.Analyzer/AwaitOrCaptureTasksAnalyzer.cs

switching to the semantic model is clearly the most expensive operation in the analyzer. Therefore we should try to avoid using the semantic model whenever possible. This PR introduces a pre-check to check the invoked methods for a match with one of the method names from our APIs (e.g. `Send` `Publish` `Stop` etc.) before looking at the full semantic version of the invoked method.
This speeds up invocations for code which doesn't use an NServiceBus API (e.g. the added `Task.Run` test):
before:
after:
for actual analyzer hits, this change as barely any impact:
before:
after:

Avoid querying semantic model when possible

---

src/NServiceBus.Core.Analyzer.Tests/AwaitOrCaptureTasksAnalyzerTests.cs
src/NServiceBus.Core.Analyzer.Tests/Helpers/DiagnosticVerifier.cs
src/NServiceBus.Core.Analyzer.Tests/UniformSessionStubs/IUniformSession.cs
src/NServiceBus.Core.Analyzer.Tests/UniformSessionStubs/IUniformSessionExtensions.cs
src/NServiceBus.Core.Analyzer/AwaitOrCaptureTasksAnalyzer.cs

Adds the `IUniformSession` APIs to the analyzer's list of APIs to check.
This PR also contains unit tests for the uniform session API by copying the uniform session API to the test project to allow the semantic model to resolve the full name of the referenced API. Thanks @danielmarbach for that idea.
This approach has the following disadvantage:
* This copy of the API needs to be kept in sync with the actual uniformsession API
* We also need to reference the test library in the workspace which runs the analyzer
we can also remove the testing part again since it was only used to "implement" the changes.

Add UniformSession API to analyzer

---

src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_excluding_event_type_from_autosubscribe.cs
src/NServiceBus.AcceptanceTests/Core/CoreTestSuiteConstraints.cs
src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_using_autosubscribe_with_missing_publisher_information.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus__NET452.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus__NETSTANDARD2_0.approved.txt
src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs
src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribeSettings.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs

log warnings when autosubscribe isn't able to subscribe to an event handled by the endpoint.

Autosubscribe warnings

---

src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_excluding_event_type_from_autosubscribe.cs

the test wasn't adjusted to the changes of logging errors instead of warnings.

Fix autosubscribe acceptance test by checking for the correct log level

---

src/NServiceBus.AcceptanceTesting/AsyncLocal.cs
src/NServiceBus.AcceptanceTests/NServiceBusAcceptanceTest.cs
src/NServiceBus.AcceptanceTests/Tx/When_receiving_with_dtc_enabled.cs
src/NServiceBus.Core.Analyzer.Tests/Helpers/DiagnosticVerifier.cs
src/NServiceBus.Core.Tests/API/APIApprovals.cs
src/NServiceBus.Core.Tests/ApprovalTestConfig.cs
src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
src/NServiceBus.Core.Tests/Persistence/InMemory/When_persisting_a_saga_with_InMemory_and_an_escalated_DTC_transaction.cs
src/NServiceBus.Core.Tests/Serializers/XML/SerializingNullableTypesTests.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyValidator.cs
src/NServiceBus.Core/Licensing/Browser.cs
src/NServiceBus.Core/Licensing/LicenseManager.cs
src/NServiceBus.Core/Unicast/Transport/Config/TransportExtensions.cs
src/NServiceBus.Core/Unicast/Transport/TransportConnectionString.cs
src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWork.cs

These version-agnostic automatic define constants have been added to the SDK recently, I believe as part of the .NET Core 2.1 SDK.
This ensures that these continue to work as expected even when the actual TFMs change.

Use version-agnostic define constants

---

src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs

ServiceControl requires an async done condition because it needs to fetch the context from the http APIs. This allows us to remove the custom component hack that we had to write to enable this.

Async done condition for ATT framework

---

src/NServiceBus.AcceptanceTesting/Support/EndpointBehaviorBuilder.cs
src/NServiceBus.AcceptanceTesting/Support/WhenDefinition.cs

Similar to #5212 SC sometimes needs to fetch preconditions from the HTTP Apis. This enables an async precondition

Async when condition for ATT framework

---

src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageType.cs

Noticed during some SC related work, that the xml doco on the equality comparison is incorrectly stating that major versions are still taken into account, which isn't the case.

Clarify MessageType equality behavior

---

src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_subscribing_to_scaled_out_publisher.cs
src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_unsubscribing_to_scaled_out_publisher.cs

fixes https://github.com/Particular/NServiceBus/issues/5178 by using concurrent collections instead of a regular list (which can be modified by the different scaled-out instances in parallel and therefore fail the test)

Use concurrent collections to avoid race conditions in acceptance test

---

README.md
src/NServiceBus.Core.Tests/ApprovalFiles/PipelineTests.ShouldCreateCachedExecutionPlan.approved.txt
src/NServiceBus.Core.Tests/DocumentationTests.cs
src/NServiceBus.Core.Tests/StandardsTests.cs
src/NServiceBus.Core/Pipeline/FastExpressionCompiler.g.cs
src/NServiceBus.Core/Pipeline/PipelineExecutionExtensions.cs

Using FastExpressionCompiler to compile the pipeline expression tree

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core/Settings/SettingsHolder.cs

Connects to #5228 
Deprecates `Set<T>(object)` and `SetDefault<T>(object)` in favour of generic versions added in #5228.

Deprecate redundant overloads for Set and SetDefault

---

src/NServiceBus.TransportTests/NServiceBusTransportTest.cs

fixes https://github.com/Particular/NServiceBus/issues/5099
ensure to start & stop the transport infrastructure at the right moment. I put it between creating the queues (https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/InitializableEndpoint.cs#L75) and initializing the receivers (https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/StartableEndpoint.cs#L32)
See https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs#L46 for the shutdown sequence
tested against:

Start and stop transport infrastructure on transport tests

---

src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_reusing_sendoptions_with_delay.cs
src/NServiceBus.Core/DelayedDelivery/DelayedDeliveryOptionExtensions.cs
src/NServiceBus.Core/SendOptions.cs
src/NServiceBus.Core/Unicast/MessageOperations.cs

fixes https://github.com/Particular/NServiceBus/issues/5147
ping @SeanFeldman

Allow SendOptions with delayed delivery constraints to be reused

---

src/NServiceBus.Core.Tests/Serializers/SimpleJsonTests.cs
src/NServiceBus.Core/Serializers/SimpleJson/SimpleJson.g.cs

Even after the changes @timbussmann made in #5131, it there are some other cases that aren't handled that I think we might want to support.
Currently, if a dictionary key isn't a string, `ToString` is called on it, and then it's serialized as a string:
https://github.com/Particular/NServiceBus/blob/f347ae2026e654a4154555d710d945a20fff9c14/src/NServiceBus.Core/Serializers/SimpleJson/SimpleJson.g.cs#L1070
This breaks things like `DateTime` since it's not serialized to the correct format. I would think this almost always the wrong thing to do, since most types are not going to produce a valid string from calling `ToString' on it.

SimpleJson fails with DateTime used as Dictionary key

---

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_autosubscribe_with_missing_publisher_information.cs
src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj
src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj
src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
src/NServiceBus.Persistence.InMemory.AcceptanceTests/NServiceBus.Persistence.InMemory.AcceptanceTests.csproj
src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj

also shortens the test name of `When_using_autosubscribe_with_missing_publisher_information` to avoid exceeding 200 character length path on the build server on PRs.

Target .NET Core 2.1 in test projects

---

GitVersion.yml
src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.AcceptanceTesting/packages.config
src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
src/NServiceBus.AcceptanceTests/packages.config
src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj
src/NServiceBus.ContainerTests/packages.config
src/NServiceBus.Core.Analyzer/GitVersion.yml
src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/packages.config
src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj
src/NServiceBus.Testing.Fakes/packages.config
src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
src/NServiceBus.TransportTests/packages.config

Sign and version the analyzer assembly to allow multiple versions of the analyzer to be loaded into the same solution.
@bording it seemed to me that the originally used GVT version 3.6.5 used by v6 doesn't work well with the .net core SDK project used by the analyzer. Using the 4.0-beta12 seems to work but requires all projects to update as they can't handle to required update of the GitVersion.yml file otherwise. Maybe you've got a better idea instead?

Hotfix 6.5.1

---

src/NServiceBus.AcceptanceTests/Core/Mutators/When_defining_outgoing_message_mutators.cs
src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_autosubscribe_with_missing_publisher_information.cs
src/NServiceBus.Core.Tests/MessageMutators/MutateInstanceMessage/MutateIncomingMessageBehaviorTests.cs
src/NServiceBus.Core.Tests/MessageMutators/MutateInstanceMessage/MutateOutgoingMessageBehaviorTests.cs
src/NServiceBus.Core.Tests/MessageMutators/MutateTransportMessage/MutateIncomingTransportMessageBehaviorTests.cs
src/NServiceBus.Core.Tests/MessageMutators/MutateTransportMessage/MutateOutgoingTransportMessageBehaviorTests.cs
src/NServiceBus.Core.Tests/MessageMutators/MutatorRegistrationExtensionsTests.cs
src/NServiceBus.Core.Tests/Serializers/XML/SerializingNullableTypesTests.cs
src/NServiceBus.Core/MessageMutators/MutateInstanceMessage/MutateIncomingMessageBehavior.cs
src/NServiceBus.Core/MessageMutators/MutateInstanceMessage/MutateOutgoingMessageBehavior.cs
src/NServiceBus.Core/MessageMutators/MutateTransportMessage/MutateIncomingTransportMessageBehavior.cs
src/NServiceBus.Core/MessageMutators/MutateTransportMessage/MutateOutgoingTransportMessageBehavior.cs
src/NServiceBus.Core/MessageMutators/MutatorRegistrationExtensions.cs
src/NServiceBus.Core/MessageMutators/Mutators.cs

Any user registering more than one message mutator [of the same kind](https://docs.particular.net/nservicebus/pipeline/message-mutators) using the [`EndpointConfiguration.RegisterMessageMutator(myMutator)` API](https://docs.particular.net/nservicebus/pipeline/message-mutators#registering-a-mutator) and is not using [Autofac or StructureMap as their DI container.](https://docs.particular.net/nservicebus/dependency-injection/#supported-containers)
Only the last registered mutator of each kind is invoked.
Use the following syntax to workaround the issue by manually register the mutators:
```
endpointConfiguration.RegisterComponents(r => {
r.ConfigureComponent<FooMessageMutator>(DependencyLifecycle.SingleInstance);
r.ConfigureComponent<BarMessageMutator>(DependencyLifecycle.SingleInstance); …
```

When using the explicit registration API only the last registered mutator is invoked

---

src/NServiceBus.Core/Transports/Learning/AsyncDirectory.cs
src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs

It is possible that a file handle is still open although the file APIs already returned, in such a case Directory.Move would fail
Found this issue while trying to run the Monitoring demo on the learning transport

DirectoryBasedTransaction should retry directory move

---

packaging/nuget/tools/init.ps1

Related to a reconfiguration in the website. The POST will continue to be reverse-proxied as necessary on the public website for all old versions of the package we cannot change, but this will be the canonical URL going forward.

Replace URL in init.ps1

---

src/NServiceBus.Core.Tests/Licensing/LicenseManagerTests.cs
src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
src/NServiceBus.Core/Licensing/LicenseManager.cs
src/NServiceBus.Core/Licensing/LicenseReminder.cs
src/NServiceBus.Core/NServiceBus.Core.csproj

log better messages when the license expired and start warning about expiring licenses a few days before the expiration date.

Improve license warnings

---

src/NServiceBus.ContainerTests/When_building_components.cs

As a result of https://discuss.particular.net/t/system-outofmemoryexception-with-iconfigurecomponents-and-dp/856 it is clear that containers need to be able to build recursive types. This test makes sure that all containers will allow this behavior (Unity currently does not).

Add test to confirm recursive types can be built

---

src/NServiceBus.AcceptanceTesting/AcceptanceTestingContainer/AcceptanceTestingContainer.cs
src/NServiceBus.AcceptanceTests/EndpointTemplates/DefaultServer.cs
src/NServiceBus.Core/InitializableEndpoint.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs

Users configuring a container that is immutable after first resolve like Spring.net and SimpleInjector.
Endpoint fails to start with an exception that container registrations can't be altered after first resolve.
Backport of https://github.com/Particular/NServiceBus/pull/5304

Enabling installers cause endpoints to fail during startup when the container used is immutable

---

src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs

As part of making the platform switch to the new Platform package, we realized that when using the MonitoringDemo when you only have binaries or when you have a solution less dotnet core only workflow we always force users to specify the transport directory. This introduces a convention that first looks for a solution file (takes precedence) and then looks for a directory called `.learningtransport` at the same level.
This would also get rid of the Marker.sln that we had to add as part of the MonitoringDemo rework https://github.com/Particular/MonitoringDemo/pull/54/commits/9ba781d1fa764317114ee50ee09fa3f192570484

Smarter convention that discovers either solution file or .learningtransport directory

---

src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs

While working on https://github.com/Particular/MonitoringDemo/pull/51 to let the monitoring demo run on the learning transport, several problems were encountered:
- https://github.com/Particular/NServiceBus/pull/5299#issue-233877697
- https://github.com/Particular/NServiceBus/pull/5299#issuecomment-442411526
- https://github.com/Particular/NServiceBus/pull/5299#issuecomment-444073957
This PR fixes these problems by guarding against the exceptions that can be thrown.
It also prevents a critical error from being raised for a case that can actually be recovered from instead.

Learning transport throws exceptions when there are competing consumers

---

packaging/nuget/nservicebus.acceptancetests.nuspec
packaging/nuget/nservicebus.containertests.nuspec
packaging/nuget/nservicebus.transporttests.nuspec
src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.AcceptanceTesting/packages.config
src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
src/NServiceBus.AcceptanceTests/packages.config
src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj
src/NServiceBus.ContainerTests/packages.config
src/NServiceBus.Core.Analyzer.Tests/NServiceBus.Core.Analyzer.Tests.csproj
src/NServiceBus.Core.Tests.x86/NServiceBus.Core.x86.Tests.csproj
src/NServiceBus.Core.Tests.x86/packages.config
src/NServiceBus.Core.Tests/API/APIApprovals.cs
src/NServiceBus.Core.Tests/App.config
src/NServiceBus.Core.Tests/App_Packages/PublicApiGenerator.8.0.1/ApiGenerator.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/ArgumentExceptionTests.cs
src/NServiceBus.Core.Tests/Msmq/MsmqExtensionsTests.cs
src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
src/NServiceBus.Core.Tests/Persistence/PersistenceExtensionsTests.cs
src/NServiceBus.Core.Tests/packages.config
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/packages.config
src/NServiceBus.Msmq.AcceptanceTests/NServiceBus.Msmq.AcceptanceTests.csproj
src/NServiceBus.Msmq.AcceptanceTests/packages.config
src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj
src/NServiceBus.Testing.Fakes/packages.config
src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj
src/NServiceBus.TransportTests/packages.config

This updates development tooling on the `support-6.5` branch.
This doesn't switch to Particular.Approvals because it has a Json.NET 12 dependency, which conflicts with the 8.0 dependency in core in this branch. However, this branch is using the TestApprover predecessor of Particular.Approvals, so that is good enough to allow approval tests to work on TeamCity properly.
Note: It is okay for this to be squashed.

Update development tooling

---

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj
src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj

This PR includes the following bits of cleanup:
- It removes a workaround that should no longer be needed now that the build agents are on VS 2017 15.9.
- It adds a workaround notice for the places where we had to do something special to include source files in packages due to the projects being multi-targeted.
- It stops setting `OutputPath` since we have no reason do it.

Miscellaneous project file cleanup

---

src/NServiceBus.AcceptanceTesting/Support/FailTestOnErrorMessageFeature.cs
src/NServiceBus.AcceptanceTests/Core/DelayedDelivery/TimeoutManager/When_reusing_sendoptions_with_delay.cs
src/NServiceBus.AcceptanceTests/Core/Diagnostics/When_message_is_audited.cs
src/NServiceBus.AcceptanceTests/Core/Diagnostics/When_message_is_faulted.cs
src/NServiceBus.AcceptanceTests/Core/Diagnostics/When_sending_ensure_proper_headers.cs
src/NServiceBus.AcceptanceTests/Core/Recoverability/When_message_is_moved_to_error_queue_with_header_customizations.cs
src/NServiceBus.AcceptanceTests/DelayedDelivery/When_using_special_characters_in_headers.cs
src/NServiceBus.AcceptanceTests/Forwarding/When_forwarding_is_configured_for_endpoint.cs
src/NServiceBus.AcceptanceTests/Forwarding/When_requesting_message_to_be_forwarded.cs
src/NServiceBus.AcceptanceTests/MessageId/When_message_has_empty_id_header.cs
src/NServiceBus.AcceptanceTests/Outbox/When_headers_contain_special_characters.cs
src/NServiceBus.AcceptanceTests/Pipeline/When_sending_to_another_endpoint.cs
src/NServiceBus.AcceptanceTests/Recoverability/When_using_special_characters_in_headers.cs

Some acceptance tests as well as the `FailTestOnErrorMessageFeature` do not make a copy of the headers. The headers are added to the scenario context which outlives the message handling lifetime as well as the endpoint lifetime. By doing that the core does not allow the transport to optimize for header dictionary reuse. More context available at 
https://github.com/Particular/NServiceBus.AmazonSQS/pull/277

Copy headers because they are exposed on the scenario context which lives longer than the endpoint

---

src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs
src/NServiceBus.Core/Persistence/Learning/SagaPersister/SagaStorageFile.cs
src/NServiceBus.Core/Serializers/SimpleJson/EnumAwareStrategy.cs

Inheritors of PocoSerializationStrategy need to be singletons because of the reflection caches. Made the EnumAwareStrategy a singleton and the constructor private to avoid having multiple instances around in core. Found an unused field in the InMemorySagaPersister

SimpleJson usage cleanup

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core.Tests/Recoverability/RecoverabilityExecutorTests.cs
src/NServiceBus.Core/Recoverability/Discard.cs
src/NServiceBus.Core/Recoverability/RecoverabilityAction.cs
src/NServiceBus.Core/Recoverability/RecoverabilityExecutor.cs

On a live chat today a user had the following requirement
They have certain types of messages that they want to retry a few times and after they failed a certain number of times they want to ignore/discard the message. We first started exploring whether it is possible to implement this scenario with the recoverability policy but found out it is not possible. 
Trying to implement that with behaviors in the pipeline becomes really cumbersome because you are essentially faced with reimplementing parts of the recoverability seam inside behaviors. Especially the counting of how many times a message has failed can become very brittle.
This demonstrates that a discard action in the recoverability seam would be easy to add in a non-breaking way and could provide good benefit to some of our …

Implement discard action for recoverability policy

---

src/NServiceBus.AcceptanceTests/Core/Conventions/When_receiving_non_matching_message_with_handler.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core.Tests/Handlers/MessageHandlerRegistryTests.cs
src/NServiceBus.Core.Tests/Unicast/HandlerInvocationCache.cs
src/NServiceBus.Core.Tests/Unicast/LoadHandlersBehaviorTests.cs
src/NServiceBus.Core/Unicast/Config/RegisterHandlersInOrder.cs
src/NServiceBus.Core/Unicast/MessageHandlerRegistry.cs

To avoid messages going to the error queue when there are issues with [conventions](https://docs.particular.net/nservicebus/messaging/messages-events-commands) we should process messages if there are handlers for it regardless of conventions.

Always process messages that have handlers regardless of conventions

---

src/NServiceBus.AcceptanceTests/ConfigureEndpointMsmqTransport.cs
src/NServiceBus.Core.Tests/Msmq/MsmqMessagePumpTests.cs
src/NServiceBus.Core/Licensing/GenerateReleaseDate.targets
src/NServiceBus.Core/Transports/Msmq/MessagePump.cs
src/NServiceBus.Core/Transports/Msmq/MsmqSettings.cs
src/NServiceBus.Core/Transports/Msmq/MsmqTransport.cs
src/NServiceBus.Core/Transports/Msmq/MsmqTransportInfrastructure.cs
src/NServiceBus.Msmq.AcceptanceTests/BasicServer.cs
src/NServiceBus.TransportTests/NServiceBusTransportTest.cs

Fixes https://github.com/Particular/NServiceBus/issues/5349
Adding a new setting for passing the MessageEnumeratorTimeout
The default value will be 1 second instead of 10 milliseconds
This new setting will be available as part of the connection string.

MSMQ Transport results in unnecessary IO when reading from empty queues due to very short timeout value

---

src/NServiceBus.Core.Tests/MessageMapper/MessageMapperTests.cs
src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/MessageMapper.cs

After seeing https://discuss.particular.net/t/exception-when-starting-endpoint/1052, I took a look the `MessageMapper`, and it looks like the "Can only" portion of the second exception was incorrectly copied from the first one.
I went ahead and reworded both of them for clarity.

Clean up GenerateImplementationFor error messages

---

src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
src/NServiceBus.TransportTests/TransportTestLoggerFactory.cs
src/NServiceBus.TransportTests/When_on_error_throws.cs

Make sure transports invoke critical error if recoverability fails

---

src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
src/NServiceBus.TransportTests/When_modifying_incoming_headers.cs

As part of fixing the header manipulation issues in the RabbitMQ transport, https://github.com/Particular/NServiceBus.RabbitMQ/pull/532 added transport tests to verify the correct behavior.
These tests should actually be in Core instead so all transports can be tested.

Add header manipulation transport tests

---

src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs
src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs
src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs
src/NServiceBus.Core.Tests/Routing/RoutingToDispatchConnectorTests.cs
src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs
src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs
src/NServiceBus.Core.Tests/Unicast/MessageOperationsTests.cs
src/NServiceBus.Core.Tests/Unicast/RunningEndpointInstanceTest.cs
src/NServiceBus.Core/InitializableEndpoint.cs
src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
src/NServiceBus.Core/Pipeline/RootContext.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/Serialization/SerializationFeature.cs
src/NServiceBus.Core/Unicast/MessageOperations.cs

This would eliminate the need to use the builder to access it.
Would we be fine with adding this to the patch or would we want this to go against develop only?

Stop using DI to access the message mapper

---

src/NServiceBus.AcceptanceTests/Core/Routing/When_replying_with_pre_created_interface.cs
src/NServiceBus.AcceptanceTests/Core/Routing/When_routing_interface_message.cs
src/NServiceBus.AcceptanceTests/Routing/When_publishing_pre_created_interface.cs
src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs
src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs
src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs
src/NServiceBus.Core.Tests/Routing/RoutingToDispatchConnectorTests.cs
src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs
src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs
src/NServiceBus.Core.Tests/Unicast/MessageOperationsTests.cs
src/NServiceBus.Core.Tests/Unicast/RunningEndpointInstanceTest.cs
src/NServiceBus.Core/InitializableEndpoint.cs
src/NServiceBus.Core/Pipeline/Incoming/DeserializeLogicalMessagesConnector.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
src/NServiceBus.Core/Pipeline/RootContext.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/Serialization/SerializationFeature.cs
src/NServiceBus.Core/Unicast/MessageOperations.cs

Interface messages created using `IMessageCreator` can't be routed since they message type resolves to the `{message-type}__impl` type generated by NServiceBus.
Users that defines messages using interfaces and creates them using the `IMessageCreator` API.
Send operations fail with an exception that no route can be found for `message-type`.

Interface messages created with IMessageCreator can't be routed

---

src/NServiceBus.AcceptanceTests/Outbox/When_clearing_saga_timeouts.cs

The test is in the main folder, not the Core folder, so it shouldn't have the Core namespace.

Fix namespace of test

---

src/NServiceBus.AcceptanceTests/Core/Routing/When_callbacks_are_used_to_reply_with_int_or_enum.cs
src/NServiceBus.Core/MessageInterfaces/MessageMapper/Reflection/MessageMapper.cs

Backport of fix for #5382 to the `support-6.`5 branch.

Using callbacks to reply with Int or Enums is broken

---

src/NServiceBus.AcceptanceTests/Sagas/When_handling_concurrent_messages.cs
src/NServiceBus.AcceptanceTests/Sagas/When_using_saga_and_outbox.cs

While working on a Raven release, I discovered we don't have an acceptance test that tests a Saga and the Outbox together, nor do we really have one that puts a saga through multiple steps with a possibility of concurrency issue. So I was passing all tests but still having a concurrency issue where successive updates to the saga data were overriding each other. This test covers that case.

Add acceptance test that tests Saga and Outbox together

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core/Recoverability/DelayedRetries/DelayedRetryMessage.cs
src/NServiceBus.Core/Recoverability/Faults/ErrorsNotifications.cs

Based on https://discuss.particular.net/t/faults-delayedretrymessage/1244
Seemed like a low hanging fruit.
I currently went for obsolete with warn of the existing constructor. Happy to discuss the pros and cons

Expose MessageId on DelayedRetryMessage

---

src/NServiceBus.AcceptanceTests/ConfigureEndpointInMemoryPersistence.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core.Tests/Persistence/InMemory/InMemoryGatewayDeduplicationTests.cs
src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs
src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayPersistence.cs
src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayPersistenceConfigurationExtensions.cs

LRU based to contraint the number of items. Refactored to also remove an O(n) operation.

Add configuration API for In memory gateway deduplication persistence

---

src/NServiceBus.ContainerTests/When_building_components.cs

This test is supposed to ensure that recursive types do not cause our DI adapters to run into SO exceptions. However, any exception will cause this test to fail.
Running this test against Autofac throws the following exception:
> Autofac.Core.DependencyResolutionException : Circular component dependency detected
which will fail the test as well. I'm not sure the Autofac behavior is correct this way but at least it's not a stack overflow exception which is what this test is looking for.
It's also interesting to note that depending on the exact type of configuration, multiple contains throw exceptions due to detected circular dependencies.
thoguhts @WilliamBZA @Particular/nservicebus-maintainers ?

Only fail test on StackOverflowExceptions

---

src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/Routing/RoutingComponent.cs

Moved all routing code into the routing component and aligned the `Initalize` method with the others on that sense that they take in the "component" that it depends on.

Cleanup routing component

---

src/NServiceBus.Core/Features/FeatureActivator.cs

Idea to structure the feature activation slightly different. It would mean we don't have to iterate through the controllers multiple times and everything is neatly contained in the initialize method including the side effects on the feature configuration context. Just an idea. Feel free to drop if you don't like it

Introduce InitializeFrom on FeatureInfo

---

src/NServiceBus.Core.Tests/Features/FakeFeatureConfigurationContext.cs
src/NServiceBus.Core.Tests/Features/FeatureDefaultsTests.cs
src/NServiceBus.Core.Tests/Features/FeatureDependencyTests.cs
src/NServiceBus.Core.Tests/Features/FeatureDifferingOnlyByNamespaceTests.cs
src/NServiceBus.Core.Tests/Features/FeatureSettingsTests.cs
src/NServiceBus.Core.Tests/Features/FeatureStartupTests.cs
src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/Features/FeatureActivator.cs

After talk to @danielmarbach and @timbussmann I realized that the current code led us to believe that the features infrastructure had a bunch of dependencies. That isn't the case since they where only there to be exposed on the `FeatureSetupContext`. This change changes the code to highlight that the features have no dependencies on other "components".
It also have the added benefit of causing less churn on tests next time we need to expose something new on the feature setup context.

Use a factory method for the feature setup context

---

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_providing_custom_handler_registry.cs
src/NServiceBus.Core/Unicast/Config/RegisterHandlersInOrder.cs

This change allows a `MessageHandlerRegistry` (public class) to be configured in the settings. I think there is currently no way to access the message handler in order to register your own handlers otherwise. At the point where the handler registry can be resolved via DI, some important points like autosubscribe have already made use of the registry, so it would be to late to add handlers once it's resolvable from the container.
This "non-public" change can open the doors for some ideas like delegate based message handlers.

Make MessageHandlerRegistry configurable

---

src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransport.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportSettingsExtensions.cs
src/NServiceBus.AcceptanceTests/Core/TransportSeam/When_features_are_setup.cs

As part of https://github.com/Particular/NServiceBus/pull/5427 we discovered that the transport depends on features "enabled state" to be present in settings so that the transports can make decisions based on if the TimeoutManager is enabled or not.
This test documents this "hidden" dependency.
Once this is merged to master I will adjust https://github.com/Particular/NServiceBus/pull/5427 to pass this new test.
I have run this test locally on https://github.com/Particular/NServiceBus/pull/5427 and it does indeed fail there

Add test to document transport dependency on feature state

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core.Tests/Transports/IncomingMessageTests.cs
src/NServiceBus.Core/Transports/IncomingMessage.cs

Fixes #5391 
`IncomingMessage` receives the native message ID from the transport. This PR exposes the native message ID as a `NativeMessageId` property to allow access in advanced scenarios when this value should be logged for troubleshooting.

Expose native message ID on the IncomingMessage

---

src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/Features/FeatureActivator.cs

I can't see any good reason why we would lock the settings inside the features component. There is no need to lock them as part of the feature initialization as the feature setup process still requires write access and afterwards there is no further access to the settings.

Lock settings outside feature component

---

src/NServiceBus.AcceptanceTests/Core/Persistence/When_a_persistence_does_not_support_subscriptions.cs
src/NServiceBus.AcceptanceTests/Core/PublishSubscribe/When_disabling_publishing.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/DisabledPublishingConnector.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/DisabledPublishingTerminator.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensions.cs

Fixes #5120
When users use `DisableFeature<MessageDrivenSubscriptions>()` they want to avoid to provide a subscription storage. As the subscription storage is only used when publishing events, this means that people can only choose between completely disable pub-sub or provide a subscription storage, e.g. when they want to subscribe to events but don't publish from this endpoint.
This features provides a new public configuration API which is available to transports using message driven pub-sub. It can be enabled using `transportSettings.DisablePublishing()`. With publishing disabled, an endpoint doesn't need a subscription storage when starting up.
Calling `Publish(...)` when publishing has been disabled causes an InvalidOperationException due to the special pipeline terminator.
This …

Allow disabling publish functionality

---

src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/Pipeline/PipelineComponent.cs
src/NServiceBus.Core/StartableEndpoint.cs

Aligns the names of pipeline components lifecycle methods to the "standard" `Initialize` and `Start`. It also moves the `Start` method to `IStartableEndpoint.Start()` which is the correct spot to invoke it.
* Message session is created on start and not when the startable instance is created. This should have no externally visible effect
* Pipeline cache is only created on Start. This should have no externally visible effect

Adjust names of the PipelineComponent lifecycle methods

---

src/NServiceBus.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt
src/NServiceBus.Core.Tests/Reliability/Outbox/TransportReceiveToPhysicalMessageConnectorTests.cs
src/NServiceBus.Core.Tests/Routing/DetermineRouteForPublishBehaviorTests.cs
src/NServiceBus.Core.Tests/Routing/DetermineRouteForReplyBehaviorTests.cs
src/NServiceBus.Core.Tests/Routing/Routers/MulticastPublishConnectorTests.cs
src/NServiceBus.Core.Tests/Routing/Routers/ReplyConnectorTests.cs
src/NServiceBus.Core.Tests/Routing/Routers/SendConnectorTests.cs
src/NServiceBus.Core.Tests/Routing/Routers/UnicastPublishConnectorTests.cs
src/NServiceBus.Core.Tests/Utils/Reflection/ExtensionMethodsTests.cs
src/NServiceBus.Core/Audit/Audit.cs
src/NServiceBus.Core/Audit/AuditContext.cs
src/NServiceBus.Core/Audit/AuditToRoutingConnector.cs
src/NServiceBus.Core/Pipeline/Incoming/DeserializeMessageConnector.cs
src/NServiceBus.Core/Pipeline/Incoming/ReceiveFeature.cs
src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs
src/NServiceBus.Core/Routing/NativePublishSubscribeFeature.cs
src/NServiceBus.Core/Routing/Routers/MulticastPublishConnector.cs
src/NServiceBus.Core/Routing/Routers/ReplyConnector.cs
src/NServiceBus.Core/Routing/Routers/SendConnector.cs
src/NServiceBus.Core/Routing/Routers/UnicastPublishConnector.cs
src/NServiceBus.Core/Routing/RoutingComponent.cs
src/NServiceBus.Core/Routing/RoutingOptionExtensions.cs
src/NServiceBus.Core/Routing/SubscriptionMigrationMode/MigrationModePublishConnector.cs
src/NServiceBus.Core/Routing/SubscriptionMigrationMode/SubscriptionMigrationMode.cs
src/NServiceBus.Core/Serialization/SerializationFeature.cs
src/NServiceBus.Persistence.InMemory.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt

fixes https://github.com/Particular/NServiceBus/issues/3621
* Made sure that all connectors end with "Connector" and all terminators end with "Terminator".
* I did not strictly rename them to match the `<TFrom>To<TTo>Connector` because, as also pointed out in the related issue by Mike, it might be more useful to give them more meaningful names.
* The renamed behaviors are still registered with their old ids for now to minimize impact on something relying on those ids.
* We should raise a followup issue to change to registration ids with the next major to align them with the behavior/connector name.
* Some missing "terminators" pointed out in #3621 are now satellite behaviors which don't use the main pipleline infrastructure (e.g. not implementing the behavior, connector and terminator …

Align behavior names

---

src/NServiceBus.Core.Tests/Logging/RollingLoggerTests.cs
src/NServiceBus.Core/Logging/ColoredConsoleLogger.cs
src/NServiceBus.Core/Logging/DefaultLog.cs
src/NServiceBus.Core/Logging/DefaultLoggerFactory.cs
src/NServiceBus.Core/Logging/RollingLogger.cs
src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerTerminator.cs

Fixes #2609
Add additional information about the message and handler types when a message handler fails with an exception. This uses the `Exception.Data` dictionary which allows to add these additional type of information. Other behaviors in the pipeline could make use of this as well and if we merge this, we should document this approach more clearly.
By default, none of the loggers logs the values in `Exception.Data` though. Therefore this PR also adjusts the default logger to log the additional data at the end. A sample log statement would now look something like this:
> 2019-10-01 13:01:00.065 INFO  Immediate Retry is going to retry message 'e5cf778e-e1be-4267-9a6e-aad900b41ae1' because of an exception:
Microsoft.Azure.ServiceBus.MessageLockLostException: test
at …

Add additional log information when handlers fail

---

src/NServiceBus.AcceptanceTesting/EndpointConfigurationBuilder.cs
src/NServiceBus.AcceptanceTests/Core/PublishSubscribe/When_subscribing_on_send_only_endpoint.cs
src/NServiceBus.AcceptanceTests/Core/PublishSubscribe/When_unsubscribing_on_send_only_endpoint.cs
src/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
src/NServiceBus.AcceptanceTests/EndpointTemplates/DefaultServer.cs
src/NServiceBus.AcceptanceTests/EndpointTemplates/ExternallyManagedContainerServer.cs
src/NServiceBus.AcceptanceTests/EndpointTemplates/ServerWithNoDefaultPersistenceDefinitions.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs
src/NServiceBus.Core/Routing/NativePublishSubscribeFeature.cs
src/NServiceBus.Core/Routing/SendOnlySubscribeTerminator.cs
src/NServiceBus.Core/Routing/SendOnlyUnsubscribeTerminator.cs

_Follow-up to #5120_
* This PR registers special pipeline Terminators when running in send-only so that instead of a pipeline building exception (due to missing pipeline steps) the user receives a more meaningful InvalidOperationException stating that you can't subscribe/unsubscribe on send-only endpoints.
* To properly test this with acceptance tests, we need the ability to configure the endpoint with a message-driven and a native pubsub transport. By default, all acceptance tests run with the learningtransport though. Based on that, I've tweaked the acceptance testing setup slightly to allow overwriting the defaults defined by the `TestSuiteConstraints` class. With that, it's possible to configure custom transport & persistence settings for a single test while still being able to use …

Throw better exceptions when subscribing/unsubscribing on send-only endpoints

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core.Tests/Recoverability/ErrorContextTests.cs
src/NServiceBus.Core/Transports/ErrorContext.cs

Fixes #5333 
I have some mixed feelings about this API because it should technically be unidirectional i.e. transports should be able to add stuff to the bag but then the error policy should only be able to read the bag, not add to it. Using `ContextBag` makes it possibly to modify the bag after it is created. This has the drawback of having to allocate the `ContextBag` even if the transport does not use it.
Thoughts? Should we create a *read only context bag* for such cases? Or am I complicating things too much?

Add ContextBag to ErrorContext

---

src/NServiceBus.Core.Tests/Routing/UnicastPublisherRouterTests.cs
src/NServiceBus.Core/Routing/UnicastPublishRouter.cs

Fixes #4119 
With message-driven pub/sub, when an event is published and no subscribers are found, log a warning.

Log debug statement when publishing without subscribers with message-driven transport

---

src/NServiceBus.Core.Tests/Transports/TransportReceiverTests.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/StartableEndpoint.cs
src/NServiceBus.Core/Transports/TransportReceiver.cs

Spelunking the code with @timbussmann made me realize that since the start method is called in the async part of the startup lifecycle it should be task returning.
We can't change the transport seam since it would be a breaking change so I will raise an issue to track this for the next major

Make ReceiveComponent.Start async

---

src/NServiceBus.AcceptanceTests/Pipeline/When_message_processing_fails.cs
src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerTerminator.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs

Adding some additional information to the `Exception.Data` bag when a message handler fails so this information is also available in logs even when running on non-debug log-levels.

Add additional exception information

---

src/NServiceBus.AcceptanceTests/Core/Recoverability/When_subscribing_to_delayed_retries_notifications.cs
src/NServiceBus.AcceptanceTests/Core/Recoverability/When_subscribing_to_error_notifications.cs
src/NServiceBus.AcceptanceTests/Core/Recoverability/When_subscribing_to_immediate_retries_notifications.cs
src/NServiceBus.AcceptanceTests/Pipeline/When_message_processing_fails.cs
src/NServiceBus.AcceptanceTests/Recoverability/When_immediate_retries_disabled.cs
src/NServiceBus.AcceptanceTests/Recoverability/When_immediate_retries_with_dtc_on.cs
src/NServiceBus.AcceptanceTests/Recoverability/When_immediate_retries_with_native_transactions.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core/DeepCopy.cs
src/NServiceBus.Core/Persistence/InMemory/SagaPersister/InMemorySagaPersister.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
src/NServiceBus.Core/Recoverability/Faults/ErrorsNotifications.cs
src/NServiceBus.Core/Recoverability/RecoverabilityMessageUtilities.cs
src/NServiceBus.Core/Recoverability/Settings/DelayedRetriesSettings.cs
src/NServiceBus.Core/Recoverability/Settings/ImmediateRetriesSettings.cs
src/NServiceBus.Core/Recoverability/Settings/RetryFailedSettings.cs

Fixes https://github.com/Particular/NServiceBus/issues/5393
Provides a new notification API which is based on the internal notifications infrastructure which can support async notification subscribers.
The new APIs have been moved to the corresponding recoverability configuration settings and I've tried to give them more accurate and meaningful names.

Task-based notifications API

---

src/NServiceBus.AcceptanceTests/ConfigureEndpointLearningPersistence.cs
src/NServiceBus.AcceptanceTests/Core/PublishSubscribe/When_disabling_publishing.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs

The `SubscriptionReceiverBehavior` has a dependency on the subscription storage as it's responsbile for storing incoming subscription messages into the database. This throws an exception as on endpoints with publishing disabled and no subscription storage, the container is unable to build this behavior. This behavior only makes sense to do when publishing is enabled, as the subscription storage is only queried when publishing events.
When there is no `SubscriptionReceiverBehavior` registered, incoming subscription messages will just be discarded later in the pipeline.
This wasn't discovered by the acceptance tests, as those always register a subscription storage by default and therefore the behavior could be resolved from the container. I've made the learning persister configuration for …

Fix DisablePublishing

---

src/NServiceBus.Core.Tests/MessageMapper/MessageMapperTests.cs

Repro for https://github.com/Particular/NServiceBus/issues/5398
Created a test to demonstrate the behavior described.

Mapping an interface containing an attribute that has a nullable property fails

---

src/NServiceBus.Core/Licensing/ConfigureLicenseExtensions.cs
src/NServiceBus.Core/Licensing/LicenseSources.cs

When a user configures a license via `EndpointConfiguration.License(...)` or `EndpointConfiguration.LicensePath(...)`, we still check all the default license sources (directory folders) as well and there is the possibility that a valid license from those locations is taken if the user-provided license isn't valid anymore.
This behavior causes problems with the `When_license_expired` acceptance test on developer machines when the local machine has a valid license in the directories, the test can't be configured to not have a valid license even though there is a specific license configured using `EndpointConfiguration.License(...)`.
Not 100% sure about this change, but it feels like user-configured licenses should take precedence over the default sources and if a user configures a value …

Give user defined licenses precedence

---

src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerTerminator.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs

Testing showed that there are some edge cases where an exception object can be reused. E.g. when the pipeline fails to build, it throws an exception inside a builder delegate of a `Lazy<T>`, this causes repeated attempts to build that pipeline to return the same exception instance. Similar issues could also happen with user code. Therefore it's safer to assign or update instead of using `Add` on the `Exception.Data` dictionary.

Avoid exceptions when key already exists

---

src/NServiceBus.Core.Tests/Persistence/PersistenceStartupTests.cs
src/NServiceBus.Core/Persistence/PersistenceStartup.cs

_Follow-up on https://github.com/Particular/NServiceBus/pull/5435_
When one of the features (Sagas or Outbox) is not enabled, we should not throw an exception if those are configured to use different persistences. E.g.
```c#
endpointConfiguration.UsePersistence<InMemoryPersistence>();
endpointConfiguration.UsePersistence<LearningPersistence, StorageType.Sagas>();
```
This PR ensures the exception is solely thrown when both features are enabled and use different persistence.

Improve persistence check to throw when both persistences are enabled and different

---

src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs

The current implementation to detect `.learningtransport` directories doesn't actually work as the directories returned by `Directory.EnumerateDirectories` return the full path of the directory, not just the directory name. Therefore, the equality check can never be true.
I tried to use a simpler approach and just check for the existence of the specific directory. `Directory.Exists` states to be case-insensitive, but testing this on WSL, it seems to be case-sensitive when running on linux, so it should be fine in regards to that aspect.

Fix leanringtransport directory check

---

src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/Installation/InstallationComponent.cs

This cleans up the endpoint creator and makes the dependencies of the installation parts more visible.
* Receive component is created before the installer component since it needs to be passed to it. 
* This should have no visible effect on the ReceiveComponent since the installer just registers intaller instances in the container
* This should have no visible effect since the InstallerComponent only needs to read 2 settings that aren't controlled by the Receive component. This also highlight a design smell. I think the installer should depend on the transport component instead. See more details below
* This makes the installation component stand out since it's the only component that "starts" before users call `.Start()`. This is due to …

Add Installation component

---

src/NServiceBus.AcceptanceTests/ConfigureEndpointLearningPersistence.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportInfrastructure.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/ProcessingOptimizations/When_using_concurrency_limit.cs
src/NServiceBus.AcceptanceTests/Core/PublishSubscribe/When_disabling_publishing.cs
src/NServiceBus.AcceptanceTests/Core/PublishSubscribe/When_subscribing_on_send_only_endpoint.cs
src/NServiceBus.AcceptanceTests/Core/PublishSubscribe/When_unsubscribing_on_send_only_endpoint.cs
src/NServiceBus.AcceptanceTests/Core/TransportSeam/When_initializing_transport.cs

https://github.com/Particular/NServiceBus/pull/5455 made me look into why we would need storage configured for tests that run with a fully capable transport. Turned out that we only needed it for some test using the `FakeTransport`, I made it "support" native pubsub and timeouts so all tests are now green with the added bonus that we assert that `ConfigureSubscriptionInfrastructure` is called in the correct startup order

Cleanup persister use in tests

---

src/NServiceBus.Core/obsoletes.cs

The feature was removed as part of but I forgot to obsolete the internal feature.
I noticed that we started just wrapping the whole obsoleted class including the namespaces instead of moving them to the already existing namespaces in the obsoletes.cs. Not sure whether that was intentional or not. I continued with that approach as it's actually easier to obsolete a class that way and it doesn't seem to case issues.

Obsolete removed OutgoingPipelineFeature

---

src/NServiceBus.Core.Tests/Pipeline/FakeRootContext.cs
src/NServiceBus.Core.Tests/Unicast/MessageOperationsTests.cs
src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/MessageSession.cs
src/NServiceBus.Core/Pipeline/Incoming/IncomingContext.cs
src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveContext.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
src/NServiceBus.Core/Pipeline/Outgoing/OutgoingContext.cs
src/NServiceBus.Core/Pipeline/Outgoing/SendComponent.cs
src/NServiceBus.Core/Pipeline/PipelineCache.cs
src/NServiceBus.Core/Pipeline/PipelineComponent.cs
src/NServiceBus.Core/Pipeline/RootContext.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/StartableEndpoint.cs
src/NServiceBus.Core/Unicast/MessageOperations.cs

Makes the `MessageOperations` class non-static. This way, dependencies can be passed to the instance and don't need to be fetched from the context settings bag at runtime.
The send pipelines are now created as part of initializing the send component. This ensures that the pipelines can be built at startup time.
The remaining challenge is passing down the MessageOperations class the context hierarchy without a breaking change. To do this properly, we would most likely have to break some public APIs so they operations get currently added to the context bag by the root context but this way we need less dependencies in the context bag (message mapper & pipeline cache).
I was also wondering whether we should rename `MessageOperations` to something like  `OutgoingPipelines`?

Create send pipelines in SendComponent

---

src/NServiceBus.Persistence.InMemory.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt

`MessageMetadataRegistry` now shows up because due to the changes in endpoint startup, the outgoing pipelines are built at startup time instead on-demand. The in-mem tests use a non-native pubsub transport configuration and the message driven pubsub feature resolves the `MessageMetadataRegistry` to build parts of the pipeline.

Update approval file

---

src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
src/NServiceBus.Core/Pipeline/PipelineCache.cs
src/NServiceBus.Core/Pipeline/PipelineComponent.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs

Removes `AddRootContextItem` from the PipelineComponent as it's only usage is internal.
By building the receive pipeline explicitly, it removes another usage of the pipeline cache which is the only remaining on the RootContext except for the builder.

Create receive pipeline in component

---

src/NServiceBus.AcceptanceTests/Core/SubscriptionMigration/When_send_only_endpoint_uses_migration_mode.cs
src/NServiceBus.Core/Routing/SubscriptionMigrationMode/SubscriptionMigrationMode.cs

The current behavior will crash endpoint startup because the subscribe/unsubscribe pipelines are built at startup time instead of lazily (in that case it only throws on subscribe/unsubscribe runtime). This change contains the same terminators also used by the native and the message-driven pubsub features for send-only endpoints (and the tests are very similar)

Register terminators when using migration-mode on send-only endpoints

---

src/NServiceBus.Core/Receiving/ReceiveComponent.cs

`Configuration` is never null. Use `IsReadOnlyEndpoint` property to do the check.

Only add diagnostics if it's not a read-only endpoint

---

src/NServiceBus.Core/Installation/InstallationComponent.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs

Contains two fixes:
* `ExecuteTheseHandlersFirst ` didn't read the value from the settings key it used to. See https://github.com/Particular/NServiceBus/commit/e84962eb1848c4dfb1a944f26492dc048297f6dd#diff-2a6bc7a3fd6ac7aef3875cb0b908ccbbL22
* ShouldCreateQeueus default was set in the installation component. Moved this to the receive settings. I avoided the `SetDefault` and accessed the actual property instead. Could that cause any problems?

Receive settings fixes

---

src/NServiceBus.Core/Receiving/ReceiveComponent.cs

_Connects to PR #5520_
I was wondering why do we bother to register all the receiving related behaviours if the endpoint is read-only. This PR is to verify if we're breaking any tests by registering these receiving behaviors in `ReceiveComponent` conditionally.

Do not register behaviors that are not needed for read only endpoint

---

src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/StartableEndpoint.cs

The ReceiveComponent shouldn't register behaviors in the settings after the pipeline component has been initialized as this can cause registrations to be not be applied to the container.

Don't use PipelineSettings after PipelineComponent.Initialize

---

src/NServiceBus.Core/Gateway/IDeduplicateMessages.cs

Since this interface has to stay until the next major version we should also just fix the description.
As pointed out [here](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs#L20), `false` is returned to indicate a duplicate message and `true` to indicate an "unknown"/new message.
Same behavior is used in [RavenDB](https://github.com/Particular/NServiceBus.RavenDB/blob/master/src/NServiceBus.RavenDB/Gateway/RavenDeduplication.cs) and [NHibernate](https://github.com/Particular/NServiceBus.NHibernate/blob/master/src/NServiceBus.NHibernate/Deduplication/GatewayDeduplication.cs)

Fix return value description for DeduplicateMessage

---

src/NServiceBus.AcceptanceTests/Core/TransportSeam/When_configuring_transport.cs

adding a test to verify that `TransportInfrastructure` is accessible via settings as downstreams can depend on it to access transport information not available elsewhere.

Add test for TransportInfrastructure in settings

---

src/NServiceBus.Core.Tests/Pipeline/Incoming/InvokeHandlerTerminatorTest.cs
src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerTerminator.cs

The exception data that is added by the invoke handler terminator does not only influence logging it is also added by the `ExceptionHeaderHelper` to the failed message. The `ExceptionHeaderHelper` blindly invokes `ToString` on the passed data. This causes the date-time that we add to be formatted in the culture aware format of the current runtime environment. By consistently using strings for both the handler type as well as the start and stop time our data is added in a consistent format
Changing how the ExceptionHeaderHelper treats instances of `IFormattable` seemed to me a larger issue than just making sure our data is consistent

Exception data as strings instead of type and datetime

---

src/NServiceBus.Core.Tests/Persistence/InMemory/ClientIdStorageTests.cs
src/NServiceBus.Core.Tests/Persistence/InMemory/InMemoryGatewayDeduplicationTests.cs
src/NServiceBus.Core/Persistence/InMemory/Gateway/ClientIdStorage.cs
src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayDeduplication.cs
src/NServiceBus.Core/Persistence/InMemory/Gateway/InMemoryGatewayPersistence.cs

Messages are not emitted by the receiving gateway with the following log statement:
`"Message with id: {message-id} has already been dispatched, ignoring incoming gateway message."`
The sending gateway treats the message as successfully transmitted and the message is technically lost.
All users of the Gateway below version 3.1 that use the InMemory option for deduplication storage.
The record of the message-id is stored before the message is emitted to the transport and is not rolled back should the outgoing operation fail. This leads to the message being considered a duplicate once retried.

InMemory gateway deduplication can cause message loss

---

src/NServiceBus.AcceptanceTests/Core/Hosting/When_endpoint_starts.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs

This record all handlers loaded for each message type and in what order they would be invoked.
```
{
...
"Receiving":{
"LocalAddress":"EndpointStarts.MyEndpoint",
"InstanceSpecificQueue":null,
"LogicalAddress":{
"Qualifier":null,
"EndpointInstance":{
"Endpoint":"EndpointStarts.MyEndpoint",
"Discriminator":null,
"Properties":{
}
}
},
"PurgeOnStartup":false,
"QueueNameBase":"EndpointStarts.MyEndpoint",
"TransactionMode":"SendsAtomicWithReceive",
"MaxConcurrency":8,
"Satellites":[
],
"ExternalHandlerRegistry":false,
"MessageHandlers":{
"NServiceBus.AcceptanceTests.Core.Hosting.When_endpoint_starts+MyMessage":[
"NServiceBus.AcceptanceTests.Core.Hosting.When_endpoint_starts+MyMessageHandler"
]
}
},
...
}

Add handler types and order to startup diagnostics

---

src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj

This changes the analyzer project to reference Particular.Packaging instead of directly referencing GitVersionTask.
This ensures that we keep all the projects using the same version of GitVersionTask by bringing it transitively through Particular.Packaging.

Use Particular.Packaging instead of GitVersionTask in analyzer project

---

guidelines/coding-guidelines.md

We allow C# v7.3 as the maximum version, not 7.

Language version is incorrect

---

src/NServiceBus.Core/StartableEndpoint.cs

Backport of #5583 fix for release-7.2 branch

Thread.CurrentPrincipal will throw PlatformNotSupportedException on .NET Core 3.x

---

src/NServiceBus.Core/StartableEndpoint.cs

Backport of #5583 fix for release-7.1 branch

Thread.CurrentPrincipal will throw PlatformNotSupportedException on .NET Core 3.x 

---

src/NServiceBus.AcceptanceTesting/ContextAppender.cs

In case some code/tests are run outside of a test `Scenario`, logging causes an NRE in case a test Scenario ran before. This happens because the test scenarios setup a custom logger (using the `ContextAppender`) which is then cached in the static logger field. Once some other code tries to log using this cached logger, it will potentially run into an NRE because `Scenario.Current` is `null`. Due to the `Scenario.Current` being an async local variable, it won't preserve after a test completed.
There could also be the explicit goal to catch logging attempts outside of a defined test scenario in the acceptance tests so I'm not 100% whether this makes sense, but I ran into this [here](https://github.com/Particular/NServiceBus.RavenDB/pull/451) where I had to move a test to the regular unit …

Avoid NRE for logging outside test scenario

---

src/Custom.Build.props
src/Directory.Build.props
src/NServiceBus.sln

This is the sort of thing we'll need to do for any repos that have customized Directory.Build.props files.
I'm not sure I'm happy with the name of the new file. `Local.Build.props` doesn't really seem to convey the intention of the file.
Can we think of something better?

Move non-standard stuff into separate props file

---

src/NServiceBus.Core/Sagas/SagaMetadata.cs

Having to debug some failed tests, I struggled to find the involved tests since the `Name` property value was very ambiguous, using the `FullName` helped to locate the affected types and solve the issue quickly.

Improve exception message for incorrect saga configurations

---

src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnosticsWriterFactory.cs

Based on feedback https://github.com/Particular/docs.particular.net/issues/4766
>If setting up the diagnostics part is not blocking, i would put the level of the error on Warn.
>
>See following error. (Since we did the upgrade to nsb v7)
>
>```
>2020-04-03 10:07:25,975 [5] ERROR NServiceBus.HostStartupDiagnostics - Unable to create the diagnostics output directory. Check the attached exception for further information, or change the diagnostics directory using 'EndpointConfiguration.SetDiagnosticsPath()'.
>System.UnauthorizedAccessException: Access to the path 'd:\Services\xyz.diagnostics' is denied.
>at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost) …
```

Lowered log entry level to Warn as this is not a blocking failure

---

src/NServiceBus.AcceptanceTests/Core/Feature/When_depending_on_feature.cs
src/NServiceBus.Core.Tests/Features/FeatureStartupTests.cs
src/NServiceBus.Core/Features/FeatureActivator.cs

- Customers or downstream components using features that depend on another feature with startup tasks
- The startup sequence is violated and can cause exception depending on the reflection order
Ask multiple developers the following question
> If you have two Features `A` and `B` both with a startup task `ATask` and `BTask`. Feature B depends on A. What would your expectation be for the startup tasks?
The answer is always: `ATask` should be started first.
The core answer is:
It depends on the reflection order. 
This is very problematic because
- It violates the logical reasoning
- Features can register dependencies in the container and they can use startup tasks to initialize those dependencies.
- Dependent features can inject dependencies of other features they depend upon into their …

Start FeatureStartupTasks in feature dependency order

---

src/NServiceBus.AcceptanceTests/Core/Feature/When_depending_on_feature.cs
src/NServiceBus.Core.Tests/Features/FeatureStartupTests.cs
src/NServiceBus.Core/Features/FeatureActivator.cs

Backport of #5620 for release-7.1 branch
- Customers or downstream components using features that depend on another feature with startup tasks
- The startup sequence is violated and can cause exception depending on the reflection order
Ask multiple developers the following question
> If you have two Features `A` and `B` both with a startup task `ATask` and `BTask`. Feature B depends on A. What would your expectation be for the startup tasks?
The answer is always: `ATask` should be started first.
The core answer is:
It depends on the reflection order. 
This is very problematic because
- It violates the logical reasoning
- Features can register dependencies in the container and they can use startup tasks to initialize those dependencies.
- Dependent features can inject dependencies of other …

Start FeatureStartupTasks in the feature dependency order

---

src/Custom.Build.props

This is no longer needed now that it's been added to Particular.Packaging instead.

Remove redundant target from Custom.Build.props

---

src/NServiceBus.Core/IMessageSessionExtensions.cs

Users do not see a send options parameter and don't know that SendLocal is just a shortcut.

Intellisense doco indicating SendLocal is a shortcut

---

src/NServiceBus.AcceptanceTests/Core/Sagas/When_saga_scanned_send_only_and_no_saga_storage.cs
src/NServiceBus.Core/Sagas/Sagas.cs

When a saga is scanned in any of the assemblies picked up of the assembly scanner the saga feature is activated even on send-only endpoints causing the endpoint to throw a 
```
The selected persistence doesn't have support for saga storage. Select another persistence or disable the sagas feature using endpointConfiguration.DisableFeature<Sagas>()
```

Disables saga feature on send-only endpoint

---

src/NServiceBus.Core/Hosting/Helpers/AssemblyValidator.cs

Add `Microsoft.Azure.ServiceBus` public key token to ignore during assembly scanning

Additional assembly token to ignore

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScanningComponentTests.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerConfiguration.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanningComponent.cs

Partially addresses https://github.com/Particular/NServiceBus.AzureFunctions/issues/44 part 1: `The Core doesn't allow assembly scanning with an alternate path`

Add support for setting an additional assembly scanning path

---

src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
src/NServiceBus.TransportTests/When_on_error_throws.cs

Previously the test was broken. The first run would set the LogManager but as loggers are static all following runs would not get a new logger but re-use their previously acquired static instance.

Make LogFactory static in transport tests

---

src/NServiceBus.Core/Licensing/LicenseManager.cs

Fixed some funky encoding issue with the license manager that cause the tests to fail on mac/rider. Note that the change is not visible in the diff view of Github but opening the old file in the VSCode/Rider shows the funky character.

fix broken tests on rider/mac

---

src/NServiceBus.Core.Tests/ApprovalFiles/JsonPrettifierTests.Print_ShouldPrettifyCollections.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/JsonPrettifierTests.Print_ShouldPrettifyEscapedStrings.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/JsonPrettifierTests.Print_ShouldPrettifyJsonContent.approved.txt
src/NServiceBus.Core.Tests/Diagnostics/JsonPrettifierTests.cs
src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnosticsWriterFactory.cs
src/NServiceBus.Core/Hosting/StartupDiagnostics/JsonPrettyPrinter.cs

Prettifies the output of the Diagnostics file. Connects to #5050.

add json prettifier for the diagnostic file

---

src/NServiceBus.AcceptanceTests/Core/Installers/When_creating_queues.cs
src/NServiceBus.AcceptanceTests/Core/Pipeline/When_modifying_headers_during_forwarding.cs
src/NServiceBus.AcceptanceTests/Forwarding/When_forwarding_is_configured_for_endpoint.cs
src/NServiceBus.AcceptanceTests/Outbox/When_dispatching_forwarded_messages.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core/Forwarding/ConfigureForwarding.cs
src/NServiceBus.Core/Forwarding/ForwardReceivedMessages.cs
src/NServiceBus.Core/Forwarding/IForwardingContext.cs
src/NServiceBus.Testing.Fakes/TestableForwardingContext.cs

This feature is often used accidentally when message auditing is desired instead. Message forwarding will be moved into [a sample](https://github.com/Particular/docs.particular.net/pull/4934).

Obsolete message forwarding

---

src/NServiceBus.Core.Tests/Pipeline/PipelineSettingsTests.cs
src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/Pipeline/PipelineSettings.cs

fixes: https://github.com/Particular/NServiceBus/issues/4873
At the moment the Settings are being locked preventing from being modified. This PR introduces a similar mechanism for Pipeline modifications (Register, Remove, Replace) highlighting common errors when modifying pipeline after an endpoint has started.

Protecting pipeline from modifications after endpoint is started

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core.Tests/ConventionsTests.cs
src/NServiceBus.Core.Tests/MessageConventionSpecs.cs
src/NServiceBus.Core.Tests/Sagas/CustomFinderAdapterTests.cs
src/NServiceBus.Core/Conventions/Conventions.cs
src/NServiceBus.Core/Conventions/ConventionsBuilder.cs
src/NServiceBus.Core/Conventions/IMessageConvention.cs
src/NServiceBus.Core/Conventions/NServiceBusMarkerInterfaceConvention.cs
src/NServiceBus.Core/Conventions/OverridableMessageConvention.cs
src/NServiceBus.Core/EndpointCreator.cs

Enables registering multiple message conventions in isolation. Example:
```csharp
class SuffixMessageConvention : IMessageConvention
{
public string Name { get; } = "Type name suffix";
public bool IsCommandType(Type t) => t.FullName.EndsWith("Command");
public bool IsEventType(Type t) => t.FullName.EndsWith("Event");
public bool IsMessageType(Type t) => t.FullName.Endswith("Message");
}
// Implements the conventions from https://github.com/mauroservienti/NServiceBus.AttributeConventions
class AttributeMessageConvention : IMessageConvention
{
public string Name { get; } = "Attribute decorator";
public bool IsCommandType(Type t) => t.GetCustomAttribute<CommandAttribute>(false) != null;
public bool IsEventType(Type t) => t.GetCustomAttribute<EventAttribute>(false) != null;
public bool …
```

Improve message convention extensibility

---

src/NServiceBus.Core.Tests/Unicast/HandlerInvocationCache.cs

This test is marked as explicit but it's bring run in Visual Studio 2019 due to [this issue in the NUnit3TestAdapter that will be fixed in v4](https://github.com/nunit/nunit3-vs-adapter/issues/658).
Passing null for message handler context results in NRE but we don't need it to do anything

Fix performance test

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core/Sagas/CorrelatedSagaPropertyMapper.cs
src/NServiceBus.Core/Sagas/SagaPropertyMapper.cs

The current saga mapping API implies that you can have multiple correlation properties but you can't (we detect this and throw an exception). This proposed alternative puts the definition of the correlation property first, so that you can specify correlation property once and then map different messages to it.
i.e. Instead of this
```csharp
public override void ConfigureHowToFindSaga(SagaPropertyMapper<ProcessOrderSagaData> mapper)
{
mapper.CreateMapping<SubmitOrder>(msg => msg.OrderId).ToSaga(saga => saga.OrderId);
mapper.CreateMapping<OrderBilled>(msg => msg.OrderId).ToSaga(saga => saga.OrderId);
mapper.CreateHeaderMapping<OrderShipped>("Shipping.OrderId").ToSaga(saga => saga.OrderId);
}
```
you can do this instead
```csharp
public override void …
```

Proposed Saga Mapping API in reverse direction

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Persistence/InMemory/SubscriptionStorage/InMemorySubscriptionPersistence.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensions.cs
src/NServiceBus.Core/Routing/SubscriptionMigrationMode/SubscriptionMigrationMode.cs
src/NServiceBus.Core/obsoletes-v8.cs

As discussed with @andreasohlund , this brings back the public `MessageDrivenSubscriptions` so that downstream persisters can continue to use `DependsOn<MessageDrivenSubscriptions>`.

Bring back MessageDrivenSubscriptions

---

src/NServiceBus.Core/Receiving/ReceiveComponent.cs

As discussed, we shouldn't rely on the `IServiceCollection` information but we can make use of the `GetServices` method that returns null when there is no service found.

Replace HasComponents usage with GetService call

---

src/NServiceBus.Core/DataBus/DataBus.cs
src/NServiceBus.Core/DataBus/DataBusReceiveBehavior.cs
src/NServiceBus.Core/DataBus/DataBusSendBehavior.cs
src/NServiceBus.Core/DelayedDelivery/TimeoutManager/TimeoutManager.cs
src/NServiceBus.Core/Pipeline/Incoming/IncomingLogicalMessageContext.cs
src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs
src/NServiceBus.Core/Pipeline/Outgoing/SendComponent.cs
src/NServiceBus.Core/Pipeline/RegisterStep.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/Recoverability/RecoverabilityComponent.cs
src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs
src/NServiceBus.Core/Routing/SubscriptionMigrationMode/SubscriptionMigrationMode.cs
src/NServiceBus.Core/Sagas/CustomFinderAdapter.cs
src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs
src/NServiceBus.Core/Sagas/Sagas.cs

During the migration to `IServiceProvider`, usages of `Build(Type t)` have been changed to `GetService(Type t)`. However, `Build` did throw an exception if the resolved type was `null`, therefore it's behavior matches better with `GetRequiredService(Type t)`. This PR adjust all usages that do not expect the resolved service to be null with `GetRequiredService`. There are 5 remaining usages of `GetService` that can resolve `null` and that's properly handled by the code.

Use GetRequiredService internally

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/Pipeline/BehaviorRegistrationsCoordinatorTests.cs
src/NServiceBus.Core.Tests/Pipeline/PipelineModelBuilderTests.cs
src/NServiceBus.Core.Tests/Pipeline/PipelineSettingsTests.cs
src/NServiceBus.Core/Pipeline/AddOrReplaceStep.cs
src/NServiceBus.Core/Pipeline/Pipeline.cs
src/NServiceBus.Core/Pipeline/PipelineModelBuilder.cs
src/NServiceBus.Core/Pipeline/PipelineModifications.cs
src/NServiceBus.Core/Pipeline/PipelineSettings.cs
src/NServiceBus.Core/Pipeline/RegisterOrReplaceStep.cs
src/NServiceBus.Core/Pipeline/StepRegistrationsCoordinator.cs
src/NServiceBus.Core/obsoletes-v8.cs

- Register should throw if the step id already existed
- Replace should throw if the step id does not exist
- New RegisterOrReplace API is added to support adding or removing, this should never throw
- Remove API is deprecated

Rethink the Pipelinesettings API

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/Scheduler/ScheduleTests.cs
src/NServiceBus.Core/IMessageSession.cs
src/NServiceBus.Core/MessageSession.cs
src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs

During implementing of https://github.com/Particular/NServiceBus/pull/5770 we saw that `IMessageSession` has inconsistent naming of the `options` argument. This PR aligns all methods on the interface to use the same naming convention.

Refactored IMessageSession option argument

---

src/NServiceBus.AcceptanceTests/Core/Stopping/When_transport_infrastructure_throws_on_stop.cs
src/NServiceBus.Core.Tests/Unicast/RunningEndpointInstanceTest.cs
src/NServiceBus.Core/IMessageSession.cs
src/NServiceBus.Core/MessageSession.cs
src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs

Resolves https://github.com/Particular/NServiceBus/issues/5221.
* State check implemented in `RunningEndpointInstance` and not in `MessageSession` as `MessageSession` can not verify the current state.
* No need to inline `MessageSession`
* No custom exception required. `InvalidOprationException`  is enough.
* Not added XML exception documentation because non of our public API has that. Also, that should include null checks that will be too much.

Running endpoint instance throws meaningful exceptions in stopping/stopped states.

---

src/NServiceBus.Core/Recoverability/DefaultRecoverabilityPolicy.cs
src/NServiceBus.Core/Routing/SubscriptionMigrationMode/MigrationUnsubscribeTerminator.cs

Both missed locations on the current master branch are implicitly converted to `DateTimeOffset`. This ensures this implicit conversion is not needed. There are no behavioral changes.

Adoption of DateTimeOffset, missed DateTime.UtcNow

---

src/NServiceBus.AcceptanceTests/Core/Diagnostics/When_message_is_audited.cs
src/NServiceBus.AcceptanceTests/Core/Diagnostics/When_message_is_faulted.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/DateTimeExtensionsTests.cs
src/NServiceBus.Core.Tests/DelayedDelivery/RouteDeferredMessageToTimeoutManagerBehaviorTests.cs
src/NServiceBus.Core.Tests/Pipeline/Incoming/InvokeHandlerTerminatorTest.cs
src/NServiceBus.Core.Tests/Recoverability/DefaultRecoverabilityPolicyTests.cs
src/NServiceBus.Core.Tests/Recoverability/DelayedRetryExecutorTests.cs
src/NServiceBus.Core.Tests/Reliability/Outbox/TransportReceiveToPhysicalMessageConnectorTests.cs
src/NServiceBus.Core/DateTimeOffsetExtensions.cs
src/NServiceBus.Core/DateTimeOffsetHelper.cs
src/NServiceBus.Core/DelayedDelivery/TimeoutManager/DispatchTimeoutBehavior.cs
src/NServiceBus.Core/DelayedDelivery/TimeoutManager/StoreTimeoutBehavior.cs
src/NServiceBus.Core/DelayedDelivery/TimeoutManagerRoutingStrategy.cs
src/NServiceBus.Core/Performance/Statistics/AuditProcessingStatisticsBehavior.cs
src/NServiceBus.Core/Performance/Statistics/ProcessingStatisticsBehavior.cs
src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerTerminator.cs
src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs
src/NServiceBus.Core/Pipeline/Outgoing/AttachSenderRelatedInfoOnMessageBehavior.cs
src/NServiceBus.Core/Recoverability/DefaultRecoverabilityPolicy.cs
src/NServiceBus.Core/Recoverability/DelayedRetriesHeaderExtensions.cs
src/NServiceBus.Core/Recoverability/DelayedRetryExecutor.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscribeTerminator.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenUnsubscribeTerminator.cs
src/NServiceBus.Core/Routing/SubscriptionMigrationMode/MigrationSubscribeTerminator.cs
src/NServiceBus.Core/Routing/SubscriptionMigrationMode/MigrationUnsubscribeTerminator.cs
src/NServiceBus.Core/Sagas/ActiveSagaInstance.cs
src/NServiceBus.Core/Utils/ExceptionHeaderHelper.cs
src/NServiceBus.Core/obsoletes-v8.cs

* Adding `DateTime DateTimeExtensions.ToUtcDateTime(string)` to obsolete methods, requires new API `DateTimeOffset DateTimeExtensions.ToDateTimeOffset`.
* Introducing new class DateTimeOffsetExtensions and extracted helper methods to DateTimeOffsetHelper.

Additional DateTimeOffset refactorings accompanying #5646

---

src/NServiceBus.AcceptanceTesting/AcceptanceTestingPersistence/TimeoutPersister/AcceptanceTestingTimeoutPersistence.cs

Fix missing registration for IPersistTimeouts during AcceptanceTestingTimeoutPersistence feature setup.

Missing AcceptanceTestingTimeoutPersistence  IPersistTimeouts registration 

---

src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_failed_message.cs
src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_successful_message.cs
src/NServiceBus.AcceptanceTests/Core/UnitOfWork/When_using_custom_unit_of_work_with_wrap_handlers_in_scope.cs
src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWork.cs
src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWorkBehavior.cs

There is a behavior change that was introduced between 7.2 and 7.3 due to internal refactorings
as far as I understand the `TransactionScopeUnitOfWorkBehavior` was always placed after the `ExecuteUnitOfWork` behavior which makes sense because a custom unit of work could introduce a transaction scope and that would not be compatible with `endpointConfiguration.UnitOfWork().WrapHandlersInTransactionScope`. In previous versions of NServiceBus up to version 7.2 if a custom unit of work would have added a scope the following exception would have been thrown
> Ambient transaction detected. The transaction scope unit of work is not supported when there already is a scope present.
with the refactorings between 7.2 and 7.3 this behavior was broken similar to #5712. The consequence of this behavior …

Pipeline UOW ordering fix

---

src/NServiceBus.AcceptanceTests/Sagas/When_handling_concurrent_messages.cs

Tests executed on ASP. This will have a huge impact on all builds

Fix When condition in When_handling_concurrent_messages to no longer run into timeout

---

src/NServiceBus.AcceptanceTests/Outbox/When_blowing_up_just_after_dispatch.cs

I was hunting down several bugs in ASP because this test randomly failing. It helped me to find a few things but still, it is randomly failing. I think this test makes wrong assumptions by trying to be accurate. When we blow up right after dispatch the message will go through retries. Due to that, it is entirely possible to handle yet another retry between the done condition being observed as true and actually shutting down. From the perspective of the test we only care about the fact that the operations go out and not how many times they go out so a bool flag is way more representative of the behavior, we want to observe. I decided against having a greater or equal condition.

Fix race on When_blowing_up_just_after_dispatch

---

src/NServiceBus.AcceptanceTests/DelayedDelivery/When_Deferring_a_message.cs
src/NServiceBus.AcceptanceTests/DelayedDelivery/When_deferring_to_non_local.cs

Most transports have a multi-second send/receive latency by default due to setup/teardown. Local testing even had this sometimes be 15 seconds. This ensures the test is not accidentally green due to standard latency.

Increase delay to 5 seconds to compensate for send/receive latency

---

src/NServiceBus.Core/Hosting/Helpers/AssemblyValidator.cs

Azure Functions has [implemented this change](https://github.com/Particular/NServiceBus.AzureFunctions.ServiceBus/pull/104) to avoid picking up `Microsoft.Data.SqlClient` during assembly scanning and loading incorrect assembly.

Exclude Microsoft.Data.SqlClient from assembly scanning

---

src/NServiceBus.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt
src/NServiceBus.AcceptanceTests/Core/Pipeline/When_providing_custom_handler_registry.cs
src/NServiceBus.AcceptanceTests/Core/TestSuiteConstraints.cs

I recently noticed that a bunch of acceptance tests that are part of the `Core` folder, and therefore not shipped to downstreams, are never executed because their test requirements were never met.
There are in total 4 tests in the Core folder that require message-driven pub-sub and did not run because the transport in both acceptance tests projects in the repo were configured using native pub-sub. One test required native pub-sub to run. I changed the one test to be compatible with message-driven pub-sub and switched over the configuration of `NServiceBus.AcceptanceTests` to use message-driven pub-sub. Notice that `NServiceBus.Learning.AcceptanceTests` does support native pub-sub and therefore all tests requiring native pub-sub are still run as part of the repo's test suites.

Enable some missing core acceptance tests

---

src/NServiceBus.AcceptanceTesting/AcceptanceTestingPersistence/Outbox/AcceptanceTestingOutboxPersistence.cs
src/NServiceBus.AcceptanceTesting/AcceptanceTestingPersistence/SagaPersister/AcceptanceTestingSagaPersister.cs

Introduced in https://github.com/Particular/NServiceBus/pull/5781.
Note that we removed all R# artifacts in https://github.com/Particular/NServiceBus/pull/5776/files as part of switching over to StyleCop.Analyzers.

remove R# suppressions

---

src/NServiceBus.Core/Features/FeatureStartupTaskController.cs

log `FeatureStartupTask`s that are being started. This can be extremely valuable information when investigating issues that might involve FST order.

Log starting FeatureStartupTasks

---

src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/Pipeline/Outgoing/SendComponent.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.Configuration.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/StartableEndpoint.cs
src/NServiceBus.Core/Transports/TransportSeam.cs

proposed small refactoring to hide the `transportSeam.TransportInfrastructure` property. With this, the property can't be accessed accidentally before the transport has been created. In most cases, it is safe to pass the `TransportInfrastructure` instance as an argument to other components, however there is one edge case: We register the `ISubscriptionManager` for the main receiver in the DI container, this registration requires access to the `TransportInfrastructure`. We can't complete that registration (by assigning the internal field value used by the registration) in the `ReceiveComponent.Start` because at this point we expect the pipeline to already been built. The pipeline cache will fail to build because that runs before we start the receiver. With an event (as proposed here) we …

Transport seam infrastructure

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/obsoletes-v8.cs

To make sure the downstream extension methods can still compile with obsolete messages of their extension methods.

Do not treat TransportExtensions type as error from v8

---

src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/NServiceBus.targets

This adds an MSBuild target that will cause a build error when the package is installed on `net461` through `net471`, which is possible because of the `netstandard2.0` assembly that we currently ship in the package.

Add target to block < net472

---

src/NServiceBus.Core/Transports/TransportOperations.cs

I think there is no need to clone the properties here? Each operation has it's dedicated OpertionProperties instance and there should be no risk of reuse or something like that which would require cloning.
Thoughts?

Do not clone OperationProperties

---

src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeReceiver.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/Routing/NativeSubscribeTerminatorTests.cs
src/NServiceBus.Core/Transports/ISubscriptionManager.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportSubscriptionManager.cs

completes the changes to `ISubscriptionManager` by removing the `Subscribe` option that isn't being called anymore, so removal is pretty simple.

Remove Subscribe from ISubscriptionManager

---

src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_starting_an_endpoint_with_autosubscribe_disabled.cs

Test that when disabling autosubscribe, no events are automatically subscribed, regardless if the transport uses native or message driven pubsub. This ensures that the "disable autosubscribe" configuration is respected in both cases.
There need to be two test cases because of the slightly different setup requirements for subscriptions and the delayed nature of message driven pub-sub

Add a test for disabled autosubscribe behavior

---

src/NServiceBus.Core.Tests/Pipeline/EnsureNativeBehaviors.cs
src/NServiceBus.Core/Pipeline/Incoming/InferredMessageTypeEnricherBehavior.cs

Test ensures that internal behaviors won't inherit the convenience abstract behaviors `Behavior<TContext>` or `ForkConnector<TFromContext, TForkContext>`, which are provided for convenience of external users and carry a performance overhead in the compiled pipeline.

Ensure internal behaviors implement more performant behavior interfaces

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs
src/NServiceBus.Core/Reliability/Outbox/TransportOperation.cs

Reverting the changes made recently to rename the property containing the additional properties back to `Options` to keep the breaking changes for persisters smaller.

Revert renaming of Outbox.TransportOperation Options property

---

src/NServiceBus.Core/Transports/QueueAddress.cs

Initializes the `Properties` property with an empty collection in case `null` is passed. This makes it easier for downstreams to check as they can only check for the necessary values without having to ensure the collection itself is there in the first place.

Initialize collection property

---

src/NServiceBus.Core/Transports/HostSettings.cs
src/NServiceBus.TransportTests/NServiceBusTransportTest.cs

I think this should be set to null when not explicitly defined, as downstreams will have a hard time to determine whether the collection is empty. There is no direct API available on this type to check if the collection is empty or not so transports should be able to rely on a null check instead.
This is for example an issue for MSMQ right now because MSMQ requires an error queue configuration when running as part of Core but not otherwise, so some checks are only verified when running as part of core.

Set HostSettings.CoreSettings to null instead of empty

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Transports/HostSettings.cs

The core settings property is a `IReadOnlySettings` while the parameter on the ctor is a `SettingsHolder`. This can cause some potential issues e.g. when trying to copy over host settings because you can't pass the host settings property as a parameter due to the type mismatch.

Align HostSettings argument type

---

src/NServiceBus.AcceptanceTests/Core/TestSuiteConstraints.cs
src/NServiceBus.AcceptanceTests/EndpointTemplates/Requires.cs
src/NServiceBus.AcceptanceTests/EndpointTemplates/TestSuiteConstraints.cs
src/NServiceBus.AcceptanceTests/Feature/When_purging_queues.cs
src/NServiceBus.AcceptanceTests/Feature/When_subscribing_in_FST.cs
src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/StartableEndpoint.cs
src/NServiceBus.Learning.AcceptanceTests/TestSuiteConstraints.cs
src/NServiceBus.TransportTests/ConfigureLearningTransportInfrastructure.cs

`IPushMessages.Init` was executed before Features (and their startup tasks) were executed. This has been changed during the transport seam redesign, probably by accident because the `Initialize` functionality has been reintroduced at a later point. When migrating transports, it might cause issues when initialization logic now runs only after startup tasks have executed (e.g. purging queues or setting up the subscription-manager).
I've added two acceptance tests that failed on downstreams (one in MSMQ, one in ASB) due to the initialize behavior. Those tests would probably be more appropriate as transport tests, but the transport test infrastructure currently doesn't allow for such fine-grained lifecycle control.

Initialize transport receivers before Features are started

---

src/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
src/NServiceBus.Learning.AcceptanceTests/When_disabling_payload_restrictions.cs

This can be used by downstreams when configuring the transport settings as I've seen this helper method being implemented on multiple downstreams.
Instead of using
```
var t = (MyTransport)endpointConfiguration.ConfigureTransport();
```
you can avoid the manual cast every time:
```
var t = endpointConfiguration.ConfigureTransport<MyTransport>();
```
fun fact, this saves exactly 0 characters 😆

Add generic support for ConfigureTransport extension

---

src/NServiceBus.AcceptanceTesting/NServiceBus.AcceptanceTesting.csproj
src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
src/NServiceBus.ContainerTests/NServiceBus.ContainerTests.csproj
src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyValidator.cs
src/NServiceBus.Core/Licensing/Browser.cs
src/NServiceBus.Core/Licensing/LicenseManager.cs
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/NServiceBus.targets
src/NServiceBus.Core/ObjectBuilder/LightInject/LightInject.Microsoft.DependencyInjection.g.cs
src/NServiceBus.Core/ObjectBuilder/LightInject/LightInject.g.cs
src/NServiceBus.Core/StartableEndpoint.cs
src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWork.cs
src/NServiceBus.Learning.AcceptanceTests/NServiceBus.Learning.AcceptanceTests.csproj
src/NServiceBus.PersistenceTests/NServiceBus.PersistenceTests.csproj
src/NServiceBus.Testing.Fakes/NServiceBus.Testing.Fakes.csproj
src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj

This PR changes the assembly scanner to use the `AssemblyLoadContext` APIs to ensure that assemblies are loaded into the correct load context when running on .NET Core.
This PR also includes the changes from #5890 to move to to a `necoreapp2.1` target instead of `netstandard2.0`.

Use AssemblyLoadContext APIs on .NET Core

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/obsoletes-v8.cs

This is required to properly show obsoletion methods for downstream that with the new seam do not provide a default constructor e.g. SqlTransport that requires connection string.

Remove `new()` constraint on `UseTransport` obsoletion

---

src/NServiceBus.AcceptanceTesting/AcceptanceTestingTransport/AcceptanceTestingTransportInfrastructure.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportInfrastructure.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/ProcessingOptimizations/When_using_concurrency_limit.cs
src/NServiceBus.AcceptanceTests/Core/Recoverability/When_custom_policy_provided.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs
src/NServiceBus.Core/Transports/TransportInfrastructure.cs
src/NServiceBus.TransportTests/NServiceBusTransportTest.cs

(based on top of https://github.com/Particular/NServiceBus/pull/5915)
Implements the proposal made by @danielmarbach to use a dictionary instead of a list for faster lookup which is the main usage for core.
It seems to have a potential downside that it is no longer clear in what order the receivers were added and some hacks that assumed the first receiver to be the main receiver don't work with that anymore.
Thoughts?

use dictionary for receivers

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/obsoletes-v8.cs

Noticed that these obsoleted configuration methods do not show a proper obsolete warning when I updated some samples & snippets.
@andreasohlund was this just overseen or was there some intention behind this?

Add missing obsolete attributes to Express messaging configuration API

---

src/NServiceBus.AcceptanceTesting/AcceptanceTestingTransport/AcceptanceTestingTransportInfrastructure.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransportInfrastructure.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/ProcessingOptimizations/When_using_concurrency_limit.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs
src/NServiceBus.Core/Transports/TransportInfrastructure.cs

following up #5916 , it might be better to use the `IReadOnlyDictionary` interface for the property type as this allows easier assignment in transport. With this, implementations of the `TransportInfrastructure` won't have to always wrap their internal structure in a new `ReadOnlyDictionary`.
Thoughts @danielmarbach ?

Use IReadOnlyDictionary interface for Receivers property

---

src/NServiceBus.AcceptanceTests/Routing/MessageDrivenSubscriptions/When_missing_publisher_information.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/Recoverability/DefaultRecoverabilityPolicyTests.cs
src/NServiceBus.Core.Tests/Recoverability/RecoverabilityExecutorTests.cs
src/NServiceBus.Core/Transports/ErrorContext.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
src/NServiceBus.TransportTests/When_processing_fails.cs

Transports should float the context of `OnMessage` to `OnError` to enable users to share state between calls to them.
Examples of this are [satellites ](https://docs.particular.net/nservicebus/satellites/#implementing-a-satellite ) that want to access context items added by `OnMessage` in their error handling via the `ErrorContext`
```
public class MySatelliteFeature :
Feature
{
public MySatelliteFeature()
{
EnableByDefault();
}
protected override void Setup(FeatureConfigurationContext context)
{
context.AddSatelliteReceiver(
name: "MyCustomSatellite",
transportAddress: "targetQueue",
runtimeSettings: PushRuntimeSettings.Default,
recoverabilityPolicy: (config, errorContext) =>
{
if(errorContext.Extension.Get<string>("SomeKey") =="SomeValue" )
{
//do something
}
return …
```

Add test to make sure transports float context to on error

---

src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs

I had second thoughts about this.
The scenario described in the comment is an edge case. Most of the time, when we get an `OperationCanceledException` it will be because `messageProcessingCancellationToken.IsCancellationRequested == true`. In the edge case, we are cancelling anyway, so let's just cancel and take that to be the result of the `onMessage` invocation, rather than it failing. Also, what does explicitly throwing an `OperationCanceledException` in a handler (or behaviour) convey? It conveys that the operation is being cancelled, so let's just roll with that. Anything else is probably reduced to a corner case. In any case, our `when` condition allows recoverability to kick in when message processing is not being cancelled, so the corner case is probably reduced even further to a …

fixup! Introduce OnCompleted to the transport seam (#5936)

---

src/NServiceBus.Core/NServiceBus.Core.csproj

As far as I can see, this package ref has had no effect since we switched to an SDK style project, since the source files are contained in the package's `/content` folder, which only works with the old-style csproj. The new style csproj requires files in `/contentFiles`. Newer versions of the package have the source files in `/contentFiles`.
However, instead of relying on the package ref, we have committed the source files to `/src/NServiceBus.Core/ObjectBuilder/LightInject/`. We have also modified them. Regardless of the modifications, we have to keep doing this, because we need `LightInject.Microsoft.DependencyInjection.Source.cs`, which is no longer provided as a package. At one time it was, but [it has not been updated](https://www.nuget.org/packages/LightInject.Microsoft.DependencyInj …

remove LightInject.Source package ref

---

src/NServiceBus.Core.Tests/Serializers/XML/SerializerTests.cs

This stops the beloved `a.xml` from appearing in the local folder after running tests.
It writes the filename to the console, which appears in the "additional output" in the test runner, in case it is necessary to inspect the contents of the file in the case of failure.

stop serializer test from polluting local folder

---

src/NServiceBus.TransportTests/NServiceBusTransportTest.cs

Disposing the token source could cause a critical error in a test that is shutting down to encounter an exception while the pump is shutting down. Disposal of the token source should come last.

Move disposal of cancellation source to after shutdown

---

src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerTerminator.cs

In case handler code does not handle cancellation, provide opportunity to abort immediately before invoking handler

When shutting down throw OperationCancelledException before handler invocation

---

src/NServiceBus.AcceptanceTests/ConfigureEndpointAcceptanceTestingTransport.cs

No downstream is going to want to use TransportTransactionMode.None as the default for acceptance tests. Persisters, for instance, must use ReceiveOnly for Outbox tests to work.
This defaults to ReceiveOnly but provides an optional param to be used from `TestSuiteConstraints.cs` to select the transaction mode without needing to call (and knowing you need to include `using NServiceBus.AcceptanceTests.EndpointTemplates;` to find) this:
```
var transport = configuration.ConfigureTransport<AcceptanceTestingTransport>();
transport.TransportTransactionMode = TransportTransactionMode.ReceiveOnly;
```
That's appropriate in a specific test that needs a specific transaction mode for that test but isn't a good thing to force every downstream to have to do.

Allow acceptance tests to easily select transport transaction mode

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/ObjectBuilder/ServiceCollectionExtensions.cs

I realise that it's unlikely that the type is used explicitly, since all the methods are extension methods, but it's not immediately obvious that the entire type is obsolete. It requires scanning through all the methods and noticing that that they are all obsolete.

obsolete ServiceCollectionExtensions

---

src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs

Under .NET Core these additional assemblies are loaded from nunit and might fail depending on the test runner. Since we already track exclusions for nunit adding those doesn't hurt

Exclude nunit.engine related assemblies

---

src/NServiceBus.AcceptanceTests/ConfigureEndpointAcceptanceTestingTransport.cs

I think I made a mistake in https://github.com/Particular/NServiceBus/pull/5976 by making the default ReceiveOnly, when a non-choice should allow the transport to do its thing normally, which in the case of the AcceptanceTestingTransport would be to go to its highest supported mode of SendsAtomicWithReceive. So downstreams that weren't making a selection were being forced into ReceiveOnly.

Nullable default for acceptance test transport transaction mode

---

src/NServiceBus.AcceptanceTests/Core/Sagas/When_using_ReplyToOriginator_with_headers.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Sagas/Saga.cs

Closes #5982
https://discuss.particular.net/t/saga-replytooriginator-using-headers-impossible/2317
So instead of forcing users to do this ugly hack
```c#
protected Task ReplyToOriginatorCustom(IMessageHandlerContext context, object message)
{
if (string.IsNullOrEmpty(Entity.Originator))
{
throw new Exception("Entity.Originator cannot be null. Perhaps the sender is a SendOnly endpoint.");
}
var options = new ReplyOptions();
options.SetDestination(Entity.Originator);
dynamic correlationIdState = Activator.CreateInstance(Type.GetType("NServiceBus.AttachCorrelationIdBehavior+State"), true);
correlationIdState.CustomCorrelationId = Entity.OriginalMessageId;
context.Extensions.Set(correlationIdState);
var correlationHeaderState = Activator.CreateInstance(Type.GetType("NServiceBus.PopulateAutoCor …
```

Allow setting headers on ReplyToOriginator

---

src/NServiceBus.Core/Reliability/Outbox/Outbox.cs

Outbox should not have been limited to only ReceiveOnly mode.
Consider Azure Service Bus that has a SendsAtomicWithReceives mode. The point of Outbox is to gain consistency between messaging operations and database operations. ASB already has consistency between the incoming & outgoing messages, it doesn't make sense to sabotage that in order to get the consistency with data. The result is that running in SendsAtomic, ASB can limit the number of duplicate messages to start with, and therefore the system can run more efficiently and at lower cost.
TransportTransactionMode.None is still out, or else Outbox doesn't work.
TransactionScope is still out, because then you have the DTC transaction to keep your messaging consistent with data and Outbox isn't needed. It *is* possible to use a DTC …

Allow Outbox to run in SendsAtomicWithReceives

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/obsoletes-v8.cs

After obsoleting several items and marking them with `ReplacementTypeOrMember = "OperationProperties"` , the `OperationProperties` class got further renamed to `DispatchProperties`, and because the ObsoleteEx attributes used constant strings, it wasn't caught.
In these cases where the replacement type is a single member, this PR replaces those with a `nameof` expression, e.g. `ReplacementTypeOrMember = nameof(OperationProperties)`.
I decided not to go to this level with compound identifiers, as this looks pretty messy, and after NServiceBus 8 hits RTM, these will not changed, and readability will be more desirable:
```
ReplacementTypeOrMember = nameof(EndpointConfiguration) + "." + nameof(UseTransport) + "(" + nameof(TransportDefinition) + ")")]
```
For the next major, we should have C# …

Fix obsolete messages with nameof()

---

src/NServiceBus.Core/Licensing/LicenseManager.cs

Since we support deferred logging we can't assume what log level the "real" logger will have. This removes this assumption.
Fixes https://github.com/Particular/NServiceBus.Extensions.Hosting/issues/144

Make sure we always log selected license as INFO

---

src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs

Make sure exceptions when loading message types specified by the EnclosedMessageTypes header are logged

---

src/NServiceBus.Core.Tests/Features/FeatureStartupTests.cs
src/NServiceBus.Core/Features/FeatureActivator.cs

@DavidBoike — @andreasohlund and me sync'd on this and we came to the conclusion that adding a cancellation token to `StartFeatures` implies that the method supports cancellation (er... rather obviously), regardless of https://github.com/Particular/NServiceBus/issues/6015, and so it should indeed do whatever is required to honour that.
If this change also solves https://github.com/Particular/NServiceBus/issues/6015, it's coincidental.

support cancellation during feature startup

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/obsoletes-v8.cs

Clarify the obsolete message for the `LogicalAddress`.

better wording for the obsolete message

---

src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs

As specified in this [issue](https://github.com/Particular/NServiceBus/issues/5935) and the solution mentioned by @bording, here is the corresponding PR.

prevent loading assemblies when name is empty

---

src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs

Endpoints deployed using `.net5.0` [single file deployments](https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file) fail on startup with:
```
System.ArgumentException: Empty path name is not legal. (Parameter 'path')
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
at System.IO.File.OpenRead(String path)
at NServiceBus.AssemblyValidator.ValidateAssemblyFile(String assemblyPath, Boolean& shouldLoad, String& reason)
at NServiceBus.Hosting.Helpers.AssemblyScanner.TryLoadScannableAssembly(String assemblyPath, AssemblyScannerResults results, Assembly& assembly)
at …
```

Do not try to load assemblies with no name

---

src/NServiceBus.PersistenceTests/NServiceBus.PersistenceTests.csproj
src/NServiceBus.PersistenceTests/Sagas/When_persisting_a_saga_with_record_type.cs

_Related to https://github.com/Particular/DeveloperExperience/issues/1461_
- Changed language version to 9.0 to be able to make use of `record`.
- Added two tests
- One that uses `record` for saga data
- One that has `record` as property

Persistence tests for .NET 5 record types.

---

src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/Hosting/HostInfoSettingsTests.cs
src/NServiceBus.Core/Hosting/HostInfoSettings.cs
src/NServiceBus.Core/Support/RuntimeEnvironment.cs

There are 2 mechanisms to set the hostname;
- [override host ID](https://docs.particular.net/nservicebus/hosting/override-hostid)
- [override machine name](https://docs.particular.net/nservicebus/hosting/override-machine-name)
The `MachineNameAction` override happens in a different timeframe to the HostID, meaning the behaviour is different which causes support cases.
This PR obsoletes the `MachineNameAction` and introduces a new API on the `HostInfoSettings` class to unify the approach and make the time that each is applied uniform.
Usage example:
```c#
endpointConfiguration
.UniquelyIdentifyRunningInstance()
.OverrideHostName(Dns.GetHostEntry(Environment.MachineName).HostName);
```

Obsolete MachineNameAction

---

src/NServiceBus.Core.Tests/Recoverability/MoveToErrorsExecutorTests.cs
src/NServiceBus.Core/Recoverability/MoveToErrorsExecutor.cs

It seems this call to `RevertToOriginalBodyIfNeeded ` in the `MoveToErrorsExecutor` doesn't really seem to be necessary, as there should never be a body modification that needs to be reverted.
The only way to do body modifications that can be reverted, is by calling `IncomingMessage.UpdateBody` which is `internal`, therefore not accessible to users. The only place this update body method is called from, and made accessible to users, is in `IncomingPhysicalMessageContext.UpdateBody`. The "baseline" body for the `IncomingMessage` available in the recoverability logic (e.g. custom policy), and therefore to the errors executor, [is set when a new `ErrorContext` is created](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Transports/ErrorContext.cs#L33). There is no …

Remove unnecessary RevertToOriginalBodyIfNeeded call

---

.github/workflows/release.yml

This PR converts the NuGet package signing to use a certificate stored in Key Vault, which enables us to use an EV code signing certificate.

Use Key Vault certificate for signing - release-7.4

---

.github/workflows/release.yml

This PR converts the NuGet package signing to use a certificate stored in Key Vault, which enables us to use an EV code signing certificate.

Use Key Vault certificate for signing - release-7.5

---

src/NServiceBus.AcceptanceTests/Core/Sagas/When_overriding_saga_id_creation.cs
src/NServiceBus.AcceptanceTests/DeterministicGuid.cs

https://github.com/dotnet/runtime/issues/46934
Cherry pick as a result of https://github.com/Particular/NServiceBus/pull/6108

fix: net6 SYSLIB0021: Derived cryptographic types are obsolete

---

src/NServiceBus.Core/NServiceBus.Core.csproj

This version downgrades `System.Security.Cryptography.Xml` from 5.0 to 4.7 and therefore also requires the project dependencies to be adjusted.

Update to latest licensing package

---

src/NServiceBus.Core/Logging/RollingLogger.cs

The introduction of DateTimeOffset throughout our APIs introduced an issue when finding the logfiles for a specific day.

Fixes for logfile retrieval for a certain date

---

src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
src/NServiceBus.TransportTests/When_creating_send_only_transport.cs

To test that the receivers property is never null but at least an empty collection for easier handling by consumers of the transport API.
Some helper methods had to be made more accessible, as those could so far only be called when using tests that start a working pump, so there was no way to create a send-only endpoint before

Add receivers transport test for send-only endpoints

---

src/NServiceBus.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt
src/NServiceBus.AcceptanceTests/Core/DependencyInjection/When_endpoint_is_warmed_up.cs
src/NServiceBus.Learning.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt

Change the structure of the DI approval test slightly to give better indication whether types registered and used from DI are public or private.

Add additional information to DI approval tests

---

src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
src/NServiceBus.AcceptanceTesting/Support/FeatureStartupTaskRunner.cs
src/NServiceBus.AcceptanceTests/Core/CriticalError/When_raising_critical_error_at_startup.cs
src/NServiceBus.AcceptanceTests/Core/CriticalError/When_raising_critical_error_from_a_handler.cs
src/NServiceBus.AcceptanceTests/Core/PublishSubscribe/When_configuring_subscription_authorizer.cs
src/NServiceBus.AcceptanceTests/Feature/When_purging_queues.cs
src/NServiceBus.AcceptanceTests/Feature/When_subscribing_in_FST.cs
src/NServiceBus.AcceptanceTests/Recoverability/When_retrying_control_message_from_error_queue.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_expired.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_expired_convention.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_used_with_unobtrusive_mode.cs

Simple spike that adds a small feature for acceptance tests that allows registration of `FeatureStartupTask` without having to define owning `Feature`s first. This removes unnecessary noisy code and makes writing tests easier and faster.
Might also be a feature to be considered as a public feature in NServiceBus. Mauro already built something very similar but focused on pure startup actions (https://github.com/mauroservienti/NServiceBus.Extensions.EndpointStarted)

Startup task runner for acceptance tests

---

src/NServiceBus.PersistenceTests/IPersistenceTestsConfiguration.cs
src/NServiceBus.PersistenceTests/Sagas/When_concurrent_update_exceed_lock_request_timeout_pessimistic.cs
src/NServiceBus.PersistenceTests/TestVariant.cs

Related to https://github.com/Particular/NServiceBus.RavenDB/pull/822/commits/9217110e26a2dde12e6c2d591d8d12416b97a434
During implementing cluster wide transaction support for the RavenDB persistence, we realized having a short time cause to be problematic, since even settling a compare exchange value in the cluster can take some time. This can then cause operations to the cluster to timeout immediately, throwing an `OperationCanceledException`.
With this change, the session timeout can be overridden by the test variant without having to copy the test locally.
Ideally, we would also need this for 7.x branch later

Allow the session timeout to be controlled per permutation

---

src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/NServiceBus.props

This adds the `NServiceBus` namespace automatically when a project has [implicit global usings](https://docs.microsoft.com/en-us/dotnet/core/project-sdk/overview#implicit-using-directives) enabled by having `<ImplicitUsings>enable</ImplicitUsings>` in the project file. 
NOTE: This feature does require using the .NET 6 SDK to work, but does not cause problems if used with an older SDK.

Add props file to package for implicit global usings support

---

src/NServiceBus.Core/Pipeline/Incoming/LogicalMessageFactory.cs

null check is already covered on line 42 (https://github.com/Particular/NServiceBus/compare/redundant-check?expand=1#diff-b4ea485fb29bd22af38b7d89635850ce4c7687192747ed2e96c208cfd069dbcbL41)

Remove redundant null check

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/ObjectBuilder/ServiceProviderExtensions.cs
src/NServiceBus.Core/obsoletes-v8.cs

Restored obsolete APIs which are being removed

Obsolete APIs for next major 

---

src/NServiceBus.AcceptanceTests/Core/Audit/When_a_message_is_audited.cs
src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Transports/IncomingMessage.cs
src/NServiceBus.Core/Transports/OutgoingMessage.cs

This allows things like storing the message body separate from the headers and audit metadata

Allow dispatch behaviors to modify message bodies

---

src/NServiceBus.Core.Tests/IdGeneration/IdGenerationTests.cs
src/NServiceBus.Core/IdGeneration/CombGuid.cs

This PR modernizes slight the CombGuid code that we haven't touched for ages. Now that we target platforms directly, we can leverage some more specific APIs. With CSharp 8 and Spans we can leverage stack allocations to have the buffers allocated on the local stack to reduce the memory allocations during the GUID generation. This code is involved on the hot path (for example during saga creation) and it is worth optimizing allocations away. 
[Benchmark](https://github.com/danielmarbach/MicroBenchmarks/commit/589835fff565842dd83b95c1baedd2e1ad268115)

Optimize the CombGuid generation strategy

---

src/NServiceBus.AcceptanceTests/Serialization/When_defining_serializer_with_no_content_type.cs
src/NServiceBus.Core.Tests/Serializers/MessageDeserializerResolverTests.cs
src/NServiceBus.Core/Serialization/SerializationFeature.cs
src/NServiceBus.Core/Serializers/MessageDeserializerResolver.cs

A small fix and additional checks to prevent some edge cases where serializer resolving would fail.
If the header `NServiceBus.ContentType` is set but has no value (`null`) the dictionary fails due to an invalid `null` argument. This PR prevents null-arguments by falling back to the default serializer in this case.
Since handling of `string.Empty` would be a bit unexpected if it would be allowed in this case (e.g. define an additional deserializer with `string.Empty` as the content type could in the default serializer be resolved, depending on how the transport handles header serialization), this PR also strictly prevents any deserializer definition that doesn't specify a content type.

Serializer resolving resiliency

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/Recoverability/DelayedRetryRecoverabilityActionTests.cs
src/NServiceBus.Core.Tests/Recoverability/MoveToErrorsExecutorTests.cs
src/NServiceBus.Core.Tests/Recoverability/RecoverabilityExecutorTests.cs
src/NServiceBus.Core/Recoverability/DelayedRetry.cs
src/NServiceBus.Core/Recoverability/Discard.cs
src/NServiceBus.Core/Recoverability/Faults/MessageFaulted.cs
src/NServiceBus.Core/Recoverability/Faults/MessageProcessingFailed.cs
src/NServiceBus.Core/Recoverability/Faults/MessageToBeRetried.cs
src/NServiceBus.Core/Recoverability/IRecoverabilityActionContext.cs
src/NServiceBus.Core/Recoverability/IRecoverabilityContext.cs
src/NServiceBus.Core/Recoverability/ImmediateRetry.cs
src/NServiceBus.Core/Recoverability/MoveToError.cs
src/NServiceBus.Core/Recoverability/RecoverabilityContext.cs
src/NServiceBus.Core/Recoverability/RecoverabilityPipelineExecutor.cs
src/NServiceBus.Core/Recoverability/SatelliteRecoverabilityExecutor.cs
src/NServiceBus.Testing.Fakes/TestableRecoverabilityContext.cs

To align the design with the incoming pipeline which doesn't expose the message context

Stop exposing error context on the recoverability pipeline

---

src/NServiceBus.AcceptanceTests/Serialization/When_disabling_serializer_type_detection.cs
src/NServiceBus.AcceptanceTests/Serialization/When_disabling_serializer_type_inference.cs
src/NServiceBus.AcceptanceTests/Serialization/When_message_type_header_is_whitespaces.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core/Pipeline/Incoming/DeserializeMessageConnector.cs
src/NServiceBus.Core/Serialization/SerializationConfigExtensions.cs
src/NServiceBus.Core/Serialization/SerializationExtensions.cs
src/NServiceBus.Core/Serialization/SerializationExtensionsExtensions.cs
src/NServiceBus.Core/Serialization/SerializationFeature.cs

Backport of #6244 (including #6269 )

Disable type inference from message content

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core.Tests/Pipeline/Outgoing/AttachSenderRelatedInfoOnMessageTests.cs
src/NServiceBus.Core/Headers.cs
src/NServiceBus.Core/Pipeline/Outgoing/AttachSenderRelatedInfoOnMessageBehavior.cs

This is related to #5893
Currently, critical time in NServiceBus.Metrics and ServiceControl is being calculated based on the `TimeSent` header in a message.  However, this does not take into account that there could be a delayed delivery set for a message, which can cause the critical time that is displayed in ServicePulse to appear inaccurate especially for messages that could be set far into the future.  Critical time should be measured as the time between when a message should be delivered to an endpoint and when the message is finished processing.
This PR adds `DeliverAt` to the header of a message.  The `DeliverAt` value is calculated by either taking the `TimeSent` value and adding the `DelayDeliveryWith` time span or setting `DeliverAt` to the value of `DoNotDeliverBefore` …

Added DeliverAt to message header for auditing and metrics

---

src/NServiceBus.Core.Tests/Pipeline/Outgoing/AttachSenderRelatedInfoOnMessageTests.cs
src/NServiceBus.Core/Pipeline/Outgoing/AttachSenderRelatedInfoOnMessageBehavior.cs

Since `DelayedDeliveryConstraint` cannot be directly added to the `SendOptions` `contextBag`, in order to assign the `DeliverAt` header the `TryGetDeliveryConstraint` method needs to be used.

Fixed how the DeliverAt header is assigned

---

src/NServiceBus.Core/MessageSession.cs
src/NServiceBus.Core/Pipeline/BehaviorContext.cs

Fixes https://github.com/Particular/NServiceBus/issues/6256
This PR makes sure the linking is no longer part of the `BehaviorContext` constructor but a responsibility of the calling code. Only by doing so we can make sure the linked token source is properly disposed and will not leak memory

Make the message session responsible for linking the token source

---

src/NServiceBus.TransportTests/NServiceBusTransportTest.cs

As promised to @timbussmann here are the fixes to make sure we:
- Properly dispose the token registration
- No longer leak `CancellationTokenSource` that have a timer attached (will cause memory leaks)
The PR changes slightly the semantics of how the CancellationTokenSource is created and when the time of the test execution time starts ticking. I felt though this should not be a problem and makes the test infrastructure logic simpler to follow.

Transport Test Cancellation Fixes

---

src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/UnitOfWork/TransactionScopes/TransactionScopeUnitOfWork.cs

After [refactoring to use the native API for the MSMQ transport](https://github.com/Particular/NServiceBus.Transport.Msmq/pull/381) I discovered that Core has the same code.

Use native TransactionManager.MaxTimeout API

---

src/NServiceBus.AcceptanceTests/Recoverability/When_retrying_message_from_error_queue.cs
src/NServiceBus.Core/Reliability/Outbox/Outbox.cs

Some test cleanup to remove an unused behavior and put the `RetryId` on the test context so it can be inspected and compared if the test fails.

Minor cleanup

---

src/NServiceBus.PersistenceTests/NServiceBus.PersistenceTests.csproj
src/NServiceBus.PersistenceTests/Outbox/OutboxStorageTests.cs
src/NServiceBus.PersistenceTests/Sagas/SagaPersisterTests.cs

This is an alternative fix to #6302
By deep copying the test parameters we ensure that tests can't interfere with each other.

Deep copy test parameters

---

src/NServiceBus.Core.Analyzer/AwaitOrCaptureTasksAnalyzer.cs

Have seen reports of some users just assigning tasks to variables and then not doing anything else with those variables, because that's what the message currently suggests and that's the easiest way (at least in their minds at the time) to get rid of the diagnostic. This makes the primary message drive right to the heart of what needs to be done: whether or not you assign the task to a variable first, **the task needs to be awaited**.
The more nuanced version continues to exist in the diagnostic description - you might need to expand the diff view down a bit to see it.

Clarify what we want user to do on missing await

---

src/Custom.Build.props
src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj
src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.sln

This adds an `AnalyzerTargetFramework` property that can be used in both projects that need to sync the TFM used to get the analyzer assembly in the package.

Add AnalyzerTargetFramework property

---

src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
src/NServiceBus.Core.Analyzer.Tests.Common/ForwardCancellationToken/ForwardFromPipelineTests.cs
src/NServiceBus.Core.Analyzer.Tests.Common/Helpers/AnalyzerTestFixture.cs
src/NServiceBus.Core.Analyzer.Tests.Common/Helpers/CodeFixTestFixture.cs

If `env:CI != "true"` (i.e. local development) then nothing really changes.
If `env:CI == "true"` then by default the test output will be much quieter, because:
* Do not output a lot of gunk for acceptance tests unless `runSummary.Result.Failed` is true. Which is a bit weird, because that means the **scenario** failed, not that the test failed. But it is what it is.
* This will also help out with too much verbosity in other repos that use AcceptanceTesting framework.
* Analyzer tests will not pump out source code and diagnostic information.
If `env:VERBOSE_TEST_LOGGING == "true"` then it will be just as noisy as before. It would be possible to add a parameter to [run-tests-action](https://github.com/Particular/run-tests-action) to easily support this.
Results before and after change on …

Make test output quieter by default

---

src/NServiceBus.AcceptanceTests/Core/Routing/When_setting_operation_state_in_pipeline.cs
src/NServiceBus.Core/Causation/AttachCausationHeadersBehavior.cs
src/NServiceBus.Core/Causation/ConversationRoutingExtensions.cs
src/NServiceBus.Core/Extensibility/ExtendableOptions.cs
src/NServiceBus.Core/Extensibility/ExtendableOptionsExtensions.cs
src/NServiceBus.Core/Pipeline/Outgoing/ImmediateDispatchOptionExtensions.cs
src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs
src/NServiceBus.Core/PublishOptions.cs
src/NServiceBus.Core/Routing/ApplyReplyToAddressBehavior.cs
src/NServiceBus.Core/Routing/MessagingBestPractices/BestPracticesOptionExtensions.cs
src/NServiceBus.Core/Routing/MessagingBestPractices/EnforcePublishBestPracticesBehavior.cs
src/NServiceBus.Core/Routing/MessagingBestPractices/EnforceReplyBestPracticesBehavior.cs
src/NServiceBus.Core/Routing/MessagingBestPractices/EnforceSendBestPracticesBehavior.cs
src/NServiceBus.Core/Routing/MessagingBestPractices/EnforceSubscribeBestPracticesBehavior.cs
src/NServiceBus.Core/Routing/MessagingBestPractices/EnforceUnsubscribeBestPracticesBehavior.cs
src/NServiceBus.Core/Routing/Routers/ReplyConnector.cs
src/NServiceBus.Core/Routing/RoutingOptionExtensions.cs
src/NServiceBus.Core/Routing/UnicastSendRouter.cs
src/NServiceBus.Core/Sagas/PopulateAutoCorrelationHeadersForRepliesBehavior.cs
src/NServiceBus.Core/Sagas/Saga.cs
src/NServiceBus.Core/Scheduling/ScheduleBehavior.cs
src/NServiceBus.Core/Scheduling/ScheduleExtensions.cs
src/NServiceBus.Core/SendOptions.cs
src/NServiceBus.Core/Unicast/MessageOperations.cs

Potential fix using a dedicated context bag that is added to the pipeline context hierarchy as a property rather than being merged. This ensures that value lookups never travel further through the hierarchy due to the absence of settings.
This requires adjusting all code setting and reading state though. Conceptually it's basically the as `DispatchProperties` in v8 but for the pipeline only (therefore supporting reference types).

Message operation context

---

src/NServiceBus.AcceptanceTests/Routing/When_nested_send_with_outer_replyTo_routing.cs

The actual reply address can vary, depending on the transport that runs this test. E.g. this fails on MSMQ (see https://github.com/Particular/NServiceBus.Transport.Msmq/actions/runs/2159281452 because MSMQ adds the machine name to the return address which is not taken into account by the conventions helper class.)

Relax address assertion

---

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_setting_ttbr_in_outer_publish.cs
src/NServiceBus.AcceptanceTests/DelayedDelivery/When_deferring_outer_send.cs
src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingPublishContextTests.cs
src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingReplyContextTests.cs
src/NServiceBus.Core.Tests/Pipeline/Outgoing/OutgoingSendContextTests.cs
src/NServiceBus.Core.Tests/Routing/SubscribeContextTests.cs
src/NServiceBus.Core.Tests/Routing/UnsubscribeContextTests.cs
src/NServiceBus.Core/Pipeline/Outgoing/OutgoingPublishContext.cs
src/NServiceBus.Core/Pipeline/Outgoing/OutgoingReplyContext.cs
src/NServiceBus.Core/Pipeline/Outgoing/OutgoingSendContext.cs
src/NServiceBus.Core/Routing/SubscribeContext.cs
src/NServiceBus.Core/Routing/UnsubscribeContext.cs

The `DeliveryConstraint`s are managed via a mutable collection that is created directly on the behavior context rather than on the extendable option's context bag to prevent "sideway" leaks from reusing send options. Since they are accessed directly from the context and are only created when values have been defined, they are also affected in a very similar behavior to the options leak described in #6223 as the delivery constraint's from an "outer" operation might be found and applied.
With this behavior, delivery constraint's set in the incoming pipeline are always hidden (ignored) but I couldn't find any usage  like this.

Prevent DeliveryConstraints from leaking in nested operations

---

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_skipping_serialization_with_nested_send.cs
src/NServiceBus.Core/Serialization/SerializationContextExtensions.cs

Relates to #6223 
The `SkipSerialization` configuration can leak into nested sends, preventing nested sends to be correctly deserialized. This could lead to complete message loss as the receiving endpoint might discard the message due to the missing body.
This setting is currently only used by callbacks.
Since `MessageOperationProperties` are read-only, the behavior needs to set values scoped to the current message operation, which can be identified by the message id.

Fix SkipSerialization leak

---

src/NServiceBus.AcceptanceTests/Core/Pipeline/When_skipping_serialization_with_nested_send.cs
src/NServiceBus.Core/Serialization/SerializationContextExtensions.cs

Backport https://github.com/Particular/NServiceBus/pull/6361 to 7.5

Backport SkipSerialization leak fix to 7.5

---

src/NServiceBus.Core.Analyzer.Tests.Common/Sagas/RewriteConfigureHowToFindSagaFixerTests.cs
src/NServiceBus.Core.Analyzer/Sagas/RewriteConfigureHowToFindSagaFixer.cs

`SimpleNameSyntax` is a base class for both `IdentifierNameSyntax` and `GenericNameSyntax` which is why the generic message type failed.
Regardless of whether mapping a generic message type is supported by saga infrastructure (see [designing messages](https://docs.particular.net/nservicebus/messaging/messages-events-commands#designing-messages) in docs) it shouldn't cause a code fix to throw an error.
Fixes a bug reported in https://github.com/Particular/NServiceBus/issues/6399

Prevent generic saga from crashing saga analyzer code fix

---

src/NServiceBus.Core/Licensing/LicenseManager.cs

Reports the .NET Framework major version in the licensing URL, using a regular expression on the result of [RuntimeInformation.FrameworkDescription](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.runtimeinformation.frameworkdescription?view=net-6.0).
The regular expression finds the first digit group and returns only that, resulting in the major version.
The values of `FrameworkDescription` found using various versions of LINQPad were found to agree with the documentation:
* .NET 6: `.NET 6.0.5`
* .NET 5: `.NET 5.0.17`
* .NET Core 3.1: `.NET Core 3.1.25`
* .NET Framework 4.8: `.NET Framework 4.8.4470.0`
Given that NServiceBus 8 targets `net472;net6.0` we don't have to worry about any overlap with .NET Framework 3.x and .NET Core 3.1. The only values that should …

Report framework version in license URL

---

src/NServiceBus.AcceptanceTests/Diagnostics/TestingActivityListener.cs
src/NServiceBus.AcceptanceTests/Diagnostics/When_ambient_trace_in_pipeline.cs
src/NServiceBus.AcceptanceTests/Diagnostics/When_incoming_message_has_trace.cs
src/NServiceBus.AcceptanceTests/Diagnostics/When_processing_message_with_multiple_handlers.cs
src/NServiceBus.AcceptanceTests/Diagnostics/When_processing_message_with_saga_handler.cs
src/NServiceBus.Core/Diagnostics/ActivityDecorator.cs
src/NServiceBus.Core/Diagnostics/ActivityNames.cs
src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerTerminator.cs

Built on top of #6410
This adds a trace for each handler invocation. It creates two tags:
- `nservicebus.handler_type` contains the full type name of the handler being invoked
- `nservicebus.saga_id` gets filled in if the handler is a saga instance

Trace handler invocations

---

src/NServiceBus.Core/Routing/AutomaticSubscriptions/AutoSubscribe.cs

Noticed that Autosubscribe is currently always invoking the subscription pipeline, even when there is no event being handled.
Added some small refactoring to resolve the event types to subscribe at the FST start time instead inside the instance factory.

Do not autosubscribe without events

---

src/NServiceBus.Core/Reliability/Outbox/Outbox.cs

The `$` shouldn't be there
We seem to use both `'` and ` for the messages, I don't think we have clear guidance on which one to use for messages.

Fix outbox settings exception message

---

src/NServiceBus.AcceptanceTests/Diagnostics/When_processing_incoming_message.cs
src/NServiceBus.AcceptanceTests/Diagnostics/When_publishing_messages.cs
src/NServiceBus.AcceptanceTests/Diagnostics/When_sending_messages.cs
src/NServiceBus.AcceptanceTests/Diagnostics/When_subscribing.cs
src/NServiceBus.AcceptanceTests/Diagnostics/When_unsubscribing.cs
src/NServiceBus.Core.Tests/Diagnostics/MessageOperationsTests.cs
src/NServiceBus.Core.Tests/Pipeline/MainPipelineExecutorTests.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
src/NServiceBus.Core/Unicast/MessageOperations.cs

improves the span's display name with a bit more precision in the context of all the spans to be more clear this is about messages/events

Improve OT spans display names for pipelines

---

src/NServiceBus.Core/Performance/Metrics/MessagingMetricsFeature.cs

Disabled the metrics feature "silently" instead of throwing an exception. I think this makes more sense because diagnostics-related configuration/behavior should not prevent endpoints from starting or running. We could even leave the feature completely enabled since the registered behavior would do nothing on a send-only feature but I think disabling it gives a bit more insights in case the user looks at the diagnostics file (this might change anyway if we add any non-processing related metrics?).

Disable instead of throwing an exception

---

src/NServiceBus.AcceptanceTests/Diagnostics/When_sending_messages_from_pipeline.cs
src/NServiceBus.Core.Tests/Reliability/Outbox/FakeOutboxStorage.cs
src/NServiceBus.Core.Tests/Reliability/Outbox/TransportReceiveToPhysicalMessageConnectorTests.cs
src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs

Paired up with @lailabougria to play around some ideas to add events or tags that might be of interest for the activities.
* Adds 2 events for the dispatching "phase": A more lightweight alternative instead of creating a custom span (might still be done by the transport when needed) and making the batch dispatch behavior a little bit more visible with some additional details on the number of messages that are being dispatched.
* Adds a special tag when the outbox has already a record for the incoming message and therefore "deduplicates" the message (not invoke message handler) and re-dispatches any remaining messages if needed. This might help identify cases where the outbox comes into play but where it's not immediately clear to users.

Additional pipeline events/tags

---

src/NServiceBus.Core.Tests/Reliability/Outbox/TransportReceiveToPhysicalMessageConnectorTests.cs
src/NServiceBus.Core/Diagnostics/ActivityExtensions.cs
src/NServiceBus.Core/Diagnostics/ActivityFactory.cs
src/NServiceBus.Core/Diagnostics/SubscribeDiagnosticsBehavior.cs
src/NServiceBus.Core/Diagnostics/UnsubscribeDiagnosticsBehavior.cs
src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs

splits the APIs by using different access keys in the ContextBag. Alternatively, we can remain on a single key that should probably be renamed. In this case, there would be no way to access the incoming pipeline activity from a sending behavior. I'm not sure that would be abig deal though so that might be simpler but less flexible option?.

Split incoming and outgoing activities in pipeline context

---

guidelines/coding-guidelines.md

Since the language version has been updated in https://github.com/Particular/NServiceBus/pull/6389.
Not sure whether to completely remove this section instead. It would probably be more helpful to state some guidance about what version is allowed in a way without documenting a specific version so that this document won't fall out of date again. Any suggestions @bording ?

Update allowed language version

---

src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/OpenTelemetryEnabledEndpoint.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_ambient_trace_in_message_session.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_ambient_trace_in_pipeline.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_incoming_event_has_trace.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_incoming_message_has_baggage_header.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_incoming_message_has_no_trace.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_incoming_message_has_trace.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_messages_processed_successfully.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_outgoing_activity_has_baggage.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_processing_fails.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_processing_incoming_message.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_processing_message_with_multiple_handlers.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_processing_message_with_saga_handler.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_publishing_messages.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_retrying_messages.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_sending_messages.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_sending_messages_from_pipeline.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_sending_replies.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_subscribing.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_unsubscribing.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Hosting/HostingComponent.Configuration.cs
src/NServiceBus.Core/Hosting/HostingComponent.Settings.cs
src/NServiceBus.Core/OpenTelemetry/Metrics/MessagingMetricsFeature.cs
src/NServiceBus.Core/OpenTelemetry/OpenTelemetryConfigurationExtensions.cs

Alternative to #6444 that instead changes the API to an explicit opt-in API for both traces and metrics.
When enabled, OT instrumentation will always be "enabled", slightly decreasing endpoint performance due to the overhead (although it is minimal), regardless whether listeners for metrics and or traces have been registered.
This approach avoids all potential race conditions with the registration of OpenTelemetry listeners and would even allow runtime subscriptions.
downside of this approach:
* users need to double-opt-in into OpenTelemetry instrumentation via the `AddSource` and the `EnableOpenTelemetry` API.
* Currently a single API controlling both metrics and traces. Maybe a more granular API would be better to let users decide which parts of the instrumentation should be added.

OpenTelemetry opt-in API

---

src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
src/NServiceBus.AcceptanceTests/Core/SubscriptionMigration/AcceptanceTestingTransportServer.cs
src/NServiceBus.AcceptanceTests/EndpointTemplates/ConfigureExtensions.cs
src/NServiceBus.AcceptanceTests/EndpointTemplates/ServerWithNoDefaultPersistenceDefinitions.cs

replaces https://github.com/Particular/NServiceBus/pull/6380
Simplifies the registration of the ScenarioContext in the settings and DI by doing it in a single place and by default so that this doesn't have to be replicated on custom endpoint templates.

Register ScenarioContext setting and DI in EndpointRunner

---

src/NServiceBus.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt
src/NServiceBus.AcceptanceTests/Core/Reliability/SynchronizedStorage/When_opening_storage_session_outside_pipeline.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netframework.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.netstandard.approved.txt
src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/Reliability/SynchronizedStorage/CompletableSynchronizedStorageSessionAdapter.cs
src/NServiceBus.Core/Reliability/SynchronizedStorage/CompletableSynchronizedStorageSessionExtensions.cs
src/NServiceBus.Core/Reliability/SynchronizedStorage/SynchronizedStorage.cs
src/NServiceBus.Persistence.InMemory.AcceptanceTests/ApprovalFiles/When_endpoint_is_warmed_up.Make_sure_things_are_in_DI.approved.txt

As discussed on yesterday's sync, this is a quick attempt of making the adapter class public instead of directly implementing and wrapping `CompleteableSynchronizedStorageSession` to reduce potential confusion about the specific implementation of the interface.

Make the session adapter class public

---

src/NServiceBus.AcceptanceTests/Core/Installers/InstallationOnlyComponent.cs
src/NServiceBus.AcceptanceTests/Core/Installers/When_installing_endpoint.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Installation/Installer.cs
src/NServiceBus.Core/Installation/InstallerWithExternallyManagedContainer.cs

Based on #6549, this PR adds new installation APIs that can be used to run installation separately with or without an externally managed container without starting the endpoint.
This goes further than `Endpoint.Create` as it also initializes the transport seam and allows endpoints with an externally managed container to execute setup/installation logic without starting the endpoint (currently not possible)
docs PR: https://github.com/Particular/docs.particular.net/pull/5882

Add dedicated Installer APIs

---

src/NServiceBus.Core.Tests/OpenTelemetry/ActivityFactoryTests.cs
src/NServiceBus.Core/OpenTelemetry/Tracing/ActivityFactory.cs

Due to hard-to-predict sampler behavior, it might be that the incoming message activity is not created although we have a listener registered. When invoking handler, the `Activity.Current` can be `null` in such cases which means that the `StartActivity` call for the handler span will be run through the sampler again and might be created. This can cause handler spans being created but not properly connected which is especially weird when multiple handlers for a single message exist. If the incoming message activity hasn't been created (or no other user-defined ambient activity exists), the handler activity should never be created.

Don't create handler activity when incoming message activity isn't set

---

src/NServiceBus.Core/OpenTelemetry/Tracing/ActivityFactory.cs

Parsing the `ActivityContext` currently always sets `isRemote` false. This can cause sampler behavior to be incorrect as some samplers, e.g. [`ParentBasedSampler`](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Trace/ParentBasedSampler.cs#L122) (default sampler) can use this property to adjust the sampling behavior. The default behavior isn't impacted by the current implementation as both remote and local parent fall back to not sampling, but a user-defined configuration might behave differently.
This PR changes the implementation to correctly set the `isRemote` flag on the parent context. This needs to be done via a workaround until .NET 7 which will contain a proper API for this, see https://github.com/dotnet/runtime/issues/42575
Note that this can't …

Correctly set parent activity for ReceiveMessage activity as remote

---

src/NServiceBus.PersistenceTests/Sagas/When_updating_saga_concurrently_on_same_thread.cs
src/NServiceBus.PersistenceTests/Sagas/When_updating_saga_concurrently_twice_on_the_same_thread.cs

This PR aligns
- `When_updating_saga_concurrently_on_same_thread`
- `When_updating_saga_concurrently_twice_on_the_same_thread`
with `When_updating_saga_concurrently_on_different_thread` [which already does update a property of the saga](https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.PersistenceTests/Sagas/When_updating_saga_concurrently_on_different_threads.cs#L55). 
It is required to update something on the saga otherwise persisters like RavenDB that can discover whether something has change or not will simply not execute any side effect because the document hasn't been updated which then also doesn't trigger a concurrency conflict.
- [Release 8.0](TBD)
- [Release 7.8](TBD)

Persistence Tests - Make sure stale records are modified before save

---

src/NServiceBus.PersistenceTests/Sagas/When_updating_saga_concurrently_on_same_thread.cs
src/NServiceBus.PersistenceTests/Sagas/When_updating_saga_concurrently_twice_on_the_same_thread.cs

Backport #6603 to `release-8.0`

Persistence Tests - Make sure stale records are modified before save - Backporting of #6603

---

src/NServiceBus.PersistenceTesting/Sagas/When_updating_saga_concurrently_on_same_thread.cs
src/NServiceBus.PersistenceTesting/Sagas/When_updating_saga_concurrently_twice_on_the_same_thread.cs

Backport of #6603 to `release-7.8`

Persistence Tests - Make sure stale records are modified before save - Backporting of #6603 

---

src/NServiceBus.Core.Analyzer.Tests.Common/ForwardCancellationToken/ForwardCancellationTokenTests.cs
src/NServiceBus.Core.Analyzer.Tests.Common/Helpers/AnalyzerTestFixture.cs
src/NServiceBus.Core.Analyzer/ForwardCancellationTokenAnalyzer.cs

This fixes a bug discovered in the ForwardCancellationTokenAnalyzer and adds several more test cases.
The analyzer is supposed to ignore when you pass `CancellationToken.None`, but throwing an exception when doing the same thing but by using a default operator or literal which were introduced between C# 7 and 8:
```csharp
// OK
await Task.Delay(100, CancellationToken.None);
// Throwing exceptions in 8.0.0
await Task.Delay(100, default(CancellationToken));
await Task.Delay(100, default);
```
This requires better analysis to make sure the presence of `default` doesn't throw it off:
```csharp
public async Task SomeMethod(int a, string b, CancellationToken token = default) { }
// Would pass the 0 and null but not provide a token:
await SomeMethod(default, default);
```
This PR also introduces …

Fix ForwardCancellationTokenAnalyzer bug on default parameter values

---

src/NServiceBus.Core.Analyzer.Tests.Common/ForwardCancellationToken/ForwardCancellationTokenTests.cs
src/NServiceBus.Core.Analyzer.Tests.Common/Helpers/AnalyzerTestFixture.cs
src/NServiceBus.Core.Analyzer/ForwardCancellationTokenAnalyzer.cs

*Backports https://github.com/Particular/NServiceBus/pull/6616 to the release-8.0 branch.*
---
This fixes a bug discovered in the ForwardCancellationTokenAnalyzer and adds several more test cases.
The analyzer is supposed to ignore when you pass `CancellationToken.None`, but throwing an exception when doing the same thing but by using a default operator or literal which were introduced between C# 7 and 8:
```csharp
// OK
await Task.Delay(100, CancellationToken.None);
// Throwing exceptions in 8.0.0
await Task.Delay(100, default(CancellationToken));
await Task.Delay(100, default);
```
This requires better analysis to make sure the presence of `default` doesn't throw it off:
```csharp
public async Task SomeMethod(int a, string b, CancellationToken token = default) { }
// Would pass the 0 …
```

Ensure ForwardCancellationTokenAnalyzer treats usages of default expressions properly (release-8.0)

---

src/NServiceBus.Core/Serializers/XML/XmlSerializer.cs

Backport of #6615 to the release-8.0 branch

XmlSerializer SanitizeInput and SkipWrappingRawXml settings use same configuration key

---

src/NServiceBus.AcceptanceTests/Core/DependencyInjection/When_registering_async_disposables_externally_managed.cs
src/NServiceBus.AcceptanceTests/Core/DependencyInjection/When_registering_async_disposables_internally_managed.cs
src/NServiceBus.Core/EndpointInstanceExtensions.cs
src/NServiceBus.Core/Hosting/ExternallyManagedContainerHost.cs
src/NServiceBus.Core/Hosting/HostCreator.cs
src/NServiceBus.Core/Hosting/HostingComponent.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
src/NServiceBus.Core/Recoverability/RecoverabilityPipelineExecutor.cs
src/NServiceBus.Core/Unicast/RunningEndpointInstance.cs

Backport of https://github.com/Particular/NServiceBus/pull/6650 to `release-8.0`

Use async scope to make sure scoped IAsyncDisposable instances get disposed 

---

src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveContext.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs
src/NServiceBus.Core/Recoverability/RecoverabilityContext.cs
src/NServiceBus.Core/Recoverability/RecoverabilityPipelineExecutor.cs

Just a rough version to show the potential for removing allocations of the `PipelineRootContext` class for the main and recoverability pipelines fairly easily. The root context is just used as an intermediary class that is directly passed to a new context.
The ctors of the `TransportReceiveContext` and `RecoverabilityContext` look a lot uglier though, so I'm not sure it's really worthwhile pursuing this idea but it could safe a few allocations, especially when thinking about the `ContextBag`'s internal data structure.
I haven't changed the instances of `PipelineRootContext` on the `IMessageSession` operations as this would require more parameters rippling through more method calls, making the code a lot messier without some other refactoring to counter that smell.

Remove unnecessary allocations of PipelineRootContext

---

src/NServiceBus.AcceptanceTesting/Support/CaptureRecoverabilityActionBehavior.cs
src/NServiceBus.AcceptanceTesting/Support/EndpointRunner.cs
src/NServiceBus.AcceptanceTests/ApprovalFiles/When_pipelines_are_built.Should_preserve_order.approved.txt
src/NServiceBus.AcceptanceTests/Recoverability/When_custom_policy_discards_message.cs
src/NServiceBus.Learning.AcceptanceTests/ApprovalFiles/When_pipelines_are_built.Should_preserve_order.approved.txt

The acceptance testing framework tracks all pipeline exceptions and keeps the test running until the message has processed successfully or has been moved to the error queue. However, when using the `Discard` recoverability action, the test would run into a timeout and show the error message `Some failed messages were not handled by the recoverability feature.`
This PR changes the acceptance testing framework to track discarded messages as "completed" messages too so that the test no longer times out in such cases.
Since we don't have any public notification APIs for discarded messages (probably a separate issue to raise), a custom behavior is used to inspect the applied recoverability action which is now possible due to the recoverability pipeline extensibility. Along with that, I also …

Complete acceptance test when messages are discarded

---

src/NServiceBus.Core/Recoverability/RecoverabilityAction.cs

Fixes https://github.com/Particular/docs.particular.net/issues/5983
Related to https://github.com/Particular/docs.particular.net/pull/5982
I imagine this improvement to xmldoc would not be backported to previous versions and would be released with the next minor version of NServiceBus, whenever that happens to be.

Clearer xmldoc on RecoverabilityActions

---

src/NServiceBus.PersistenceTests/Sagas/When_multiple_sagas_in_outbox_transaction.cs
src/NServiceBus.PersistenceTests/Sagas/When_updating_saga_in_outbox_transaction.cs

Adds a set of tests that test the combination of the outbox transaction and the saga persister, specifically:
* Verifies that multiple saga modifications can be handled properly within a single outbox transaction
* Verifies that commits are correctly moved to the outbox transaction session
These tests have been tested to work on the persisters via:
* https://github.com/Particular/NServiceBus.Persistence.CosmosDB/pull/543 ✅ 
* https://github.com/Particular/NServiceBus.Storage.MongoDB/pull/475 ✅ 
* https://github.com/Particular/NServiceBus.Persistence.Sql/pull/1167 ✅ 
* https://github.com/Particular/NServiceBus.Persistence.AzureTable/pull/751 ✅ 
* https://github.com/Particular/NServiceBus.RavenDB/pull/1126 ✅ 
* https://github.com/Particular/NServiceBus.NHibernate/pull/962 ✅

Add additional outbox+saga persistence tests

---

releasing.md

Those instructions are covered by the internal release procedure documentation

Delete releasing instructions

---

src/NServiceBus.PersistenceTests/Outbox/OutboxStorageTests.cs
src/NServiceBus.PersistenceTests/Sagas/When_concurrently_persisting_sagas_with_same_correlation_prop.cs
src/NServiceBus.PersistenceTests/Sagas/When_persisting_a_saga_with_the_same_unique_prop_as_another_saga.cs

* Adds a basic test verifying that loading an existing outbox record contains the same message id as the id passed into the query.
* Renames some saga tests that have been renamed by https://github.com/Particular/NServiceBus/pull/6117 and don't align with the overall naming convention in the project

Add basic outbox loading persistence test

---

src/NServiceBus.AcceptanceTests/Core/Installers/When_creating_queues.cs
src/NServiceBus.Core/Audit/Audit.cs

The changes to the NServiceBus 8 transport seam treat all queues the same and pass them as a collection to the transport, and transports create them. Becuase the Audit feature was not dependent upon whether the endpoint was send-only, this means that the audit queue was also being created, as well as other unnecessary stuff like the diagnostics entry, logging, and adding behaviors to the receive pipeline.
This PR adds a prerequisite so that the Audit feature will not run if the endpoint is send only.
This is a fix for https://github.com/Particular/NServiceBus/issues/6736.

Don't configure auditing or create audit queue if endpoint is SendOnly

---

src/NServiceBus.Core.Analyzer.Tests.Common/ForwardCancellationToken/ForwardCancellationTokenFixerTests.cs
src/NServiceBus.Core.Analyzer/ForwardCancellationTokenFixer.cs

Fix CancellationTokenAnalyzer fluent style API bug

---

src/NServiceBus.Core.Tests/Serializers/SystemTextJson/SystemJsonSerializerTests.cs
src/NServiceBus.Core/Serializers/SystemJson/JsonMessageSerializer.cs

This makes it compatible with Newtonsoft which adds the BOM by default, see https://docs.particular.net/nservicebus/serialization/newtonsoft#usage-custom-writer

Make system json handle payloads with BOM

---

src/NServiceBus.Core/NServiceBus.Core.csproj

Follow up for #6771 and the discussion in https://github.com/Particular/NServiceBus/pull/6749#pullrequestreview-1464490349
@andreasohlund and I discussed this again, and we believe the same minimum version of System.Text.Json should be used for all supported TFMs to avoid confusion for us and the customer. As an example, today if we would leverage internally the source generation to speed up serialization for existing types you could use the new `.Default` property in nNET472 but not on NET6.
Additionally, from an end-user perspective, you could be using `JsonDerivedTypedAttribute` to support polymorphic serialization, but you have to take an extra step in NET 6 by adding an explicit reference to System.Text.Json 7.0 and higher. 
Once we remove support for .NET 6 we can move the reference …

Take an explicit reference to System.Text.Json 7.0.3 for all the supported TFMs

---

src/NServiceBus.Core.Tests/API/NullableApiUsages.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Sagas/CorrelatedSagaPropertyMapper.cs
src/NServiceBus.Core/Sagas/IConfigureHowToFindSagaWithMessage.cs
src/NServiceBus.Core/Sagas/SagaPropertyMapper.cs
src/NServiceBus.Core/Sagas/ToSagaExpression.cs

* Backport of https://github.com/Particular/NServiceBus/pull/6776 for release-8.1

Backport saga mapper nullability fix to release-8.1

---

src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs

When an acceptance tests fails, the exception is logged ~4 times for the failing test. Some of this seems to be part of nUnit which already logs exceptions thrown anyway. This removes one of the exception dumps since there are already enough stack traces dumped to the text context and log.
A potential case where this might be an issue could be when the exception from `Scenario.Run` is caught by the test code. In this case, the stack trace might not be dumped except for the log entries but that seems acceptable.

Reduce logging output on test completion

---

src/NServiceBus.AcceptanceTesting/ScenarioWithContext.cs
src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs
src/NServiceBus.AcceptanceTesting/Support/TestContextExtensions.cs
src/NServiceBus.AcceptanceTests/NServiceBusAcceptanceTest.cs

An attempt to further reduce log output for passing tests.
Currently, the acceptance testing `Scenario` writes additional log output when the scenario fails. However, we have quite a few tests that use `Assert.Throws` since they test cases where exceptions are expected. However, the scenario isn't aware of the assertions and logs regardless. This causes a lot (~2-6k lines) of additional log output for each execution of the acceptance tests that aren't really necessary and might be quite confusing when looking through log files.
I think the best approach is to move the logging responsibility away from the `Scenario` classes into the tests instead. Since all acceptance tests already have a shared base class, this isn't too hard (however it adds some coupling as data need to be shared …

Log additional test information only on failing test case

---

src/NServiceBus.AcceptanceTesting/Support/ScenarioRunner.cs

The while loops don't contain a sleep to throttle the DONE check in the acceptance test runner which causes the CPU to spike. 
By adding a `Thread.Delay` acceptance tests run without hammering the CPU and have pretty much the same test run duration.

Replace Yield with Delay to not hammer the CPU

---

src/NServiceBus.AcceptanceTesting/AcceptanceTestingTransport/AcceptanceTestingTransport.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/FakeTransport.cs
src/NServiceBus.AcceptanceTests/Core/FakeTransport/ProcessingOptimizations/When_using_concurrency_limit.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/Config/When_configuring_transport_twice.cs
src/NServiceBus.Core.Tests/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptionsConfigExtensionsTests.cs
src/NServiceBus.Core/Audit/AuditContext.cs
src/NServiceBus.Core/Transports/Learning/LearningTransport.cs
src/NServiceBus.Core/obsoletes-v9.cs
src/NServiceBus.Testing.Fakes/TestableAuditContext.cs

Obsoletes cleanup round 2

---

src/NServiceBus.Core.Tests/AssemblyScanner/When_exclusion_predicate_is_used.cs
src/NServiceBus.Core.Tests/AssemblyScanner/When_validating_assemblies.cs
src/NServiceBus.Core.Tests/Config/When_scanning_assemblies.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerConfiguration.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanningComponent.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyValidator.cs

Fixes https://github.com/Particular/NServiceBus/issues/6820
Improves the assembly scanner performance in "regular cases" slightly and in cases when the exclusion list is larger, up to 4 times.
I was doing some investigations for a customer that mentioned they are seeing slow startup times in their rather large solution. Once I was able to get my hands on the profiler data it was apparent that the `IsExcluded` check is the culprit. 
I have created a [solution generator](https://github.com/danielmarbach/NServiceBusAssemblyScanning) that allows simulating arbitrary solution sizes. As a reference point, I created a solution with roughly 960 projects and more than 140K types. 
Here is the excerpt from the customer callstack
|         Method |       Mean |     Error |    StdDev |     Median | …

AssemblyScanner improvements

---

src/NServiceBus.Core.Tests/AssemblyScanner/AssemblyScannerTests.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs

Backport of #6814 to `release-8.1`

AssemblyScanning exclusion list matching inefficiency slows down the endpoint creation significantly

---

src/NServiceBus.Core.Tests/ApprovalFiles/DiagnosticsWriterTests.ShouldWriteEntriesWithTypesUsingTheFullName.approved.txt
src/NServiceBus.Core.Tests/OpenTelemetry/DiagnosticsWriterTests.cs
src/NServiceBus.Core/Hosting/StartupDiagnostics/HostStartupDiagnosticsWriter.cs

- Fixes https://github.com/Particular/NServiceBus/issues/6813

Startup diagnostic serialization fails when diagnostic entries include System.Type properties

---

src/NServiceBus.Core.Tests/AssemblyScanner/When_exclusion_predicate_is_used.cs
src/NServiceBus.Core.Tests/TestDlls/some.random.dll
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs

Fixes https://github.com/Particular/NServiceBus/issues/6835

Allow assemblies without extensions to be excluded

---

src/NServiceBus.Core.Tests/AssemblyScanner/When_exclusion_predicate_is_used.cs
src/NServiceBus.Core.Tests/TestDlls/some.random.dll
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanner.cs

- Backport of https://github.com/Particular/NServiceBus/pull/6834 to `release-8.1`

AssemblyNames containing a dot without file extensions cannot be excluded in the assembly scanner

---

src/NServiceBus.AcceptanceTesting/AcceptanceTestingPersistence/SagaPersister/AcceptanceTestingSagaPersister.cs
src/NServiceBus.AcceptanceTesting/Support/EndpointBehavior.cs
src/NServiceBus.AcceptanceTesting/Support/FeatureStartupTaskRunner.cs
src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_excluding_event_type_from_autosubscribe.cs
src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga.cs
src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_starting_an_endpoint_with_a_saga_autosubscribe_disabled.cs
src/NServiceBus.AcceptanceTests/Core/AutomaticSubscriptions/When_starting_an_endpoint_with_autosubscribe.cs
src/NServiceBus.Core.Tests/Pipeline/BehaviorRegistrationsCoordinatorTests.cs
src/NServiceBus.Core.Tests/Serializers/XML/Pull_819.cs
src/NServiceBus.Core.Tests/Serializers/XML/SerializerTests.cs
src/NServiceBus.Core/Audit/AuditContext.cs
src/NServiceBus.Core/Extensibility/ExtendableOptions.cs
src/NServiceBus.Core/Features/Feature.cs
src/NServiceBus.Core/Features/FeatureConfigurationContext.cs
src/NServiceBus.Core/Features/PrerequisiteStatus.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScannerResults.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanningComponent.cs
src/NServiceBus.Core/Persistence/PersistenceExtensions.cs
src/NServiceBus.Core/Pipeline/Outgoing/RoutingContextExtensions.cs
src/NServiceBus.Core/Pipeline/Pipeline.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.Configuration.cs
src/NServiceBus.Core/Recoverability/RecoverabilitySettingsExtensions.cs
src/NServiceBus.Core/Routing/EndpointInstances.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/Publishers.cs
src/NServiceBus.Core/Routing/UnicastPublishRouter.cs
src/NServiceBus.Core/Sagas/SagaMetadata.cs
src/NServiceBus.Core/Serialization/SerializationSettingsExtensions.cs
src/NServiceBus.Core/StaticHeaders/StaticHeadersConfigExtensions.cs
src/NServiceBus.TransportTests/NServiceBusTransportTest.cs

This change satisfies the new `IDE0028` analyzer rules in the .NET 8 SDK.

Use C# 12 collection expressions

---

src/NServiceBus.PersistenceTests/IPersistenceTestsConfiguration.cs

This PR enables `ImplicitDistributedTransactions` in the persistence tests package.
Follow-up to #6850

Enable distributed transactions in persistence tests

---

src/NServiceBus.Core/NServiceBus.Core.csproj
src/NServiceBus.Core/Utils/DeterministicGuid.cs
src/NServiceBus.Core/Utils/PathUtilities.cs

Incorporates https://github.com/Particular/NServiceBus/pull/6843
|   Method |              input1 |              input2 |       Mean |    Error |   StdDev | Ratio |  Gen 0 | Allocated |
|--------- |-------------------- |-------------------- |-----------:|---------:|---------:|------:|-------:|----------:|
| Original |            Instance |                Host | 1,237.7 ns | 23.49 ns | 23.07 ns |  1.00 | 0.0038 |     368 B |
|       V2 |            Instance |                Host |   542.0 ns |  6.28 ns |  5.57 ns |  0.44 | 0.0010 |      88 B |
|       V3 |            Instance |                Host |   501.0 ns |  3.96 ns |  3.51 ns |  0.41 |      - |      48 B |
|          |                     |                     |            |          |          |       |        |           |
| …

Utils improvements

---

src/NServiceBus.PersistenceTests/IPersistenceTestsConfiguration.cs
src/NServiceBus.PersistenceTests/Sagas/When_persisting_a_saga_with_an_escalated_DTC_transaction.cs

Change the logic in the DTC persistence test to confirm participating transactions are rolled back when the persistence fails to update instead of expecting a specific exception type.
Prior to these changes, this test was written to expect the same implementation as the NonDurable persistence, where the [update logic](https://github.com/Particular/NServiceBus.Persistence.NonDurable/blob/master/src/NServiceBus.Persistence.NonDurable/SagaPersister/NonDurableSagaPersister.cs#L99) is enlisted and committed as part of a [DTC enlistment notification implementation](https://github.com/Particular/NServiceBus.Persistence.NonDurable/blob/master/src/NServiceBus.Persistence.NonDurable/SynchronizedStorage/NonDurableSynchronizedStorageSession.cs#L67).
In other persistences, such as SQL Persistence, the …

Fix DTC persistence test

---

.github/workflows/release.yml

This PR lets the release workflow be manually triggered on any branch or tag in the repo.
When it is is manually triggered, the release workflow pushes the packages to a new testing feed instead of deploying to Octopus.
This testing feed can then be used on downstream PRs to test the changes easily without causing any of the problems that would occur if Octopus/the main feed was used.

Add manual trigger to push packages to testing feed

---

src/NServiceBus.TransportTests/NServiceBusTransportTest.cs
src/NServiceBus.TransportTests/When_multiple_messages_are_available.cs

A new transport test that verifies the concurrent message processing behavior by testing whether message processing pipelines are guaranteed to execute in parallel and independently from each other.
Todo:
* MSMQ - not going to be updated to core v9

Transport concurrency test

---

src/NServiceBus.TransportTests/When_multiple_messages_are_available.cs

I realized that this `WaitAsync` is not necessary as the `TaskCompletionSource` created via `CreateTaskCompletionSource()` is already hooked up to the test timeout cancellation token, therefore this is redundant.

Remove unnecessary WaitAsync

---

src/NServiceBus.PersistenceTests/Sagas/When_persisting_a_saga_with_an_escalated_DTC_transaction.cs

Add a TaskCompletionSource so make sure the DTC transaction completely rollback before Asserting.

Add TaskCompletionSource to avoid race

---

src/NServiceBus.Core.Tests/Unicast/LoadHandlersConnectorTests.cs
src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs
src/NServiceBus.Core/Reliability/SynchronizedStorage/CompletableSynchronizedStorageSessionExtensions.cs
src/NServiceBus.Testing.Fakes/TestableIncomingContext.cs

Once merged:
- Remove validation code in SqlP like https://github.com/Particular/NServiceBus.Persistence.Sql/blob/master/src/SqlPersistence/SynchronizedStorage/SqlDialect_MsSqlServer.cs#L36

Verify that users are not tampering with the transaction scope opened by the transport

---

src/NServiceBus.Core.Analyzer/Sagas/RewriteConfigureHowToFindSagaFixer.cs

The "elastic" category of trivia appear to be something that the roslyn code formatter that runs after a code fixer has been executed will detect and fix up to be correct for the document.
Source of info: https://github.com/dotnet/roslyn/issues/47382#issuecomment-686267146

Use ElasticCarriageReturnLineFeed in code fixer

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/Recoverability/FaultMetadataExtractor.cs
src/NServiceBus.Core/Recoverability/Faults/FaultMetadataExtractor.cs
src/NServiceBus.Core/Recoverability/Faults/FaultsHeaderKeys.cs

Introduce fault header keys

---

src/NServiceBus.AcceptanceTests/DataBus/When_sending_databus_properties_with_systemjsonserializer.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/DataBus/DataBusProperty.cs

Fixes: https://github.com/Particular/NServiceBus/issues/6804

Prevent Type property on DataBusProperty<T> from being serialized

---

src/NServiceBus.AcceptanceTests/DataBus/When_sending_databus_properties_with_systemjsonserializer.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/DataBus/DataBusProperty.cs

- Backport of https://github.com/Particular/NServiceBus/pull/6881 to `release-8.1`

Message serialization and deserialization fails when using SystemJsonSerializer and sending large message through DataBusProperty<T>

---

src/NServiceBus.Core/Transports/MessageContext.cs

Fix the property description that incorrectly stated the value being related to a failed message. This is most likely a copy/paste error taken from `ErrorContext.ReceiveAddress`.

Fix MessageContext.ReceiveAddress property description

---

src/NServiceBus.AcceptanceTests/DataBus/When_sending_databus_properties_with_systemjson_message_serializer.cs
src/NServiceBus.AcceptanceTests/DataBus/When_sending_databus_properties_with_xml_message_serializer.cs
src/NServiceBus.AcceptanceTests/DataBus/When_sending_unobtrusive_databus_properties_with_systemjson_message_serializer.cs
src/NServiceBus.AcceptanceTests/DataBus/When_sending_unobtrusive_databus_properties_with_xml_message_serializer.cs
src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/DataBus/DataBusProperty.cs

This PR finishes up the changes made to `DataBusProperty<T>` in #6810 and #6889. It cleans up leftover stuff from the `ISerializable` removal and ensures that it will still be able to serialize properly with the in-box serializers.
I also expanded the test coverage a bit to ensure that both message serializers are tested for both `DataBusProperty<T>` and unobtrusive DataBus options.

Update DataBusProperty serialization

---

src/NServiceBus.Core/NServiceBus.Core.csproj

System.Security.Cryptography.Xml 7.0.1 references System.Security.Cryptography.Pkcs 7.0.0, which is affected by [CVE-2023-29331](https://github.com/dotnet/announcements/issues/257).
System.Security.Cryptography.Pkcs has been elevated to a top-level dependency and updated to a non-vulnerable version to ensure that systems using NServiceBus are not relying on a vulnerable version of System.Security.Cryptography.Pkcs.

Add top-level reference to System.Security.Cryptography.Pkcs

---

src/NServiceBus.Core.Tests/DocumentationTests.cs
src/NServiceBus.Core.Tests/StandardsTests.cs
src/NServiceBus.Core/NServiceBus.Core.csproj

We don't need to reference System.Diagnostics.DiagnosticSource or System.Text.Json because they ship as part of .NET.
SimpleJson had already been removed from the repo, but the package was still being referenced.
There were also some leftover references to things that have been removed in some tests, so I cleaned those up as well.

Remove unnecessary packages

---

src/NServiceBus.AcceptanceTesting/AcceptanceTestingPersistence/Outbox/AcceptanceTestingOutboxStorage.cs
src/NServiceBus.AcceptanceTests/Outbox/When_publishing_with_outbox.cs
src/NServiceBus.Core.Tests/Routing/RoutingToDispatchConnectorTests.cs
src/NServiceBus.Core/Pipeline/Outgoing/RoutingContextExtensions.cs
src/NServiceBus.Core/Pipeline/Outgoing/RoutingToDispatchConnector.cs
src/NServiceBus.Core/Recoverability/SatelliteRecoverabilityExecutor.cs

Backport of #6905 to `release-8.0`

Combining the outbox with message-driven transport may lead to message loss on publish to multiple subscribers

---

src/NServiceBus.Core/NServiceBus.Core.csproj

The NServiceBus.props file adds the `NServiceBus` namespace to the list of implicltly referenced namespaces when `<ImplicitUsings>enable</ImplicitUsings>` is set in a project file. However, when the NServiceBus package is referenced transitively (for example, like we do in a lot of our samples), the namespace isn't added properly.
Adding the props file to the `buildTransitive` folder in the package fixes that.

Add props file to buildTransitive also

---

.github/workflows/ci.yml
.github/workflows/release.yml
THIRD-PARTY-NOTICES.txt
src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj
src/NServiceBus.PersistenceTests/NServiceBus.PersistenceTests.csproj
src/NServiceBus.TransportTests/NServiceBus.TransportTests.csproj

Follow-up to #6924 to adjust the repo to the new Particular.Packaging version.
I also went ahead and removed the `preview` quality from the workflow files because I noticed that despite the RTM version of the SDK being available, the RC was still being used.

Particular.Packaging update follow-up

---

src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs
src/NServiceBus.TransportTests/When_starting_again.cs

Also fixes the learning transport behavior

TransportTest that verifies transports can be started again after stopping

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core/obsoletes-v8.cs

The obsolete message on the class type referred to `DateTimeOffsetExtensions`, which is an internal class. Instead, it should be `DateTimeOffsetHelper`, as it correctly is on all class members.

Fix ReplacementTypeOrMember for DateTimeExtensions

---

src/NServiceBus.Core/Features/FeatureActivator.cs

- avoid additional array allocation and conversion
- avoid implicit checking of duplicates using `Union` method

use collection expression spread operator

---

src/Custom.Build.props
src/NServiceBus.AcceptanceTesting/AcceptanceTestingPersistence/SubscriptionStorage/AcceptanceTestingSubscriptionStorage.cs
src/NServiceBus.Core.Analyzer/SemanticModelCache.cs
src/NServiceBus.Core.Tests/Serializers/XML/SerializerTests.cs
src/NServiceBus.Core/DeepCopy.cs
src/NServiceBus.Core/MessageMutators/MutateInstanceMessage/MutateIncomingMessageBehavior.cs
src/NServiceBus.Core/MessageMutators/MutateInstanceMessage/MutateOutgoingMessageBehavior.cs
src/NServiceBus.Core/MessageMutators/MutateTransportMessage/MutateIncomingTransportMessageBehavior.cs
src/NServiceBus.Core/MessageMutators/MutateTransportMessage/MutateOutgoingTransportMessageBehavior.cs
src/NServiceBus.Core/MessageMutators/Mutators.cs
src/NServiceBus.Core/Routing/EndpointInstances.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/Publishers.cs
src/NServiceBus.Core/Routing/UnicastRoutingTable.cs

Particular.Analyzers 2.1.0 will introduce `PS0025:Dictionary keys should implement IEquatable<T>`. This PR prepares the repo by fixing the issues that analyzer will find, based on an alpha version of the analyzer.
Contains 1 change to public API, making `NServiceBus.Unicast.Subscriptions.MessageDrivenSubscriptions.Subscriber` a record class, automatically creating the `IEquatable<Subscriber>` implementation necessary to be used as a HashSet key in [AcceptanceTestingSubscriptionStorage](https://github.com/Particular/NServiceBus/blob/9.0.0/src/NServiceBus.AcceptanceTesting/AcceptanceTestingPersistence/SubscriptionStorage/AcceptanceTestingSubscriptionStorage.cs#L31-L42).

Fixes for Particular.Analyzers 2.1.2 - master

---

src/NServiceBus.Core/DataBus/FileShareDataBusImplementation.cs

Fixes FileNotFoundException in cross-platform scenarios (Windows to Linux or Linux to Windows). The bug was due to incompatible path separators causing exceptions.

Fix for FileNotFoundException in FileShareDataBusImplementation in cross-platform scenarios

---

src/NServiceBus.Core/DataBus/FileShareDataBusImplementation.cs

Backport of #7042 which fixes #7043 for the 9.0 branch

FileShareDataBusImplementation throws a FileNotFoundException when sending databus messages from Windows to Linux

---

src/NServiceBus.AcceptanceTests/DataBus/When_sending_databus_properties_from_different_environments.cs
src/NServiceBus.Core.Tests/DataBus/FileShare/AcceptanceTests.cs

Part of https://github.com/Particular/PlatformBugs/issues/1322
Added a test to ensure databus message from windows to linux (and vice versa) are processed correctly via the FileShareDataBus.

FileShareDataBus acceptance tests for multi environments

---

src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_expired.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_expired_convention.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_used_with_unobtrusive_mode.cs

Acceptance tests for TTBR do not specify `Done` condition and use the default `Done` condition i.e. `() => true`. This causes the test to end immediately, just after the `OnStart` method of `FeatureStartupTask` finishes. 
As a result, the tests that check if messages with TTBR are not delivered when the expiry time elapses finish with false positive results.

Ensure that the TTBR test do not end just after the feature startup is done

---

src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_expired.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_has_expired_convention.cs
src/NServiceBus.AcceptanceTests/TimeToBeReceived/When_TimeToBeReceived_used_with_unobtrusive_mode.cs

Version 9.0 backport of:
- https://github.com/Particular/NServiceBus/pull/7062

Backport: Ensure that the TTBR test do not end just after the feature startup is done

---

src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/When_messages_processed_successfully.cs
src/NServiceBus.Core/OpenTelemetry/Metrics/ReceiveDiagnosticsBehavior.cs

_related to https://github.com/Particular/NServiceBus/issues/7022_
Currently, a metric tag containing the content of the EnclosedMessageTypes header is added to the Fetches, Failures, and Success metrics emitted through System.Diagnostics in Core.
However, the value of this header can be quite large, and doesn't provide as much value, as filtering makes most sense on the message type, not its entire hierarchy tree.
This PR changes that value to be limited to the most concrete message type, and only includes the message type full name, and excludes assembly info.
The full contents of the header are still emitted as trace tags.

Limit metric tag to concrete message type

---

src/NServiceBus.Core.Tests/Unicast/Messages/AssemblyQualifiedNameParserTests.cs
src/NServiceBus.Core.Tests/Unicast/Messages/AssemblyQuallifiedNameParserTests.cs
src/NServiceBus.Core/Unicast/Messages/AssemblyQualifiedNameParser.cs
src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs

The current fallback logic to extract the fullname bluntly assumes it is OK to split by `,` and then take the first part. While this works in some cases it fails with more advanced types like generics. We are aware [that generic are not officially supported](https://docs.particular.net/nservicebus/messaging/messages-events-commands#designing-messages), but regardless of that, the parsing logic should treat the assembly qualified names properly and not lead to invalid data types.
Instead of string splitting or trying to do a fancy regular expression match and replace (with all the consequences of those potentially timing out etc.), I came up with a straightforward approach that should be robust and reliable (see test cases) and even in the cases when we get a full name already even faster …

Robust and faster handling of AssemblyQualifiedNames in MessageMetadataRegistry

---

src/NServiceBus.Core.Tests/AssemblyScanner/When_using_type_forwarding.cs

While back port #7081 the System.Runtime assembly had exported types which caused me to realize there should be a where clause there. I did already bring the change here to the back ported PRs otherwise it wouldn't have passed on the release-8.2 branch

Add more restrictive where clause to type forwarding test

---

src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/Metrics/When_message_is_processed_successfully.cs
src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/Metrics/When_message_processing_fails.cs
src/NServiceBus.Core.Tests/ApprovalFiles/MeterTests.Verify_MeterAPI.approved.txt
src/NServiceBus.Core.Tests/OpenTelemetry/Helpers/TestingMetricListener.cs
src/NServiceBus.Core.Tests/OpenTelemetry/MeterTests.cs
src/NServiceBus.Core/OpenTelemetry/Metrics/MetricsExtensions.cs
src/NServiceBus.Core/Pipeline/Incoming/IncomingPipelineMetrics.cs
src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs
src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs

- Adds a new metric for the processing time (time to invoke all handlers and persist the sagas and the outbox data)
- Adjusts the critical time metric to include the time it takes to successfully dispatch the outgoing messages
Documentation PR https://github.com/Particular/docs.particular.net/pull/6724

Introduce processing time metric.

---

src/NServiceBus.AcceptanceTests/NServiceBus.AcceptanceTests.csproj

Two unneeded `RemoveSourceFileFromPackage` sneaked into the NServiceBus.AcceptanceTests project, causing the linked test sources to be included in the source package and ultimately causing downstream packages to fail when updating to Core 9.1.
This pull request removes the unwanted MSBuild elements, removing the two test files from the source package

Remove wrongly added RemoveSourceFileFromPackage elements from ATT project

---

src/NServiceBus.Core/NServiceBus.Core.csproj

The fix is to add a direct reference to System.Formats.Asn1 to avoid a version with a security vulnerability

System.Formats.Asn1 (an indirect reference) has a security vulnerability

---

src/NServiceBus.AcceptanceTests/Core/Hosting/When_disabling_assembly_scanning.cs
src/NServiceBus.Core/Hosting/Helpers/AssemblyScanningComponent.cs
src/NServiceBus.Core/Unicast/Messages/MessageMetadataRegistry.cs

as per [the documentation](https://docs.particular.net/nservicebus/messaging/messages-events-commands#designing-messages), generic message types are not supported. This change adds a debug log to that effect

Log debug when using generic message types

---

src/NServiceBus.TransportTests/IConfigureTransportInfrastructure.cs
src/NServiceBus.TransportTests/NServiceBusTransportTest.cs

This updates the base transport test to allow SqlTransport to remove its own local copy.
See https://github.com/Particular/NServiceBus.SqlServer/pull/1435 for more context

Backport transport test changes from sql transport

---

src/nuget.config

Dependabot isn't opening PRs for packages that we only push to Feedz. I have a hunch it's because it's no longer finding our `nuget.config` in the repo root.
For now, let's copy it into the `src` folder, and we'll see if that fixes Dependabot.

Add nuget.config to src to see if that fixes Dependabot

---

src/NServiceBus.AcceptanceTests/Core/Conventions/When_scanning_an_assembly_containing_a_ref_struct_and_sagas_enabled.cs
src/NServiceBus.Core/Sagas/Sagas.cs

Backport of #7187 which fixes #7179 for the release-9.2 branch

Ref struct in scanned assembly results in app crash at startup, if sagas are present

---

src/NServiceBus.AcceptanceTests/Core/Conventions/When_scanning_an_assembly_containing_a_ref_struct_and_sagas_enabled.cs
src/NServiceBus.Core/Sagas/Sagas.cs

Backport of #7187 which fixes #7179 for the release-8.2 branch

Ref struct in scanned assembly results in app crash at startup, if sagas are present 

---

src/NServiceBus.Core.Tests/StandardsTests.cs
src/NServiceBus.Core/Transports/Learning/LearningTransport.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportMessagePump.cs

This aligns the learning transport to stop the pumps on transport shutdown and at the same time makes sure the pumps stop method can be called multiple times. 
This is part of addressing some low-hanging fruit to align all transports for the transport seam usage scenarios to make sure pumps are stopped when the transport shuts down. 
I have tried to write a transport test for it to enforce it eventually for all transport but couldn't find a way to do that without introducing flags on the transport interface and using fancy techniques like default members which seams overkill

Learning Transport: Stop pumps on shutdown

---

.github/workflows/code-analysis.yml
.github/workflows/integrity.yml

Replaces https://github.com/Particular/NServiceBus/pull/6951, however that PR shows the fixes necessary to pass the repo integrity tests. Note, however, changes due to .NET 9 preparations will require some of the repo integrity tests to change before a global rollout.

Centralizable code analysis workflow

---

.github/workflows/code-analysis.yml

The new code analysis was not working because the NServiceBus repo is using a global.json file stipulating .NET 9 while the code analysis action itself is built in .NET 8.
This now uses a shared workflow so that the workflow synced to each repo is minimal. The workfow and action itself has been updated so that it changes paths to avoid the target repo's global.json getting in the way.

Use shared workflow for code analysis

---

src/NServiceBus.Core.Tests/Sagas/SagaModelPartialProperty1Tests.cs
src/NServiceBus.Core.Tests/Sagas/SagaModelPartialProperty2Tests.cs
src/NServiceBus.Core.Tests/Sagas/SagaModelTests.cs
src/NServiceBus.Core.Tests/Sagas/When_saga_is_correlated_on_a_unsupported_datetime_property_type.cs

Move the partial class MyPartialEntity to separate files

Testing of partial properties 

---

src/NServiceBus.Core.Tests/NServiceBus.Core.Tests.csproj
src/NServiceBus.Core.Tests/Sagas/SagaModelPartialProperty1Tests.cs
src/NServiceBus.Core.Tests/Sagas/SagaModelPartialProperty2Tests.cs
src/NServiceBus.Core.Tests/Sagas/SagaModelTests.cs
src/NServiceBus.Core.Tests/Sagas/When_saga_is_correlated_on_a_unsupported_datetime_property_type.cs

Adds saga unit test coverage using a C# 13.0 partial property as correlation id

Saga unit test coverage using a C# 13.0 partial property as correlation id

---

src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/Traces/When_incoming_message_was_delayed.cs
src/NServiceBus.Core/OpenTelemetry/Tracing/ActivityFactory.cs

Addresses https://github.com/Particular/NServiceBus/issues/7209

Fix delayed message null activity

---

src/NServiceBus.Core.Tests/Hosting/HostInfoSettingsTests.cs
src/NServiceBus.Core/Hosting/HostInfoSettings.cs
src/NServiceBus.Core/Hosting/HostingComponent.Settings.cs

Fixes [Overriding the host name does not work consistently #7026](https://github.com/Particular/NServiceBus/issues/7026)

Fixing overriding the host name does not work consistently

---

src/NServiceBus.Core.Tests/Hosting/HostInfoSettingsTests.cs
src/NServiceBus.Core/Hosting/HostInfoSettings.cs
src/NServiceBus.Core/Hosting/HostingComponent.Settings.cs

Backport of https://github.com/Particular/NServiceBus/pull/7282 which fixes https://github.com/Particular/NServiceBus/issues/7026 for the release-9.1 branch

Overriding the host name does not work consistently

---

src/NServiceBus.AcceptanceTests/Core/Routing/When_extending_command_routing_with_thisinstance.cs
src/NServiceBus.AcceptanceTests/Routing/NativePublishSubscribe/MultiSubscribeToPolymorphicEvent.cs
src/NServiceBus.AcceptanceTests/Routing/NativePublishSubscribe/When_publishing_to_scaled_out_subscribers.cs
src/NServiceBus.AcceptanceTests/Routing/When_base_event_from_2_publishers.cs
src/NServiceBus.AcceptanceTests/Routing/When_extending_command_routing.cs
src/NServiceBus.AcceptanceTests/Routing/When_using_custom_routing_strategy.cs

The scenario runner firsts starts all endpoints concurrently and then executes the whens concurrently

Checking endpoint started within When is no longer necessary

---

src/NServiceBus.AcceptanceTests/Core/OpenTelemetry/Traces/When_processing_message_with_multiple_handlers.cs
src/NServiceBus.Core.Tests/OpenTelemetry/ActivityFactoryTests.cs
src/NServiceBus.Core.Tests/Pipeline/Incoming/InvokeHandlerTerminatorTest.cs
src/NServiceBus.Core.Tests/Unicast/LoadHandlersConnectorTests.cs
src/NServiceBus.Core/OpenTelemetry/Tracing/ActivityFactory.cs
src/NServiceBus.Core/OpenTelemetry/Tracing/IActivityFactory.cs
src/NServiceBus.Core/OpenTelemetry/Tracing/NoOpActivityFactory.cs
src/NServiceBus.Core/Pipeline/Incoming/InvokeHandlerTerminator.cs
src/NServiceBus.Core/Pipeline/Incoming/LoadHandlersConnector.cs
src/NServiceBus.Core/Receiving/ReceiveComponent.cs
src/NServiceBus.Core/Sagas/SagaPersistenceBehavior.cs

Going down this route enables the user to use pipeline behaviors to enrich the span if needed.
No tests had to be changed, but this is arguably a behavior change since the span now includes a larger chunk of the pipeline. I think that is ok, though.
Potential solution for https://github.com/Particular/NServiceBus/issues/7315
Docs changes to consider:
- Will be done once we figure out when this will be released 
- Went with a retitle instead https://github.com/Particular/docs.particular.net/pull/7077

Make handler span surround the entire handler pipeline stage

---

src/NServiceBus.Core/Transports/Learning/AsyncFile.cs
src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs

- Moving the file to the `.pending` transaction folder only returns `true` if file exists and is not locked (and not just when all attempts have been used)
- `BeginTransaction` removes the `.pending` folder if fails to begin the transaction

Fix learning competing consumers bug

---

src/NServiceBus.Core/Transports/Learning/AsyncFile.cs
src/NServiceBus.Core/Transports/Learning/DirectoryBasedTransaction.cs

* AsyncFile.Move returns true only if the file was read (i.e. exists and not locked)
* Clean up the .pending directory if unable to move and unlock the file

Port fix learning competing consumers bug (#7324)

---

src/NServiceBus.Core/Reliability/SynchronizedStorage/ICompletableSynchronizedStorageSession.cs

Add GC.SuppressFinalize to ICompletableSynchronizedStorageSession
so that if any future classes inherit from it, they won't have to worry about calling GC.SuppressFinalize

Add GC.SuppressFinalize to ICompletableSynchronizedStorageSession

---

src/NServiceBus.AcceptanceTesting/AcceptanceTestingTransport/AcceptanceTestingTransportInfrastructure.cs
src/NServiceBus.Core/Transports/Learning/LearningTransportInfrastructure.cs

Microsoft is adding support for [a new solution file format](https://devblogs.microsoft.com/visualstudio/new-simpler-solution-file-format/).
The learning and acceptance test transports both look for a solution file to determine the default location of the transport folder. As the file extension has changed for the new format, it breaks these transports.
This PR adds support for the new format by checking for `.sln` _and_ `.slnx` files.

Support slnx solution files

---

src/NServiceBus.AcceptanceTests/Core/Audit/When_a_message_is_audited.cs
src/NServiceBus.AcceptanceTests/Core/Audit/When_processing_a_control_message.cs

This confirms that control messages are audited

Add acceptance test to verify audit behavior for control messages

---

src/NServiceBus.Core.Tests/Unicast/MessageTypeTests.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageType.cs

Fix `ArgumentOutOfRangeException` when parsing `MessageType` with no trailing comma after `Version=...`
This PR fixes a bug introduced by #7349 in `MessageType.ParseVersion` where it assumed that a comma always follows the `Version=` segment in the message type string. If no comma is present (e.g. `"TypeName, Version=1.0.0.0"`), the method would still attempt to slice the span using `[..-1]` resulting in an `ArgumentOutOfRangeException`.
This PR includes a test to validate the behavior, and modifies the `ParseVersion` method logic to only attempt to slice the span when a comma is found after the `Version=` part of the string.

Update version parsing

---

src/NServiceBus.Core.Tests/ApprovalFiles/APIApprovals.ApproveNServiceBus.approved.txt
src/NServiceBus.Core.Tests/ApprovalFiles/NullableAnnotations.ApproveNullableTypes.approved.txt
src/NServiceBus.Core.Tests/ContextBagTests.cs
src/NServiceBus.Core/DelayedDelivery/ThrowIfCannotDeferMessageBehavior.cs
src/NServiceBus.Core/Extensibility/ContextBag.cs
src/NServiceBus.Core/Pipeline/Incoming/DeserializeMessageConnector.cs
src/NServiceBus.Core/Transports/TransportTransaction.cs

This PR enables Nullable annotations on the context bag. It seems there are valid use cases to store a key with a null value when the key itself and a null value are used as an indicator. For example, NServiceBus uses that as part of the ConversationRoutingExtensions
https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/Causation/ConversationRoutingExtensions.cs#L15-L16
Therefore the nullable annotations have been changed to clearly indicate that the T values can be null in some cases.

Enable nullable type annotations on the ContextBag

---

src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs

This is an outcome of a revelation from some work around metrics in the transactional session.
This pull request updates how message processing time is measured in `TransportReceiveToPhysicalMessageConnector`. Instead of using `DateTimeOffset.UtcNow`, it now uses `Stopwatch` for more accurate timing and moves the measurement outside the transaction scope to better reflect the actual processing duration, especially for configurations where work is done during transaction scope disposal.
Improvements to message processing time measurement:
* Changed the start time measurement from `DateTimeOffset.UtcNow` to `Stopwatch.GetTimestamp()` for higher precision.
* Moved the processing time calculation and recording to after the transaction scope is disposed, using `Stopwatch.GetElapsedTime`, to …

Improve processing time metric

---

src/NServiceBus.Core.Tests/Persistence/PersistenceStartupTests.cs
src/NServiceBus.Core.Tests/Persistence/PersistenceStorageMergerTests.cs
src/NServiceBus.Core/EndpointConfiguration.cs
src/NServiceBus.Core/EndpointCreator.cs
src/NServiceBus.Core/Persistence/PersistenceComponent.cs
src/NServiceBus.Core/Persistence/PersistenceExtensions.cs
src/NServiceBus.Core/Persistence/PersistenceStorageMerger.cs
src/NServiceBus.Core/Reliability/Outbox/Outbox.cs
src/NServiceBus.Core/Routing/MessageDrivenSubscriptions/MessageDrivenSubscriptions.cs
src/NServiceBus.Core/Sagas/Sagas.cs

Minimal changes to avoid assembly scanning for persistence startup to happen

Stop using IWantToRunBeforeConfigurationIsFinalized for persistence config

---

src/NServiceBus.Core/Reliability/SynchronizedStorage/ICompletableSynchronizedStorageSession.cs

Now that we're working a new major, we can remove the default `IAsyncDisposable` implementation on `ICompletableSynchronizedStorageSession`.
This aligns the interface to match the changes in #7407 so that we don't have one interface with a default implementation and one without.

Remove default IAsyncDisposable implementation from ICompletableSynchronizedStorageSession

---

src/Custom.Build.props
src/NServiceBus.Core.Analyzer/NServiceBus.Core.Analyzer.csproj

Now that .NET 10 RC1 has been released, we don't need to set the language anymore.

Prepare for NServiceBus 10 - Remove LangVersion
